### DISCUSSION TITLE
thanos.shipper.json.tmp: read-only file system

### DISCUSSION THREAD

**Discussion by davidy718** [thanos-io/thanos#4842] [General]
Hi
I'm running prometheus with thanos sidecar and I get an error "`thanos.shipper.json.tmp: read-only file system`"
```
- name: thanos-sidecar
  image: quay.io/thanos/thanos:main-2021-11-06-abc5d4c3
  args:
              - "sidecar"
              - "--prometheus.url=http://localhost:9090/"
              - "--tsdb.path=/bucket"
              - "--objstore.config-file=/bucket/bucket.yml"
              - "--log.level=debug"
```
bucket.yml
```
   type: S3 
    config: 
      bucket: my-s3-bucket
      endpoint: s3.eu-west-1.amazonaws.com
```
the host has an AMI role to the S3 bucket
this is from in the sidecar container 
`drwxrwxrwx    3 root     root            99 Nov  8 21:24 bucket`

`level=error ts=2021-11-08T22:27:15.018260899Z caller=sidecar.go:279 err="WAL dir is not accessible. Is this dir a TSDB directory? If yes it is shared with TSDB?: stat /bucket/wal: no such file or directory"`
