### DISCUSSION TITLE
Not able to understand why is thanos is not deleting really old data?

### DISCUSSION THREAD

**Discussion by dharapvj** [thanos-io/thanos#5080] [Questions & Answers]
Hi, I have a thanos sidecar and standalone thanos setup.

Thanos has below retention setting:
```yaml
    compact:
      retention:
        resolutionRaw: 2d
        resolution5m: 7d
        resolution1h: 60d
```

pometheus is started with below params:
```
            --storage.tsdb.retention.time=5d 
            --storage.tsdb.min-block-duration=2h 
            --storage.tsdb.max-block-duration=2h 
```

But as can be seen from screenshots... sidecar is not clearing data all the way back to Sept 10th 2021 (almost 130 days old)

I don't understand why
![Thanos timerange](https://user-images.githubusercontent.com/1920926/150279745-765107bc-6079-4cd6-ad9e-90e9059a01c1.png)

As we can see below.. the data is stored for so long is provided by sidecar
![sidecar source](https://user-images.githubusercontent.com/1920926/150279743-3af8acc2-44a4-45c2-80f0-bb851449b7f7.png)

How can clear up old blocks so that I only retain 60 days worth of data?

**Comment by fktkrt** [comment]
Hey, could you please share your Compactor's config/flags?

**Comment by dharapvj** [comment]
thanos is started with below args
```
compact --data-dir=/var/compact-data --objstore.config-file=/etc/thanos/objstore.yaml --retention.resolution-raw=2d --retention.resolution-5m=7d --retention.resolution-1h=60d --wait
```
objstore.yaml has below contents:
```
config:
  access_key: <my_access_key>
  bucket: thanos
  endpoint: minio.minio.svc.cluster.local:9000
  insecure: true
  secret_key: <my_secret_key>
type: S3
```
Hope that helps.
