### DISCUSSION TITLE
Thanos store/compact error: Truncated response should have continuation token set

### DISCUSSION THREAD

**Discussion by LukaszWasko** [thanos-io/thanos#5208] [Questions & Answers]
I got error today on working instances (for about 3 months with no problems) Thanos store/compact on NetApp S3 :
```
Mar 03 16:04:21 thanos thanos[67666]: {"caller":"http.go:74","component":"store","err":"bucket store initial sync: sync block: BaseFetcher: iter bucket: Truncated response should have continuation token set","level":"info","msg":"internal server is shutting down","service":"http/server","ts":"2022-03-03T15:04:21.156903187Z"}"
```
I cannot launch them.
Thanos Receiver works fine with pushing metrics to S3.

I googled around and I found a possible cause to be returning truncated amounts of results because of some kind of page limit on S3 API.

NetApp shows me that it has about 3800 objects:
```
NetApp::> bucket show metrics-prod -fields object-count
  (vserver object-store-server bucket show)
vserver                      bucket           object-count
---------------------------- ---------------- ------------
metrics.prod metrics-prod 3872
```
Adding to s3.yaml below line doesn't help:
```
list_objects_version: "v1"
```
After couple of minutes thanos throw an error _context deadline exceeded_

I did not find a clear answer, should I change any parameter on the Thanos Store / Minio client (s3.yaml) side or on the NetApp side?
Has anyone had experience with this? 

Thanos version: thanos-0.24.0-1.el8.x86_64
System: CentOS 8

thanos store parameters:
```
--objstore.config-file /etc/thanos-store/s3.yaml --http-address=0.0.0.0:10904 --grpc-address=0.0.0.0:10901 --data-dir="/var/lib/thanos/store" --log.level=debug --log.format=json'
```

/etc/thanos-store/s3.yaml:
```
type: S3
config:
  bucket: "metrics-prod"
  endpoint: "metrics.prod"
  region: "us-east-1a"
  access_key: XXX
  insecure: false
  signature_version2: false
  secret_key: XXX
  http_config:
    idle_conn_timeout: 0s
  sse_config:
    type: "SSE-S3"
```
