### DISCUSSION TITLE
prefix in configuration not working correctly

### DISCUSSION THREAD

**Discussion by z2665** [thanos-io/thanos#5514] [Questions & Answers]
I have a config 
```
type: s3
config:
    bucket: test-metrics-s3
    endpoint: test-metrics-s3.s3.us-west-2.amazonaws.com
    aws_sdk_auth: false
prefix: test1/test2/metrics/
```
so I want path result is 
```
<bucket>/prefix
test-metrics-s3/test1/test2/metrics/
```
but I got the result is
```
<bucket>/<bucket name>/prefix
test-metrics-s3/test-metrics-s3/test1/test2/metrics/
```
Is there something wrong with the configuration here?
Thanks all
