### DISCUSSION TITLE
Multiple sidecar have set "prefix", how set store to read all of them?

### DISCUSSION THREAD

**Discussion by X-Mars** [thanos-io/thanos#5517] [Questions & Answers]
### sidecar 1
```
type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
      bucket: "thanos-dev"
      access_key_id: "2222"
      access_key_secret: "2222"
    prefix: "sidecar1"
```
### sidecar 2
```
type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
      bucket: "thanos-dev"
      access_key_id: "2222"
      access_key_secret: "2222"
    prefix: "sidecar2"
```

### store
```
type: ALIYUNOSS
config:
  endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
  bucket: "thanos-dev"
  access_key_id: "2222"
  access_key_secret: "2222"
prefix: ""
```
Thank you !
