### DISCUSSION TITLE
Querier: Unable to stack queriers

### DISCUSSION THREAD

**Discussion by envyj020** [thanos-io/thanos#5916] [Questions & Answers] [answered]
#### Versions used:
Prometheus: v2.38.0
Thanos: 0.28.0

#### Environment:
AWS EKS

### Issue description:
Trying to stack external queriers from a centralized querier meant to be our single entrypoint to observe other kubernetes clusters, I have exposed the GRPC endpoint with a combination of **external-dns** and **alb-ingress-controller**, everything is showing healthy from outside, I can even connect to the GRPC endpoint from outside the cluster:

```
$ grpcurl querier.dev.example.internal.com:443 list

grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection
thanos.Exemplars
thanos.Metadata
thanos.Query
thanos.Rules
thanos.Store
thanos.Targets
thanos.info.Info
``` 

The following Ingress and service definition is used:

### GRPC Ingress:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/group.name: example-dev
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-xxx, subnet-yyy, subnet-zzz
    alb.ingress.kubernetes.io/target-type: instance
    external-dns.alpha.kubernetes.io/aws-zone-type-private: "true"
    external-dns.alpha.kubernetes.io/hostname: querier.dev.example.internal.com
    kubernetes.io/ingress.class: alb
  name: thanos-querier-grpc-ingress
spec:
  rules:
  - host: querier.dev.example.internal.com
    http:
      paths:
      - backend:
          service:
            name: thanos-query-svc
            port:
              number: 10901
        path: /
        pathType: Prefix
```

### GRPC Service:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  name: thanos-query-svc
spec:
  ports:
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  type: NodePort
```

### Error logs:

```
$ thanos query --http-address "0.0.0.0:9090" --endpoint "dns+querier.dev.example.internal.com:443" --log.level=debug

level=info ts=2022-11-22T11:41:59.407630043Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-11-22T11:41:59.408583284Z caller=query.go:724 msg="starting query node"
level=info ts=2022-11-22T11:41:59.408932445Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-11-22T11:41:59.408995163Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:9090
level=info ts=2022-11-22T11:41:59.409619596Z caller=tls_config.go:195 service=http/server component=query msg="TLS is disabled." http2=false
level=info ts=2022-11-22T11:41:59.414617708Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-11-22T11:41:59.415370892Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=warn ts=2022-11-22T11:42:09.41321717Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.31.80.62:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.31.80.62:443
level=warn ts=2022-11-22T11:42:09.413217173Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.31.82.142:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.31.82.142:443
level=warn ts=2022-11-22T11:42:09.413258171Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.31.87.110:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.31.87.110:443
level=warn ts=2022-11-22T11:42:14.413571566Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.31.82.142:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.31.82.142:443
level=warn ts=2022-11-22T11:42:14.413843036Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.31.87.110:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.31.87.110:443
level=warn ts=2022-11-22T11:42:14.413971731Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.31.80.62:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.31.80.62:443

```

But if I try to connect directly to the **NodeIP:NodePort** exposed, everything works:
```
$ thanos query --http-address "0.0.0.0:9090" --endpoint "10.31.82.37:32654" --log.level=debug

level=info ts=2022-11-22T12:24:52.920908263Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-11-22T12:24:52.924620011Z caller=query.go:724 msg="starting query node"
level=info ts=2022-11-22T12:24:52.926443089Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-11-22T12:24:52.928087156Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:9090
level=info ts=2022-11-22T12:24:52.930298428Z caller=tls_config.go:195 service=http/server component=query msg="TLS is disabled." http2=false
level=info ts=2022-11-22T12:24:52.929251491Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-11-22T12:24:52.930634844Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2022-11-22T12:24:52.932686726Z caller=endpointset.go:381 component=endpointset msg="adding new query with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI QueryAPI]" address=10.31.82.37:32654 extLset="{cluster=\"example-dev\", purpose=\"kubernetes\", replica=\"prometheus-prometheus-kube-prometheus-0\"},{cluster=\"example-dev\", purpose=\"kubernetes\", replica=\"prometheus-prometheus-kube-prometheus-1\"}"
```

I'd really appreaciate any ideas of what am I missing here, thanks in advance!
