### DISCUSSION TITLE
Downsampling, how it works ?

### DISCUSSION THREAD

**Discussion by mixman68** [thanos-io/thanos#6292] [Questions & Answers]
Hello,

I try to configure a new thanos cluster

my Compactor is set as 

```
  thanos-compactor:                             
    image: quay.io/thanos/thanos:v0.31.0                       
    volumes:                            
      - ./thanos/:/etc/thanos/                                 
      - compactor_data:/data/                 
    command:                                  
      - "compact"                                  
      - "--log.level=debug"                     
      - "--data-dir=/data"                                               
      - "--objstore.config-file=/etc/thanos/bucket_config.yaml" 
      - "--retention.resolution-raw=2d"                        
      - "--retention.resolution-5m=120d"                       
      - "--retention.resolution-1h=1y"                               
      - "--wait"                                               
      - "--wait-interval=3m"                                             
    restart: always
```

But i see no downsampling, the metric thanos_compact_downsample_total still 0.

Scrapes has beginned et 2023-04-15 @ 13:00

![image](https://user-images.githubusercontent.com/3840229/232839447-60de513a-972b-47e4-8f54-fc3e40ba8a85.png)

Can you help me please, i think it is a little issue in my config, but i don't found which
