### DISCUSSION TITLE
Thanos ruler evaluates rules much slower after upgrading to V0.25.0

### DISCUSSION THREAD

**Discussion by robocanic** [thanos-io/thanos#6649] [Questions & Answers]
Hey guys, I come up with a really wired problem: I upgrade the prometheus to V2.32.1, thanos ruler, thanos query to V0.25.0. But the thanos ruler evaluates much slower than before. And I have the same workloads(ruler,query ,etc) in another cluster( k8s,etc are the same version) with  same configurations which are working fine. I have been disappointed for almost 1 week. Can you guys help me out?
This is the configuration of thanos ruler:
```yml
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: http
              containerPort: 10902
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rules
              mountPath: /etc/thanos/rules
            - name: thanos-rules
              mountPath: /var/thanos/rule
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'quay.io/thanos/thanos:v0.25.0'
          args:
            - rule
            - '--log.level=warn'
            - '--rule-file=/etc/thanos/rules/*.yaml'
            - '--query=dnssrv+_http._tcp.thanos-query.$(NAMESPACE).svc'
            - '--grpc-address=:10901'
            - '--http-address=:10902'
            - '--data-dir=/var/thanos/rule'
            - '--eval-interval=10s'
            - '--tsdb.retention=48h'
            - '--alertmanagers.url=http://alertmanager-main:9093'
            - '--alert.label-drop=rule_replica'
```
this is the configuration of thanos query:
```yml
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: http
              containerPort: 9090
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'quay.io/thanos/thanos:v0.25.0'
          args:
            - query
            - '--log.level=warn'
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:9090'
            - '--query.partial-response'
            - '--query.replica-label=rule_replica'
            - '--query.replica-label=replica'
            - '--query.replica-label=prometheus_replica'
            - '--query.max-concurrent-select=40'
            - '--rule=dnssrv+_grpc._tcp.thanos-rule-headless.$(NAMESPACE).svc'
            - '--store=dnssrv+_grpc._tcp.prometheus-k8s.$(NAMESPACE).svc'
            - '--store=dnssrv+_grpc._tcp.thanos-rule-headless.$(NAMESPACE).svc'
```
and here is one of many alerts of thanos rule:
```txt
Thanos Rule 10.255.178.26:10902 has higher evaluation latency than interval for /var/thanos/rule/.tmp-rules/ABORT/etc/thanos/rules/monitoring-prometheus-k8s-rules-2cde94d2-17bc-4e4b-a112-a3944f592fe4.yaml;kube-prometheus-node-recording.rules.
```
the comparison of two thanos ruler evaluating duration:
![image](https://github.com/prometheus/prometheus/assets/79916872/24e3a131-a614-4c29-ba0d-0ace85422e10)
![image](https://github.com/prometheus/prometheus/assets/79916872/01681087-92e0-42bc-97ec-fe16f2fbf771)
