### DISCUSSION TITLE
Thanos receiver hogs high memory utilisation for more than 16 hours after stress tests

### DISCUSSION THREAD

**Discussion by yliu138repo** [thanos-io/thanos#7165] [Questions & Answers]
HI Folks, we have memory issues with Thanos receive horizontal autoscaling as they don't actually scale down after 16 hours from the load testing.  we have HPA with min=2 and max=9. During the load testing, receive clusters scale up to 9 pods. As the below image implies, from the initial peak due to load testing around 17:00, the scaled up pods never gets scaled down. Instead ALL pods' memory usage remain flat afterwards, and never drops; Inital 2 pods remain even higher around 890Mi, and the memory limit is 2.5Gi! This has made the whole setup unusable since every time running load testing, we have to reinstall the whole thanos stacks to avoid any pod crashes. (We set each memory limit to 2.5Gi because we'd like to compare how well thanos autoscales, and try to keep the same configs with initial prometheus configuration)

![image (1)](https://github.com/thanos-io/thanos/assets/105641046/92b5ab53-b68c-42c0-9f8c-595eee6b3208)

We are using [bitnami helm package](https://github.com/bitnami/charts/tree/main/bitnami/thanos) for thanos on Openshift Cluster, and the image using is thanos:0.33.0-debian-11-r1 , thanos receive configuration

```
            - receive
            - '--log.level=debug'
            - '--log.format=logfmt'        
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:10902'
            - '--remote-write.address=0.0.0.0:19291'
            - '--receive.hashrings-algorithm=ketama'
            - '--objstore.config=$(OBJSTORE_CONFIG)'
            - '--tsdb.path=/var/thanos/receive'
            - '--label=replica="$(NAME)"'
            - '--label=receive="true"'
            - '--tsdb.retention=6h'
            - >-
              --receive.local-endpoint=$(NAME).obs-thanos-receive-headless.$(NAMESPACE).svc.cluster.local:10901
```

`--tsdb.retention=6h` was set up to keep the samples for only 6 hours, samples will get uploaded to a s3 bucket (MinIO)
we have default hashring with 1 tenant only
```
[
  {
    "hashring": "default",
    "endpoints": [
      "obs-thanos-receive-0.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-1.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-2.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-3.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-4.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-5.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-6.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-7.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901",
      "obs-thanos-receive-8.obs-thanos-receive-headless.NAMESPACE.svc.cluster.local:10901"
    ]
  }
]
```
 the HPA setup
```
  maxReplicas: 9
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: obs-thanos-receive
```

We are not sure what configs we are missing so Thanos receive hogs high memory after long itme - 16 hours with `--tsdb.retention=6h` . In my understanding, we should be able to write the incoming data to the disk every 2 hours and send it to object storage periodically, and remove the samples from disk every 6 hours. Not sure of the reason to hold data in-memory. Please correct me if I am wrong.  Thanks in advance
