### DISCUSSION TITLE
K8S doesn't create Service for Thanos sidecar

### DISCUSSION THREAD

**Discussion by vsfomin** [thanos-io/thanos#7396] [Questions & Answers]
Thanos launches successfully, but I can't understand why no Services are created in K8S for it. 
For some reason I also can't get to the sidecar-http port of the container: I get a 404 page not found error. Although in the container itself I can see that port 10902 is listening. 
What do I need to do for Helm to automatically create services for the sidecar container? And can I check if gRPC port working properly?  
I install Prometheus together with Thanos sidecar this way:
```
 helm upgrade --version=“25.11.0” --install --namespace=“monitoring” --values values.yaml prometheus-thanos-sidecar promethehe
us-community/prometheus
```

```
sidecarContainers:
    thanos-sidecar:
      image: quay.io/thanos/thanos:v0.31.0  
      resources:
        requests:
          memory: "512Mi"
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secret/sa
      args:
        - "sidecar"
        - --log.level=debug
        - --tsdb.path=/data
        - --prometheus.url=http://prometheus-thanos-sidecar-server
        - --objstore.config-file=/etc/thanos/bucket_config.yml
        - --reloader.config-envsubst-file=/etc/prometheus-config/prometheus.yml
        - --reloader.config-file=/etc/prometheus-config/prometheus.yml
        - --reloader.rule-dir=/etc/prometheus-config/rules
      ports:
        - name: sidecar-http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
```
