### DISCUSSION TITLE
How to pass forward async-workers to thanos ?

### DISCUSSION THREAD

**Discussion by chit786** [thanos-io/thanos#7408] [Questions & Answers] [answered]
Thanos version: 0.34.1
Helm chart: 15.0.2

```
thanos: error: unknown long flag '--receive.forward.async-workers'
```

**Comment by chit786** [comment]
found it was released with 0.35.1. 🙏

**Reply by chit786** [reply]
I jumped the gun. With latest image `thanos:0.35.1-debian-12-r0` i still am not able to pass these flags.

**Reply by chit786** [reply]
```
    - name: receive
      image: docker.io/bitnami/thanos:0.35.1-debian-12-r0
      args:
        - receive
        - '--log.level=debug'
        - '--log.format=logfmt'
        - '--grpc-address=0.0.0.0:10901'
        - '--http-address=0.0.0.0:10902'
        - '--remote-write.address=0.0.0.0:19291'
        - '--label=replica="$(NAME)"'
        - '--label=receive="true"'
        - '--receive.hashrings-file=/var/lib/thanos-receive/hashrings.json'
        - '--receive.replication-factor=3'
        - '--receive.hashrings-algorithm=ketama'
        - '--receive.hashrings-file-refresh-interval=5s'
        - '--receive.forward.async-workers=3000'
        - '--receive-forward-timeout=10s'
        - '--receive-forward-max-backoff=5s'
        - |
          --tracing.config=type: OTLP
          config:
            service_name: "receive-distributor"
            client_type: "grpc"
            insecure: true
            endpoint: "<OTEL_ENDPOINT>:4317"
```
