### DISCUSSION TITLE
Setting up Thanos locally and getting OOMKilled every time I access Thanos Query UI

### DISCUSSION THREAD

**Discussion by dbeilin** [thanos-io/thanos#7561] [Questions & Answers]
On my local KinD cluster, I used Helm to deploy `kube-prometheus-stack` for Prometheus and Alertmanager, as well as the Bitnami Thanos chart with the following values:

```
query:
  enabled: true
  logLevel: debug
  dnsDiscovery:
    enabled: false
  resourcesPreset: "none"

ruler:
  enabled: true
  logLevel: debug
  clusterName: local-ruler
  alertmanagers:
    - http://prometheus-kube-prometheus-alertmanager.prometheus.svc.cluster.local:9093
  config: |-
    groups:
      - name: example
        rules:
          - alert: HighCPUUsage-test
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High CPU usage detected
  resourcesPreset: "none"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: false

objstoreConfig: |-
  type: FILESYSTEM
  config:
    directory: /tmp/thanos/object-storage
```

When I port-forward `thanos-query` and go to "rules" for example, the UI hangs until the pod gets killed with a OOM error.
I'm not sure what I'm doing wrong, any help would be appreciated.
