### DISCUSSION TITLE
Sidecar S3: in-bucket path

### DISCUSSION THREAD

**Discussion by CherrySuryp** [thanos-io/thanos#7774] [Questions & Answers] [answered]
Hi Thanos community!

I'm planning to setup about 10 prometheus instances for different clients. For each instance I want to setup sidecar to backup metrics to MinIO S3.
During configuration I've notices that there's no option to setup in-bucket path, for example:  `bucket/custom-path/`.
Can it be configured in `S3` configuration, or there's no such option? I just don't want to create new bucket for each new client, instead I wanted to configure it like `bucket/client-1`, `bucket/client-2`, etc.

My current configuration
```yaml
type: s3
config:
  bucket:     prometheus
  endpoint:   s3.example.com
  access_key: ""
  secret_key: ""
```

I tried add custom path like this, but it returned an error:
```yaml
type: s3
config:
  bucket:     prometheus/client-1
  endpoint:   s3.example.com
  access_key: ""
  secret_key: ""
```

**Comment by dosubot** [comment]
Hey @CherrySuryp! I'm here to help you out with any issues or questions you have. Let's tackle this together!


You can configure an in-bucket path for MinIO S3 in Thanos sidecar by using the `prefix` field in the S3 configuration. This allows you to separate blocks coming from different sources into paths with different prefixes within the same bucket.

Here is an example configuration:

```yaml
type: S3
config:
  bucket: "prometheus"
  endpoint: "s3.example.com"
  access_key: ""
  secret_key: ""
  prefix: "client-1"
```

This configuration will store the data under the `prometheus/client-1` path within the specified bucket <sup>[[1]](https://github.com/thanos-io/thanos/blob/main/docs/storage.md)</sup>.

Additionally, there is no need for any extra configuration on the MinIO side to support the `prefix` field <sup>[[1]](https://github.com/thanos-io/thanos/blob/main/docs/storage.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by CherrySuryp** [reply, marked as answer]
This is correct configuration of prefix
```yaml
type: S3
prefix: "client-1"
config:
  bucket: "prometheus"
  endpoint: "s3.example.com"
  access_key: ""
  secret_key: ""
```

**Comment by MichaHoffmann** [comment]
I think what the bot said was correct!

**Reply by CherrySuryp** [reply]
I will try it now, thanks!

**Reply by MichaHoffmann** [reply]
Can you close if it works for you?

**Reply by CherrySuryp** [reply]
Nope, it's not working
![image](https://github.com/user-attachments/assets/0be97627-7ed5-4f7d-b1a7-25e7f21d6076)

**Reply by MichaHoffmann** [reply]
What's your config ?

**Reply by MichaHoffmann** [reply]
Ah prefix needs to be at same level like type and config. The bot made an indentation error

**Reply by CherrySuryp** [reply]
```yaml
    type: s3
    config:
      bucket:     prometheus
      prefix:     someprefix
      endpoint:   s3.example.com
      access_key: accesskey
      secret_key: secretkey
```
