### DISCUSSION TITLE
Sidecar S3 Configuration "reading meta file failed" error

### DISCUSSION THREAD

**Discussion by berkayalan** [thanos-io/thanos#8058] [Questions & Answers]
Hi,

I would like to deploy thanos sidecar to ecs as a task. I created an S3 bucket for it : com-thanos-data-bucket .

This is my dockerfile:

```
FROM thanosio/thanos:v0.37.2

COPY objstore.yml /objstore.yml

USER root

RUN sed -i "s/%%%THANOS_BUCKET_ALIAS%%%/com-thanos-data-bucket /g" /objstore.yml 

ENTRYPOINT ["/bin/thanos", "sidecar"]

CMD ["--prometheus.url=https://prometheus.myendpoint.tech", \
"--objstore.config-file=/objstore.yml", \
"--log.level=debug"]
```

And this is also my objstore.yml file:

```
type: S3
config:
  bucket: "%%%THANOS_BUCKET_ALIAS%%%"
  endpoint: "s3.eu-central-1.amazonaws.com"
  region: "eu-central-1"
```

But I got these errors:

```
level=warn msg="reading meta file failed, will override it" err="failed to read data/thanos.shipper.json: open data/thanos.shipper.json: no such file or directory"

level=warn err="read dir: open ./data: no such file or directory"
```

I think my objstore can't connect to S3. What am I doing wrong? I checked my ECS role and it has permission to access S3.

Thanks in advance.
