### DISCUSSION TITLE
UI: thanos does not support nginx proxy access page

### DISCUSSION THREAD

**Discussion by magiceses** [thanos-io/thanos#8341] [Questions & Answers]
**Prerequisite: I don't want to change the original API route thanos**

But when I try to deploy a nginx before thanos, and when all routes are prefixed by rewrite, the page returns 404 to me. Config Example:

nginx ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ccc
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/pm/(.*) /$1 break;
      rewrite ^/global/(.*) /$1 break;
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: xxx-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "401: Authentication Required"
spec:
  rules:
  - host: xxxxxxxxxxxx
    http:
      paths:
      - backend:
          service:
            name: thanos-query
            port:
              name: web
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: thanos-query-global
            port:
              name: web
        path: /global
        pathType: ImplementationSpecific
      - backend:
          service:
            name: prometheus-shard-{{ $shard }}
            port:
              name: web
        path: /pm
        pathType: ImplementationSpecific
```

Then I visited the page and heard the following error(And the route of Go back to home page is /graph, not /global/graph):
<img width="644" alt="image" src="https://github.com/user-attachments/assets/5a0eb3e0-1b7b-4916-9895-ee7d8276b75d" />

But when I use the same configuration to operate prometheus(such as /pm), the prometheus page is accessed normally. Each button on the page will automatically have a prefix of pm.

Is there any difference between the pages of thanos and prometheus? Or how do I need to configure thanos or nginx?
