### ISSUE TITLE
Thanos sidecar doesn't seem to retry to connect prometheus

### ISSUE THREAD

**Issue by kimxogus** [thanos-io/thanos#1085]
**Thanos, Prometheus and Golang version used**
Thanos: `improbable/thanos:v0.2.1`, `improbable/thanos:v0.3.2`
Prometheus: `quay.io/prometheus/prometheus:v2.7.2` in prometheus operator `0.29` installed by prometheus helm chart

**What happened**
Thanos sidecar outputs following log and no more logs are written. It seems thanos sidecar doesn't retry to connect prometheus.

**What you expected to happen**
Thanos sidecar retries to connect prometheus

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

<details>Logs
<p>

```
level=info ts=2019-04-26T01:04:13.661087548Z caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=100.96.1.106:10901
level=info ts=2019-04-26T01:04:13.663956385Z caller=main.go:256 component=sidecar msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-04-26T01:04:13.664005953Z caller=factory.go:39 msg="loading bucket configuration"
level=info ts=2019-04-26T01:04:13.66468131Z caller=sidecar.go:293 msg="starting sidecar" peer=
level=info ts=2019-04-26T01:04:13.665367076Z caller=main.go:308 msg="Listening for metrics" address=0.0.0.0:10902
level=info ts=2019-04-26T01:04:13.665498225Z caller=sidecar.go:220 component=sidecar msg="Listening for StoreAPI gRPC" address=[100.96.1.106]:10901
level=warn ts=2019-04-26T01:04:13.665716012Z caller=sidecar.go:132 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="request flags against http://127.0.0.1:9090/api/v1/status/config: Get http://127.0.0.1:9090/api/v1/status/config: dial tcp 127.0.0.1:9090: connect: connection refused"
```

</p>
</details>

**Anything else we need to know**

This is chart values used to create prometheus operator

<details>
<p>

```yaml
# Default values for prometheus-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## Provide a name in place of prometheus-operator for `app:` labels
##
nameOverride: ""
## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""
## Labels to apply to all resources
##
commonLabels: {}
# scmhash: abc123
# myLabel: aakkmd
## Create default rules for monitoring the cluster
##
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    general: true
    k8s: true
    kubeApiserver: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubeScheduler: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    node: true
    prometheusOperator: true
    prometheus: true
  labels: {}
  annotations: {}
## Provide custom recording or alerting rules to be deployed into the cluster.
##
additionalPrometheusRules: []
#  - name: my-rule-file
#    groups:
#      - name: my_group
#        rules:
#        - record: my_record
#          expr: 100 * my_record
##
global:
  rbac:
    create: true
    pspEnabled: true
  imagePullSecrets: []
## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  enabled: true
  serviceAccount:
    create: true
    name: ""
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: ""
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'
  templateFiles: {}
  #
  #
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    hosts: []
    paths: []
    tls: []
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    nodePort: 30903
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
  serviceMonitor:
    interval: ""
    selfMonitor: true
  alertmanagerSpec:
    podMetadata: {}
    image:
      repository: quay.io/prometheus/alertmanager
    secrets: []
    configMaps: []
    logLevel: info
    replicas: 1
    retention: 120h
    storage: {}
    externalUrl:
    routePrefix: /
    paused: false
    nodeSelector: {}
    resources: {}
    podAntiAffinity: ""
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    tolerations: []
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    listenLocal: false
    containers: []
    priorityClassName: ""
    additionalPeers: []
## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
##
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    labels: {}
    hosts: []
    path: /
    tls: []
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      label: grafana_datasource
  extraConfigmapMounts: []
  additionalDataSources: []
  serviceMonitor:
    interval: ""
    selfMonitor: true
## Component scraping the kube api server
##
kubeApiServer:
  enabled: true
  tlsConfig:
    serverName: kubernetes
    insecureSkipVerify: false
  relabelings: []
  serviceMonitor:
    interval: ""
    jobLabel: component
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
    metricRelabelings: []
## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    interval: ""
    https: true
    cAdvisorMetricRelabelings: []
    cAdvisorRelabelings: []
## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: true
  endpoints: []
  service:
    port: 10252
    targetPort: 10252
    selector:
      component: kube-controller-manager
  serviceMonitor:
    interval: ""
    https: false
    metricRelabelings: []
    relabelings: []
## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: true
  service:
    port: 9153
    targetPort: 9153
    selector:
      k8s-app: kube-dns
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
## Component scraping kubeDns. Use either this or coreDns
##
kubeDns:
  enabled: false
  service:
    selector:
      k8s-app: kube-dns
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
## Component scraping etcd
##
kubeEtcd:
  enabled: false
  endpoints: []
  service:
    port: 2379
    targetPort: 2379
    selector:
      k8s-app: etcd-manager-main
  serviceMonitor:
    interval: ""
    scheme: http
    insecureSkipVerify: false
    serverName: ""
    caFile: ""
    certFile: ""
    keyFile: ""
    metricRelabelings: []
    relabelings: []
## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false
  endpoints: []
  service:
    port: 10251
    targetPort: 10251
    selector:
      component: kube-scheduler
  serviceMonitor:
    interval: ""
    https: false
    metricRelabelings: []
    relabelings: []
## Component scraping kube state metrics
##
kubeStateMetrics:
  enabled: true
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  rbac:
    create: true
  podSecurityPolicy:
    enabled: true
## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true
  jobLabel: node-exporter
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  podLabels:
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  serviceAccount:
    create: true
    name: ""
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    nodePort: 30080
    additionalPorts: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    externalIPs: []
  createCustomResource: false
  crdApiGroup: monitoring.coreos.com
  cleanupCustomResource: false
  podLabels: {}
  podAnnotations: {}
  priorityClassName: PRIORITY_CLASS_NAME
  logFormat: json
  kubeletService:
    enabled: true
    namespace: kube-system
  serviceMonitor:
    interval: ""
    selfMonitor: true
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  image:
    repository: quay.io/coreos/prometheus-operator
    pullPolicy: IfNotPresent
  configmapReloadImage:
    repository: quay.io/coreos/configmap-reload
  prometheusConfigReloaderImage:
    repository: quay.io/coreos/prometheus-config-reloader
  hyperkubeImage:
    repository: k8s.gcr.io/hyperkube
    pullPolicy: IfNotPresent
## Deploy a Prometheus instance
##
prometheus:
  enabled: true
  serviceAccount:
    create: true
    name: ""
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    targetPort: 9090
    additionalPorts:
    - name: thanos-cluster
      port: 10900
    - name: thanos-grpc
      port: 10901
    - name: thanos-http
      port: 10902
    externalIPs: []
    nodePort: 30090
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    sessionAffinity: ""
  rbac:
    roleNamespaces:
      - kube-system
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: ""
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    hosts: []
    paths: []
    tls: []
  serviceMonitor:
    interval: ""
    selfMonitor: true
  prometheusSpec:
    scrapeInterval: ""
    evaluationInterval: ""
    listenLocal: false
    image:
      repository: quay.io/prometheus/prometheus
    tolerations: []
    alertingEndpoints: []
    externalLabels: {}
    externalUrl: ""
    nodeSelector: {}
    secrets: []
    configMaps: []
    query: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: true
    ruleSelector: {}
    #
    serviceMonitorSelectorNilUsesHelmValues: true
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    retention: 10d
    paused: false
    replicas: 2
    logLevel: info
    routePrefix: /
    podMetadata:
      labels:
        thanos-peer: "true"
        app: prometheus
      annotations:
        iam.amazonaws.com/role: ROLE
    podAntiAffinity: "hard"
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    remoteRead: []
    remoteWrite: []
    resources:
      requests:
        cpu: 300m
        memory: 2048Mi
    storageSpec: {}
    additionalScrapeConfigs: []
    additionalAlertManagerConfigs: []
    additionalAlertRelabelConfigs: []
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    priorityClassName: PRIORITY_CLASS_NAME
    thanos:
      version: v0.3.2
      peers: "thanos-peers:10900"
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-object-storage-config
    containers: []
    additionalScrapeConfigsExternal: false
  additionalServiceMonitors: []
```

</p>
</details>
