### ISSUE TITLE
No store matched for this query for last 2 hours

### ISSUE THREAD

**Issue by pablokbs** [thanos-io/thanos#1352]
**Thanos, Prometheus and Golang version used**
```
Thanos v0.6.0
Prometheus v2.7.2
```

When I query metrics for the last 2 hours, I get no metrics, after the metrics are sent to S3, I get them

![image](https://user-images.githubusercontent.com/4028336/61836137-3c61b400-ae55-11e9-9d0e-6e9a2e4091df.png)

Query logs:

query logs: ```thanos-query-6558d4dcd7-4bjmn thanos-query level=warn ts=2019-07-24T20:52:13.415109742Z caller=proxy.go:269 err="No store matched for this query" stores="store Addr: thanos-store:10901 LabelSets:  Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out"```

`thanos-store` does not log anything when I do a query

Service config

```
Name:              thanos-store
Namespace:         monitoring
Labels:            <none>
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"thanos-store","namespace":"monitoring"},"spec":{"ports":[{"name":...
Selector:          app=thanos,thanos-peers=true
Type:              ClusterIP
IP:                172.31.83.139
Port:              grpc  10901/TCP
TargetPort:        grpc/TCP
Endpoints:         172.21.130.9:10901
Session Affinity:  None
Events:            <none>
```

Endpoint looks fine: `thanos-store-0                         1/1     Running   0          47m   172.21.130.9`

Port seems fine

```
Containers:
  thanos-store:
    Container ID:  docker://897b4a6cd9e30bed64fdcd28b9b682050a4ec9e6f83e7b05a76e38eeb952ee5e
    Image:         improbable/thanos:v0.6.0
    Image ID:      docker-pullable://improbable/thanos@sha256:ae27356a5959e8225f1299822a29d87206a659fdf8b4ae5f76a8e57a485dc88c
    Ports:         10900/TCP, 10901/TCP, 10902/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      store
      --log.level=debug
      --data-dir=/var/thanos/store
      --objstore.config=$(OBJSTORE_CONFIG)
    State:          Running
      Started:      Wed, 24 Jul 2019 17:13:34 -0300
```

From query

```
/ # nc -vz thanos-store:10901
thanos-store:10901 (172.31.83.139:10901) open
```

query deployment

```
Pod Template:
  Labels:           app=thanos-query
                    thanos-peers=true
  Service Account:  prometheus-k8s
  Containers:
   thanos-query:
    Image:       improbable/thanos:v0.6.0
    Ports:       10902/TCP, 10901/TCP, 10900/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Args:
      query
      --log.level=debug
      --query.replica-label=prometheus_replica
      --query.auto-downsampling
      --store=thanos-store:10901
```

prometheus-statefulset

```
  Containers:
   prometheus:
    Image:      quay.io/prometheus/prometheus:v2.7.2
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=24h
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.route-prefix=/
      --storage.tsdb.min-block-duration=2h
      --storage.tsdb.max-block-duration=2h
    Requests:
      memory:     6Gi
    Liveness:     http-get http://:web/-/healthy delay=0s timeout=3s period=5s #success=1 #failure=6
    Readiness:    http-get http://:web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=120
    Environment:  <none>
    Mounts:
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-k8s-rulefiles-0 from prometheus-k8s-rulefiles-0 (rw)
      /prometheus from prometheus-k8s-db (rw)
   prometheus-config-reloader:
    Image:      quay.io/coreos/prometheus-config-reloader:v0.31.1
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/prometheus-config-reloader
    Args:
      --log-format=logfmt
      --reload-url=http://localhost:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    Limits:
      cpu:     100m
      memory:  25Mi
    Environment:
      POD_NAME:   (v1:metadata.name)
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
   rules-configmap-reloader:
    Image:      quay.io/coreos/configmap-reload:v0.0.1
    Port:       <none>
    Host Port:  <none>
    Args:
      --webhook-url=http://localhost:9090/-/reload
      --volume-dir=/etc/prometheus/rules/prometheus-k8s-rulefiles-0
    Limits:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/rules/prometheus-k8s-rulefiles-0 from prometheus-k8s-rulefiles-0 (rw)
   thanos-sidecar:
    Image:       improbable/thanos:v0.6.0
    Ports:       10902/TCP, 10901/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      sidecar
      --prometheus.url=http://localhost:9090/
      --tsdb.path=/prometheus
      --grpc-address=[$(POD_IP)]:10901
      --objstore.config=$(OBJSTORE_CONFIG)
    Environment:
      POD_IP:            (v1:status.podIP)
      OBJSTORE_CONFIG:  <set to the key 'thanos.yaml' in secret 'thanos-objstore-config'>  Optional: false
    Mounts:
      /prometheus from prometheus-k8s-db (rw)
  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s
    Optional:    false
   config-out:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
   prometheus-k8s-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-k8s-rulefiles-0
    Optional:  false
   prometheus-k8s-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
```

While using the thanos ui, I try to query:

![image](https://user-images.githubusercontent.com/4028336/61836512-e42bb180-ae56-11e9-8234-79166687339d.png)

`/stores`

![image](https://user-images.githubusercontent.com/4028336/61836572-3371e200-ae57-11e9-9aef-42713f88bd6d.png)

So according to the [architecture diagram](https://raw.githubusercontent.com/thanos-io/thanos/master/docs/img/arch.jpg), thanos-query makes requests to the thanos-sidecar to get metrics, how that works? I can't find anything in thanos-query that points to the thanos-sidecar

Any ideas?

**Comment by jojohappy** [comment]
Hi, you should also add the sidecar as Store API with `--store`, default the last 2 hours metrics are stored in the memory of prometheus instances, the sidecar would query those by remote read api.

**Comment by pablokbs** [comment]
> Hi, you should also add the sidecar as Store API with `--store`, default the last 2 hours metrics are stored in the memory of prometheus instances, the sidecar would query those by remote read api.

That was it!!! Thanks!!

This is what I did:

* Created a new service to point to the thanos-sidecar inside the prometheus pod:

```
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-sidecar
  namespace: monitoring
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  selector:
    app: prometheus  # <---- this matches my prometheus pods
    thanos-peers: "true"
```

* Modified the query-deployment manifest to add this new service as a store:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: thanos-query
    thanos-peers: "true"
  name: thanos-query
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-query
      thanos-peers: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peers: "true"
    spec:
      containers:
      - args:
        - query
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --query.auto-downsampling
        - --store=thanos-store:10901
        - --store=thanos-store-sidecar:10901 # <---- new service
        image: improbable/thanos:v0.6.0
        name: thanos-query
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        - containerPort: 10900
          name: cluster
      serviceAccountName: prometheus-k8s
```
