### ISSUE TITLE
failed" err="add config file watch: no such file or directory"

### ISSUE THREAD

**Issue by kapilgarg83** [thanos-io/thanos#1428]
kubectl logs pod/prometheus-server-0 -n prom -c prometheus-thanos
level=info ts=2019-08-16T11:04:02.421406698Z caller=flags.go:75 msg="gossip is disabled"
level=info ts=2019-08-16T11:04:02.421595094Z caller=main.go:256 component=sidecar msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-08-16T11:04:02.421622706Z caller=sidecar.go:235 msg="No supported bucket was configured, uploads will be disabled"
level=info ts=2019-08-16T11:04:02.421637911Z caller=sidecar.go:293 msg="starting sidecar" peer="no gossip"
level=warn ts=2019-08-16T11:04:02.422012005Z caller=sidecar.go:132 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="request flags against http://localhost:9090/api/v1/status/config: Get http://localhost:9090/api/v1/status/config: context canceled"
level=info ts=2019-08-16T11:04:02.422065781Z caller=sidecar.go:220 component=sidecar msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2019-08-16T11:04:02.422118826Z caller=main.go:308 msg="Listening for metrics" address=0.0.0.0:10902
level=error ts=2019-08-16T11:04:02.422284868Z caller=main.go:181 msg="running command failed" err="add config file watch: no such file or directory"

facing this issue since long not able to resolve.
.yml
```

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    name: prometheus-server
  name: prometheus-server
  namespace: prom
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
      component: server
  serviceName: prometheus-server-headless
  template:
    metadata:
      annotations: {}
      labels:
        app: prometheus
        component: server
        thanos-store-api: "true"
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus:v2.9.2
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
            - --storage.tsdb.retention=2w
            - --storage.tsdb.min-block-duration=2h
            - --storage.tsdb.max-block-duration=2h
            - --web.enable-admin-api
          env: []                   
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30          
          ports:
            - containerPort: 9090
              name: http-prometheus
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config              
            - name: storage-volume
              mountPath: /data
              subPath: ''
            - name: config-shared
              mountPath: /etc/prometheus-shared  
              
        - name: prometheus-server-configmap
          image: jimmidyson/configmap-reload:v0.2.2
          imagePullPolicy: IfNotPresent                        
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9090/-/reload
          env: []                              
          ports: []
          volumeMounts:
            - name: config-volume 
              mountPath: /etc/config
              
              
        - name: prometheus-thanos
          image: improbable/thanos:v0.3.1
          imagePullPolicy: IfNotPresent
          args:
          - sidecar
          - --log.level=debug
          - --tsdb.path=/var/prometheus
          - --prometheus.url=http://localhost:9090
          - --cluster.disable  
          - --reloader.config-file=/etc/prometheus/prometheus.yaml.tmpl
          - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yaml
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          ports:
          - name: http-sidecar
            containerPort: 10902
          - name: grpc
            containerPort: 10901
            
          volumeMounts:
          - name: storage-volume
            mountPath: /data
          - name: config-shared
            mountPath: /etc/prometheus-shared
          - name: config-volume
            mountPath: /etc/config            
              
      imagePullSecrets: []
      initContainers:
        - name: init-chown-data
          image: busybox:latest
          imagePullPolicy: IfNotPresent          
          command:
            - chown
            - -R
            - 65534:65534
            - /data                             
          volumeMounts:
            - mountPath: /data
              name: storage-volume
              subPath: ''
      serviceAccountName: prometheus-server
      terminationGracePeriodSeconds: 300
      volumes:
              
        - name: config-shared
          emptyDir: {}
                    
        - name: config-volume
          configMap:
            name: prometheus-server-config
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "gp2"
        resources:
          requests:
            storage: 8Gi




```
