### ISSUE TITLE
store endpoint healthy but "rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=storer:19090"

### ISSUE THREAD

**Issue by goek-han** [thanos-io/thanos#1452]
**Environment**
```
Thanos: 0.6.1
Prometheus: 2.9.2
Golang: 1.12.7
```
_<details><summary>docker-compose.yaml</summary><p>_
```yaml
version: '3.7'

services:
  prometheus1:
    image: prom/prometheus:v2.9.2
    command:
    - --web.enable-lifecycle
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --storage.tsdb.min-block-duration=2h # small just to not wait hours to test :)
    - --storage.tsdb.max-block-duration=2h # small just to not wait hours to test :)
    - --storage.tsdb.retention=2h
    volumes:
    - ./prometheus1.yaml:/etc/prometheus/prometheus.yml
    - ./data:/prometheus
    ports:
    - 9090:9090
  sidecar1:
    image: quay.io/thanos/thanos:v0.6.1
    volumes:
    - ./data:/var/prometheus
    - ./bucket_config.yaml:/bucket_config.yaml
    command:
    - sidecar
    - --tsdb.path=/var/prometheus
    - --prometheus.url=http://prometheus1:9090
    - --objstore.config-file=/bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --grpc-address=0.0.0.0:19090

  # to search on old metrics
  storer:
    image: quay.io/thanos/thanos:v0.6.1
    volumes:
    - ./bucket_config.yaml:/bucket_config.yaml
    command:
    - store
    - --data-dir=/var/thanos/store
    - --objstore.config-file=bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --grpc-address=0.0.0.0:19090
    - --log.level=debug

  # downsample metrics on the bucket
  compactor:
    image: quay.io/thanos/thanos:v0.6.1
    volumes:
    - ./bucket_config.yaml:/bucket_config.yaml
    command:
    - compact
    - --data-dir=/var/thanos/compact
    - --objstore.config-file=bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --wait

  # querier component which can be scaled
  querier:
    image: quay.io/thanos/thanos:v0.6.1
    labels:
    - "traefik.enable=true"
    - "traefik.port=19192"
    - "traefik.frontend.rule=PathPrefix:/"
    command:
    - query
    - --http-address=0.0.0.0:19192
    - --store=sidecar1:19090
    - --store=storer:19090
    - --query.replica-label=replica
    ports:
      - 19192:19192

  # a load balancer to reverse-proxy to all queriers
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml

networks:
  default:
    driver: bridge
```
</p></details>

_<details><summary>prometheus1.yaml</summary><p>_
```yaml
global:
  scrape_interval:     60s
  evaluation_interval: 60s
  external_labels:
    region: test1
    replica: A

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
```
</p></details>

**What happened**
Thanos Query shows that all stores are healthy, see below
![Stores are healthy](https://i.imgur.com/ZtaD8OV.png)

but the logs of Thanos **Querier** show this **error**:
```
level=warn ts=2019-08-22T13:55:49.340051254Z caller=storeset.go:322 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=storer:19090
```

while the logs of Thanos **Storer** indicate that it's _alive and healthy_:
```
storer_1       | level=debug ts=2019-08-22T13:54:13.753458344Z caller=store.go:144 msg="initializing bucket store"
storer_1       | level=debug ts=2019-08-22T13:55:57.763289318Z caller=store.go:148 msg="bucket store ready" init_duration=1m44.009828962s
storer_1       | level=info ts=2019-08-22T13:55:57.763643441Z caller=main.go:274 msg="disabled TLS, key and cert must be set to enable"
storer_1       | level=info ts=2019-08-22T13:55:57.7637344Z caller=store.go:191 msg="starting store node"
storer_1       | level=info ts=2019-08-22T13:55:57.763881497Z caller=store.go:181 msg="Listening for StoreAPI gRPC" address=0.0.0.0:19090
storer_1       | level=info ts=2019-08-22T13:55:57.763900701Z caller=main.go:326 msg="Listening for metrics" address=0.0.0.0:19191
```

Any ideas why the web interface of Query shows everything doing well while the component throws errors?
