### ISSUE TITLE
store: won't start, no logs indicating why

### ISSUE THREAD

**Issue by asmith60** [thanos-io/thanos#1455]
**Thanos, Prometheus and Golang version used**
Thanos: 0.6.0
Prometheus: 2.10.0

**What happened**
The Thanos store won't start. It tries to start up, but crashes in ~30 seconds. Inspecting the pod indicates that the process exited with a non-zero code. The log output with debug enabled is below.

```
level=info ts=2019-08-23T18:55:30.952906789Z caller=main.go:154 msg="Tracing will be disabled"
level=info ts=2019-08-23T18:55:30.952955736Z caller=factory.go:39 msg="loading bucket configuration"
level=info ts=2019-08-23T18:55:30.969576127Z caller=cache.go:172 msg="created index cache" maxItemSizeBytes=4294967296 maxSizeBytes=8589934592 maxItems=math.MaxInt64
level=debug ts=2019-08-23T18:55:30.969822743Z caller=store.go:144 msg="initializing bucket store"
```
**What you expected to happen**
Thanos store to start successfully.

**Anything else we need to know**
6 HA pairs of Prometheus instances (12 total instances) are uploading metrics to the AWS S3 bucket. The current bucket size is ~750GB. The store pod manifest is below (I removed the obj-store config, AWS IAM config, etc)

<details>Store pod
<p>

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-store
  serviceName: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
        - name: thanos-store
          imagePullPolicy: Always
          image: "improbable/thanos:v0.6.0"
          args:
            - store
            - --data-dir=/data
            - --log.level=debug
            - --index-cache-size=8GB
            - --chunk-pool-size=20GB
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            limits:
              cpu: 2000m
              memory: 32000Mi
            requests:
              cpu: 2000m
              memory: 32000Mi
          volumeMounts:
            - mountPath: /data
              name: storage-volume
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "128Gi"

```

</p>
</details>
