### ISSUE TITLE
Thanos sidecar failing : cant reach tsdb.path for prometheus (installed with istio)

### ISSUE THREAD

**Issue by kuberkaul** [thanos-io/thanos#1502]
**prometheus: "docker.io/prom/prometheus:v2.8.0"
thanos: docker.io/thanosio/thanos:v0.7.0
 -> running in kubernetes cluster**

**What happened**
I have an installation of prometheus (through helm for istio) which is running and exposed via ingress.This is running as deployment and not stateful set. 
I have added the thanos sidecar to this prometheus pod and here are the arguments for both :

```
containers:
        - name: prometheus
          image: "docker.io/prom/prometheus:v2.8.0"
          imagePullPolicy: IfNotPresent
          args:
            - --web.external-url=http://prometheus.istio-system.svc.cluster.local:9090/prometheus
            - --web.route-prefix=prometheus
            - --storage.tsdb.retention.time=6h
            - --config.file=/etc/prometheus/prometheus.yml
            -  --storage.tsdb.path=data/
            - --web.enable-lifecycle
            - --web.enable-admin-api
            - --storage.tsdb.no-lockfile
            - --storage.tsdb.min-block-duration=2h
            - --storage.tsdb.max-block-duration=2h
          ports:
            - containerPort: 9090
              name: http
          livenessProbe:
           httpGet:
             path: /prometheus/-/healthy
             port: 9090
          readinessProbe:
           httpGet:
             path: /prometheus/-/ready
             port: 9090
          resources:
            requests:
              cpu: 10m
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
        - name: thanos-sidecar
          args:
          - sidecar
          - --prometheus.url=http://0.0.0.0:9090/prometheus
          #- --tsdb.path=data/
          - --reloader.config-file=/etc/prometheus/prometheus.yml
          - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yaml
          - --objstore.config-file=/etc/thanos/thanos-store-config.yml
          - --http-address=[$(POD_IP)]:10902
          - --grpc-address=[$(POD_IP)]:10901
          - --log.level=debug
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: docker.io/thanosio/thanos:v0.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-sidecar
              containerPort: 10902
            - name: thanos-grpc
              containerPort: 10901
              protocol: TCP
          resources:
            requests:
              cpu: 10m
          volumeMounts:
          - mountPath: /etc/thanos/
            name: thanos-store-config
          - mountPath: /etc/prometheus-shared
            name: config-shared
          - name: config
            mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus
        - name: config-shared
          emptyDir: {}
        - name: thanos-store-config
          configMap:
            defaultMode: 420
            name: thanos-store-config
```
When I run this, prometheus comes up fine and im able to get metrics as well (its storing all data in data/ in prom container but thanos fails with :

```level=error ts=2019-09-07T10:26:20.186408709Z caller=sidecar.go:254 err="WAL dir is not accessible. Is this dir a TSDB directory? If yes it is shared with TSDB?: stat data/wal: no such file or directory"
level=warn ts=2019-09-07T10:26:52.187968611Z caller=sidecar.go:282 err="iter local block metas: read dir: open ./data: no such file or directory" uploaded=0
level=warn ts=2019-09-07T10:26:52.188035954Z caller=sidecar.go:287 msg="reading timestamps failed" err="read shipper meta file: open data/thanos.shipper.json: no such file or directory"
``` 

**What you expected to happen**

Thanos to come up with no errors/warning and ship data to S3

**Full logs to relevant components**

<details>Logs
<p>

```
[root@ip-10-147-7-180 istio-patch]# kubectl logs pod/prometheus-5b888d6565-44t9k -n istio-system -c thanos-sidecar
level=debug ts=2019-09-07T10:26:20.142592706Z caller=main.go:120 msg="maxprocs: Leaving GOMAXPROCS=[2]: CPU quota undefined"
level=info ts=2019-09-07T10:26:20.142870405Z caller=main.go:168 msg="Tracing will be disabled"
level=info ts=2019-09-07T10:26:20.143116599Z caller=main.go:288 component=sidecar msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-09-07T10:26:20.143140686Z caller=factory.go:39 msg="loading bucket configuration"
level=error ts=2019-09-07T10:26:20.186408709Z caller=sidecar.go:254 err="WAL dir is not accessible. Is this dir a TSDB directory? If yes it is shared with TSDB?: stat data/wal: no such file or directory"
level=info ts=2019-09-07T10:26:20.186634705Z caller=sidecar.go:298 msg="starting sidecar"
level=info ts=2019-09-07T10:26:20.186958429Z caller=main.go:363 msg="listening for metrics" address=[10.147.15.146]:10902
level=info ts=2019-09-07T10:26:20.186995925Z caller=prober.go:143 msg="changing probe status" status=healthy
level=info ts=2019-09-07T10:26:20.187127454Z caller=sidecar.go:231 component=sidecar msg="Listening for StoreAPI gRPC" address=[10.147.15.146]:10901
level=info ts=2019-09-07T10:26:20.200900635Z caller=reloader.go:286 component=reloader msg="Prometheus reload triggered" cfg_in=/etc/prometheus/prometheus.yml cfg_out=/etc/prometheus-shared/prometheus.yaml rule_dirs=
level=info ts=2019-09-07T10:26:20.204134367Z caller=reloader.go:154 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg=/etc/prometheus/prometheus.yml out=/etc/prometheus-shared/prometheus.yaml dirs=
level=info ts=2019-09-07T10:26:20.205472249Z caller=sidecar.go:164 msg="successfully loaded prometheus external labels" external_labels="{env=\"production\",lz=\"build\",region=\"virginia\"}"
level=info ts=2019-09-07T10:26:20.20549365Z caller=prober.go:114 msg="changing probe status" status=ready
level=warn ts=2019-09-07T10:26:22.18785748Z caller=sidecar.go:282 err="iter local block metas: read dir: open ./data: no such file or directory" uploaded=0
level=warn ts=2019-09-07T10:26:22.187927628Z caller=sidecar.go:287 msg="reading timestamps failed" err="read shipper meta file: open data/thanos.shipper.json: no such file or directory"
level=warn ts=2019-09-07T10:26:52.187968611Z caller=sidecar.go:282 err="iter local block metas: read dir: open ./data: no such file or directory" uploaded=0
level=warn ts=2019-09-07T10:26:52.188035954Z caller=sidecar.go:287 msg="reading timestamps failed" err="read shipper meta file: open data/thanos.shipper.json: no such file or directory"
```

</p>
</details>

**Anything else we need to know**

I think I understand the issue is thanos container is unable to get to /data folder within prometheus container as its running as a sidecar besides but with istio, prometheus is deployed as deployment with no volume claim that can be shared between containers so how do I go about solving this without adding a volume claim ?
