### ISSUE TITLE
Thanos Store unable to use GCS auth settings in newer versions

### ISSUE THREAD

**Issue by analogpixel** [thanos-io/thanos#1629]
Google Cloud Storage

In older versions of thanos/store (v0.3.2)  I was able to use my google json auth file to authenticate to the google bucket.  In version v0.6.0, I now get the error message:

`level=error ts=2019-10-11T01:02:46.003731179Z caller=main.go:184 err="store command failed: create bucket client: create GCS client: failed to create credentials from JSON: invalid character '/' looking for beginning of value"`

## relevant kubernetes config 
```yaml
      image: improbable/thanos:v0.6.0
      ...

        args:
        - store
        - --log.level=debug
        - --data-dir=/data
        - --index-cache-size=500MB
        - --chunk-pool-size=500MB
        - --objstore.config-file=/etc/thanos-bucket/bucket-config.yaml
```

## /etc/thanos-bucket/bucket-config.yaml
```yaml
type: GCS
config:
  bucket: "my-thanos-bucket"
  service_account: "/etc/thanos-bucket/thanos-user.json"
```

The only thing that I change the causes it to break is the thanos version.
