### ISSUE TITLE
Compactor retention resolution flags are unknown

### ISSUE THREAD

**Issue by JonasDeGendt** [thanos-io/thanos#1674]
**Thanos, Prometheus and Golang version used**: thanosio/thanos:v0.8.0

**Object Storage Provider**: Azure Blob

**What happened**: 

I use the statefulset definition below to deploy a compactor on Kubernetes, but the container fails to start and throws error messages on the resolution flags.

<details>StatefulSet manifest
<p>

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ cluster + '-thanos-compactor' }}"
  namespace: monitoring
  labels:
    app: thanos-compactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ cluster + '-thanos-compactor' }}"
  serviceName: "{{ cluster + '-thanos-compactor' }}"
  template:
    metadata:
      labels:
        app: "{{ cluster + '-thanos-compactor' }}"
    spec:
      containers:
      - name: thanos
        image: thanosio/thanos:v0.8.0
        args:
        - compact
        - --log.level=warn
        - --data-dir=/data
        - --objstore.config-file=/objstore/thanos.yaml
        - --retention.resolution-raw=1d
        - --retention.resolution-5m=2d
        - --retention.resolution-1h=10d
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        volumeMounts:
        - mountPath: /objstore
          name: "{{ cluster + '-objstore-config' }}"
      volumes:
      - name: "{{ cluster + '-objstore-config' }}"
        secret:
          secretName: "{{ cluster + '-objstore-config' }}"
```
</p>
</details>

**What you expected to happen**: 

The container to run, it runs fine if I remove the retention flags.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

<details>Logs
<p>

```
~ kubectl logs -n monitoring sli-weu-01-thanos-compactor-0 
Error parsing commandline arguments: unknown long flag '--retention.resolution-raw'
thanos: error: unknown long flag '--retention.resolution-raw'
```

</p>
</details>

I checked `compact.go` and the flags are in there, so not sure what I'm doing wrong :)
