### ISSUE TITLE
query.auto-downsampling=true error

### ISSUE THREAD

**Issue by shancang** [thanos-io/thanos#1742]
config
```
      containers:
      - name: thanos
        image: thanosio/thanos:master-2019-11-05-27a578da
        args:
        - query
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --query.auto-downsampling=true
```
- --query.auto-downsampling=true
Error parsing commandline arguments: unexpected true
thanos: error: unexpected true
