### ISSUE TITLE
How do I register a store with the Thanos querier?

### ISSUE THREAD

**Issue by raz08** [thanos-io/thanos#1745]
prometheus.yaml
```

  thanos:
    baseImage: custom/thanos
    version: v0.8.0
    peers: thanos-peers.fed-prometheus.svc:10900
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
```
thanos.yaml

```
{{- define "thanos" -}}
type: FILESYSTEM
config:
  directory: "/var/thanos/store"
{{- end -}}
```

thanos-secret.yaml
```
apiVersion: v1
data:
  thanos.yaml: |
{{ include "thanos" . | b64enc | indent 4 }}
kind: Secret
metadata:
  creationTimestamp: "2019-11-12T05:46:26Z"
  name: thanos-objstore-config
  namespace: fed-prometheus
  resourceVersion: "7674204"
  selfLink: /api/v1/namespaces/fed-prometheus/secrets/thanos-objstore-config
  uid: c426704d-050f-11ea-b42a-fa163e3c7ad7
type: Opaque

```

querier-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: fed-prometheus
  labels:
    app: thanos-query
    thanos-peers: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
      thanos-peers: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peers: "true"
    spec:
      containers:
      - name: thanos-query
        image: custom/thanos:v0.8.0
        args:
        - "query"
        - "--log.level=debug"
        - "--query.replica-label=prometheus_replica"
        #- "--cluster.peers=thanos-peers.fed-prometheus.svc:10900"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900

```
thanos-store.yaml

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  namespace: fed-prometheus
  labels:
    app: thanos-store
    thanos-peer: "true"
spec:
  serviceName: "thanos-store"
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-store
        thanos-peer: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
      - name: thanos-store
        image: custom/thanos:v0.8.0
        args:
        - "store"
        - "--log.level=debug"
        - "--data-dir=/var/thanos/store"
        #- "--cluster.peers=thanos-peers.fed-prometheus.svc.cluster.local:10900"
        - "--objstore.config-file=/config/thanos-store.yml"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
        - name: data
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-store-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-store-config
  namespace: fed-prometheus
data:
  thanos-store.yml: |-
    type: FILESYSTEM
    config:
      directory: "/var/thanos/store"

```
thanos-compactor.yaml

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compactor
  namespace: fed-prometheus
  labels:
    app: thanos-compactor
    thanos-peer: "true"
spec:
  serviceName: "thanos-compactor"
  replicas: 1
  selector:
    matchLabels:
      app: thanos-compactor
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-compactor
        thanos-peer: "true"
    spec:
      containers:
      - name: thanos-compactor
        image: custom/thanos:v0.8.0
        args:
        - "compact"
        - "--log.level=debug"
        - "--data-dir=/var/thanos/store"
        - "--objstore.config-file=/config/thanos-store.yml"
        - "--wait"
        ports:
        - name: http
          containerPort: 10902
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
        - name: data
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-store-config

```

**Comment by Rajashekharaiah-M** [comment]
Query logs looks fine.

level=debug ts=2019-11-14T06:10:41.011927341Z caller=main.go:101 msg="maxprocs: Leaving GOMAXPROCS=[4]: CPU quota undefined"
level=info ts=2019-11-14T06:10:41.012138842Z caller=main.go:149 msg="Tracing will be disabled"
level=info ts=2019-11-14T06:10:41.013300302Z caller=options.go:20 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-11-14T06:10:41.013542219Z caller=query.go:415 msg="starting query node"
level=info ts=2019-11-14T06:10:41.013766227Z caller=prober.go:143 msg="changing probe status" status=healthy
level=info ts=2019-11-14T06:10:41.013801749Z caller=http.go:54 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2019-11-14T06:10:41.014021851Z caller=prober.go:114 msg="changing probe status" status=ready
level=debug ts=2019-11-14T06:10:41.014131211Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=0
level=info ts=2019-11-14T06:10:41.014147099Z caller=grpc.go:100 service=gRPC/server component=query msg="listening for StoreAPI gRPC" address=0.0.0.0:10901
level=debug ts=2019-11-14T06:10:41.014154454Z caller=storeset.go:335 component=storeset msg="checked requested storeAPIs" healthyStores=0 cachedStores=0
level=debug ts=2019-11-14T06:10:46.014246126Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=0

**Comment by squat** [comment]
Can you please share the exact command used to run the thanos querier? E.g. the full kubernetes deployment.

**Comment by Rajashekharaiah-M** [comment]
Hi squat, I have updated now. Please check

**Comment by squat** [comment]
Hi, the UI shows no registered stores because you have not told the querier where it can find any stores. The querier requires `--store=......` flags in order to know how to locate a store API. Please see https://thanos.io/components/query.md/ for help getting started.

**Comment by Rajashekharaiah-M** [comment]
--store            "0.0.0.0:10901"

is this right?

**Comment by jojohappy** [comment]
> --store "0.0.0.0:10901"
> 
> is this right?

No, you should setup the grpc address of your storeAPI components, such as storeGW, query..

**Comment by Rajashekharaiah-M** [comment]
I have set it up. Check above

**Comment by squat** [comment]
Not quite, it must be the address of your thanos store gateway. For example:
`--store=<POD-CLUSTER-IP>:10901`
In order to avoid hard coding an IP, you can use the DNS name, or you can also leverage DNS SRV records:
`--store=dnssrv+_grpc._tcp.thanos-store.fed-prometheus.svc.cluster.local`

For a complete example, see: https://github.com/thanos-io/kube-thanos/blob/master/manifests/thanos-querier-deployment.yaml

**Comment by Rajashekharaiah-M** [comment]
Im getting this error
`
level=error ts=2019-11-14T12:08:45.216045926Z caller=provider.go:101 msg="dns resolution failed" addr=dnssrv+_grpc._tcp.thanos-store.fed-prometheus.svc.cluster.local err="lookup SRV records \"_grpc._tcp.thanos-store.fed-prometheus.svc.cluster.local\": lookup _grpc._tcp.thanos-store.fed-prometheus.svc.cluster.local on 10.96.0.10:53: no such host"
`

**Comment by jojohappy** [comment]
You should create a headless service first.

```
apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: fed-prometheus
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app: thanos-store
  type: ClusterIP
```

**Comment by Rajashekharaiah-M** [comment]
Thanks jojohappy, That worked.

Now Thanos UI is not  loading. (http://{clusterip}:9090)

**Comment by squat** [comment]
@Rajashekharaiah-M but the querier logs look good, right?
Cluster IPs are private IPs that, unless you are VPN'd or have some forwarding, are only accessible from inside your cluster. Better to try to `kubectl port-forward` to access the querier UI, e.g. https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod

**Comment by Rajashekharaiah-M** [comment]
I have service for that 
```

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  name: thanos-query
  labels:
    app: thanos-query
    release: prometheus-operator
    jobLabel: thanos
  namespace: fed-prometheus
spec:
  selector:
    app: thanos-query
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http-query
  externalIPs:
  - <clusterip>

```

Is both Prometheus and Thanos query exposed with same port(external port)?

**Comment by squat** [comment]
Setting your cluster IP as an external IP in the service does not make it available to the outside world. The external IPs field is a way of saying: "hey, Kubernetes, any traffic that arrives on this  IP should be forwarded to my service." But it does not mean that your cluster IP from the private IP address space is accessible to the whole internet.

More info on external IPs: https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

**Comment by raz08** [comment]
By mistake I have added --http-address=0.0.0.0:9090. that is the reason UI was not coming up. I fixed it now.

One last support.
Sidecars and data is not visible in Thanos query UI.

**Comment by squat** [comment]
You need to specify the sidecar gRPC address on the query command as well, just like with the store gateway.

```
--store=<storegateway IP>:port
--store=<sidecar IP>:port
```

**Comment by raz08** [comment]
Added this
```
        - --store=dnssrv+_http._tcp.thanos-peers.fed-prometheus.svc.cluster.local:10902
        - --store=dnssrv+_cluster._tcp.thanos-peers.fed-prometheus.svc.cluster.local:10900

```
but it says connection refused.

thanos-peers-service.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: thanos-peers
  namespace: fed-prometheus
spec:
  type: ClusterIP
  ports:
  - name: cluster
    port: 10900
    targetPort: cluster
  - name: http
    port: 10902
    targetPort: http
  selector:
    thanos-peers: "true"

```
