### ISSUE TITLE
The confusing log output of the sidecar component startup.

### ISSUE THREAD

**Issue by johncming** [thanos-io/thanos#1859]
## k8s enviroment:

```
apiVersion: v1
kind: Pod
metadata:
  name: promandsidecar
  labels:
    name: promandsidecar
spec:
  containers:
  - name: prometheus
    image: prom/prometheus:v2.14.0
    ports:
      - containerPort: 9090
  - name: thanossidecar
    image: thanosio/thanos:master-2019-11-30-229f978d
    args:
      - sidecar
      - --prometheus.url=http://localhost:9090
```

## log

```
level=info ts=2019-12-10T06:56:40.9457331Z caller=main.go:149 msg="Tracing will be disabled"
level=info ts=2019-12-10T06:56:40.9460567Z caller=sidecar.go:138 msg="no supported bucket was configured, uploads will be disabled"
level=info ts=2019-12-10T06:56:40.9462969Z caller=options.go:20 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-12-10T06:56:40.9467325Z caller=sidecar.go:327 msg="starting sidecar"
level=info ts=2019-12-10T06:56:40.9471088Z caller=prober.go:127 msg="changing probe status" status=healthy
level=info ts=2019-12-10T06:56:40.9471641Z caller=http.go:53 service=http/server component=sidecar msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2019-12-10T06:56:40.9478937Z caller=reloader.go:154 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg= out= dirs=
level=info ts=2019-12-10T06:56:40.9482213Z caller=prober.go:107 msg="changing probe status" status=ready
level=info ts=2019-12-10T06:56:40.9484017Z caller=grpc.go:98 service=gRPC/server component=sidecar msg="listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2019-12-10T06:56:40.950276Z caller=sidecar.go:195 msg="successfully loaded prometheus external labels" external_labels={} 
level=warn ts=2019-12-10T06:56:40.9504769Z caller=prober.go:117 msg="changing probe status" status=not-ready reason="no external labels configured on Prometheus server, uniquely identifying external labels must be configured"
level=info ts=2019-12-10T06:56:40.9507583Z caller=http.go:78 service=http/server component=sidecar msg="internal server shutdown" err="no external labels configured on Prometheus server, uniquely identifying external labels must be configured"
level=info ts=2019-12-10T06:56:40.9508588Z caller=prober.go:137 msg="changing probe status" status=not-healthy reason="no external labels configured on Prometheus server, uniquely identifying external labels must be configured"
level=info ts=2019-12-10T06:56:40.9511293Z caller=grpc.go:117 service=gRPC/server component=sidecar msg="gracefully stopping internal server"
level=info ts=2019-12-10T06:56:40.9513265Z caller=grpc.go:129 service=gRPC/server component=sidecar msg="internal server shutdown" err="no external labels configured on Prometheus server, uniquely identifying external labels must be configured"
level=error ts=2019-12-10T06:56:40.9514806Z caller=main.go:194 msg="running command failed" err="no external labels configured on Prometheus server, uniquely identifying external labels must be configured"
```

Confusing output

```
level=info ts=2019-12-10T06:56:40.950276Z caller=sidecar.go:195 msg="successfully loaded prometheus external labels" external_labels={} 
level=warn ts=2019-12-10T06:56:40.9504769Z caller=prober.go:117 msg="changing probe status" status=not-ready reason="no external labels configured on Prometheus server, uniquely identifying external labels must be configured"
```

In line 1, the log output represents the external labels for the successful loading of Prometheus
In line 2, no external labels for Prometheus were found
Both logs are printed at the same second

**Comment by ElderMael** [comment]
@johncming did you fix this?

I am having this error only on K8s version 1.15.x on AKS, not on minikube with K8s version 1.17

**Comment by xsorifc28** [comment]
FWIW, I was able to fix this by adding to the prometheus deployment.

```yaml
spec:
  ...
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
```
The default `externalLabels` were not being written to the `prometheus.env.gz` secret, they are written when these empty selector values are provided.

Using `stable/prometheus-operator` helm chart (app v0.38.1).
