### ISSUE TITLE
Receive crash continuously 

### ISSUE THREAD

**Issue by omerlh** [thanos-io/thanos#1932]
**Thanos, Prometheus and Golang version used**:
Thanos - 0.9.0
Prometheus - 2.15.1

**Object Storage Provider**: S3

**What happened**:
Thanos receive pods keep crashing:
![image](https://user-images.githubusercontent.com/6730584/71683472-4b9d4400-2d9b-11ea-9d69-e4058ad62460.png)

Thanos installed using kube-thanos. Prometheus is installed using Prometheus operator, and configure with remote write using:

```yaml
remoteWrite: 
  - url: http://thanos-receive.monitoring.svc.cluster.local:19291/api/v1/receive
```

**What you expected to happen**:

Thanos receive work as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy receive
2. Configure Prometheus to send data to it.

**Full logs to relevant components**:

<details>Logs
<p>

```
level=debug ts=2020-01-02T17:56:36.487711206Z caller=main.go:101 msg="maxprocs: Updating GOMAXPROCS=[1]: determined from CPU quota"
level=info ts=2020-01-02T17:56:36.487867582Z caller=main.go:149 msg="Tracing will be disabled"
level=warn ts=2020-01-02T17:56:36.48789661Z caller=receive.go:170 component=receive msg="setting up receive; the Thanos receive component is EXPERIMENTAL, it may break significantly without notice"
level=info ts=2020-01-02T17:56:36.487915919Z caller=options.go:20 component=receive protocol=HTTP msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-01-02T17:56:36.502561595Z caller=options.go:80 component=receive msg="TLS client using system certificate pool"
level=debug ts=2020-01-02T17:56:36.503678848Z caller=receive.go:224 component=receive msg="setting up tsdb"
level=debug ts=2020-01-02T17:56:36.503702581Z caller=receive.go:282 component=receive msg="setting up hashring"
level=debug ts=2020-01-02T17:56:36.503715593Z caller=receive.go:334 component=receive msg="setting up http server"
level=debug ts=2020-01-02T17:56:36.503738813Z caller=receive.go:351 component=receive msg="setting up grpc server"
level=debug ts=2020-01-02T17:56:36.503754519Z caller=receive.go:395 component=receive msg="setting up receive http handler"
level=info ts=2020-01-02T17:56:36.503771063Z caller=factory.go:43 component=receive msg="loading bucket configuration"
level=info ts=2020-01-02T17:56:36.505014947Z caller=receive.go:476 component=receive msg="starting receiver"
level=info ts=2020-01-02T17:56:36.505155533Z caller=receive.go:322 component=receive msg="hashring has changed; server is not ready to receive web requests."
level=info ts=2020-01-02T17:56:36.525192894Z caller=prober.go:127 component=receive msg="changing probe status" status=healthy
level=info ts=2020-01-02T17:56:36.525219184Z caller=http.go:53 component=receive service=http/server component=receive msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-01-02T17:56:36.525356015Z caller=options.go:20 component=receive protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-01-02T17:56:36.525371695Z caller=handler.go:171 component=receive component=receive-handler msg="Start listening for connections" address=0.0.0.0:19291
level=info ts=2020-01-02T17:56:36.619027167Z caller=head.go:584 component=receive component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2020-01-02T17:56:40.522425388Z caller=head.go:584 component=receive component=tsdb msg="replaying WAL, this may take awhile"
level=warn ts=2020-01-02T17:56:44.582847031Z caller=receive.go:246 component=receive err="flushing WAL: read WAL: read records: corruption in segment /var/thanos/receive/wal/00000000 at 25187307: unexpected checksum 66752eb, expected fcd3074d" msg="failed to flush storage"
level=info ts=2020-01-02T17:56:44.582970813Z caller=http.go:78 component=receive service=http/server component=receive msg="internal server shutdown" err="flushing storage: flushing WAL: read WAL: read records: corruption in segment /var/thanos/receive/wal/00000000 at 25187307: unexpected checksum 66752eb, expected fcd3074d"
level=info ts=2020-01-02T17:56:44.583017135Z caller=prober.go:137 component=receive msg="changing probe status" status=not-healthy reason="flushing storage: flushing WAL: read WAL: read records: corruption in segment /var/thanos/receive/wal/00000000 at 25187307: unexpected checksum 66752eb, expected fcd3074d"
level=error ts=2020-01-02T17:56:44.584257526Z caller=main.go:194 msg="running command failed" err="flushing storage: flushing WAL: read WAL: read records: corruption in segment /var/thanos/receive/wal/00000000 at 25187307: unexpected checksum 66752eb, expected fcd3074d"

```

</p>
</details>

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Any logs? What events do you see on the K8s pods?

**Comment by omerlh** [comment]
Sorry - the logs was hidden, I fixed that now.

**Comment by squat** [comment]
Thanos receive is complaining the TSDB WAL is corrupt. Are you re-using a TSBD directory that was created by another component? In any case, if you restart the receiver pointing at another directory, does everything start correctly?

**Comment by omerlh** [comment]
This is the statefulset definition:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: thanos-receive
  name: thanos-receive
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-receive
    spec:
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --label=replica="$(NAME)"
        - --label=receive="true"
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objstore-config
        image: quay.io/thanos/thanos:v0.9.0
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-receive
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: remote-write
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/thanos/receive
          name: thanos-receive-data
          readOnly: false
      terminationGracePeriodSeconds: 120
      volumes:
      - emptyDir: {}
        name: thanos-receive-data
```

The only folder is mounted from an empty folder volume, which I guess is fine, no?
