### ISSUE TITLE
sidecar v0.10.0: envsubst does not work

### ISSUE THREAD

**Issue by sepich** [thanos-io/thanos#2018]
**Thanos, Prometheus and Golang version used**:
v0.10.0

**Object Storage Provider**:
None 

**What happened**:
Trying to render env variable to prometheus config, but it does not work.

prometheus.yml
```yml
global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
    location: $LOCATION

```

docker-compose.yml
```yml
version: '2.4'
services:
  thanos-sidecar:
    container_name: thanos-sidecar
    image: thanosio/thanos:v0.10.0
    user: "65534"
    command:
      - sidecar
      - --tsdb.path=/data
      - --prometheus.url=http://prometheus:9090/
      - --reloader.config-envsubst-file=/tmp/prometheus.yml
      - --reloader.config-file=/prometheus.yml
    environment:
      - LOCATION=test
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - /tmp/data:/data
    mem_limit: 150m
    restart: always

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.15.0
    user: "65534"
    command:
      - --web.enable-lifecycle
      - --config.file=/prometheus.yml
      - --storage.tsdb.path=/data
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - /tmp/data:/data
    mem_limit: 1g
    restart: always
```
Check env:
```
$ docker exec -it thanos-sidecar env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=2296288b1629
TERM=xterm
LOCATION=test
HOME=/home
```
Check result:
```
$ docker exec -it thanos-sidecar cat /tmp/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
    location: $LOCATION
```

**What you expected to happen**:
Expecting to see rendered config with `$LOCATION` (tried `${LOCATION}` too) expanded to `test`

**Full logs to relevant components**:
```
$ docker logs thanos-sidecar
level=info ts=2020-01-21T11:37:36.7560827Z caller=main.go:149 msg="Tracing will be disabled"
level=info ts=2020-01-21T11:37:36.7561793Z caller=sidecar.go:142 msg="no supported bucket was configured, uploads will be disabled"
level=info ts=2020-01-21T11:37:36.7562848Z caller=options.go:20 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-01-21T11:37:36.7571157Z caller=sidecar.go:331 msg="starting sidecar"
level=info ts=2020-01-21T11:37:36.7572562Z caller=prober.go:107 msg="changing probe status" status=ready
level=info ts=2020-01-21T11:37:36.7573049Z caller=prober.go:127 msg="changing probe status" status=healthy
level=info ts=2020-01-21T11:37:36.7573505Z caller=http.go:53 service=http/server component=sidecar msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-01-21T11:37:36.7578129Z caller=grpc.go:98 service=gRPC/server component=sidecar msg="listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2020-01-21T11:37:36.760427Z caller=sidecar.go:199 msg="successfully loaded prometheus external labels" external_labels="{location=\"$LOCATION\"}"
level=info ts=2020-01-21T11:37:36.7703093Z caller=reloader.go:286 component=reloader msg="Prometheus reload triggered" cfg_in=/prometheus.yml cfg_out=/tmp/prometheus.yml rule_dirs=
level=info ts=2020-01-21T11:37:36.7705027Z caller=reloader.go:154 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg=/prometheus.yml out=/tmp/prometheus.yml dirs=
```

**Anything else we need to know**:
I want to use thanos-sidecar without object storage, just aside with `prometheus` and `git-sync` to have configs updated and prometheus reloaded automatically.

**Comment by yeya24** [comment]
@sepich Hello!
The correct way to set the env substitution is to use $(xxx).
And I think we don't have this part in sidecar docs. So it is better to add it.
```
global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
    location: $(LOCATION)
```
