### ISSUE TITLE
Make CI smarter: run certain tests, based on what files are changed.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2257]
As mentioned by amazing @yeya24 here in GitHub Action we can do magic like this:

```
on:
  push:
    paths-ignore:
    - 'docs/**'
```

Wonder if we can improve our CI (make it faster) for just docs changes etc. WDYT?

The only problem is that it's easy to miss that some tests were skipped if some code will move around to `docs` for some reason etc.
