### ISSUE TITLE
 MountVolume.SetUp failed for volume "thanos-storage-secret" : secrets "thanos-storage-secret" not found

### ISSUE THREAD

**Issue by Rajeev9045** [thanos-io/thanos#2280]
Facing issue with `MountVolume.SetUp failed for volume "thanos-storage-secret" : secrets "thanos-storage-secret" not found` 
I am using values.yaml file provided in `https://github.com/thanos-io/thanos/tree/master/tutorials/kubernetes-helm`
If I exclude values from values.yaml the pod itself doesn't get created.
```
  extraSecretMounts:
  - name: thanos-storage-secret
    mountPath: /etc/secret/
    subPath: sa
    readOnly: false
    secretName: thanos-storage-secret
```
Can anyone help here?.

If i check secret `thanos-storage-secret` deson't even exist

```
➜  thanos kubectl get secret
NAME                                           TYPE                                  DATA   AGE
default-token-f6swg                            kubernetes.io/service-account-token   3      14d
prometheus-thanos-sidecar-server-token-q69x2   kubernetes.io/service-account-token   3      7m5s
➜  thanos
```
```
➜  thanos kubectl get pod
NAME                                 READY   STATUS     RESTARTS   AGE
prometheus-thanos-sidecar-server-0   0/3     Init:0/1   0          7m47s
➜  thanos
```
