### ISSUE TITLE
Readiness check fails intermittently for thanos-store

### ISSUE THREAD

**Issue by joshulyne** [thanos-io/thanos#2376]
**Thanos, Prometheus version used**:  0.10.1, 2.15.2 
**Object Storage Provider**: AWS S3

**What happened**:
Thanos-store intermittently fails readiness checks. When I look at the pod logs, it seems to be running fine but since readiness checks are not passing, the service is not available, preventing thanos-query from querying object store data. When it does pass the readiness check, it takes over a minute for it to do so. I wondered if I should increase the delay seconds, but I saw another issue somewhere saying liveness/readiness checks should happen immediately?

**How to reproduce it (as minimally and precisely as possible)**:
I realize that for the thanos-store, since it's an intermittent issue it's hard for me to reproduce. But any guidance on how I can diagnose / investigate further into this issue would be great!

**Full logs to relevant components**:
<details> Thanos Store Logs
<p>
level=info ts=2020-04-03T17:50:32.172786587Z caller=main.go:149 msg="Tracing will be disabled"
level=info ts=2020-04-03T17:50:32.172857251Z caller=factory.go:43 msg="loading bucket configuration"
level=info ts=2020-04-03T17:50:32.184665132Z caller=inmemory.go:167 msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=262144000 maxItems=math.MaxInt64
level=info ts=2020-04-03T17:50:32.185619682Z caller=options.go:20 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-04-03T17:50:32.185802527Z caller=store.go:288 msg="starting store node"
level=info ts=2020-04-03T17:50:32.185894435Z caller=prober.go:127 msg="changing probe status" status=healthy
level=info ts=2020-04-03T17:50:32.18588818Z caller=store.go:243 msg="initializing bucket store"
level=info ts=2020-04-03T17:50:32.18612117Z caller=http.go:53 service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-04-03T17:50:32.814360937Z caller=fetcher.go:361 component=block.MetaFetcher msg="successfully fetched block metadata" duration=628.23248ms cached=26 returned=26 partial=0
</p>
</details>

^^ logs look good, and I see `"changing probe status" status=healthy`, but i'm assuming its missing something like: 
```
level=info ts=2020-04-03T17:58:44.678805297Z caller=store.go:249 msg="bucket store ready" init_duration=2m8.964320552s

level=info ts=2020-04-03T17:58:44.678976759Z caller=prober.go:107 msg="changing probe status" status=ready```?  <- Those logs were from a thanos-store that successfully passed the readiness check
```

**Comment by kakkoyun** [comment]
Thanos Store sets its readiness probe immediately after it's ready. Being ready for Thanos Store means that its local index is synced from the bucket after it's initialized and it's ready to serve traffic. So in that sense readiness probe is implemented properly, because without an index Store can't respond to Querier requests. If you have a large amount of data to be synced, this could take a while. I recommend you to try increasing the check count or period.

As an example you can check out example configuration in `kube-thanos`:
https://github.com/thanos-io/kube-thanos/blob/00fe1af48041e136b81b20f179dbb63b1fffc57e/manifests/thanos-store-statefulSet.yaml#L55-L61

I'm not sure about intermittent part though. Could you provide more information on what changes in your system? Is Thanos Store restarting fo a reason?

**Comment by joshulyne** [comment]
Ah I think that's exactly it, I believe I need to increase the failure threshold -- we definitely have large amounts of data so it takes a while (^ like 2m8.964320552s from the log above). I believe the intermittent part was that the time it took was right along the failure threshold. But that explains a lot about why the readiness check takes a while for thanos-store. Thanks so much!

**Comment by Kampe** [comment]
How id you end up solving this?  Increasing liveness and readycheck doesn't do it for me.  Probes are being set, however liveness is failing intermittently.

**Comment by joshulyne** [comment]
I'm pretty sure all I did was increased the failureThreshold to 40:
```
        readinessProbe:
          failureThreshold: 40
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
```

**Comment by sojakub** [comment]
For time travelers: I had the same issue with thanos-store, and I fixed it with these changes:

```
...
        readinessProbe:
          failureThreshold: 240
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 600
...
        resources:
          limits:
            cpu: 420m
            memory: 2Gi
          requests:
            cpu: 123m
            memory: 123Mi
 ...
```
