### ISSUE TITLE
ruler: Ruler Stuck on some queries with latency > interval.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2397]
Detected by our new alert: 

```
alert: ThanosRuleTSDBNotIngestingSamples
  annotations:
    message: Thanos Rule {{$labels.job}} did not ingest any samples for the last 15
      minutes.
  expr: |
    sum by (job) (rate(prometheus_tsdb_head_samples_appended_total{job=~"thanos-rule.*"}[5m])) <= 0
  for: 10m
  labels:
    severity: critical
```
https://github.com/thanos-io/thanos/blob/master/examples/alerts/alerts.md

Investigating.
