### ISSUE TITLE
compact: fails to dedup data from thanos-receive

### ISSUE THREAD

**Issue by sepich** [thanos-io/thanos#2550]
**Thanos, Prometheus and Golang version used**:
v0.12.1

**What happened**:
Tried to use deduplication apeared in https://github.com/thanos-io/thanos/pull/2250
We run 3 thanos-receive with `--label=replica="$(NAME)"` (with no other labels)
So in `bucket inspect` we have:
```
| 01E4N18DW7663APZ5V0B3D3CY1 | 30-03-2020 05:30:00 | 30-03-2020 06:00:00 | 30m0s    | 39h30m0s   | 545,049    | 50,824,911     | 545,054     | 1          | false       | replica=thanos-receive-0 | 0s         | receive   |
| 01E4N18DW8A4Z0ES2GCXBFEVVH | 30-03-2020 05:30:00 | 30-03-2020 06:00:00 | 30m0s    | 39h30m0s   | 545,049    | 50,824,911     | 545,054     | 1          | false       | replica=thanos-receive-2 | 0s         | receive   |
| 01E4N18DW8AR0CRXN0F4N0F7VY | 30-03-2020 05:30:00 | 30-03-2020 06:00:00 | 30m0s    | 39h30m0s   | 545,049    | 50,824,911     | 545,054     | 1          | false       | replica=thanos-receive-1 | 0s         | receive   |
```
And thanos-compact (master-2020-03-27-4e5c2f25) cannot process that due to: `empty external labels are not allowed for Thanos block`
```
level=info ts=2020-03-30T02:24:48.810475048Z caller=compact.go:441 msg="compact blocks" count=3 mint=1583366400000 maxt=1584576000000 ulid=01E4M5KHECGZQ1BV66E6SQGH78 sources="[01E3V4JCD9Z5BK5B8A5KSYGMV3 01E3WMG1NXY78KB6GKXR594FMS 01E3T3609JKQ5V1TKZ8NYTGE58]" duration=4h13m14.923098503s
level=info ts=2020-03-30T02:24:48.955331391Z caller=compact.go:704 compactionGroup=0@{} compactionGroupKey=0@17241709254077376921 msg="compacted blocks" blocks="[/data/compact/0@17241709254077376921/01E3V4JCD9Z5BK5B8A5KSYGMV3 /data/compact/0@17241709254077376921/01E3WMG1NXY78KB6GKXR594FMS /data/compact/0@17241709254077376921/01E3T3609JKQ5V1TKZ8NYTGE58]" duration=4h13m15.067940785s overlapping_blocks=true
level=info ts=2020-03-30T02:27:09.523306206Z caller=bucket.go:487 msg="synchronizing block metadata"
level=info ts=2020-03-30T02:27:12.627788832Z caller=bucket.go:500 msg="downloaded blocks meta.json" num=101
level=warn ts=2020-03-30T02:29:27.744301881Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="error executing compaction: compaction: group 0@17241709254077376921: upload of 01E4M5KHECGZQ1BV66E6SQGH78 failed: empty external labels are not allowed for Thanos block."
level=info ts=2020-03-30T02:29:27.744689058Z caller=http.go:81 service=http/server component=compact msg="internal server shutdown" err="error executing compaction: compaction: group 0@17241709254077376921: upload of 01E4M5KHECGZQ1BV66E6SQGH78 failed: empty external labels are not allowed for Thanos block."
level=info ts=2020-03-30T02:29:27.744812002Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="error executing compaction: compaction: group 0@17241709254077376921: upload of 01E4M5KHECGZQ1BV66E6SQGH78 failed: empty external labels are not allowed for Thanos block."
level=error ts=2020-03-30T02:29:27.745248074Z caller=main.go:212 err="group 0@17241709254077376921: upload of 01E4M5KHECGZQ1BV66E6SQGH78 failed: empty external labels are not allowed for Thanos block.\ncompaction\nmain.runCompact.func5\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:377\nmain.runCompact.func6.1\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:428\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/go/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:72\nmain.runCompact.func6\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:427\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.0.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nerror executing compaction\nmain.runCompact.func6.1\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:455\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/go/src/github.com/thanos-io/thanos/pkg/runutil/runutil.go:72\nmain.runCompact.func6\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:427\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.0.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\ncompact command failed\nmain.main\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/main.go:212\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
```
We can add one more label for new data.
But compactor starts processing from oldest data to newest, and failing. So, we need a proper way to process historical data too.

**What you expected to happen**:
I'm able to deduplicate data from 3 HA thanos-receive as the feature promises.

**How to reproduce it (as minimally and precisely as possible)**:
Start 3x thanos-receive :
<details>
<summary>Args</summary>

```
          args:
          - receive
          - |
            --objstore.config=type: GCS
            config:
              bucket: jb-thanos
          - --tsdb.path=/data
          - --tsdb.retention=1d
          - --tsdb.min-block-duration=30m  # have to be >2x(prometheus side 15m), https://github.com/thanos-io/thanos/issues/2114
          - --tsdb.max-block-duration=30m
          - --label=replica="$(NAME)"
          - --receive.local-endpoint=$(NAME).thanos-receive.monitoring.svc.cluster.local:10901
          - --receive.hashrings-file=/cfg/hashrings.json
          - --receive.replication-factor=3
```

</details>
<details>
<summary>Hashring</summary>

```
    [
      {
        "hashring": "soft-tenants",
        "endpoints": [
          "thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901"
        ]
      }
    ]
```

</details>
