### ISSUE TITLE
Thanos ruler UI is not responsive after running normall for sometime 

### ISSUE THREAD

**Issue by homelessnessbo** [thanos-io/thanos#2708]
Component: ruler
Docker image: official v0.13.0-rc.0, but we observed the same behaviour on previous images too.

**What happened**:

After running for some undefined time (feels like a few hours, hard to measure) - Thanos ruler UI loads forever and never finishes nor it gives any standard HTTP error message, just loading indicator going forever.

The rest of UIs (we mostly use query UI) are always responsive, though they are short-living and restart quite often.

Rules executions are going on normally, alerts are being sent. 

**How to reproduce it (as minimally and precisely as possible)**:

I really don't know what is the circumstances to cause that. 

**Full logs to relevant components**:

There is nothing unusual in log (warn level) except standard logs about query executions. 

**Anything else we need to know**:

We run 1.2k rules on this certain instance,
limits of the container are 3 vCPU and 6GB of RAM, where 1.5 vCPU and 4.5GB are used on average.

**Comment by homelessnessbo** [comment]
ah yea, it has nginx-ingress with oAuth2 in front of it:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://$SOME_ADDRESS/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$SOME_ADDRESS//auth
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: $SOME_HOST
    http:
      paths:
      - backend:
          serviceName: rule-service
          servicePort: 10902
        path: /ruler
  tls:
  - hosts:
    - $SOME_HOST
    secretName: $SOME_SECRET

```
