### ISSUE TITLE
Sidecar: not upload promethues data to oss storage 

### ISSUE THREAD

**Issue by klzsysy** [thanos-io/thanos#2709]
**Thanos, Prometheus and Golang version used**:
```
/ # thanos --version
thanos, version 0.12.2 (branch: HEAD, revision: 52e10c6e0f644ea98fd057e7fbece828d8dd07c7)
  build user:       circleci@241aa351893e
  build date:       20200430-16:37:24
  go version:       go1.13.1

prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2
```

**Object Storage Provider**:
ALIYUNOSS

**What happened**:
sidecar not upload promethues data to oss

**What you expected to happen**:
upload promethues data to oss

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    chart: prometheus
    heritage: Tiller
    release: istio
  name: prometheus
  namespace: istio-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      creationTimestamp: null
      labels:
        app: prometheus
        chart: prometheus
        heritage: Tiller
        release: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 2
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
              weight: 2
            - preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - s390x
              weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - name: thanos-sidecar
          image: quay.io/thanos/thanos:v0.12.2
          args:
            - sidecar
            - --prometheus.url=http://localhost:9090
            - --objstore.config-file=/config/bucket_config.yaml
            - --tsdb.path=/prometheus
            - --shipper.upload-compacted
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 100Mi
          ports:
            - containerPort: 10902
              name: http-metrics
              protocol: TCP
            - containerPort: 10901
              name: grpc-storageapi
              protocol: TCP
          volumeMounts:
            - mountPath: /prometheus
              name: promethues-temp
            - mountPath: /config/
              name: thanos-objstore-config
        - args:
            - '--storage.tsdb.retention.time=12h'
            - --storage.tsdb.min-block-duration=1m
            - --storage.tsdb.max-block-duration=1m
            - '--web.enable-lifecycle'
            - --web.enable-admin-api
            - '--config.file=/etc/prometheus/prometheus.yml'
          image: 'docker.io/prom/prometheus:v2.18.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: prometheus
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: 10m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /prometheus
              name: promethues-temp
            - mountPath: /etc/prometheus
              name: config-volume
            - mountPath: /etc/istio-certs
              name: istio-certs
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/logging: 'true'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: promethues-temp
        - configMap:
            name: thanos-objstore-config
          name: thanos-objstore-config
        - configMap:
            defaultMode: 420
            name: prometheus
          name: config-volume
        - name: istio-certs
          secret:
            defaultMode: 420
            secretName: istio.default
---
apiVersion: v1
data:
  bucket_config.yaml: |-
    type: ALIYUNOSS
    config:
      endpoint: oss-cn-hangzhou-internal.aliyuncs.com
      bucket: monitoring-thanos-storage
      access_key_id: LTAI4GJucZWvM***
      access_key_secret: *****
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: istio-system

```

**Full logs to relevant components**:

Uncomment if you would like to post collapsible logs:

thanos sidecar log:

<details>Logs
<p>

```
level=debug ts=2020-06-03T09:14:17.52291171Z caller=main.go:103 msg="maxprocs: Leaving GOMAXPROCS=[16]: CPU quota undefined"
--
  | level=info ts=2020-06-03T09:14:17.523278309Z caller=main.go:152 msg="Tracing will be disabled"
  | level=info ts=2020-06-03T09:14:17.523572193Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
  | level=info ts=2020-06-03T09:14:17.523974216Z caller=factory.go:46 msg="loading bucket configuration"
  | level=error ts=2020-06-03T09:14:17.529219019Z caller=sidecar.go:312 err="WAL dir is not accessible. Is this dir a TSDB directory? If yes it is shared with TSDB?: stat /prometheus/wal: no such file or directory"
  | level=info ts=2020-06-03T09:14:17.529268763Z caller=sidecar.go:356 msg="starting sidecar"
  | level=info ts=2020-06-03T09:14:17.529434441Z caller=reloader.go:157 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg= out= dirs=
  | level=info ts=2020-06-03T09:14:17.529479505Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
  | level=info ts=2020-06-03T09:14:17.529724658Z caller=intrumentation.go:48 msg="changing probe status" status=ready
  | level=info ts=2020-06-03T09:14:17.530266841Z caller=grpc.go:106 service=gRPC/server component=sidecar msg="listening for StoreAPI gRPC" address=0.0.0.0:10901
  | level=info ts=2020-06-03T09:14:17.529546495Z caller=http.go:56 service=http/server component=sidecar msg="listening for requests and metrics" address=0.0.0.0:10902
  | level=warn ts=2020-06-03T09:14:17.531734739Z caller=sidecar.go:368 msg="failed to get Prometheus flags. Is Prometheus running? Retrying" err="request config against http://localhost:9090/api/v1/status/flags:  Get http://localhost:9090/api/v1/status/flags:  dial tcp [::1]:9090: connect: connection refused"
  | level=warn ts=2020-06-03T09:14:19.533122053Z caller=sidecar.go:391 msg="found that TSDB block time is not 2h. Only 2h block time is recommended." block-time=1m
  | level=info ts=2020-06-03T09:14:19.539176125Z caller=sidecar.go:220 msg="successfully loaded prometheus external labels" external_labels="{monitor=\"cluster-prod\", region=\"hangzhou\", replica=\"A\"}"
  | level=info ts=2020-06-03T09:14:19.539232996Z caller=intrumentation.go:48 msg="changing probe status" status=ready
```

</p>
</details>

promethues log:

<details>Logs
<p>

```

  | level=info ts=2020-06-03T09:14:17.741Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.1, branch=HEAD, revision=ecee9c8abfd118f139014cb1b174b08db3f342cf)"
-- | --
  | level=info ts=2020-06-03T09:14:17.741Z caller=main.go:338 build_context="(go=go1.14.2, user=root@2117a9e64a7e, date=20200507-16:51:47)"
  | level=info ts=2020-06-03T09:14:17.741Z caller=main.go:339 host_details="(Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 prometheus-7f4b6765d7-w6fr7 (none))"
  | level=info ts=2020-06-03T09:14:17.741Z caller=main.go:340 fd_limits="(soft=1048576, hard=1048576)"
  | level=info ts=2020-06-03T09:14:17.741Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
  | level=info ts=2020-06-03T09:14:17.744Z caller=web.go:523 component=web msg="Start listening for connections" address=0.0.0.0:9090
  | level=info ts=2020-06-03T09:14:17.744Z caller=main.go:678 msg="Starting TSDB ..."
  | level=info ts=2020-06-03T09:14:17.750Z caller=head.go:575 component=tsdb msg="Replaying WAL, this may take awhile"
  | level=info ts=2020-06-03T09:14:17.751Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
  | level=info ts=2020-06-03T09:14:17.751Z caller=head.go:627 component=tsdb msg="WAL replay completed" duration=868.706µs
  | level=info ts=2020-06-03T09:14:17.753Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
  | level=info ts=2020-06-03T09:14:17.753Z caller=main.go:695 msg="TSDB started"
  | level=info ts=2020-06-03T09:14:17.753Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
  | level=info ts=2020-06-03T09:14:17.756Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2020-06-03T09:14:17.759Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2020-06-03T09:14:17.761Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2020-06-03T09:14:17.763Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2020-06-03T09:14:17.765Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2020-06-03T09:14:17.766Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
  | level=info ts=2020-06-03T09:14:17.766Z caller=main.go:646 msg="Server is ready to receive web requests."
  | level=info ts=2020-06-03T09:16:09.528Z caller=compact.go:495 component=tsdb msg="write block" mint=1591175662886 maxt=1591175700000 ulid=01E9WQEB78BE4WAK3H4JRW5X59 duration=16.59171727s
  | level=info ts=2020-06-03T09:16:10.451Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=516.589857ms
  | level=info ts=2020-06-03T09:16:46.946Z caller=compact.go:495 component=tsdb msg="write block" mint=1591175700000 maxt=1591175760000 ulid=01E9WQFFDVA13A1H1MMFV80TAW duration=16.935280996s
  | level=info ts=2020-06-03T09:16:47.846Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=574.453751ms
  | level=info ts=2020-06-03T09:17:46.095Z caller=compact.go:495 component=tsdb msg="write block" mint=1591175760000 maxt=1591175820000 ulid=01E9WQHA0SZA75P16XA8C7CT30 duration=16.085306947s
  | level=info ts=2020-06-03T09:17:47.031Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=527.96743ms
  | level=info ts=2020-06-03T09:17:50.182Z caller=head.go:734 component=tsdb msg="WAL checkpoint complete" first=0 last=1 duration=3.150715152s
  | level=info ts=2020-06-03T09:18:46.514Z caller=compact.go:495 component=tsdb msg="write block" mint=1591175820000 maxt=1591175880000 ulid=01E9WQK4KSWCGQY4T1QMXEQHY0 duration=16.505293374s
  | level=info ts=2020-06-03T09:18:47.474Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=539.642968ms
  | level=info ts=2020-06-03T09:19:45.970Z caller=compact.go:495 component=tsdb msg="write block" mint=1591175880000 maxt=1591175940000 ulid=01E9WQMZ6S6GD10A20ZT4P7WX9 duration=15.961143328s
  | level=info ts=2020-06-03T09:19:46.954Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=547.729076ms
  | level=info ts=2020-06-03T09:19:49.875Z caller=head.go:734 component=tsdb msg="WAL checkpoint complete" first=2 last=3 duration=2.920522625s
  | level=info ts=2020-06-03T09:20:46.112Z caller=compact.go:495 component=tsdb msg="write block" mint=1591175940000 maxt=1591176000000 ulid=01E9WQPSSRDR4AAE7SAPZFDTBQ duration=16.103512475s
  | level=info ts=2020-06-03T09:20:46.996Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=542.294985ms
  | level=info ts=2020-06-03T09:21:46.002Z caller=compact.go:495 component=tsdb msg="write block" mint=1591176000000 maxt=1591176060000 ulid=01E9WQRMCSGSG10MP6XR22GCK0 duration=15.993127816s
  | level=info ts=2020-06-03T09:21:47.142Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=675.474052ms


```

</p>
</details>

Has been running for more than two hours, but there is no data in the oss bucket (new), sidecars didn't upload the related logs

**Comment by xiaodangjia457** [comment]
hello, i have encountered the same problem, do you fix this issue?

**Comment by klzsysy** [comment]
> hello, i have encountered the same problem, do you fix this issue?

explicit declaration `--tsdb.path` sidecar parameter 

```yaml
        - args:
            - sidecar
            - '--log.level=debug'
            - '--prometheus.url=http://localhost:9090'
            - '--objstore.config-file=/config/bucket_config.yaml'
            - '--tsdb.path=/prometheus'
          image: 'registry.forchange.cn/public/thanos:v0.12.2'
```
