### ISSUE TITLE
receiver: "Out of bounds metric" reported for time series that is only 2 seconds old

### ISSUE THREAD

**Issue by itzg** [thanos-io/thanos#2918]
**Thanos, Prometheus and Golang version used**: 

Docker images `quay.io/thanos/thanos:master-2020-07-09-60ede4c1` and `quay.io/thanos/thanos:master-2020-07-20-bc7dad08`

**Object Storage Provider**: 

GCP

**What happened**: 

POST to receiver's `/api/v1/receive` endpoint and it responded with 409. Receiver logs reported:

```
level=debug ts=2020-07-21T21:15:56.671868671Z caller=writer.go:85 component=receive component=receive-writer msg="Out of bounds metric" lset="{__name__=\"ping_available\", resource=\"123456\", resource_label=\"123456-test\", system_monitoringZone=\"dfw\", tenant_id=\"1222333\"}" sample="value:100 timestamp:1595366154246 "
level=warn ts=2020-07-21T21:15:56.671972045Z caller=writer.go:99 component=receive component=receive-writer msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1
```

NOTE: timestamp `1595366154246` = `Tuesday, July 21, 2020 9:15:54.246 PM GMT` and the log is reporting 2 seconds after that at `2020-07-21T21:15:56.671868671Z`.

**What you expected to happen**: 

A 200 response code and metricset accepted

**How to reproduce it (as minimally and precisely as possible)**: 

- ensure TSDB directory is newly created
- post metricset in log reported above

**Full logs to relevant components**:

Full logs are not practical since failure was part of a larger test case. Relevant log lines are provided above.

**Anything else we need to know**:

Receiver deployed in GKE with pod template:
```yaml
      containers:
        - image: quay.io/thanos/thanos:master-2020-07-20-bc7dad08
          name: thanos-receiver
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - receive
            - --log.level=debug
            - --tsdb.path=/data
            - --objstore.config-file=/etc/thanos/objstore/objstore-config.yaml
            - --receive.hashrings-file=/etc/thanos/receiver/hashring.json
            - --receive.local-endpoint=$(POD_NAME).thanos-receiver:10901
            - --receive.tenant-label-name="tenant_bucket"
            - --label
            - "receive_replica=\"$(POD_NAME)\""
            - --tsdb.retention=0d
          volumeMounts:
            - mountPath: /etc/thanos/objstore/
              name: objstore-config
            - mountPath: /etc/thanos/receiver/
              name: receiver-config
            - mountPath: /data
              name: data
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 10902
              name: http
            - containerPort: 19291
              name: write
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
      volumes:
        - name: objstore-config
          secret:
            secretName: thanos-poc-objstore-config
        - name: receiver-config
          configMap:
            name: thanos-receiver
```
