### ISSUE TITLE
Store Gateway: memcached, "create index header reader: write index header: new index reader : get object attributes of <block>/index: The specified key does not exist."

### ISSUE THREAD

**Issue by Jakob3xD** [thanos-io/thanos#2922]
**Thanos, Prometheus and Golang version used**:
Docker Thanos: quay.io/thanos/thanos:v0.14.0

**Object Storage Provider**:
Docker Minio S3
Docker memcached: MEMCACHED_VERSION=1.6.6

**What happened**:
Using 4 Minio servers.
On each Minio server is a store gateway and a memcached.
The store gateway tries to load blocks from the S3 cached in memcached,
but fails as the blocks are located on the other Minio.

**What you expected to happen**:
The store gateway should only try to load blocks which it is responsibility for defined in the bucket config.
Maybe prefix the data with some value to only load blocks with his prefix.

**How to reproduce it (as minimally and precisely as possible)**:
Two or more servers with Minio memcached and store gateway.
Each Minio has different Data. The Store gateway connects to all memcached services on all servers.

**Full logs to relevant components**:
<details>Logs
<p>

```
level=debug ts=2020-07-22T13:40:38.151917448Z caller=main.go:102 msg="maxprocs: Leaving GOMAXPROCS=[24]: CPU quota undefined"
level=info ts=2020-07-22T13:40:38.152214713Z caller=main.go:151 msg="Tracing will be disabled"
level=info ts=2020-07-22T13:40:38.152337963Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2020-07-22T13:40:38.152856018Z caller=caching_bucket_factory.go:68 msg="loading caching bucket configuration"
level=info ts=2020-07-22T13:40:38.153654561Z caller=memcached.go:47 msg="created memcached cache"
level=info ts=2020-07-22T13:40:38.153808005Z caller=factory.go:33 msg="loading index cache configuration"
level=info ts=2020-07-22T13:40:38.154502362Z caller=memcached.go:54 msg="created memcached index cache"
level=info ts=2020-07-22T13:40:38.155475363Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-07-22T13:40:38.155573078Z caller=grpc.go:95 service=gRPC/server component=store msg="registering as gRPC StoreAPI"
level=info ts=2020-07-22T13:40:38.156228615Z caller=store.go:374 msg="starting store node"
level=info ts=2020-07-22T13:40:38.156359249Z caller=store.go:321 msg="initializing bucket store"
level=info ts=2020-07-22T13:40:38.156435596Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2020-07-22T13:40:38.156522853Z caller=http.go:56 service=http/server component=store msg="listening for requests and metrics" address=127.0.0.1:19190
level=info ts=2020-07-22T13:40:38.235978353Z caller=fetcher.go:452 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=79.55005ms cached=83 returned=61 partial=0
level=debug ts=2020-07-22T13:40:38.238616279Z caller=bucket.go:447 msg="loading new block" id=01ED8HGGSSEY92C202X8CEEPDM
level=debug ts=2020-07-22T13:40:38.238606445Z caller=bucket.go:447 msg="loading new block" id=01EDV8CFSYJPZ4Z9VYQWSRTPCN
level=debug ts=2020-07-22T13:40:38.23864704Z caller=bucket.go:447 msg="loading new block" id=01EDV9QYC1YGRX8CBDRXSZJXBQ
level=debug ts=2020-07-22T13:40:38.238701085Z caller=binary_reader.go:456 msg="failed to read index-header from disk; recreating" path=/var/thanos/store/01ED8HGGSSEY92C202X8CEEPDM/index-header err="try lock file: open /var/thanos/store/01ED8HGGSSEY92C202X8CEEPDM/index-header: no such file or directory"
[...]
level=debug ts=2020-07-22T13:40:38.273817846Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=debug ts=2020-07-22T13:40:38.274705707Z caller=stdlib.go:89 s3TraceMsg="HEAD /node/01ED8HGGSSEY92C202X8CEEPDM/index HTTP/1.1\r"
level=debug ts=2020-07-22T13:40:38.274826731Z caller=stdlib.go:89 s3TraceMsg="HTTP/1.1 404 Not Found\r"
level=debug ts=2020-07-22T13:40:38.27488157Z caller=stdlib.go:89 s3TraceMsg=---------END-HTTP---------
level=debug ts=2020-07-22T13:40:38.275087798Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=warn ts=2020-07-22T13:40:38.275477315Z caller=bucket.go:454 msg="loading block failed" elapsed=36.864168ms id=01ED8HGGSSEY92C202X8CEEPDM err="create index header reader: write index header: new index reader: get object attributes of 01ED8HGGSSEY92C202X8CEEPDM/index: The specified key does not exist."
```

</p>
</details>

**Anything else we need to know**:
<details>store memcache configs:
<p>

store_caching_bucket:
```
type: memcached
config:
  addresses:
    - 192.168.3.21:11211
    - 192.168.3.20:11211
    - 192.168.3.19:11211
    - 192.168.3.18:11211
  timeout: 5s
  max_idle_connections: 40
  max_async_concurrency: 20
  max_async_buffer_size: 2048
  max_item_size: 1MiB
  max_get_multi_concurrency: 20
  max_get_multi_batch_size: 0
  dns_provider_update_interval: 300s

chunk_subrange_size: 16000
max_chunks_get_range_requests: 3
chunk_object_attrs_ttl: 24h
chunk_subrange_ttl: 24h
blocks_iter_ttl: 5m
metafile_exists_ttl: 2h
metafile_doesnt_exist_ttl: 15m
metafile_content_ttl: 24h
metafile_max_size: 1MiB
```

store_index_caching:
```
type: MEMCACHED
config:
  addresses:
    - 192.168.3.21:11211
    - 192.168.3.20:11211
    - 192.168.3.19:11211
    - 192.168.3.18:11211
  timeout: 5s
  max_idle_connections: 40
  max_async_concurrency: 20
  max_async_buffer_size: 2048
  max_item_size: 1MiB
  max_get_multi_concurrency: 20
  max_get_multi_batch_size: 0
  dns_provider_update_interval: 300s

```

</p>
</details>
