### ISSUE TITLE
Querier cannot speak to external sidecar

### ISSUE THREAD

**Issue by atamgp** [thanos-io/thanos#2978]
**Thanos, Prometheus and Golang version used**: 
thanos: charts.bitnami.com/bitnami 2.0.0
prometheus-operator with sidecar: charts.bitnami.com/bitnami0.22.3 
sidecar image: 0.14.0-scratch-r3

**What happened**:
I have 2 eks clusters both running prometheus-operator.
1 cluster has thanos installed (above chart) and needs querier to add the sidecar of the other cluster:
Thanos is registering its local sidecar, the storage gateway but **not the external sidecar**:

cluster 1 (querier) -> aws route 55 (dns) -> nlb loadbalancer -> nginx ingress -> service -> prometheus pod -> sidecar port 10901

**What you expected to happen**:
For the external sidecar to be added to stores in Querie

**Helpful facts**:
From my laptop I can **grpcurl list** the side-car on port 443 which shows the route to work.
response: `Failed to list services: server does not support the reflection API`
I had to enable ALPN policy (HTTP2Optional) on the NLB to make this work.
This ping also works from a busybox pod in the **Thanos cluster** in the **same ns as querier**.
These show up in the nginx  logs where I **cannot find entries coming from querier...**

**How to reproduce it (as minimally and precisely as possible)**:
have 2 clusters, try to add the sidecar from 1 to the querier in the other. Use nginx ingress for this.

**Full logs to relevant components**:
**Querier:**
`level=warn ts=2020-08-04T10:33:05.274486641Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from XXXXXXXXX:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=XXXXXXXXXX:443`

**Sidecar:**
```
level=info ts=2020-08-04T07:48:09.710243084Z caller=main.go:151 msg="Tracing will be disabled"
level=info ts=2020-08-04T07:48:09.710624498Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-08-04T07:48:09.710771643Z caller=grpc.go:92 service=gRPC/server component=sidecar msg="registering as gRPC StoreAPI and RulesAPI"
level=info ts=2020-08-04T07:48:09.71109473Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2020-08-04T07:48:09.711510731Z caller=sidecar.go:301 msg="starting sidecar"
level=info ts=2020-08-04T07:48:09.711645564Z caller=reloader.go:198 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg= out= dirs=
level=info ts=2020-08-04T07:48:09.712128709Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2020-08-04T07:48:09.712603212Z caller=grpc.go:119 service=gRPC/server component=sidecar msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2020-08-04T07:48:09.712795694Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2020-08-04T07:48:09.712814177Z caller=http.go:56 service=http/server component=sidecar msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-08-04T07:48:14.724274654Z caller=sidecar.go:163 msg="successfully loaded prometheus external labels" external_labels="{cluster=\"tcloud-cloudworks\", prometheus=\"kube-system/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"
level=info ts=2020-08-04T07:48:14.724382853Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2020-08-04T09:00:16.785707212Z caller=shipper.go:361 msg="upload new block" id=01EEWB5VEM0YRJVFH72RF0TY34
level=info ts=2020-08-04T11:00:16.728795796Z caller=shipper.go:361 msg="upload new block" id=01EEWJ1JPKVYG482MRGGTFJAFV
```

**Anything else we need to know**:

**Querier config:**
```
- query
        - --log.level=debug
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --query.replica-label=replica
        - --store=dnssrv+_grpc._tcp.thanos-storegateway.kube-system.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.prometheus-operator-prometheus-thanos.kube-system.svc
        - --store=dns+thanos-sidecar.DNSNAME:443
        image: docker.io/bitnami/thanos:0.14.0-scratch-r1
```
Changing `- --store=dns+thanos-sidecar.DNSNAME:443`  to `- --store=thanos-sidecar.DNSNAME:443` did not have any effect.

**Sidecar config:**
```
- sidecar
    - --prometheus.url=http://localhost:9090
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --tsdb.path=/prometheus/
    - --objstore.config=$(OBJSTORE_CONFIG)
    - --log.level=info
```
**Sidecar Nginx/Ingress config**
We are terminating **tls** in NLB
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 360s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 360s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 360s
  creationTimestamp: "2020-07-30T08:58:56Z"
  generation: 7
  name: thanos-sidecar
  namespace: kube-system
  resourceVersion: "2043742"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/thanos-sidecar
  uid: db27bbe0-4e60-460c-b841-13000a63e8f3
spec:
  rules:
  - host: thanos-sidecar.DNSNAME
    http:
      paths:
      - backend:
          serviceName: thanos-sidecar
          servicePort: 10901
status:
  loadBalancer:
    ingress:
    - ip: XXXX
    - ip: XXXX
    - ip: XXXX
```

**Comment by atamgp** [comment]
Looking at the [code](https://github.com/thanos-io/thanos/blob/master/pkg/query/storeset.go) line 468 and 488, 
If don't understand that there is no errror on line 468 **"dialing connection"** in combination with the fact that there is no entry in nginx of an incoming call....

**Comment by atamgp** [comment]
**Update 2**
1. On the external sidecar cluster, I also deployed a local Thanos Query and connect it to that local side-car, which is working. 
In that query UI I can see the side-car under Stores

2. I exposed that external side-car under t**hanos-sidecar**.DOMAIN.org and its new local Query under 
**thanos-grpc**.DOMAIN.org of which the Thanos Query in the other cluster **cannot find either**. 
From my laptop I can query there Info (metadata):

❯ grpcurl -insecure -import-path=protobuf -import-path=thanos/pkg/    -proto=store/storepb/rpc.proto  **thanos-sidecar**.DOMAIN.org:443 thanos.Store/Info
```
{
  "labels": [
    {
      "name": "cluster",
      "value": "tcloud-cloudworks"
    },
    {
      "name": "prometheus",
      "value": "kube-system/prometheus-operator-prometheus"
    },
    {
      "name": "prometheus_replica",
      "value": "prometheus-prometheus-operator-prometheus-0"
    }
  ],
  "minTime": "1596696389180",
  "maxTime": "9223372036854775807",
  "storeType": "SIDECAR",
  "labelSets": [
    {
      "labels": [
        {
          "name": "cluster",
          "value": "tcloud-cloudworks"
        },
        {
          "name": "prometheus",
          "value": "kube-system/prometheus-operator-prometheus"
        },
        {
          "name": "prometheus_replica",
          "value": "prometheus-prometheus-operator-prometheus-0"
        }
      ]
    }
  ]
}

```
❯ grpcurl -insecure -import-path=protobuf -import-path=thanos/pkg/    -proto=store/storepb/rpc.proto  **thanos-grpc**.DOMAIN.org:443 thanos.Store/Info
```
{
  "minTime": "1596696389180",
  "maxTime": "9223372036854775807",
  "storeType": "QUERY",
  "labelSets": [
    {
      "labels": [
        {
          "name": "cluster",
          "value": "tcloud-cloudworks"
        },
        {
          "name": "prometheus",
          "value": "kube-system/prometheus-operator-prometheus"
        },
        {
          "name": "prometheus_replica",
          "value": "prometheus-prometheus-operator-prometheus-0"
        }
      ]
    }
  ]
}
```

**This means that that external sidecar is NOT the problem**. The problem is the Thanos Query component  client implementation which can talk to a local sidecar but **not to an external sidecar on another cluster**.

Changing its config to `--store=dns+thanos-grpc.DOMAIN.org:443`   got me these errors in the log:

`level=warn ts=2020-08-06T10:21:29.690134519Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from IP3:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=IP3:443`

`level=warn ts=2020-08-06T10:21:29.690537351Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from IP1:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=IP1:443`

`level=warn ts=2020-08-06T10:21:29.690703502Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from IP2:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=IP2:443
`
These 3 provides IP's are indeed the IP's of the other clusters's  NLB (in 3 availibility zones). So Route53(DNS) translation to NLB address to NLB ip's is also good.

The NLB are forwarding to the EKS Nodes Ingress and to the right Pods.
This is proved to be working with the above grpcurl test.
Hence my conclusion that somehow Thanos Query is doing something wrong in the request to the external side-car in my use-case. There is a difference in the way Query sends its request vs grpcurl.
**The requests from central Query is not even reaching the logs of the nginx ingress....**

**Comment by Sadzeih** [comment]
I have the same issue! Would love to see a fix

**Comment by avenda** [comment]
The same here!

**Comment by avenda** [comment]
We solved with a proxy. The Querier read the "local" k8s service and envoy (grpc) upstream the external sidecar.

```yaml
  ## Statically configure store APIs to connect with Thanos Querier
  ##
  stores:
    - dnssrv+_n0._tcp.envoy # n0 is a alias port (envoy config)
```

**Comment by roysha1** [comment]
Thanks @avenda! Can you please share you service.yaml?

**Comment by avenda** [comment]
@roysha1 which services?

**Comment by roysha1** [comment]
@avenda, sorry, didn't noticed you mentioned envoy.
It proxies the external urls?

**Comment by avenda** [comment]
@roysha1 Yep

**Comment by roysha1** [comment]
@avenda Thanks! can you please share your proxy configs? Thanks!

**Comment by avenda** [comment]
@roysha1 
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: cluster_name, host_rewrite: my_external_sidecar.domain.net }
          http_filters:
          - name: envoy.router
  clusters:
  - name: cluster_name
    connect_timeout: 30s
    type: logical_dns
    http2_protocol_options: {}
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    hosts: [{ socket_address: { address: my_external_sidecars.domain.net, port_value: 443 }}]
    tls_context:
      common_tls_context:
        alpn_protocols:
        - h2
        - http/1.1
      sni: my_external_sidecars.domain.net
```
My ingress using nginx controller 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    nginx.ingress.kubernetes.io/protocol: h2c
    nginx.ingress.kubernetes.io/proxy-read-timeout: "160"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: sicecard-instance-1
spec:
  rules:
  - host: my_external_sidecars.domain.net
    http:
      paths:
      - backend:
          serviceName: sicecard-instance-1-services
          servicePort: 10901
  tls:
  - hosts:
    - my_external_sidecars.domain.net
    secretName: my-tls-secret
```
