### ISSUE TITLE
receive: CPU Saturation

### ISSUE THREAD

**Issue by chaimch** [thanos-io/thanos#2982]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objectstorage
  namespace: monitoring
data:
  objectstorage.yaml: |
    type: S3
    config:
      endpoint: "s3.us-east-1.amazonaws.com"
      bucket: "sre-thanos"
```

**What happened**:
Lost data, please see below
![image](https://user-images.githubusercontent.com/12760278/89361219-4b807080-d6fd-11ea-94f4-0201ea96429e.png)

**What you expected to happen**:
No data loss

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

<details>Receiver Logs
<p>

```
level=error ts=2020-08-05T01:32:26.233522015Z caller=handler.go:299 component=receive component=receive-handler err="replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:26.248889974Z caller=handler.go:299 component=receive component=receive-handler err="replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:26.414569932Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:26.418503985Z caller=handler.go:299 component=receive component=receive-handler err="replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.114444429Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.114662597Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.114900564Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.115106052Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
```

</p>
</details>

**Anything else we need to know**:

**Environment**:
- thanos-receive-hashrings.json:
```
    [
      {
        "hashring": "soft-tenants",
        "endpoints":
        [
          "thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901"
        ]
      }
    ]
```
- receive args:
```
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: thanos
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/thanos/objectstorage.yaml
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=15d
        - --tsdb.wal-compression
        - --receive.replication-factor=3
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --receive.hashrings-file=/etc/thanos/thanos-receive-hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.monitoring.svc.cluster.local:10901
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: thanosio/thanos:v0.14.0
```
- connectivity test in thanos-receive-2
```
[ec2-user@thanos-receive-2 ~]$ k exec -ti thanos-receive-2 -n monitoring -- sh
/ # nc -vz  thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901
thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901 (172.30.213.95:10901) open
/ # nc -vz  thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901
thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901 (172.30.252.6:10901) open
/ # nc -vz  thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901
thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901 (172.30.161.204:10901) open
```

**Comment by brancz** [comment]
But you can see this without gaps in Prometheus yes?

**Comment by chaimchaim** [comment]
> But you can see this without gaps in Prometheus yes

There's no gaps in Prometheus.

Can you know the below reason ?

```
level=error ts=2020-08-05T01:32:26.233522015Z caller=handler.go:299 component=receive component=receive-handler err="replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:26.248889974Z caller=handler.go:299 component=receive component=receive-handler err="replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:26.414569932Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:26.418503985Z caller=handler.go:299 component=receive component=receive-handler err="replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.114444429Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.114662597Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.114900564Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
level=error ts=2020-08-05T01:32:27.115106052Z caller=handler.go:299 component=receive component=receive-handler err="3 errors: replicate write request, endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded; replicate write request, endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: replicate: context deadline exceeded" msg="internal server error"
```

**Comment by brancz** [comment]
I do not know. That error causes Prometheus to retry sending data though, so it's unlikely to be that. Could you try running a `master` image of Thanos? A couple of fixes for receive did land recently and haven't been released yet.

**Comment by chaimch** [comment]
I tried to modify receive.replication-factor to 1, and it never appeared again.

**Comment by brancz** [comment]
That's pretty dangerous though, that means if any one instance is not working your entire cluster is down.

**Comment by chaimch** [comment]
> That's pretty dangerous though, that means if any one instance is not working your entire cluster is down.

I am experimenting with the master branch to see if there will be problems.

HTere is a way to control the offline of a node, can the cluster work normally?

**Comment by brancz** [comment]
Replication factor is exactly what allows us to have partial downtime in a cluster and still function, obviously we need to ensure that works reliably, I'll mark this as a bug tentatively as we continue to investigate the issue and hopefully resolve it :)

**Comment by chaimch** [comment]
> But you can see this without gaps in Prometheus yes?

I changed the receive_refactor back to 3 and the problem will arise.

The first figure is in thanos. He lost his data.

![image](https://user-images.githubusercontent.com/12760278/89700393-61da3680-d960-11ea-8123-0183790e1bf0.png)

The second figure is in promethues. His data is complete.

![image](https://user-images.githubusercontent.com/12760278/89700410-89310380-d960-11ea-991a-97e08e025f08.png)

receive log
```
level=warn ts=2020-08-08T01:57:48.668899741Z caller=writer.go:91 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" num_dropped=11
level=warn ts=2020-08-08T01:57:48.669558959Z caller=writer.go:91 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" num_dropped=10
level=warn ts=2020-08-08T01:57:48.669979205Z caller=writer.go:91 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" num_dropped=4
```

receive config
```
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: thanos
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/thanos/objectstorage.yaml
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=15d
        - --tsdb.wal-compression
        - --receive.replication-factor=3
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --receive.hashrings-file=/etc/thanos/thanos-receive-hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.monitoring.svc.cluster.local:10901
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: thanosio/thanos:v0.14.0
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
```

Maybe my last log interception was incomplete. 
I guess the loss of data is caused by Error on ingesting out-of-order samples.
In this case, use the master branch of receive or sidecar ？

**Comment by chaimch** [comment]
I'll use the master branch to verify the problem first.

Is the current receive not suitable for production environment?

**Comment by chaimch** [comment]
Master branch still has the problem.

![image](https://user-images.githubusercontent.com/12760278/89723190-a67bd580-da25-11ea-9175-51a843732a01.png)

![image](https://user-images.githubusercontent.com/12760278/89723197-b2679780-da25-11ea-82de-b16b30fc21f8.png)

receive config：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objectstorage
  namespace: monitoring
data:
  objectstorage.yaml: |
    type: S3
    config:
      endpoint: "s3.us-east-1.amazonaws.com"
      bucket: "sre-thanos"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive-hashrings
  namespace: monitoring
data:
  thanos-receive-hashrings.json: |
    [
      {
        "hashring": "soft-tenants",
        "endpoints":
        [
          "thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901"
        ]
      }
    ]
---

apiVersion: v1
kind: Service
metadata:
  name: thanos-receive
  namespace: monitoring
  labels:
    kubernetes.io/name: thanos-receive
spec:
  ports:
  - name: http
    port: 10902
    protocol: TCP
    targetPort: 10902
  - name: remote-write
    port: 19291
    protocol: TCP
    targetPort: 19291
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  selector:
    kubernetes.io/name: thanos-receive
  clusterIP: None
---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    kubernetes.io/name: thanos-pdb
  name: thanos-pdb
  namespace: monitoring
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      kubernetes.io/name: thanos-receive
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    kubernetes.io/name: thanos-receive
  name: thanos-receive
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      kubernetes.io/name: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        kubernetes.io/name: thanos-receive
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: thanos
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/thanos/objectstorage.yaml
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=15d
        - --tsdb.wal-compression
        - --receive.replication-factor=3
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --receive.hashrings-file=/etc/thanos/thanos-receive-hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.monitoring.svc.cluster.local:10901
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # image: thanosio/thanos:v0.14.0
        image: thanosio/thanos:master-2020-08-07-9b578afb
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-receive
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: remote-write
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        resources:
          limits:
            cpu: "1500m"
            memory: "14.5Gi"
          requests:
            cpu: "1500m"
            memory: "14.5Gi"
        volumeMounts:
        - mountPath: /var/thanos/receive
          name: data
          readOnly: false
        - mountPath: /etc/thanos/thanos-receive-hashrings.json
          name: thanos-receive-hashrings
          subPath: thanos-receive-hashrings.json
        - mountPath: /etc/thanos/objectstorage.yaml
          name: thanos-objectstorage
          subPath: objectstorage.yaml
        - mountPath: "/var/run/secrets/eks.amazonaws.com/serviceaccount/"
          name: aws-token
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: thanos-receive-hashrings
        name: thanos-receive-hashrings
      - configMap:
          name: thanos-objectstorage
        name: thanos-objectstorage
      - name: aws-token
        projected:
          sources:
          - serviceAccountToken:
              audience: "sts.amazonaws.com"
              expirationSeconds: 86400
              path: token
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/name: thanos-receive
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi

```

receive log:
```
level=warn ts=2020-08-09T01:52:39.184802971Z caller=writer.go:92 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" num_dropped=3
level=warn ts=2020-08-09T01:52:39.185293108Z caller=writer.go:92 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" num_dropped=6
level=warn ts=2020-08-09T01:52:40.430026634Z caller=writer.go:92 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" num_dropped=5
```
