### ISSUE TITLE
receive: TLS Setup between Thanos-receiver and Prometheus

### ISSUE THREAD

**Issue by nileshbhadana** [thanos-io/thanos#3036]
While setting up TLS between Receiver and prometheus. Receiver runs for 2-3days but then starts throwing Error.

```level=error ts=2020-08-14T17:36:35.861846828Z caller=handler.go:282 component=receive component=receive-handler err="storing locally, endpoint thanos-receiver-0-0.thanos-receiver-0:10901: get appender: TSDB not ready" msg="internal server error"```

Also while increasing the pod replicas it starts throwing error:

```level=error ts=2020-08-16T08:28:39.039655526Z caller=handler.go:282 component=receive component=receive-handler err="forwarding request to endpoint thanos-receiver-0-0.thanos-receiver-0:10901: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"" msg="internal server error" ```

Here is my Hashring ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receiver-0
data:
  # endpoints should be adjusted as the number of thanos-receiver replicas is changed
  hashring.json: |
    [
      {
        "hashring": "default",
        "endpoints": [
          "thanos-receiver-0-0.thanos-receiver-0:10901",
          "thanos-receiver-0-1.thanos-receiver-0:10901"
        ]
      }
    ]
```

This is my Receiver deployment file:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-receiver-0
  name: thanos-receiver-0
spec:
  replicas: 2
  serviceName: thanos-receiver-0
  selector:
    matchLabels:
      app: thanos-receiver-0
  template:
    metadata:
      labels:
        app: thanos-receiver-0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: thanos-receiver-0
      containers:
        - image: quay.io/thanos/thanos:v0.13.0
          name: thanos-receiver-0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - receive
            - --log.level=debug
            - --tsdb.path=/data
            - --objstore.config-file=/etc/thanos/objstore/object-store.yaml
            - --receive.hashrings-file=/etc/thanos/receiver/hashring.json
            - --receive.local-endpoint=$(POD_NAME).thanos-receiver-0:10901
            - --remote-write.server-tls-cert=/etc/thanos/tls/server.crt
            - --remote-write.server-tls-key=/etc/thanos/tls/server.key
            - --remote-write.server-tls-client-ca=/etc/thanos/tls/serverca.crt
            - --tsdb.retention=3h
          resources:
            requests:
              memory: "2500Mi"
              cpu: "1000m"
            limits:
              memory: "3000Mi"
              cpu: "1500m"
          volumeMounts:
            - mountPath: /etc/thanos/objstore/
              name: objstore-config
            - mountPath: /etc/thanos/receiver/
              name: receiver-config
            - mountPath: /data
              name: data
            - mountPath: /etc/thanos/tls/
              name: thanos-tls
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 10902
              name: http
            - containerPort: 19291
              name: write
      volumes:
        - name: thanos-tls
          secret:
            defaultMode: 420
            secretName: thanos-tls
        - name: objstore-config
          secret:
            defaultMode: 420
            secretName: thanos-0
        - name: receiver-config
          configMap:
            name: thanos-receiver-0
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```

Service manifests:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver-0
  labels:
    app: thanos-receiver-0
spec:
  selector:
    app: thanos-receiver-0
  ports:
  # StoreAPI grpc
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver-ext-0
  labels:
    app: thanos-receiver-0
spec:
  selector:
    app: thanos-receiver-0
  type: LoadBalancer
  ports:
  # Prometheus remote-write http
  - name: write
    port: 19291
    targetPort: write
```

Can anybody help with TLS setup.
I am using self signed certs.
Thanks in advance.
