### ISSUE TITLE
sidecar: Enabling reloader configuration doubles the CPU and makes high disk IO

### ISSUE THREAD

**Issue by mihailgmihaylov** [thanos-io/thanos#3051]
**Thanos, Prometheus and Golang version used**:
```
/ $ thanos --version
thanos, version 0.14.0 (branch: HEAD, revision: 19165d782b04a223a9d3f17de9f641999c6826e6)
  build user:       circleci@3f2974e89cb7
  build date:       20200710-12:59:18
  go version:       go1.14.2
```
Using the docker image: `thanosio/thanos:v0.14.0`.
Prometheus: `prom/prometheus:v2.20.1`

**Object Storage Provider**:
AWS

**What happened**:
After implementing [the reloader configuration](https://github.com/thanos-io/thanos/blob/master/docs/components/sidecar.md#reloader-configuration) setting to monitor and observe changes in prometheus configmap configuration, we experienced a huge amount of CPU increase and disk IO:
<img width="1636" alt="Screenshot 2020-08-18 at 10 47 15" src="https://user-images.githubusercontent.com/19683080/90516894-51e70180-e16d-11ea-9d0f-8ee318340448.png">

The disk IO was constantly capped at 2MB/s and this was the disk that we store the prometheus config only.
Here are the settings I used:
```
- name: thanos-sidecar
  image: thanosio/thanos:v0.14.0
  args:
    - "sidecar"
    - "--log.level=info"
    - "--log.format=json"
    - "--tsdb.path=/prometheus/data"
    - "--prometheus.url=http://localhost:9090"
    - "--objstore.config-file=/etc/prometheus/thanos/bucket.yml"
    - "--reloader.config-file=/etc/prometheus/template/prometheus.yml.tmpl"
    - "--reloader.config-envsubst-file=/etc/prometheus/prometheus.yml"
    - "--reloader.rule-dir=/etc/prometheus/"
```
The container runs as a sidecar container to Prometheus and the /etc/prometheus is an EmptyDir:
```
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          emptyDir: {}
```
After removing `--reloader.rule-dir=/etc/prometheus/` The CPU load was OK and the disk IO was back to normal:
<img width="1642" alt="Screenshot 2020-08-18 at 16 16 00" src="https://user-images.githubusercontent.com/19683080/90517919-bce50800-e16e-11ea-83a8-b481264acd64.png">

**What you expected to happen**:
I would expect constant tracking of the configmap file to be less CPU and disk heavy.

**How to reproduce it (as minimally and precisely as possible)**:

I would suggest setting a `reloader.rule-dir` to a path on an EmptyDir and monitoring the `container_cpu_usage_seconds_total` and `container_fs_writes_bytes_total` metrics.

**Environment**:
- Kernel: Linux monitoring-prometheus-0 5.4.0-1018-aws #18-Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 GNU/Linux
