### ISSUE TITLE
Thanos Sidecar doesnt reload prometheus cofigfile

### ISSUE THREAD

**Issue by hedeesaa** [thanos-io/thanos#3190]
based on [this document ](https://thanos.io/tip/thanos/quick-tutorial.md/#sidecarcomponentssidecarmd) I made the docker-compose file like this:
```
version: "3"

services:
  prometheus:
    container_name: prometheus_test1
    restart: always
    image: prom/prometheus:latest
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.listen-address=:9090'
      - '--web.external-url=http://x.x.x.x:9090'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  sidecar:
    container_name: sidecar_test1
    restart: always
    image: thanosio/thanos:master-2020-09-16-5be016a3
    user: root
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml    
    ports:
      - 19191:19191
      - 19090:19090
    command:
      - 'sidecar'
      - '--http-address=0.0.0.0:19191'
      - '--grpc-address=0.0.0.0:19090'
      - '--reloader.config-file=/etc/prometheus/prometheus.yml'
      - '--prometheus.url=http://x.x.x.x:9090'
      - '--tsdb.path=/prometheus'
```
but whenever I change anything in prometheus.yml file, nothing happens.   
shouldn't sidecar reload the config file for prometheus? I thought this feature would omit the need of reloading prometheus to read new config file.
