### ISSUE TITLE
Thanos bucket Web: Provide support to flag web.route-prefix which help to route UI properly

### ISSUE THREAD

**Issue by dmilind** [thanos-io/thanos#3211]
<!--
Template relevant to bug reports only!

Keep issue title verbose enough and add prefix telling
about what components it touches e.g "query:" or ".*:"
-->

<!--
In case of issues related to exact bucket implementation, please ping corresponded maintainer from list here: https://github.com/thanos-io/thanos/blob/master/docs/storage.md
-->

**Thanos, Prometheus and Golang version used**:
Using official docker image: thanosio/thanos:v0.15.0

<!--
Output of "thanos --version" or docker image:tag used.
(Double-check if all deployed components/services have expected versions)

If you are using custom build from master branch, have you checked out the tip of the master?
-->

**Object Storage Provider**: Ceph storage blocks

**What happened**: 
I am using Thanos tools bucket web with `--web.external-prefix=/thanos/bucket`. Once I hit URL http://localhost:9090/thanos/bucket (k8s service being forwarded to 9090 from 10902 internally), I get 404. When I hit http://localhost:9090 then it shows HTML links only, and when I click on any link it routes me via a prefix path which is okay but again 404. When going through the documentation, I found 
```
      --web.external-prefix=""  Static prefix for all HTML links and redirect
                                URLs in the bucket web UI interface. Actual
                                endpoints are still served on / or the
                                web.route-prefix. This allows thanos bucket web
                                UI to be served behind a reverse proxy that
                                strips a URL sub-path.
```
Flag`web.route-prefix` is mentioned but bucket web does not support it. 
I faced a similar issue with the querier and it got resolved when I used `web.route-prefix` flag. 
When I am trying to use this flag for Thanos tools bucket web, it says there is not support for the flag `web.route-prefix`. 

**What you expected to happen**:
Bucket web UI should be loaded behind the proxy and this can be done by providing support of `web.route-prefix` flag which is missing as of now. 

**How to reproduce it (as minimally and precisely as possible)**:
1
```
      containers:
        - name: thanos-bucketweb
          image: thanosio/thanos:v0.15.0
          imagePullPolicy: IfNotPresent
          args:
            - tools
            - bucket 
            - web  
            - --log.level=info
            - --http-address=0.0.0.0:10902
            - --web.external-prefix=thanos/bucket
            - --refresh=30m
            - --objstore.config-file=/etc/thanos-store/ceph-object-storage.yaml
```
2 http://localhost:9090/thanos/bucket `404 page not found `
3 http://localhost:9090 `HTML UI is displayed and then 404 page not found after clicking a link`

**Full logs to relevant components**:
After providing  '--web.route-prefix': 
```
│ Error parsing commandline arguments: [/bin/thanos tools bucket web --log.level=info --http-address=0.0.0.0:10902 --web.route-prefix=thanos/bucket --web.external-prefix=thanos/bucket --refresh=30m --objstore.config-file=/etc/thanos-store/ceph-object-storage.yaml]: unknown long flag '--we │
│ thanos: error: unknown long flag '--web.route-prefix'                                                                                                                                                                                                                                           │
│ stream closed
```
<!--
Uncomment if you would like to post collapsible logs:

<details>Logs
<p>

```

```

</p>
</details>
-->

**Anything else we need to know**:
I see a similar issue with compact web #2727. If it is fixed then bucket web UI can be fixed easily. 
<!--
Uncomment and fill if you use not casual environment or if it might be relevant.

**Environment**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

-->
