### ISSUE TITLE
[Query] UI served behind reverse proxy on a subpath broken on 0.15.0

### ISSUE THREAD

**Issue by amrmahdi** [thanos-io/thanos#3226]
Thanos version: v.15.0

I updated from 0.14.0 to 0.15.0 and thanos query UI in not working correctly. I run thanos behind an nginx reverse proxy under a subpath. The way I've been running it so far is using the `--web.prefix-header=X-Forwarded-Prefix`

Here is my ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /thanos
  name: thanos-query-http
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - backend:
          serviceName: thanos-query-http
          servicePort: 10902
        path: /thanos/?(.*)
```
Here is what I get on v0.15.0:

![image](https://user-images.githubusercontent.com/1451116/94236174-a181c100-fec1-11ea-8366-380c720b9ee6.png)
