### ISSUE TITLE
thanos receiver doesnt create tsdb block and send to object storage 

### ISSUE THREAD

**Issue by hedeesaa** [thanos-io/thanos#3241]
I'm using Thanos receiver and it's been 45 minutes that receiver has been receiving metrics and making wal files.
but It is not sending these to object storage, and not showing any errors. it seems it cant create tsdb blocks.
receiver:
```
  receiver:
    container_name: receiver_test1
    restart: always
    image: thanosio/thanos:master-2020-09-16-5be016a3
    user: root
    volumes:
      - /test/prometheus:/etc/prometheus
      - /test/receiver-data:/prometheus
    network_mode: host
    command:
      - 'receive'
      - '--http-address=0.0.0.0:10907'
      - '--grpc-address=0.0.0.0:10909'
      - '--receive.replication-factor=1'
      - '--label=receive_replica="0"'
      - '--tsdb.path=/prometheus'
      - '--remote-write.address=0.0.0.0:10908'
      - '--objstore.config-file=/etc/prometheus/bucket_config.yml'
      - '--receive.local-endpoint=x.x.x.x:10909'
      - '--receive.hashrings-file=/etc/prometheus/hashring.json'
```
`/prometheus` directory:

```
./default-tenant/thanos.shipper.json
./default-tenant/lock
./default-tenant/wal/00000003
./default-tenant/wal/00000005
./default-tenant/wal/00000006
./default-tenant/wal/00000001
./default-tenant/wal/00000009
./default-tenant/wal/00000002
./default-tenant/wal/00000007
./default-tenant/wal/00000008
./default-tenant/wal/00000004
./default-tenant/wal/00000000

./default-tenant/chunks_head/000002
./default-tenant/chunks_head/000003
./default-tenant/chunks_head/000001



```
