### ISSUE TITLE
Thanos Receiver with Hashrings config: Error "backing off forward request for endpoint"

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#3287]
**Thanos, Prometheus and Golang version used**:
Thanos v0.15.0, Prometheus rancher/prom-prometheus:v2.7.2

**Object Storage Provider**:
S3
**What happened**:
Set up my cluster with Thanos Receiver with hashring config, thanos store and thanos query.
**What you expected to happen**:
I set up 2 thanos instances with replication-factor=1. I added the endpoints manually plus the its service.yaml definition.
I set up the rancher-prometheus and edited the proxy-nginx config to add the header value. The pods were running successfully but cannot get any metrics. 
Error in the logs:
`level=error ts=2020-10-07T09:42:27.195984409Z caller=handler.go:331 component=receive component=receive-handler err="backing off forward request for endpoint http://thanos-receive:19291/api/v1/receive: target not available" msg="internal server error"`
**How to reproduce it (as minimally and precisely as possible)**:
**hashring.json (configMap):**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/name: thanos-receive
  namespace: thanos
data:
  hashrings.json: |
    [
        {
            "hashring": "athena",
            "endpoints": ["athena-receiver-0.thanos.svc.cluster.local:19291/api/v1/receive"],
            "tenants": ["athena"]
        },
         {
            "hashring": "medusa",
            "endpoints": ["medusa-receiver-0.thanos.svc.cluster.local:19291/api/v1/receive"],
            "tenants": ["medusa"]
        }
    ]
```
```
Thanos Receiver (for athena)
      containers:
      - args:
        - receive
        - --log.level=info
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=1d
        - --label=replica="$(NAME)"
        - --label=receive="true"
        - --receive.local-endpoint=$(NAME).thanos.$(NAMESPACE).svc.cluster.local:10901
        - --receive.tenant-header="X-THANOS-TENANT"
        - --receive.default-tenant-id="default-tenant"
        - --receive.hashrings-file=/var/hashring/hashrings.json
  name: thanos-receive
```
When doing a curl in http://thanos-receive:19291/api/v1/receive it is working. 
My goal is to set up multi tenancy thanos. 
I set the proxy-header to "X-THANOS-TENANT"

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by brancz** [comment]
You don't need to specify the path on the endpoints, ever since the internal communication was switched to gRPC. Could you try removing that and see if that works?

**Comment by heartTorres** [comment]
Thanks for the reply. The endpoints, you mean in the hashrings.json (configmap)? I removed the endpoints attributes. However the error has changed to `component=receive component=receive-handler err="no matching hashring to handle tenant" msg="internal server error"`

```
     - args:
        - receive
        - --log.level=info
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=1d
        - --label=replica="$(NAME)"
        - --label=receive="true"
        - --receive.local-endpoint=$(NAME).thanos.$(NAMESPACE).svc.cluster.local:10901
        - --receive.tenant-header="X-THANOS-TENANT"
        - --receive.replica-header="ATHENA"
        - --receive.hashrings-file-refresh-interval=3m
        - --receive.tenant-label-name="athena"
        - --receive.hashrings-file=/var/hashring/hashrings.json
```

**Comment by brancz** [comment]
Sorry for being unclear, I meant change the hashring configuration to:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/name: thanos-receive
  namespace: thanos
data:
  hashrings.json: |
    [
        {
            "hashring": "athena",
            "endpoints": ["athena-receiver-0.thanos.svc.cluster.local:10901"],
            "tenants": ["athena"]
        },
         {
            "hashring": "medusa",
            "endpoints": ["medusa-receiver-0.thanos.svc.cluster.local:10901"],
            "tenants": ["medusa"]
        }
    ]
```
