### ISSUE TITLE
Query frontend: large step queries are shifted

### ISSUE THREAD

**Issue by darkweaver87** [thanos-io/thanos#3353]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.15.0 (branch: HEAD, revision: fbd14b49f95e7543883fedf9381a21127d4dda2b)
  build user:       circleci@b18149728583
  build date:       20200907-09:47:14
  go version:       go1.14.2
(docker image: quay.io/thanos/thanos:v0.15.0)

prometheus: prom/prometheus:v2.20.1

**Object Storage Provider**:
s3

**What happened**:
When I use large step on queries, points are shifted.
Examples using with:

- thanos-query 7200s step (ok):

```
curl http://127.0.0.1:10902/api/v1/query_range -d 'end=1603353600&query=count(push_time_seconds)&start=1602748800&step=7200' | jq '.data.result[]|.values|.[0]'
[
  1602748800,
  "1043"
]
```
- thanos-query-frontend 7200s step (ok):
```
curl http://127.0.0.1:10903/api/v1/query_range -d 'end=1603353600&query=count(push_time_seconds)&start=1602748800&step=7200' | jq '.data.result[]|.values|.[0]'
[
  1602748800,
  "1043"
]
```

Then with larger step:
- thanos-query 10800s step (ok):
```
curl http://127.0.0.1:10902/api/v1/query_range -d 'end=1603353600&query=count(push_time_seconds)&start=1602748800&step=10800' | jq '.data.result[]|.values|.[0]'
[
  1602748800,
  "1043"
]
```
- thanos-query-frontend 10800s step (ko):
```
curl http://127.0.0.1:10903/api/v1/query_range -d 'end=1603353600&query=count(push_time_seconds)&start=1602748800&step=10800' | jq '.data.result[]|.values|.[0]'
[
  1602741600,
  "1019"
]
```

**What you expected to happen**:
I would expect to have the same answers between queries on thanos query and query frontend :-)

**How to reproduce it (as minimally and precisely as possible)**:
cf. queries above

**Full logs to relevant components**:

**Anything else we need to know**:

Many thanks :-)

**Comment by yeya24** [comment]
Hello, thanks for the issue. 
How do you set up query frontend? Do you use cache?
If you use cache, then this is expected because the query result will be cached at the frontend when you query. This is fine because there is a cache validation time.

**Comment by darkweaver87** [comment]
Hello thanks for your reply :-)
My query frontend is setup this way (a POD in my K8S):
```
      containers:
      - args:
        - query-frontend
        - --query-frontend.compress-responses
        - --http-address=0.0.0.0:10902
        - --query-frontend.downstream-url=http://thanos-query.pilot.svc.cluster.local.:10902
        - --query-range.split-interval=24h
        - --query-range.max-retries-per-request=5
        - --query-frontend.log_queries_longer_than=5s
        - |-
          --query-range.response-cache-config="config":
            "max_size": "512MB"
            "max_size_items": 0
            "validity": "6h"
          "type": "in-memory"
        image: quay.io/thanos/thanos:v0.15.0
```
I use in-memory cache but when I disable it I've exactly the same behavior.
