### ISSUE TITLE
Thanos Rule not able to read values from expr result.

### ISSUE THREAD

**Issue by stylianosrigas** [thanos-io/thanos#3386]
**What happened**:

Hello I am trying to create an alert in Thanos Ruler using similar rule to Prometheus but I am getting the error that variable $labels is not defined.

This the rule that I am trying to apply:
```yaml
 - name: workerNodes
      rules:
      - alert: NodeNoSchedule
        annotations:
          description: '{{$labels.node}} have the NodeNoSchedule taint for more than 1 minute.'
          message: 'Instance {{$labels.node}} / ClusterID {{$labels.clusterID}} have NoSchedule taint'
        expr: kube_node_spec_unschedulable != 0
        for: 1m
        labels:
          service: cluster
          severity: high
```
The same alert in Prometheus directly is able to get the {{$labels.node}}  and {{$labels.ClusterID}} values. 

Is there a way to do the same in Thanos ruler?
