### ISSUE TITLE
sidecar: Issue when uploading data to AWS S3 using IAM role

### ISSUE THREAD

**Issue by Shan1024** [thanos-io/thanos#3451]
**Thanos, Prometheus and Golang version used**:

Prometheus:

**Docker Tag:** prom/prometheus:v2.22.0

```bash
/prometheus $ prometheus --version
prometheus, version 2.22.0 (branch: HEAD, revision: 0a7fdd3b76960808c3a91d92267c3d815c1bc354)
  build user:       root@6321101b2c50
  build date:       20201015-12:29:59
  go version:       go1.15.3
  platform:         linux/amd64
```

```
  args:
    - --config.file=/etc/prometheus-shared/prometheus.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=60d
    - --log.level=debug
    - --web.enable-lifecycle
    - --storage.tsdb.no-lockfile
    - --storage.tsdb.min-block-duration=2h
    - --storage.tsdb.max-block-duration=2h
```

---
Thanos:

**Docker Tag:** thanosio/thanos:v0.16.0

```bash
/ $ /bin/thanos --version
thanos, version 0.16.0 (branch: HEAD, revision: dc6a1666bb68cd5c11be54452842e823f57668c5)
  build user:       circleci@f967e3ca52e4
  build date:       20201026-14:08:25
  go version:       go1.15
```

```
  args:
    - sidecar
    - --log.level=debug
    - --tsdb.path=/prometheus
    - --prometheus.url=http://127.0.0.1:9090
    - --reloader.config-file=/etc/prometheus/prometheus.yaml.tmpl
    - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yaml
    - --reloader.rule-dir=/etc/prometheus/rules/
    - --objstore.config-file=/var/lib/thanos/object-store.yaml
```

---
**Object Storage Provider**:
AWS S3

object-store.yaml
```yaml
    type: S3
    config:
      bucket: BUCKET_NAME
      endpoint: sts.amazonaws.com
      signature_version2: false
      region: ap-southeast-1
      trace:
        enable: true
      http_config:
        idle_conn_timeout: 0m10s
        response_header_timeout: 0m10s
        insecure_skip_verify: false
```

**What happened**:

I am trying to upload data to AWS S3 bucket within a k8s pod using an IAM role (**Specifying an IAM role for your service account** - https://docs.amazonaws.cn/en_us/eks/latest/userguide/specify-service-account-role.html). The **AWS_ROLE_ARN**, **AWS_WEB_IDENTITY_TOKEN_FILE** environment variables are available within the pod.

But seems like there are no data available in the **[tsdb.path]/thanos/upload/*** to upload and hence the upload fails. I assume that the Thanos Sidecar is responsible for copying data to this directory in order to be uploaded. But seems like this is not happening as expected for some reason.

```bash
level=debug ts=2020-11-16T06:42:59.453105875Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=debug ts=2020-11-16T06:42:59.453347569Z caller=stdlib.go:89 s3TraceMsg="HEAD /BUCKET_NAME/01EQ06YSTS1NNYMB9DZZNTV3AS/meta.json HTTP/1.1\r"
level=debug ts=2020-11-16T06:42:59.453391722Z caller=stdlib.go:89 s3TraceMsg="HTTP/1.1 404 Not Found\r"
level=debug ts=2020-11-16T06:42:59.453407916Z caller=stdlib.go:89 s3TraceMsg=---------END-HTTP---------
level=info ts=2020-11-16T06:42:59.453535344Z caller=shipper.go:333 msg="upload new block" id=01EQ06YSTS1NNYMB9DZZNTV3AS
level=debug ts=2020-11-16T06:43:00.724273462Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=debug ts=2020-11-16T06:43:00.724501968Z caller=stdlib.go:89 s3TraceMsg="PUT /BUCKET_NAME/debug/metas/01EQ06YSTS1NNYMB9DZZNTV3AS.json HTTP/1.1\r"
level=debug ts=2020-11-16T06:43:00.724586884Z caller=stdlib.go:89 s3TraceMsg="HTTP/1.1 404 Not Found\r"
level=debug ts=2020-11-16T06:43:00.724605052Z caller=stdlib.go:89 s3TraceMsg=---------END-HTTP---------
level=warn ts=2020-11-16T06:43:00.760433712Z caller=sidecar.go:275 err="upload 01EQ06YSTS1NNYMB9DZZNTV3AS: upload meta file to debug dir: upload file /prometheus/thanos/upload/01EQ06YSTS1NNYMB9DZZNTV3AS/meta.json as debug/metas/01EQ06YSTS1NNYMB9DZZNTV3AS.json: upload s3 object: The specified key does not exist." uploaded=0
```

Expected data is available (but not in the **/prometheus/thanos/upload/** directory, but **/prometheus** directory) -

```bash
/prometheus $ ls -ltr
total 168
-rw-r--r--    1 1000     2020         20001 Nov 13 04:16 queries.active
-rw-r--r--    1 1000     2020            37 Nov 13 07:08 thanos.shipper.json
drwxr-sr-x    3 1000     2020          6144 Nov 13 07:08 01EQ06YSTS1NNYMB9DZZNTV3AS
drwxr-sr-x    3 1000     2020          6144 Nov 13 07:09 thanos
drwxr-sr-x    3 1000     2020          6144 Nov 13 09:00 01EQ0DAE1MDZQJTF85TXY519HQ
...
drwxr-sr-x    3 1000     2020          6144 Nov 16 07:00 01EQ7XMVWBV1Y3DKEHX97XDYQS
drwxr-sr-x    2 1000     2020          6144 Nov 16 07:00 chunks_head
drwxr-sr-x    3 1000     2020          6144 Nov 16 07:00 wal
```

```bash
/prometheus/01EQ06YSTS1NNYMB9DZZNTV3AS $ ls -ltr
total 18808
drwxr-sr-x    2 1000     2020          6144 Nov 13 07:08 chunks
-rw-r--r--    1 1000     2020             9 Nov 13 07:08 tombstones
-rw-r--r--    1 1000     2020           285 Nov 13 07:08 meta.json
-rw-r--r--    1 1000     2020      19243917 Nov 13 07:08 index
```

---

After trying to figure out the issue for a while and failing, I decided to add **access_key, secret_key** in the store config file to see whether i'll get the same issue. But when i use **access_key, secret_key**, data is getting uploaded successfully as expected. But I want to use the IAM Role to upload the data instead of using **access_key, secret_key**. 

I have no clue about what is wrong with the earlier approach I took. Any help is highly appreciated.

Updated **object-store.yaml** -

```yaml
    type: S3
    config:
      bucket: BUCKET_NAME
      endpoint: s3.ap-southeast-1.amazonaws.com
      access_key: ACCESS_KEY
      secret_key: SECRET_KEY
      trace:
        enable: true
      signature_version2: false
      http_config:
        idle_conn_timeout: 0m10s
        response_header_timeout: 0m10s
        insecure_skip_verify: false
```
---
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:
