### ISSUE TITLE
Consider moving HTTP Config to base object storage config level

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3715]
As per https://github.com/thanos-io/thanos/pull/3657 - it would be nice to have it for all providers as it's a common thing - all providers use HTTP (for now  though (: ) 

Something to consider (:

**Comment by GiedriusS** [comment]
Sounds good! However, we should be careful with this to not shoot ourselves in the foot with inconsistencies & compatibility. I'd propose a structure like:
```yaml
type: s3
config:
  bucket: "foobar"
  ...
transport:
  http2:
    timeout: 10s
  ...
```
