### ISSUE TITLE
compactor/sidecar: HostUnusualDiskWriteLatency

### ISSUE THREAD

**Issue by kfirfer** [thanos-io/thanos#3755]
Hello

When compactor have works to do, or Thanos sidecar is uploading the data to MinIO, there's high volume of disk write operations in a small window of time

When it occurs, this alerts is fired:
```
          - alert: HostUnusualDiskWriteLatency
            expr: rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Host unusual disk write latency (instance {{ $labels.instance }})
              description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: KubernetesVolumeFullInFourDays
            expr: predict_linear(kubelet_volume_stats_available_bytes{persistentvolumeclaim!~".*prometheus.*|.*elasticsearch.*"}[6h], 4 * 24 * 3600) < 0
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: Kubernetes Volume full in four days (instance {{ $labels.instance }})
              description: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up within four days. Currently {{ $value | humanize }}% is available.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

Would be nice to see some throttling mechanism to mitigate intensive operations (chunks with buffer/+sleep between chunks or some kind..)
