### ISSUE TITLE
/thanos.Store/Info always get 404 beetwen different clusters

### ISSUE THREAD

**Issue by ichasco-heytrade** [thanos-io/thanos#3829]
Hi, I am getting errors using thanos with different k8s clusters.

I have 2 clusters. One is the main cluster with:
* Query
* StorageGW
* Compactor
* Prometheus + Sidecar

And another cluster with:
* Prometheus + sidecar

I am using `Istio` in both clusters. In the main cluster, works everything ok. But the problem is when the query tries to connect to second clusters thanos sidecar. It gives the next error:

```
istio-internal-ingressgateway-56bd9cb498-6ktf6 istio-proxy [2021-02-24T11:43:44.700Z] "POST /thanos.Store/Info HTTP/2" 404 - via_upstream - "-" 5 19 0 0 "10.31.10.243" "grpc-go/1.29.1" "8c657b59-055e-4aab-9719-b1a65626db55" "thanos-dev.example.com:80" "10.31.10.78:10902" outbound|9090||thanos-sidecar.monitoring.svc.cluster.local 10.31.10.223:37364 10.31.10.223:8080 10.31.10.243:58085 - -
```

But if I try with curl get the metrics, it works:
```
istio-internal-ingressgateway-56bd9cb498-7pbnf istio-proxy [2021-02-24T11:37:02.344Z] "GET /metrics HTTP/1.1" 200 - via_upstream - "-" 0 48706 1 1 "10.31.10.243" "curl/7.61.1" "2626b771-fb24-4f58-a5f6-e3f582d0cb3b" "thanos-dev.example.com:80" "10.31.10.78:10902" outbound|9090||thanos-sidecar.monitoring.svc.cluster.local 10.31.10.104:51986 10.31.10.104:8080 10.31.10.81:1208 - -
```

Query Errors:
```
thanos-query-dbf98986b-p8sxk query level=warn ts=2021-02-24T11:55:44.691321324Z caller=storeset.go:458 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-dev.example.com:80: rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type \"text/plain; charset=utf-8\"" address=thanos-dev.example.com:80
thanos-query-dbf98986b-p8sxk query level=warn ts=2021-02-24T11:55:54.683175062Z caller=storeset.go:458 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-dev.example.com:80: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-dev.example.com:80
```

Second cluster service and istio configs:
Service:
```
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  namespace: monitoring
spec:
  selector:
     thanos-sidecar: "true"
  type: ClusterIP
  ports:
    - name: http-thanos
      protocol: TCP
      port: 9090
      targetPort: 10902
```

VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thanos-sidecar
  namespace: monitoring
spec:
  gateways:
    - istio-system/private
  hosts:
    - "thanos-dev.example.com"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: thanos-sidecar.monitoring.svc.cluster.local
            port:
              number: 9090
```

Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: private
  namespace: istio-system
spec:
  selector:
    istio: internal-ingressgateway
  servers:
    - port:
        number: 80
        name: http-private
        protocol: HTTP2
      hosts:
        - "*.example.com"
```

The configuration of second cluster sidecar:
```
args:
        - sidecar
        - --log.level=debug
        - --tsdb.path=/data/
        - --prometheus.url=http://127.0.0.1:9090
        - |
          --objstore.config=type: S3
          config:
            bucket: thanos
            region: eu-west-1
            endpoint: s3.amazonaws.com
            put_user_metadata: {"X-Amz-Acl": "bucket-owner-full-control"}
        - --reloader.config-file=/etc/prometheus-config/prometheus.yml
        - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml
        - --reloader.rule-dir=/etc/prometheus-config/rules
```

The query configuration:
```
extraFlags:
    - "--log.format=logfmt"
    - "--query.auto-downsampling"
    - "--query.replica-label=stage"
    - "--store=dnssrv+_thanosstores._tcp.example.com"
    - "--store=thanos-dev.example.com:80"
    - "--store.sd-interval=5m"
```

All the deployments had been done with HELM
* https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
* https://github.com/bitnami/charts/tree/master/bitnami/thanos/#installing-the-chart

Versions:
* Thanos: `0.18.0`
* Prometheus: `v2.24.1`
* Istio: `1.9.0`

Thanks!!! :)

**Comment by bwplotka** [comment]
Thanks for asking!

Wonder if the problem is not that you have configured istio to target the HTTP port not gRPC port? `"thanos-dev.example.com:80" ` 

I would suggest two routes one for HTTP and one for gRPC, or just gRPC one 🤗

**Comment by ichasco-heytrade** [comment]
Hi @bwplotka 

Yes, finally I solved exposing the service as `NodePort` with gRPC port (without istio)

Prometheus deployment values.yaml:
```
service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: thanos-dev.example.com
    type: NodePort
    gRPC:
      enabled: true
      servicePort: 10901
      nodePort: 30901
```

And with `external-dns` creates a DNS record. With node IPs.

The connection between query --> sidecar must be done always by gRPC port isn't it?

Thanks!
