### ISSUE TITLE
Index cache validity for Query and Store

### ISSUE THREAD

**Issue by Shini31** [thanos-io/thanos#3831]
### Is your proposal related to a problem?

I want to know which is the validity of the cache index for Thanos query and store.

Would it be possible to configure the validity of the cache as in Cortex

### Describe the solution you'd like

Add a new parameter for cache validity
e.g. --index-cache-validity (time in seconds)

**Comment by bwplotka** [comment]
👋🏽 
For store we have lot's of `_ttl` options: https://thanos.io/tip/components/store.md/#caching-bucket
Similar for Query Frontend: https://thanos.io/tip/components/query-frontend.md/#caching

Let us know if that works, if not, we can reopen! 🤗

**Comment by Shini31** [comment]
Thanks for the links !

II'm going to do some tests.

**Comment by Shini31** [comment]
I've just done some tests and there are some things I don't understand.

I added two Thanos query frontend pods with a cache validity of 1h.
I put Thanos query frontend as datasource in Grafana and I consulted some dashboards.

I see that the memory consumption of Thanos query and Thanos query frontend increases but the memory is never freed.

![Capture d’écran du 2021-03-03 11-10-21](https://user-images.githubusercontent.com/333820/109790025-3925d100-7c11-11eb-8715-9ce1550a698b.png)
![Capture d’écran du 2021-03-03 11-09-36](https://user-images.githubusercontent.com/333820/109790035-3aef9480-7c11-11eb-92da-e986083cda1f.png)



I don't understand why the memory is not freed after one hour on my Thanos query frontend pods and especially what is the purpose of Thanos query frontend if there is also an increase of memory on Thanos query at each request.

Here is the configuration of my 2 deployments.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-query-frontend
    version: 0.15.0
  name: thanos-query-frontend
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query-frontend
  template:
    metadata:
      labels:
        app: thanos-query-frontend
        version: 0.15.0
    spec:
      containers:
      - args:
        - query-frontend
        - --query-frontend.compress-responses
        - --http-address=0.0.0.0:10902
        - --query-frontend.downstream-url=http://thanos-query-http.monitoring.svc:10902
        - --query-range.split-interval=24h
        - --query-range.max-retries-per-request=5
        - --query-frontend.log_queries_longer_than=5s
        - |-
          --query-range.response-cache-config="config":
            "max_size": "0"
            "max_size_items": 2048
            "validity": "1h"
          "type": "in-memory"
        image: quay.io/thanos/thanos:v0.15.0
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-query-frontend
        ports:
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-query
    version: 0.15.0
  name: thanos-query
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
        version: 0.15.0
    spec:
      containers:
      - args:
        - query
        - --log.level=warn
        - --log.format=json
        - --query.replica-label=prometheus_replica
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.prometheus-operated.monitoring.svc.cluster.local
        image: quay.io/thanos/thanos:v0.15.0
        imagePullPolicy: Always
        name: thanos-query
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 120
```
