### ISSUE TITLE
Thanos Compact Crashing due to Azure Timeout

### ISSUE THREAD

**Issue by airkewld** [thanos-io/thanos#3952]
Compact component crashes when it encounters a file it cannot fully download/analyze.
```
level=info ts=2021-03-23T14:01:38.498832601Z caller=http.go:84 service=http/server component=compact msg="internal server is shutdown gracefully" err="syncing metas: incomplete view: meta.json file exists: 01F0DSQC0MQ07MBCFXSWD62NCG/meta.json: cannot get properties for Azure blob, address: 01F0DSQC0MQ07MBCFXSWD62NCG/meta.json: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/pipeline/error.go:154\nHTTP request failed\n\nHead \"https://obj_store_name.blob.core.windows.net/thanos/01F0DSQC0MQ07MBCFXSWD62NCG/meta.json?timeout=1\": context deadline exceeded\n"
```

Our obj store config includes a max_retries value of 3, but it does not seem to be passed in correctly.
```
/ # cat /proc/1/cmdline
/bin/thanoscompact--wait--log.level=debug--compact.concurrency=1--log.format=logfmt--objstore.config=type: AZURE
config:
  storage_account: "storage_account"
  storage_account_key: "storage_account_key"
  container: "container_name"
  endpoint: "blob.core.windows.net"
  max_retries: 3
--data-dir=/var/thanos/compact--debug.accept-malformed-index--retention.resolution-raw=30d--retention.resolution-5m=90d--retention.resolution-1h=180d--delete-delay=48h--deduplication.replica-label=prometheus_replica--deduplication.replica-label=rule_replica--tracing.config="config":
  "sampler_param": 2
  "sampler_type": "ratelimiting"
  "service_name": "thanos-compact"
"type": "JAEGER"/ #
```
Any assistance is appreciated.
