### ISSUE TITLE
Refactoring of azure obj store

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3957]
I wanted to add some extra configuration options, but then kinda hit a wall with the current testing method. As it's quite hard to extend those. So I started refactoring the azure part and I think I can squash a few issues; 

#3933
#2839
#3952 

Also adding; 

- Implementing our own HTTP transport method (and therefore configuration options). Just like S3.
- Adding configuration for `PipelineRetry` method
- Adding configuration for `ReaderRetry` method
- Refactoring tests

As I'm quite far, I wanted to make this issue to check if no one else was on it. Also open for further feedback :) 
If possible add, me as assignee to this issue?

**Comment by bwplotka** [comment]
Thanks!

I think no one is on it, and we saw some issues on GitHub e.g https://github.com/thanos-io/thanos/issues/3952 soi I think it's healthy to do!

**Comment by wiardvanrij** [comment]
Updated the PR. 

Absolutely not tested yet, but the image is: `wiardvanrij/thanos:azure-test`  -> https://hub.docker.com/repository/docker/wiardvanrij/thanos

Going to test this myself later on, but would like more feedback from others..

**Comment by airkewld** [comment]
`
level=error ts=2021-04-29T21:49:30.0974553Z caller=main.go:130 err="yaml: unmarshal errors:\n  line 3: field max_retries not found in type azure.Config\ncreate AZURE client\ngithub.com/thanos-io/thanos/pkg/objstore/client.NewBucket\n\t/go/src/github.com/thanos-io/thanos/pkg/objstore/client/factory.go:77\nmain.runCompact\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:198\nmain.registerCompact.func1\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/compact.go:89\nmain.main\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\npreparing compact command failed\nmain.main\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
`

Below are the contents of the obj secret
```
type: AZURE
config:
  storage_account: "storage_account"
  storage_account_key: "storage_account_key"
  container: "container_name"
  endpoint: "azure_endpoint"
  max_retries: 10
```

**Comment by wiardvanrij** [comment]
@airkewld  that's correct. Please check the changed config here: https://github.com/thanos-io/thanos/blob/2c435ade8d73af7ff9901a31b98a3920bfe1ef16/docs/storage.md#azure

**Comment by airkewld** [comment]
Perfect. I’ll give that a try. 

Thank you

**Comment by airkewld** [comment]
@wiardvanrij  ran your image all night locally with no failures.

**Comment by wiardvanrij** [comment]
> @wiardvanrij ran your image all night locally with no failures.

Awesome, what config did you use? Did you increase timeouts and/or retries? 
Also, did you by any chance tested the msi_resource? I've added it but never tested it out :P

**Comment by airkewld** [comment]
This is what i had in the config
```
  msi_resource: ""
  pipeline_config:
    max_tries: 5
    try_timeout: 10s
    retry_delay: 0s
    max_retry_delay: 0s
  reader_config:
    max_retry_requests: 3
  http_config:
    idle_conn_timeout: 5s
    response_header_timeout: 5s
    insecure_skip_verify: false
    tls_handshake_timeout: 5s
    expect_continue_timeout: 5s
    max_idle_conns: 0
    max_idle_conns_per_host: 0
    max_conns_per_host: 0
    disable_compression: false
```
