### ISSUE TITLE
Thanos receiver pod keeps restarting while saying store locally for endpoint 127.0.0.1:10901: get appender: TSDB not ready" msg="internal server error

### ISSUE THREAD

**Issue by dmilind** [thanos-io/thanos#3982]
I am newbie here and tying to understand thanos receiver work flow. 
Whats happening ? 
While checking logs from prometheus and thanos receiver side, I am hitting with below error
`level=error ts=2021-03-26T18:22:25.041639445Z caller=multitsdb.go:334 component=receive component=multi-tsdb tenant=default-tenant msg="failed to start tsdb asynchronously" err="mkdir \": permission denied"
level=error ts=2021-03-26T18:22:25.041684545Z caller=handler.go:330 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10901: get appender: TSDB not ready" msg="internal server error"`

Configuration of thanos receive:
hashring.json 
```thanos-receive-hashring.json: |
    [
      {
        "endpoints": [
            "127.0.0.1:10901"     
        ]
      }
    ]
```
thanos receive deployments: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.label }}
  namespace: {{ .Values.app.nameSpace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations: 
        sidecar.istio.io/inject: {{ .Values.template.annotations.istioSidecarInject | quote }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - receive 
            - --log.level=info
            - --grpc-address=0.0.0.0:{{ .Values.app.receiveGrpcPort }}
            - --http-address=0.0.0.0:{{ .Values.app.receiveHttpPort }}
            - --remote-write.address=0.0.0.0:{{ .Values.app.receiveHttpWritePort }}
            - --grpc-grace-period=2m         
            - --tsdb.path="/var/thanos/receive/objstorage/" 
            - --objstore.config-file=/var/thanos/receive/config/thanos-objstorage.yaml
            - --receive.local-endpoint=127.0.0.1:10901
            - --receive.hashrings-file=/var/thanos/receive/hashring/thanos-receive-hashring.json
            - --tsdb.retention={{ .Values.tsdbRetensionPeriod }}
            - --receive.replication-factor=1
            - --receive.hashrings-file-refresh-interval=3m
            - --tsdb.wal-compression   
            - --tsdb.no-lockfile  
            - --label=receive="true"
            - --label=replica="$(REPLICA_NAME)"
          env:
          - name: REPLICA_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 10902
              scheme: HTTP
            periodSeconds: 60
              #initialDelaySeconds: 30
          ports:
            - name: grpc-receive
              containerPort: {{ .Values.app.receiveGrpcPort }}
            - name: http-receive
              containerPort: {{ .Values.app.receiveHttpPort }}
            - name: http-write
              containerPort: {{ .Values.app.receiveHttpWritePort }}
          volumeMounts:
          - name: thanos-receive-server-config
            mountPath: /var/thanos/receive/config
          - name: thanos-receive-server-hashring 
            mountPath: /var/thanos/receive/hashring
          - name: thanos-objstorage
            mountPath: /var/thanos/receive/objstorage
            readOnly: false
          resources:
            requests:
              cpu: {{ .Values.resources.request.cpu }}
              memory: {{ .Values.resources.request.memory }}
            limits:
              cpu: {{ .Values.resources.limit.cpu }}
              memory: {{ .Values.resources.limit.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccount: {{ .Values.app.nameSpace }}
      serviceAccountName: {{ .Values.app.nameSpace }}
      terminationGracePeriodSeconds: 30
      volumes: 
      - name: thanos-receive-server-config
        configMap:
          name: thanos-objstorage-config
          defaultMode: 420
      - name: thanos-receive-server-hashring 
        configMap: 
          name: thanos-receive-hashring-config
          defaultMode: 420
      - name: thanos-objstorage
        emptyDir: {}
```
I understood that , there is a permission denied error while creating a dir. I am confused about which and where receiver is trying to make a directory is it on azure storage or is it internal to pod ? Also for what reason it is creating it ? Also why permission denied if it is creating internally? Also, pod is restarting with this error. 

Can some one help me out here since I am struggling with this. 

Logs from thanos receive: 
`
level=error ts=2021-03-26T18:22:24.737394278Z caller=handler.go:330 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10901: get appender: TSDB not ready" msg="internal server error"
level=info ts=2021-03-26T18:22:24.838760534Z caller=multitsdb.go:271 component=receive component=multi-tsdb tenant=default-tenant msg="opening TSDB"
level=error ts=2021-03-26T18:22:24.838845033Z caller=multitsdb.go:334 component=receive component=multi-tsdb tenant=default-tenant msg="failed to start tsdb asynchronously" err="mkdir \": permission denied"
level=error ts=2021-03-26T18:22:24.838885233Z caller=handler.go:330 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10901: get appender: TSDB not ready" msg="internal server error"
level=info ts=2021-03-26T18:22:24.94020909Z caller=multitsdb.go:271 component=receive component=multi-tsdb tenant=default-tenant msg="opening TSDB"
level=error ts=2021-03-26T18:22:24.940285489Z caller=multitsdb.go:334 component=receive component=multi-tsdb tenant=default-tenant msg="failed to start tsdb asynchronously" err="mkdir \": permission denied"
level=error ts=2021-03-26T18:22:24.940363389Z caller=handler.go:330 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10901: get appender: TSDB not ready" msg="internal server error"
level=info ts=2021-03-26T18:22:25.041541646Z caller=multitsdb.go:271 component=receive component=multi-tsdb tenant=default-tenant msg="opening TSDB"
level=error ts=2021-03-26T18:22:25.041639445Z caller=multitsdb.go:334 component=receive component=multi-tsdb tenant=default-tenant msg="failed to start tsdb asynchronously" err="mkdir \": permission denied"
level=error ts=2021-03-26T18:22:25.041684545Z caller=handler.go:330 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10901: get appender: TSDB not ready" msg="internal server error"`
