### ISSUE TITLE
thanos receive goroutine leak when appear conflict error

### ISSUE THREAD

**Issue by zjj2wry** [thanos-io/thanos#3988]
**Thanos, Prometheus and Golang version used**:
v0.19.0-rc.2

**Object Storage Provider**:

**What happened**:
![image](https://user-images.githubusercontent.com/18045633/112841652-54321680-90d3-11eb-9397-f55a396e3f4c.png)

![image](https://user-images.githubusercontent.com/18045633/112846102-3fa44d00-90d8-11eb-8554-1d7b159350a6.png)

prometheus error:
```
monitoring/api/v1/receive msg="Failed to send batch, retrying" err="server returned HTTP status 503 Service Unavailable: 3 errors: backing off forward request for endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: target not available; backing off forward request for endpoint thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901: target not available; store locally for endpoint thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901: conflict"
```

thanos-error
```
level=debug ts=2021-03-29T13:43:55.821111135Z caller=handler.go:557 component=receive component=receive-handler tenant=default-tenant request-id=8de858a3215b4b297362ff90f081732f msg="request failed, but not needed to achieve quorum" err="backing off forward request for endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: target not available"
          level=debug ts=2021-03-29T13:43:55.821111101Z caller=writer.go:80 component=receive component=receive-writer msg="Out of order sample" lset="{__name__=\"apiserver_request_duration_seconds_bucket\", app=\"kubernetes\", cluster=\"shoot/aws/us-west-2/shoot--staging--3db77bab\", component=\"apiserver\", group=\"snapshot.storage.k8s.io\", ignoreAlerts=\"false\", instance=\"10.0.142.184:443\", job=\"apiserver\", le=\"9\", name=\"3db77bab\", pod=\"kube-apiserver-78b7b9569f-nblt4\", project=\"staging\", resource=\"volumesnapshotclasses\", role=\"apiserver\", scope=\"cluster\", seed_api=\"https://172.20.0.1:443\", seed_provider=\"aws\", seed_region=\"us-west-2\", shoot_infra=\"aws\", shoot_name=\"3db77bab\", verb=\"WATCH\", version=\"v1beta1\"}" sample="timestamp:1617025143021 "
          level=debug ts=2021-03-29T13:43:55.821136833Z caller=writer.go:86 component=receive component=receive-writer msg="Out of bounds metric" lset="{__name__=\"kube_pod_status_scheduled_time\", cluster=\"seed/gke/us-central1\", instance=\"10.124.2.8:8443\", job=\"kube-state-metrics\", namespace=\"logging\", pod=\"fluent-bit-fluent-bit-loki-drznl\", prometheus=\"monitoring/k8s\", prometheus_replica=\"prometheus-k8s-0\", provider=\"gke\", region=\"us-central1\"}" sample="value:1.616421124e+09 timestamp:1617011305519 "
          level=debug ts=2021-03-29T13:43:55.821150454Z caller=handler.go:557 component=receive component=receive-handler tenant=default-tenant request-id=b88890ef4aaa520f6d7a002174f7b381 msg="request failed, but not needed to achieve quorum" err="backing off forward request for endpoint thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901: target not available"
        reason: OOMKilled
        startedAt: "2021-03-29T13:41:37Z"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.18.0
  name: thanos-receive
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/instance: thanos-receive
      app.kubernetes.io/name: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database-write-hashring
        app.kubernetes.io/instance: thanos-receive
        app.kubernetes.io/name: thanos-receive
        app.kubernetes.io/version: v0.18.0
    spec:
      serviceAccountName: "thanos"
      tolerations:
        - effect: NoSchedule
          key: memory-optimized
          value: "true"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: memory-optimized
                operator: In
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - thanos-receive
                  - thanos-store
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - thanos-receive
                  - thanos-store
              namespaces:
              - monitoring
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - thanos-receive
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - thanos-receive
              namespaces:
              - monitoring
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --label=replica="$(NAME)"
        - --label=receive="true"
        - --receive.local-endpoint=$(NAME).thanos-receive.$(NAMESPACE).svc.cluster.local:10901
        - --tsdb.retention=2h
        - --log.level=info
        - --log.format=logfmt
        - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        image: quay.io/thanos/thanos:v0.19.0-rc.2
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-receive
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: remote-write
        readinessProbe:
          failureThreshold: 40
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        resources:
          requests:
            cpu: 9
            memory: 30Gi
          limits:
            cpu: 9
            memory: 30Gi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/thanos/receive
          name: data
          readOnly: false
        - mountPath: /var/lib/thanos-receive
          name: hashring-config
      terminationGracePeriodSeconds: 900
      volumes:
      - configMap:
          name: thanos-receive-hashrings
        name: hashring-config
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/component: database-write-hashring
        app.kubernetes.io/instance: thanos-receive
        app.kubernetes.io/name: thanos-receive
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          # 2021/02/18: 200Gi is not enough, change the size to 300Gi
          storage: 300Gi
      storageClassName: prometheus.cloud-fast
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive-hashrings
  namespace: monitoring
data:
  hashrings.json: |
    [
      {
        "hashring": "soft-tenants",
        "endpoints":
        [
          "thanos-receive-0.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-1.thanos-receive.monitoring.svc.cluster.local:10901",
          "thanos-receive-2.thanos-receive.monitoring.svc.cluster.local:10901"
        ]
      }
    ]
```

**Full logs to relevant components**:

**Anything else we need to know**:
