### ISSUE TITLE
TestPrometheus_Targets_e2e doesn't work as expected

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4021]
The E2E test case for target https://github.com/thanos-io/thanos/blob/main/pkg/targets/prometheus_test.go#L23 doesn't work as expected.

It uses the config file below to start Prometheus. The addresses are hardcoded.

``` yaml
testutil.Ok(t, p.SetConfig(`
global:
  external_labels:
    region: eu-west
scrape_configs:
- job_name: 'myself'
  # Quick scrapes for test purposes.
  scrape_interval: 1s
  scrape_timeout: 1s
  static_configs:
  - targets: ['localhost:9090','localhost:80']
  relabel_configs:
  - source_labels: ['__address__']
    regex: '^.+:80$'
    action: drop
`))
	testutil.Ok(t, p.Start())
```

However, the Prometheus instances are started using `e2eutil.NewPrometheus` which allocates a random port for Prometheus. So actually the scrape config is not working. We need to change the target address to the allocated Prometheus address.

A workaround might be:
1. Create the Prometheus with a random address and use the default configuration with target `localhost:9090`
2. Start Prometheus and wait for it ready. Now we can know the real running port of Prometheus
3. Update the target  address of the config to the real Prometheus address
4. Send a SIGHUP or hit `/-/reload` endpoint for a reload

This is the approach I used to fix the same bug for metadata API https://github.com/thanos-io/thanos/pull/4013.
