### ISSUE TITLE
query: /query_exemplars receives empty response

### ISSUE THREAD

**Issue by hhsnow** [thanos-io/thanos#4136]
**Thanos, Prometheus and Golang version used**:
thanos 0.20.1 (sidecar, query, query-frontend)
prometheus 0.26.0 with --enable-feature exemplar-storage
grafana 7.5.5
(docker hub images)

**Object Storage Provider**:
aws/s3

**What happened**:
When querying for exemplars via thanos-query-frontend, I receive the response: 
```
{"status":"success","data":null}
```
The same query directly to the Prometheus that scraped the exemplars returns: 
```
{"status":"success","data":[{"seriesLabels":{"__name__":"http_request_duration_seconds_bucket"," ....
```
If Grafana is set to use the Prometheus as a datasource directly, exemplars will render on the panels.

**What you expected to happen**:
I expect that the exemplar query will be proxied to the relevant (or all) sidecars&prometheus

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

Example exemplar queries:
```
❯ curl 'https://thanos-query-frontend/api/v1/query_exemplars?query=http_request_duration_seconds_bucket&start=1619973810&end=1619974710'
{"status":"success","data":null}
```
```
❯ curl 'https://prometheus/api/v1/query_exemplars?query=http_request_duration_seconds_bucket&start=1619973810&end=1619974710'
{"status":"success","data":[{"seriesLabels":{"__name__":"http_request_duration_seconds_bucket","app":"thanos-query","code":"200","handler":"label_values","instance":"10.232.64.205:19192","job":"kubernetes-service-endpoints","kubernetes_name":"thanos-query","kubernetes_namespace":"prometheus","kubernetes_node":"ip-10-232-64-150.ec2.internal","le":"0.1","method":"get"},"exemplars":[{"labels":{"traceID":"740d43c12631af8f"},"value":"0.021576742","timestamp":1619973825.822}]},{"seriesLabels":{"__name__":"http_request_duration_seconds_bucket","app":"thanos-query","code":"200","handler":"metadata","instance":"10.232.64.205:19192","job":"kubernetes-service-endpoints","kubernetes_name":"thanos-query","kubernetes_namespace":"prometheus","kubernetes_node":"ip-10-232-64-150.ec2.internal","le":"0.001","method":"get"},"exemplars":[{"labels":{"traceID":"79df091e49c3e4cc"},"value":"0.000062484","timestamp":1619973825.971}]},{"seriesLabels":{"__name__":"http_request_duration_seconds_bucket","app":"thanos-query-frontend","code":"200","handler":"query-frontend","instance":"10.232.68.37:9090","job":"kubernetes-service-endpoints","kubernetes_name":"thanos-query-frontend","kubernetes_namespace":"prometheus","kubernetes_node":"ip-10-232-69-131.ec2.internal","le":"0.1","method":"get"},"exemplars":[{"labels":{"traceID":"740d43c12631af8f"},"value":"0.033159782","timestamp":1619973825.831}]},{"seriesLabels":{"__name__":"http_request_duration_seconds_bucket","app":"thanos-query-frontend","code":"200","handler":"query-frontend","instance":"10.232.69.135:9090","job":"kubernetes-service-endpoints","kubernetes_name":"thanos-query-frontend","kubernetes_namespace":"prometheus","kubernetes_node":"ip-10-232-69-234.ec2.internal","le":"0.01","method":"get"},"exemplars":[{"labels":{"traceID":"79df091e49c3e4cc"},"value":"0.003311645","timestamp":1619973825.972}]}]}
```
Example instant queries:
```
❯ curl 'https://thanos-query-frontend/api/v1/query?query=count(http_request_duration_seconds_bucket)'
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1619978529.442,"1008"]}]}}
```
```
❯ curl 'https://prometheus/api/v1/query?query=count(http_request_duration_seconds_bucket)'
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1619978539.197,"1008"]}]}}
```
**Anything else we need to know**:
There are around ~4 external labels used for the Prometheus target. I get the same null result if I include one or more of them in the queries to Thanos.

I can also see exemplar requests via Jaeger tracing with spans up to the querier under "/exemplars HTTP[server]", but they don't seem to propagate further. Not sure if this has been implemented yet.

**Comment by yeya24** [comment]
Hi, thanks for reporting the issue.

I will take a look tomorrow. Can you please try to use thanos query instead of query frontend as Grafana data source and check whether this issue is reproducible?

**Comment by yeya24** [comment]
Also please give me the configuration of your thanos query. I suspect there is a config issue.

**Comment by hhsnow** [comment]
I'm also receiving a "data": null response when targeting the querier directly. I guess one note is that there is a Traefik2 ingress between the query and sidecars/store.

DNS-sanitized query configs from k8s deployment:
```
  - args:
    - --log.level=debug
    - --grpc-client-tls-secure
    - --http-address=0.0.0.0:19192
    - --query.auto-downsampling
    - --query.partial-response
    - --store=thanos-store:443
    - --store=thanos-sidecar:443
    - --store=other-sidecar:443
    - |
      --tracing.config=type: JAEGER
      config:
        service_name: thanos-query
        agent_host: jaeger-agent.jaeger.svc.cluster.local
        sampler_type: const
        sampler_param: 1
        disabled: false
    command:
    - thanos
    - query
```

**Comment by yeya24** [comment]
Hi @hhsnow, it is a configuration issue.
If you want to federate exemplars from Sidecar, you need to add `--exemplar` flag for these store addresses in your thanos query component.


For example, the correct config would be

```
  - args:
    - --log.level=debug
    - --grpc-client-tls-secure
    - --http-address=0.0.0.0:19192
    - --query.auto-downsampling
    - --query.partial-response
    - --store=thanos-store:443
    - --store=thanos-sidecar:443
    - --store=other-sidecar:443
    - --exemplar=thanos-sidecar:443
    - --exemplar=other-sidecar:443
    - |
      --tracing.config=type: JAEGER
      config:
        service_name: thanos-query
        agent_host: jaeger-agent.jaeger.svc.cluster.local
        sampler_type: const
        sampler_param: 1
        disabled: false
    command:
    - thanos
    - query
```
