### ISSUE TITLE
Cant acces storeweb in 0.20

### ISSUE THREAD

**Issue by skpenpen** [thanos-io/thanos#4139]
**Thanos, Prometheus and Golang version used**:

Thanos : 0.20.0

**Object Storage Provider**: filesystem

**What happened**:

Trying to expose storeweb behind reverse proxy, working in 0.19, not in 0.20

**What you expected to happen**:

Working http exposition

**How to reproduce it (as minimally and precisely as possible)**:

````
storeweb:
    image:  thanosio/thanos:v0.20.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      replicas : 1
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=store
        - com.df.port=10902
    environment:
      - SERVICE_NAME=thanos-storeweb
    command:
        - tools
        - bucket
        - web
        - --objstore.config-file=/thanos/storage.yml
        #- --refresh=5m
    volumes:
      - /data/monitoring/prometheus:/prometheus
      - /data/monitoring/thanos:/thanos
    networks:
      default:
      monitoring:
      proxy:    
````

**Full logs to relevant components**:

`level=error ts=2021-05-03T07:55:24.087004883Z caller=http.go:48 protocol=http http.component=server msg="failed to parse host port for http log decision" err="address store.dc1.local: missing port in address"`

**Anything else we need to know**:

Docker swarm, with docker flow reverse proxy
