### ISSUE TITLE
Allow Arbitrary Tags Lightstep Tracing

### ISSUE THREAD

**Issue by midnightconman** [thanos-io/thanos#4148]
### Is your proposal related to a problem?

Not entirely, my proposal is related to a feature... one that would allow additional (arbitrary) tags to be added to the lightstep tracing configuration. The metadata that is passed to lightstep is pretty minimal, this would allow users to add more metadata (possibly that would match external labels?).

### Describe the solution you'd like

I would like the option of adding key value pairs that match the opentracing.Tags object to the lightstep tracing configuration. This would be something like this:

```
      - args:
        - query
        - |
          --tracing.config=type: LIGHTSTEP
          config:
            tags:
              tag1: milkshake
              yard: boys
              "lightstep.env": prod
```

The opentracing.Tracer can take this in the options object. 

Links:
- https://github.com/opentracing/opentracing-go/blob/master/tracer.go#L267
- https://pkg.go.dev/github.com/lightstep/lightstep-tracer-go#Options
- https://github.com/thanos-io/thanos/blob/main/pkg/tracing/lightstep/lightstep.go#L15

### Describe alternatives you've considered

Just leaving it as is and living with the lack of additional metadata?

### Additional context

Links can be found in the `Describe the solution you'd like` section.
