### ISSUE TITLE
Is there a default value for the store gateway's --max-time ?

### ISSUE THREAD

**Issue by amine250** [thanos-io/thanos#4162]
Hi,

Is there a default value for the store gateway's `--max-time` ?

I have the following store configured:
![image](https://user-images.githubusercontent.com/7514608/116987034-d6af8680-acce-11eb-83a9-c01a4f36058e.png)

Now I have set a `--min-time` to -2 weeks but no `--max-time` like so:

```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  labels:
    app: thanos-store-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-gateway
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      containers:
        - name: thanos
          image: thanosio/thanos:v0.13.0
          args:
          - "store"
          - "--log.level=debug"
          - "--data-dir=/data"
          - "--objstore.config={type: S3, config: {bucket: XXXXXXX, endpoint: s3.eu-west-1.amazonaws.com}}"
          - "--index-cache-size=500MB"
          - "--chunk-pool-size=500MB"
          - "--min-time=-2w"
          ports:
          - name: http
            containerPort: 10902
          - name: grpc
            containerPort: 10901
```

My querier looks like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  labels:
    app: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos
        image: thanosio/thanos:v0.13.0
        args:
        - query
        - --log.level=debug
        - --query.replica-label=replica
        - --store=dns+thanos-store-gateway:10901
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
```

The service `thanos-store-gateway` that the querier hits is configured like so: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    thanos-store-api: "true"
```
For the record, I have two Thanos sidecars also labeled as `thanos-store-api: "true"`, which should make me 3 "backends" (`level=debug ts=2021-05-04T09:43:41.013720654Z caller=storeset.go:334 component=storeset msg="checked requested storeAPIs" activeStores=3 cachedStores=3`)

Am I misconfiguring something that I can't get metrics later than 2021-04-29T16:00:00Z ?
