### ISSUE TITLE
Data Gaps while Querying Aggregated Metrics via Thanos Queriers 

### ISSUE THREAD

**Issue by narenreddycs** [thanos-io/thanos#4225]
**Thanos, Prometheus and Golang version used**:
v0.20.0

**Object Storage Provider**:
AWS S3
**What happened**:
In out setup, different local prometheus send metrics to Thanos using remote write. Some aggreagated queries are working perfectly fine and for some others we are seeing gaps. Also, for the queries that are showing gaps, we are seeing raw(un-aggregated) metrics and when a time window aggreagation operation is applied we are seeing gaps.

For example - 
**Query with no data gap** -
 _prometheus_tsdb_head_series{pod=~"prometheus-k8s-.*",datacenter="NP-SJC6B-DC"}_
**Query with data gaps( with time window aggregation)** - _avg_over_time(prometheus_tsdb_head_series{pod=~"prometheusk8s-.*",datacenter="NP-SJC6B-DC"}[5m])_
**If time window is increased from [5m] to [1h]** - _avg_over_time(prometheus_tsdb_head_series{pod=~"prometheus-k8s-.*",datacenter="NP-SJC6B-DC"}[1h])_ , data gaps are not there as all the data points are averaged for 1h time window.

We have **max_source_resolution=1h** set for all the queries in the Queriers UI, as **auto downsampling** is showing some data gaps. **max_source_resolution=1h** shouldn't effect querying last hour data, but setting **auto downsampling or only raw data** is resulting in more data gaps. 

We are seeing same data gaps for the above if query time range is increased from 1h to 12h or 1 day. 

since all un-aggregated metric data is there for the above example query, believe **the issue is happening at the query layer**. The following is the queriers config we are using - 
```
- name: thanos-query
        image: quay.io/thanos/thanos:v0.20.0
        args:
        - query
        - --debug.name=query       
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --query.replica-label=replica
        - --query.auto-downsampling
        - --query.partial-response 
        - --store=dnssrv+thanos-store-time-0-shard-0-grpc.thanos-prod.svc.cluster.local
        - --store=dnssrv+thanos-store-time-0-shard-1-grpc.thanos-prod.svc.cluster.local
        - --store=dnssrv+thanos-store-time-0-shard-2-grpc.thanos-prod.svc.cluster.local
        - --store=dnssrv+thanos-store-time-1-shard-0-grpc.thanos-prod.svc.cluster.local
        - --store=dnssrv+thanos-store-time-1-shard-1-grpc.thanos-prod.svc.cluster.local
        - --store=dnssrv+thanos-store-time-1-shard-2-grpc.thanos-prod.svc.cluster.local
        - --store=dns+thanos-receive-grpc.thanos-prod.svc.cluster.local:10901
        - --tracing.config-file=/etc/tracing/tracing-config.yaml
        - --query.timeout=5m
        - --query.lookback-delta=15m
```
Disabling **query.auto-downsampling** in above config didn't make a difference. 

attaching example querier charts. These charts are at the Querier layer, not at Cache Frontend.
![image-2](https://user-images.githubusercontent.com/18110003/118021744-69c07000-b310-11eb-9417-073e64c43a95.png)
![image-3](https://user-images.githubusercontent.com/18110003/118021754-6cbb6080-b310-11eb-9b87-99704c9418d2.png)
![image-4](https://user-images.githubusercontent.com/18110003/118021759-6d53f700-b310-11eb-9ac3-f93479be3eff.png)

**What you expected to happen**:
There shouldn't be any data gaps while aggregating for all the queries. 

Thank you for the help.
