### ISSUE TITLE
Ruler: skips rule files based on their names without any error/warning log.

### ISSUE THREAD

**Issue by ffilippopoulos** [thanos-io/thanos#4232]
**Thanos version used**:

thanos image: quay.io/thanos/thanos:v0.17.2

**What happened**:

We run thanos-rule with the following flag:
```
--rule-file=/var/thanos/rules/*.yaml
```
to load rules from all the yaml files we put under the above location.
We use `kustomize` `configMapGenerator` to create a configMap with the needed files:
```
configMapGenerator:
  - name: alerts
    files:
      - accounting.yaml=resources/alerts/accounting.yaml
      - billing.yaml=resources/alerts/billing.yaml
      - cbc.yaml=resources/alerts/cbc.yaml
      - partner-data.yaml=resources/alerts/partner-data.yaml
      - partner.yaml=resources/alerts/partner.yaml
      - payments.yaml=resources/alerts/payments.yaml
      - prometheus.yaml=resources/alerts/prometheus.yaml
      - unicom.yaml=resources/alerts/unicom.yaml
```
and mount it under the passed location:
```
        volumeMounts:
        - mountPath: /var/thanos/rules
          name: rules
      volumes:
      - configMap:
          defaultMode: 420
          name: alerts-845c2ttgdg
        name: rules
```
As a result, we can see all the rule files mounted in the pods:
```
$ kubectl --context=dev-merit --namespace=sys-mon exec -ti thanos-rule-56f565b58b-7lvnw -- ls /var/thanos/rules
accounting.yaml    partner-data.yaml  prometheus.yaml
billing.yaml       partner.yaml       unicom.yaml
cbc.yaml           payments.yaml

```

Moreover, thanos ruler is able to see all 8 files on startup:
```
level=info ts=2021-05-11T16:15:45.776401996Z caller=rule.go:836 component=rules msg="reload rule files" numFiles=8
```

Thanos only loads rules from 6/8 files. In particular, the following:
```
/var/thanos/rules/accounting.yaml
/var/thanos/rules/billing.yaml
/var/thanos/rules/cbc.yaml
/var/thanos/rules/payments.yaml
/var/thanos/rules/prometheus.yaml
/var/thanos/rules/unicom.yaml
```

The end result is that we are missing rules defined in 2 yaml files.

**What you expected to happen**:

Load all the rules, or give an error on why it failed to do so.

**How to reproduce it (as minimally and precisely as possible)**:

Following our example should be sufficient here.

**Full logs to relevant components**:

No useful logs from thanos regarding this one. We were profiling the issue via trying different sets of our rule files.

**Anything else we need to know**:

A workaround is to prefix all mounted files with `_`, which seems to do the trick and allows the ruler to load all our rules fine.

In particular, we believe that this behaviour is a result of: https://github.com/thanos-io/thanos/blob/f4a5904b0c3be7565298cf257ad43ac1942021cc/pkg/rules/manager.go#L358 and the way file names are trimmed to be written into tmp dir.

**Environment**:
Kube version: v1.21.0 
OS: Flatcar Container Linux by Kinvolk 2765.2.3 (Oklo)
kernel: 5.10.32-flatcar
container runtime: containerd://1.4.4
