### ISSUE TITLE
Thanos S3 access denied on istio-enabled 

### ISSUE THREAD

**Issue by Gangaram-Dewasi** [thanos-io/thanos#4241]
**Thanos, Prometheus and Golang version used**:
Prometheus-kube-stack helm: 15.2.0 

      Prometheus:
          Repo and version: quay.io/prometheus/prometheus:v2.26.0

Thanos: 
        
    thanos:v0.13.0

**Object Storage Provider**: S3 ( us-west-2 region)

**What happened**:
When we enabled `istio-injection` on the monitoring namespace, the sidecar + other thanos components stopped working with AWS S3 access denied error. 
Added the below pod annotations to the sidecar pod but still the same error,

          podMetadata: 
             annotations:
                traffic.sidecar.istio.io/excludeOutboundPorts: "10901"
                traffic.sidecar.istio.io/excludeInboundPorts: "10901"

The above observation is when we use the **ServiceAccount** on the pods which has access to the S3 bucket (which is working without istio-enabled)
Also, 
When we update the `Thanos-object-store` config to use **aws access** and **secret keys** the setup works fine with istio-enabled.

**What you expected to happen**:
 Post istio enable the thanos components should work with ServiceAccount or with the AWS access and secret keys but it fails to work with serviceAccount throwing s3 access denied error.

```
   prometheus-kub-prometheus-0 thanos-sidecar level=warn ts=2021-05-17T09:14:36.180037002Z caller=sidecar.go:283 err="check exists: stat s3 object: Access Denied." uploaded=0
```
 

**How to reproduce it (as minimally and precisely as possible)**:
Install Prometheus-kube-stack with thanos sidecar enabled, create a S3 bucket and using the eksctl command add an serviceaccount with kubernetes OIDC config to access the S3 bucket. 

```
eksctl create iamserviceaccount \
    --name thanos-s3-access \
    --namespace monitoring \
    --cluster my-dev-playground \
    --attach-policy-arn arn:aws:iam::{accout_ID}:policy/thanos-s3-access \
    --approve \
    --override-existing-serviceaccounts \
    --region us-west-2
```
**S3-Policy:**
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::dev-thanos/*",
                "arn:aws:s3:::dev-thanos"
            ]
        }
    ]
}
```
**Thanos-object-config**:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-store-config
  namespace: monitoring
data:
  thanos-store.yml: |-
    type: S3
    config:
      bucket: dev-thanos
      endpoint: "s3.us-west-2.amazonaws.com"
      insecure: false
      signature_version2: false
      #encryptsse: true
      http_config:
        idle_conn_timeout: 0s
```

**Full logs to relevant components**:

**Anything else we need to know**:
