### ISSUE TITLE
Feature: Mixin: Make lowercasing of runbook anchors optional

### ISSUE THREAD

**Issue by jalev** [thanos-io/thanos#4261]
### Is your proposal related to a problem?

Github is the superior place to put runbooks, but if you happen to be in an Org where that isn't necessarily the practice and use something which supports CamelCasing url anchors (e.g. Atlassian Confluence) you will want your runbook URLs to look prettier.

### Describe the solution you'd like

Let's make the anchor lowercasing something you can opt out of if you want to rather than something you need to modify post-processing.

e.g. you can specify something in your mixin configuration as follows:

```jsonnet

  targetGroups:: {
    cluster: 'thanos_build_info',
    namespace: 'thanos_build_info',
    service: 'thanos_build_info',
  },

  compact+:: {
    selector: 'job=~".*thanos-compact.*"',
    title: '%(prefix)sCompact' % $.dashboard.prefix,
  },

  _config+:: {
    runbookURLPattern: 'https://myCoolMetricsPage.biz/Metrics+runbook#%s',
    runbookURLAnchorsToLowercase: false
  },
```

you will get one of the following alerting rules:
```yaml
  - "alert": "ThanosCompactHasNotRun"
    "annotations":
      "description": "Thanos Compact {{$labels.job}} in {{$labels.cluster}}/{{$labels.namespace}}/{{$labels.service}} has not uploaded anything for 24 hours."
      "runbook_url": "https://myCoolMetricsPage.biz/Metrics+runbook#ThanosCompactHasNotRun"
      "summary": "Thanos Compact has not uploaded anything for last 24 hours."
    "expr": "(time() - max by (cluster, namespace, service, job) (max_over_time(thanos_objstore_bucket_last_successful_upload_time{job=~\".*thanos-compact.*\"}[24h]))) / 60 / 60 > 24"
    "labels":
      "severity": "warning"
```

### Describe alternatives you've considered

I could modify every rule post-processing but that seems excessive. Would rather we fix the data up front than having to go over every rule again just to modify specific bits of it.
