### ISSUE TITLE
Thanos compactor does not remove data post retention-time

### ISSUE THREAD

**Issue by mgronst** [thanos-io/thanos#4311]
Have a new setup running Thanos+Prometheus+MinIO+Grafana. One of the main features selecting this setup is the ability of downsampling and have different retention times on raw data vs hourly data. The downsampling seems to work, by selecting max 1H downsampling in the Thanos frontend I can see downsampled hourly data after 10 days. However the raw-data and 5m data is not removed, despite having 14d retention time both. 

Any pointers to the reason behind it? I now have 24 days with raw-data and 5m data.

Relevant config from docker-compose for thanos-compactor:
```

thanos_compactor:
    image: thanosio/thanos:v0.20.1
    container_name: thanos_compactor
    volumes:
      - /var/lib/prometheus/data/compactor:/data
    command:
      - "compact"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - |
        --objstore.config=type: S3
        config:
            bucket: thanos-data-bucket
            access_key: ****
            secret_key: ****
            endpoint: minio:9000
            insecure: true
      - "--data-dir=/data"
      - "--consistency-delay=30m"
      - "--retention.resolution-raw=14d"
      - "--retention.resolution-5m=14d"
      - "--retention.resolution-1h=5y"
      - "--block-sync-concurrency=20"
      - "--compact.concurrency=1"
      - "--delete-delay=15m"
      - "--wait"
      - "--wait-interval=3m"
    restart: unless-stopped
    expose:
      - 10902
      - 10901
    ports:
      - "10922:10902"
    depends_on:
      - minio
```
