### ISSUE TITLE
--query.auto-downsampling doesn`t seem to have any effect

### ISSUE THREAD

**Issue by mgronst** [thanos-io/thanos#4383]
Setup containing Thanos+Prometheus+Minio+Grafana running as docker containers.

Relevant configuration for Thanos Querier:
```
thanos_querier:
    image: thanosio/thanos:v0.20.1
    container_name: thanos_querier
    command:
      - "query"
      - "--log.level=debug"
      - "--log.format=logfmt"
      - "--store=thanos_sidecar:10901"
      - "--store=thanos_store:10901"
      - "--store.sd-interval=5m"
      - "--query.replica-label=monitor"
      - "--query.auto-downsampling"
    restart: unless-stopped
    expose:
      - 10902
      - 10901
    ports:
      - "10902:10902"
    depends_on:
      - minio
      - thanos_sidecar
      - thanos_store
```

When querying data from Thanos Frontend through Grafana, I only get raw data where I have a 14 days retention time.
Downsampled data with 1H resolution is not shown. Following the PromQL query from Grafana, shows the same
problem in Thanos Frontend. 

Example of PromQL query from Grafana:
`http://prom:19090/graph?g0.expr=expression%7Bapn%3D%22parameter%22%7D&g0.range_input=2592000s&g0.end_input=2021-06-28%2020%3A49&g0.step_input=1800&g0.tab=0`

If add `g0.max_source_resolution=auto` to the PromQL query, I can see the expected historical downsampled data.

So it seems like the parameter `--query.auto-downsampling` doesn`t have effect, and the default returned data is only the raw-data.
