### ISSUE TITLE
traceing use elastic apm

### ISSUE THREAD

**Issue by MrYueQ** [thanos-io/thanos#4386]
**Thanos, Prometheus and Golang version used**:
```yaml
thanos, version 0.21.0 (branch: HEAD, revision: d19aea21b178a6c08838c6a05b834dd44ef14273)
  build user:       root@30b80273f41d
  build date:       20210603-13:49:01
  go version:       go1.16.4
  platform:         linux/amd64

prometheus, version 2.25.0 (branch: HEAD, revision: a6be548dbc17780d562a39c0e4bd0bd4c00ad6e2)
  build user:       root@615f028225c9
  build date:       20210217-14:17:24
  go version:       go1.15.8
  platform:         linux/amd64
```
**Object Storage Provider**:
```yaml
COS
```
**What happened**:
```yaml
thanos turns on the traceid function. Report indicators to elastic
```
**elastic-apm-config**
```yaml
 trace.elastic.apm.yml
type: ELASTIC_APM
config:
  service_name: "thanos"
  service_version: "v1.0.0"
  service_environment: "maxwell"
  sample_rate: 0
```
**systemctl**
```yaml
Environment="ELASTIC_APM_SERVER_URL=http://apm-server:8200"
Environment="ELASTIC_APM_LOG_LEVEL=debug"
Environment="ELASTIC_APM_LOG_FILE=stdout"

thanos query --store.response-timeout=2m \
                  --query.auto-downsampling  \
                  --query.partial-response  \
                  --query.max-concurrent=200 \
                  --query.max-concurrent-select=40 \
                  --query.metadata.default-time-range=30s \
                  --log.format=json \
                  --log.level=warn \
                  --store.unhealthy-timeout=3m  \
                  --store.sd-interval=3m  \
                  --store.sd-files=/data/app/thanos/conf.d/store.yml \
                  --request.logging-config-file=/data/app/thanos/conf.d/logger.yml \
                  --tracing.config-file=/data/app/thanos/conf.d/trace.elastic.apm.yml
```
![image](https://user-images.githubusercontent.com/14846522/123916580-65314300-d9b4-11eb-962c-2a366bbec8bf.png)
![image](https://user-images.githubusercontent.com/14846522/123916659-7d08c700-d9b4-11eb-896c-a27288b56668.png)

**Full logs to relevant components**:
```yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x142274f]
goroutine 713 [running]:
go.elastic.co/apm/module/apmot.(*otSpan).setSpanContext(0xc00125a630)
/go/pkg/mod/go.elastic.co/apm/module/apmot@v1.11.0/span.go:182 +0x2ef
go.elastic.co/apm/module/apmot.(*otSpan).FinishWithOptions(0xc00125a630, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/go.elastic.co/apm/module/apmot@v1.11.0/span.go:99 +0x22e
go.elastic.co/apm/module/apmot.(*otSpan).Finish(0xc00125a630)
/go/pkg/mod/go.elastic.co/apm/module/apmot@v1.11.0/span.go:75 +0x4b
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/tracing.(*opentracingClientReporter).PostCall(0xc000372e00, 0x1fc3220, 0xc000076120, 0xe9591)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/tracing/client.go:34 +0x90
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.(*monitoredClientStream).RecvMsg(0xc000373140, 0x1c46d40, 0xc000cd41e0, 0x10, 0x1a936c0)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/client.go:78 +0x155
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredClientStream).RecvMsg(0xc00000db90, 0x1c46d40, 0xc000cd41e0, 0x2, 0x2)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/client_metrics.go:160 +0x4b
github.com/thanos-io/thanos/pkg/store/storepb.(*storeSeriesClient).Recv(0xc000a42810, 0xc0014caf70, 0x0, 0x1)
/app/pkg/store/storepb/rpc.pb.go:756 +0x62
github.com/thanos-io/thanos/pkg/store.startStreamSeriesSet.func1.2(0xc00125a7e0, 0xc0009d60c0, 0xc0009d6060)
/app/pkg/store/proxy.go:394 +0x4b
created by github.com/thanos-io/thanos/pkg/store.startStreamSeriesSet.func1
/app/pkg/store/proxy.go:392 +0x1af
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x142274f]
goroutine 837 [running]:
go.elastic.co/apm/module/apmot.(*otSpan).setSpanContext(0xc000e90fc0)
/go/pkg/mod/go.elastic.co/apm/module/apmot@v1.11.0/span.go:182 +0x2ef
go.elastic.co/apm/module/apmot.(*otSpan).FinishWithOptions(0xc000e90fc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/go.elastic.co/apm/module/apmot@v1.11.0/span.go:99 +0x22e
go.elastic.co/apm/module/apmot.(*otSpan).Finish(0xc000e90fc0)
/go/pkg/mod/go.elastic.co/apm/module/apmot@v1.11.0/span.go:75 +0x4b
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/tracing.(*opentracingClientReporter).PostCall(0xc0004fd8c0, 0x1fc3220, 0xc000076120, 0x10be2a)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/tracing/client.go:34 +0x90
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.(*monitoredClientStream).RecvMsg(0xc0004fd980, 0x1c46d40, 0xc000e7c4d0, 0x10, 0x1a936c0)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/client.go:78 +0x155
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredClientStream).RecvMsg(0xc00000d320, 0x1c46d40, 0xc000e7c4d0, 0x2, 0x2)
/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/client_metrics.go:160 +0x4b
github.com/thanos-io/thanos/pkg/store/storepb.(*storeSeriesClient).Recv(0xc000a42360, 0xc001185f70, 0x0, 0x1)
/app/pkg/store/storepb/rpc.pb.go:756 +0x62
github.com/thanos-io/thanos/pkg/store.startStreamSeriesSet.func1.2(0xc000e91170, 0xc00027c660, 0xc00027c600)
/app/pkg/store/proxy.go:394 +0x4b
created by github.com/thanos-io/thanos/pkg/store.startStreamSeriesSet.func1
/app/pkg/store/proxy.go:392 +0x1af
```
