### ISSUE TITLE
Store-Gateway can't read historical metrics from GCP bucket

### ISSUE THREAD

**Issue by iliyahoo** [thanos-io/thanos#4484]
**Thanos version used**: **v0.21.1**

**Object Storage Provider**: **GCP**

**What happened**: 
Trying to retrieve historical data from GCP bucket consistenly getting the error
```
level=debug ts=2021-07-26T11:49:09.243646183Z caller=bucket.go:1078 msg="stats query processed" stats="&{blocksQueried:0 postingsTouched:1638 postingsTouchedSizeSum:317601 postingsToFetch:0 postingsFetched:0 postingsFetchedSizeSum:0 postingsFetchCount:0 postingsFetchDurationSum:0 cachedPostingsCompressions:0 cachedPostingsCompressionErrors:0 cachedPostingsOriginalSizeSum:0 cachedPostingsCompressedSizeSum:0 cachedPostingsCompressionTimeSum:0 cachedPostingsDecompressions:1638 cachedPostingsDecompressionErrors:0 cachedPostingsDecompressionTimeSum:1996286 seriesTouched:0 seriesTouchedSizeSum:0 seriesFetched:0 seriesFetchedSizeSum:0 seriesFetchCount:0 seriesFetchDurationSum:0 chunksTouched:0 chunksTouchedSizeSum:0 chunksFetched:0 chunksFetchedSizeSum:0 chunksFetchCount:0 chunksFetchDurationSum:0 getAllDuration:0 mergedSeriesCount:0 mergedChunksCount:0 mergeDuration:0}" err="rpc error: code = Aborted desc = fetch series for block 01F9PN032H5717GYENM2ED767Z: expanded matching posting: get postings: read postings range: get range reader: Get \"https://storage.googleapis.com/thanos-long-term/01F9PN032H5717GYENM2ED767Z/index\": context canceled"
level=debug ts=2021-07-26T11:49:09.372648263Z caller=bucket.go:1078 msg="stats query processed" stats="&{blocksQueried:0 postingsTouched:2430 postingsTouchedSizeSum:481212 postingsToFetch:0 postingsFetched:792 postingsFetchedSizeSum:382632 postingsFetchCount:792 postingsFetchDurationSum:934286803292 cachedPostingsCompressions:792 cachedPostingsCompressionErrors:0 cachedPostingsOriginalSizeSum:382632 cachedPostingsCompressedSizeSum:50486 cachedPostingsCompressionTimeSum:5725057 cachedPostingsDecompressions:1638 cachedPostingsDecompressionErrors:0 cachedPostingsDecompressionTimeSum:1500990 seriesTouched:0 seriesTouchedSizeSum:0 seriesFetched:0 seriesFetchedSizeSum:0 seriesFetchCount:0 seriesFetchDurationSum:0 chunksTouched:0 chunksTouchedSizeSum:0 chunksFetched:0 chunksFetchedSizeSum:0 chunksFetchCount:0 chunksFetchDurationSum:0 getAllDuration:0 mergedSeriesCount:0 mergedChunksCount:0 mergeDuration:0}" err="rpc error: code = Aborted desc = fetch series for block 01FAF3RYJFM78QJJFTGEZJEDQQ: expanded matching posting: get postings: read postings range: get range reader: Get \"https://storage.googleapis.com/thanos-long-term/01FAF3RYJFM78QJJFTGEZJEDQQ/index\": dial tcp 142.250.74.208:443: i/o timeout"
```
The same time the **livenessProbe** is falling too:
```
# while true ; do curl http://10.114.44.3:10902/-/healthy -m 1 ; sleep 1 ; echo ; done
...
OK
OK
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received

curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received

curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received

OK
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received

curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received

OK
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received

OK
OK
...
```
_Pod resource request_
```
        resources:
          limits:
            memory: "120G"
            cpu: "4000m"
```
_Pod arguments_
```
        args:
        - store
        - --log.level=debug
        - --data-dir=/data
        - --objstore.config-file=/mnt/thanos-objstore-config/thanos-storage-conf.yaml
        - --index-cache-size=30GB
        - --chunk-pool-size=80GB
        - --ignore-deletion-marks-delay=24h
```

**How to reproduce it**:
Query metrics for last 6 months
```
netdata_system_cpu_percentage_average{job="netdata",hostname=~"ns-ng1"}
```

**Comment by hanjm** [comment]
Seems you have many blocks in object store. you should sharding store-gateway by time and relabel with hashmod or tenant. refrence doc: https://thanos.io/tip/thanos/sharding.md/#time-partitioning

**Comment by iliyahoo** [comment]
Thank you for reply. I created 12 thanos-store shards by `modulus` relabeling.  
Store is much better now but still freezes and shows metrics incompletely. 

Here is an excretion from the manifest:
```
spec:
  replicas: 12
  template:
    spec:
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.21.1
        args:
        - store
        - --log.level=debug
        - --data-dir=/data
        - --objstore.config-file=/mnt/thanos-objstore-config/thanos-storage-conf.yaml
        - --index-cache-size=7GB
        - --chunk-pool-size=20GB
        - --ignore-deletion-marks-delay=24h
        resources:
          limits:
            memory: "30G"
            cpu: "1500m"
```

Our bucket is huge. Can we tune the thanos-store anyhow or it has limitations?
