### ISSUE TITLE
Thanos Store GW cannot start

### ISSUE THREAD

**Issue by alochym01** [thanos-io/thanos#4515]
Hi

i use thanos v0.17.2 with thanos receiver and thanos store gatway.

Tha thanos receiver is working.

I use minio as S3 storage and config for minio client. **The minio S3 server is used self sign certificate**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: thanos
type: Opaque
stringData:
  thanos.yaml: |-
    type: s3
    config:
      bucket: alochym
      endpoint: minio.minio-tenant-1.svc.cluster.local:443
      insecure: true
      signature_version2: false
      access_key: 3ab97c53-50a4-4a01-ad2a-ce3f1c1bc730
      secret_key: 59f9a4d3-2f92-42c4-b766-9cc12097478b
      http_config:
        insecure_skip_verify: true
      trace:
        enable: true
```

config thanos store gateway
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: thanos-store
  name: thanos-store
  namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-store
  serviceName: thanos-store
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-store
    spec:
      containers:
      - args:
        - store
        - --log.level=info
        - --log.format=logfmt
        - --data-dir=/var/thanos/store
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --ignore-deletion-marks-delay=24h
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        image: quay.io/thanos/thanos:v0.17.2
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-store
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        volumeMounts:
        - mountPath: /var/thanos/store
          name: data
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage        
      resources:
        requests:
          storage: 10G
```

When i start thanos gateway and thanos store gateway cannot start and the error log is below

```bash
level=info ts=2021-08-03T00:04:12.91433657Z caller=http.go:84 service=http/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: read tcp 172.16.235.197:42654->10.110.100.21:443: read: connection reset by peer"
level=info ts=2021-08-03T00:04:12.91446517Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: read tcp 172.16.235.197:42654->10.110.100.21:443: read: connection reset by peer"
level=warn ts=2021-08-03T00:04:12.914532023Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: read tcp 172.16.235.197:42654->10.110.100.21:443: read: connection reset by peer"
```

How to fix it
thank you
