### ISSUE TITLE
query|query-frontend log stdout rpc 404

### ISSUE THREAD

**Issue by MrYueQ** [thanos-io/thanos#4668]
hi, thanos-query/thanos-query-fronted log stdout msg
```yaml
 {"caller":"proxy.go:146","err":"receiving exemplars from exemplars client &{0xc000318700}: rpc error: code = NotFound desc = expected 2xx response, got 404. Body: 404 page not found\n","level":"error","ts":"2021-09-16T16:58:31.723349198Z"}
```

thanos version
```yaml
 /data/app/thanos/bin/thanos --version
thanos, version 0.23.0-rc.0 (branch: HEAD, revision: 81841aed4a9e3d6f6ed772fea287f04504d164f3)
  build user:       root@d1bae1e2c93c
  build date:       20210908-14:46:03
  go version:       go1.16.7
  platform:         linux/amd64
```

thanos query config
```yaml
/data/app/thanos/bin/thanos query --store.response-timeout=5m \
                  --query.partial-response \
                  --query.timeout=5m \
                  --query.auto-downsampling  \
                  --query.default-step=15s \
                  --query.max-concurrent=200 \
                  --query.max-concurrent-select=40 \
                  --query.metadata.default-time-range=15m \
                  --query.default-evaluation-interval=3m  \
                  --log.format=json \
                  --log.level=info \
                  --store.unhealthy-timeout=5m  \
                  --store.sd-interval=3m  \
                  --request.logging-config-file=/data/app/thanos/conf.d/logger.yaml \
                  --tracing.config-file=/data/app/thanos/conf.d/trace.jaeger.yml \
                  --store.sd-files=/data/app/thanos/conf.d/store.yml
```
