### ISSUE TITLE
Thanos-QueryFrontend stdout Warning: Error fetching metrics lists.

### ISSUE THREAD

**Issue by MrYueQ** [thanos-io/thanos#4700]
hi. thanos-query-frontend web display "Warning: Error fetching metrics list: Unexpected response status when fetching metric names:"
thanos version
```yaml
thanos, version 0.22.0 (branch: HEAD, revision: 3656e290c8eb034e2e09e0afc79f087be88de481)
  build user:       root@61bcfbac7168
  build date:       20210721-15:22:37
  go version:       go1.16.6
  platform:         linux/amd64
```

![image](https://user-images.githubusercontent.com/14846522/134664197-9ea4747a-7a29-4091-8b70-b7a9a76dd83b.png)
