### ISSUE TITLE
cfggen: recognize comments in the struct while generating output

### ISSUE THREAD

**Issue by Dentrax** [thanos-io/thanos#4751]
### Is your proposal related to a problem?

As we discussed with @saswatamcode at PR https://github.com/thanos-io/thanos/pull/4749, the problem simply identifies that we had better to improve the [tracing configuration](https://thanos.io/tip/thanos/tracing.md/#configuration) doc as we proposed at https://github.com/thanos-io/thanos/issues/4748. 

(Write your answer here.)

### Describe the solution you'd like

We have to do some enhancements in the [scripts/cfggen](https://github.com/thanos-io/thanos/blob/main/scripts/cfggen/main.go) to make that tool recognize the comments.

Let's assume we have the following [config struct](https://github.com/thanos-io/thanos/blob/3040829c4c11ad276db6c8d681b581f583a877e2/pkg/tracing/jaeger/config_yaml.go#L21-L40):
```golang
// Config - YAML configuration.
type Config struct {
  // Foo used for to store string
  Foo  string   `yaml:"foo"`
  // Bar used for to store bool
  // true by default
  Bar  bool     `yaml:"bar"`
  // Baz used for to store float64
  Baz  float64  `yaml:"baz"`
}
```

cfggen should generate the following yaml snippet:

```yaml mdox-exec="go run scripts/cfggen/main.go --name=jaeger.Config"
type: JAEGER
config:
  # Foo used for to store string
  foo: ""
  # Bar used for to store bool
  # true by default
  bar: false
  # Baz used for to store float64
  baz: 0
```

### Describe alternatives you've considered

We can add Markdown table in below for each configuration like the following:

| Property 	| Description 	|
|---	|---	|
| sampler_type 	| The sampler type:  remote ,  const ,  probabilistic ,  ratelimiting  (default  remote). [More information](https://www.jaegertracing.io/docs/latest/sampling/) 	|
