### ISSUE TITLE
Out-of-order samples with HA prometheus with unique labels

### ISSUE THREAD

**Issue by joe-pll** [thanos-io/thanos#4767]
**Thanos, Prometheus and Golang version used**:
I am currently using Thanos **v0.23.1**, with Prometheus **v2.30.3**

**Object Storage Provider**:
Google Cloud Storage

**What happened**:
Hi, I am currently testing Thanos as a long term storage for metrics. At the moment I deployed Thanos with a docker-compose file in a GCP VM. I am using the configuration with the Thanos receiver since we need a push solution. As a test, I am pushing metrics from a Kubernetes test cluster with a HA Prometheus, there are 2 instances of Prometheus which have an unique set of labels; my configuration looks as follow:
```yaml
external_labels:
  cluster: cluster-test
  prometheus_replica: ${POD_NAME}
```
The variable POD_NAME takes the name of the pods, which are `prometheus-0` and `prometheus-1` since we deploy Prometheus as a StatefulSet.
Even with this configuration Thanos keeps throwing `Error on ingesting out-of-order samples` with the following logs in debug mode
```json
{"[tenant default-tenant request-id  msg local tsdb write failed err add 1 samples: duplicate sample for timestamp]":"(MISSING)","caller":"handler.go:491","component":"receive-handler","level":"debug","ts":"2021-10-11T12:40:39.515363016Z"}
```
Scaling down the HA Prometheus servers to 1 instance everything works fine. I double verified that both Prometheus instances have the correct `external_labels` in their configuration and it seems so.

**What you expected to happen**:
I should not see out-of-order messages

**How to reproduce it (as minimally and precisely as possible)**:
For Thanos receiver I use the following configuration
```yaml
receiver:
    image: quay.io/thanos/thanos:v0.23.1
    command:
      - receive
      - --tsdb.path=/data
      - --grpc-address=0.0.0.0:10907
      - --http-address=0.0.0.0:10909
      - --receive.replication-factor=1
      - --receive.local-endpoint=127.0.0.1:10907
      - --receive.hashrings-file=/conf/hashring.json
      - --remote-write.address=0.0.0.0:10908
      - --objstore.config-file=/conf/bucket.yml
      - --log.format=json
      - --log.level=debug
      - --tsdb.retention=7d
      - --label=receive_replica="rec0"
      - --label=receive_cluster="rec0"
    ports:
      - 0.0.0.0:10908:10908
      - 0.0.0.0:10909:10909
    volumes:
      - ./receiver-bucket.yml:/conf/bucket.yml
      - ./receiver-hashring.json:/conf/hashring.json
      - /mnt/receive-data:/data
```

For Prometheus I use the following instead

```yaml
global:
    scrape_interval: 30s
    scrape_timeout: 10s
    evaluation_interval: 30s
    external_labels:
      cluster: cluster-test
      prometheus_replica: ${POD_NAME}

remote_write:
  - url: http://_._._._:10908/api/v1/receive
```

The environment variables are defined as
```yaml
    env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```

**Full logs to relevant components**:

**Anything else we need to know**:

**Environment**:
For Thanos servers

- OS:
  ```
  NAME="Ubuntu"
  VERSION="20.04.3 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.3 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
  ```
- Kernel:
  ```
  Linux thanos-test 5.11.0-1020-gcp #22~20.04.1-Ubuntu SMP Tue Sep 21 10:54:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  ```
