### ISSUE TITLE
Add custom certificate CA support for object store

### ISSUE THREAD

**Issue by clyang82** [thanos-io/thanos#4820]
### Is your proposal related to a problem?

Currently, the implementation of connecting with object store is short of tls configuration.
https://github.com/thanos-io/thanos/blob/2695ecd69c4464914ad4b4480b5e924ebfcd919d/pkg/objstore/s3/s3.go#L150

for my case, I would need the ability to set a custom CA somewhere so that I can connect the external object store. for a workaround, i have to disable tls verification by
```
type: S3
config:
  bucket: ""
  endpoint: ""
  access_key: ""
  insecure: false
  signature_version2: false
  encrypt_sse: false
  secret_key: ""
  http_config:
    insecure_skip_verify: true
```

(Write your answer here.)

### Describe the solution you'd like

Support configuring certificate CA in `http_config`

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)
