### ISSUE TITLE
Missing data points for recording rule evaluation result

### ISSUE THREAD

**Issue by morvencao** [thanos-io/thanos#4900]
**Thanos, Prometheus and Golang version used**:

Thanos version: 0.22
Prometheus version: 2.29.2
Golang version: 1.17

**Object Storage Provider**: AWS S3

**What happened**:

We have defined the following recordingrule for thanos ruler:

```
      - name: foo
        rules:
        - expr: sum(cluster:kube_pod_container_resource_requests:cpu:sum) by (cluster) / sum(kube_node_status_allocatable{resource="cpu"}) by (cluster)
          record: cluster:cpu_requested:ratio
```

We found that lots of data points are missing in thanos ruler evaluation results, we user default evaluation interval(30s), as you can see from blow chart:

![image](https://user-images.githubusercontent.com/5468682/143397585-15a06b45-f63a-4bee-9e3c-ff47bbe65950.png)

But if we query the original expression directly, we can see all the data points:

![image](https://user-images.githubusercontent.com/5468682/143397246-b31462b0-6a73-470c-8fbe-2ff7a179ae90.png)

**What you expected to happen**:

Thanos rule evaluation should have the same results with the direct query.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

Is this relevant with the `prometheus_rule_evaluation_failures_total` metrics of thanos rule, I also checked the thanos rule evaluation at the period, see blow chart:

![image](https://user-images.githubusercontent.com/5468682/143398407-c767466b-4eeb-4902-9fda-37ec7eeed526.png)
