### ISSUE TITLE
component query get stalled

### ISSUE THREAD

**Issue by SeanTse** [thanos-io/thanos#4981]
We have a query deployed with docker-compose in the production environment, which looks like this. 
```
query:
    container_name: query
    image: thanosio/thanos:v0.23.1
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    network_mode: host
    command:
    - query
    - --grpc-address=0.0.0.0:10903
    - --http-address=0.0.0.0:19192
    - --store=localhost:10901
    - --store=192.168.1.1:10901 
    - --store=store-for-s3:10904
    - --query.replica-label=replica
    - --query.max-concurrent=200
    - --query.partial-response
    - --store.response-timeout=5s
```
When this query runs for a day or two, it gets stuck but dosen't crash. Looks like below and stuck here:
![query](https://user-images.githubusercontent.com/17649478/147047806-3c187f78-874b-44ee-8d7e-9f29bf913b34.jpg)
![postman](https://user-images.githubusercontent.com/17649478/147048061-f41be4d1-7f61-48c0-860b-506d669f623b.jpg)
By clicking the F12 button, it shows the query request is pending. And I find no related log. And the earlier logs is tons of lines look like belowed, which I can't tell whether they are related:
```
{"log":"level=warn ts=2021-12-21T09:06:54.122037249Z caller=proxy.go:471 component=proxy request=\"min_time:1640069984000 max_time:1640077484000 matchers:\u003cname:\\\"workspace\\\" value:\\\"10006932\\\" \u003e matchers:\u003cname:\\\"cluster\\\" value:\\\"11703738\\\" \u003e matchers:\u003ctype:RE name:\\\"mode\\\" value:\\\"user|system|iowait|irq|softirq\\\" \u003e matchers:\u003cname:\\\"__name__\\\" value:\\\"node_cpu_seconds_total\\\" \u003e aggregates:COUNT aggregates:SUM \" err=\"failed to receive any data from Addr: 192.168.1.1:10901 LabelSets: {replica=\\\"0\\\"} Mint: 1639818282057 Maxt: 9223372036854775807: context deadline exceeded\" msg=\"returning partial response\"\n","stream":"stderr","time":"2021-12-21T09:06:54.122266194Z"}
{"log":"level=warn ts=2021-12-21T09:06:55.413513718Z caller=proxy.go:471 component=proxy request=\"min_time:1640073960000 max_time:1640077560000 matchers:\u003cname:\\\"workspace\\\" value:\\\"10002223\\\" \u003e matchers:\u003cname:\\\"cluster\\\" value:\\\"11689005\\\" \u003e matchers:\u003cname:\\\"__name__\\\" value:\\\"kubevirt_vmi_vcpu_seconds\\\" \u003e aggregates:COUNT aggregates:SUM \" err=\"receive series from Addr: 192.168.1.1:10901 LabelSets: {replica=\\\"160\\\"} Mint: 1639818345948 Maxt: 9223372036854775807: rpc error: code = Canceled desc = grpc: the client connection is closing\" msg=\"returning partial response\"\n","stream":"stderr","time":"2021-12-21T09:06:55.414072875Z"}
{"log":"level=warn ts=2021-12-21T09:06:56.124223044Z caller=proxy.go:471 component=proxy request=\"min_time:1640073959000 max_time:1640077559000 matchers:\u003cname:\\\"workspace\\\" value:\\\"10002223\\\" \u003e matchers:\u003cname:\\\"cluster\\\" value:\\\"11689006\\\" \u003e matchers:\u003cname:\\\"__name__\\\" value:\\\"kubevirt_vmi_vcpu_seconds\\\" \u003e aggregates:COUNT aggregates:SUM \" err=\"receive series from Addr: 192.168.1.1:10901 LabelSets: {replica=\\\"160\\\"} Mint: 1639818345948 Maxt: 9223372036854775807: rpc error: code = Canceled desc = grpc: the client connection is closing\" msg=\"returning partial response\"\n","stream":"stderr","time":"2021-12-21T09:06:56.124626531Z"}
```
Here the `Maxt` make me confused, which is abnormally large. Where does it come from?
Restarting query can temporarily solve this problem. 

Our Prometheus TSDB Status:
| Number of Series | Number of Chunks | Number of Label Pairs | Current Min Time                         | Current Max Time                         |
| ---------------- | ---------------- | --------------------- | ---------------------------------------- | ---------------------------------------- |
| 7280056          | 11359014         | 238888                | 2021-12-22T06:00:00.000Z (1640152800000) | 2021-12-22T07:19:46.089Z (1640157586089) |
