### ISSUE TITLE
Receiver: data doesn't get deleted even beyond the retention time

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4993]
**Thanos, Prometheus and Golang version used**:
v0.23.2-rc.1

**What happened**:

We are using Thanos Receivers to accept metrics from remote write. The configured tsdb retention is 6h.

But now, I think the data from `default-tenant` is already beyond the configured retention and doesn't get deleted.

![image](https://user-images.githubusercontent.com/25150124/147290550-d2423541-d111-49a1-a6ee-a9d88be4d339.png)

I am not sure why it stops cleaning up data, but since sometime yesterday the tenant stops sending data to receiver due to some configuration change.

**What you expected to happen**:

The data from the default tenant should be deleted and the tenant is removed (maybe)?

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

From the logs, it looks like deletion does happen and should happen as the underlying Prometheus TSDB will trigger reload and check retention every 1m. 

![image](https://user-images.githubusercontent.com/25150124/147290774-f4982751-c917-40fb-88db-b6d064f47e2f.png)

**Anything else we need to know**:

``` yaml
      containers:
      - args:
        - receive
        - --log.level=info
        - --log.format=logfmt
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=6h
        - --label=replica="$(NAME)"
        - --receive.local-endpoint=$(NAME).thanos-receive-default.$(NAMESPACE).svc:10901
        - --receive.tenant-label-name=cluster
        - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
        - |-
          --tracing.config="config":
            "sampler_param": 2
            "sampler_type": "ratelimiting"
            "service_name": "thanos-receive"
          "type": "JAEGER"
```
