### ISSUE TITLE
Receive: Load distribution for hard tenant doesn't work

### ISSUE THREAD

**Issue by koktlzz** [thanos-io/thanos#4995]
**Thanos, Prometheus and Golang version used**:

Thanos: 0.23.1
Go: 1.16.8
Prometheus: 2.28.1

**Object Storage Provider**:

Huawei S3

**What happened**:

There is one soft tenant and two hard tenants(called sc and ci respectively) in my cluster and each of them has a thanos receive and obs bucket. When the prometheus of the hard tenant send metrics to the receive of soft tenant by remote write, the data isn't distributed to the receive of the hard tenant and will be stored in the bucket of the soft tenant.

**What you expected to happen**:

Due to the hashring.json in the thanos receive of soft tetant and the http header set by nginx, the metrics of hard tenant should be distributed to the receive of hard tenant.

**How to reproduce it (as minimally and precisely as possible)**:

I use the openshift container platform and expose the services by openshift routes(*.apps.test.ocp.com).

Hard tenant prometheus(out of the thanos cluster) remote write config:

```yaml
remote_write:
  - url: http://nginx-proxy-monitor.apps.test.ocp.com/api/v1/receive
```

Nginx.conf:

```shell
...
    http {
      ...
      server { # reverse-proxy and tenant header setting
        listen 80;
        proxy_set_header THANOS-TENANT sc;

        location / {
          proxy_pass      http://thanos-receiver-public.monitor.svc.cluster.local:19291$request_uri;
        }
      }
    }
```

Soft-tenat(public) thanos receive statefulset:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receiver-public
  labels:
    app: thanos-receiver
    tenant: public
    controller.receive.thanos.io: thanos-receive-controller
    controller.receive.thanos.io/hashring: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receiver
      tenant: public
      controller.receive.thanos.io: thanos-receive-controller
      controller.receive.thanos.io/hashring: default
  serviceName: thanos-receiver-public
  template:
    metadata:
      labels:
        app: thanos-receiver
        tenant: public
        controller.receive.thanos.io: thanos-receive-controller
        controller.receive.thanos.io/hashring: default
    spec:
      containers:
      - name: thanos-receiver
        image: thanos:0.23.1
        args:
        - receive
        - --label=replica="$(NAME)"
        - --receive.local-endpoint=$(NAME).thanos-receiver-public.monitor.svc.cluster.local:10901
        - --receive.default-tenant-id=public
        - --tsdb.path=/data/remote-write-receive-data
        - --tsdb.retention=12h     
        - --log.level=info
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/prometheus/obs-config/public-bucket.yaml
        - --receive.hashrings-file=/etc/prometheus/hashring-config/hashrings.json
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: remote-write
        volumeMounts:
        - name: s3-store-credentials
          mountPath: /etc/prometheus/obs-config
          readOnly: true
        - name: remote-write-data
          mountPath: /data/remote-write-receive-data
        - mountPath: /etc/prometheus/hashring-config
          name: hashring-config
      volumes:
      - name: s3-store-credentials
        secret:
          secretName: store-s3-credentials
      - name: remote-write-data
        emptyDir: {}
      - configMap:
          name: thanos-receiver-hashring-generated-config
        name: hashring-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-receiver
    tenant: public
    controller.receive.thanos.io/hashring: default
  name: thanos-receiver-public
spec:
  ports:
  - port: 10902
    protocol: TCP
    targetPort: http
    name: http
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  - port: 19291
    protocol: TCP
    targetPort: remote-write
    name: remote-write
  selector:
    app: thanos-receiver
    tenant: public
    controller.receive.thanos.io: thanos-receive-controller
    controller.receive.thanos.io/hashring: default
  type: ClusterIP
```

The hashring.json is generated by thanos-receiver-controller:

```json
[
    {
        "hashring": "default",
        "endpoints": [
            "thanos-receiver-public-0.thanos-receiver-public.monitor.svc.cluster.local:10901"
        ]
    },
    {
        "hashring": "hashring-ci",
        "tenants": [
            "ci"
        ],
        "endpoints": [
            "thanos-receiver-ci-0.thanos-receiver-ci.monitor.svc.cluster.local:10901"
        ]
    },
    {
        "hashring": "hashring-sc",
        "tenants": [
            "sc"
        ],
        "endpoints": [
            "thanos-receiver-sc-0.thanos-receiver-sc.monitor.svc.cluster.local:10901"
        ]
    }
]
```

One of hard tenant thanos receive statefulset:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receiver-sc
  labels:
    app: thanos-receiver
    tenant: sc
    controller.receive.thanos.io: thanos-receive-controller
    controller.receive.thanos.io/hashring: hashring-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receiver
      tenant: sc
      controller.receive.thanos.io: thanos-receive-controller
      controller.receive.thanos.io/hashring: hashring-sc
  serviceName: thanos-receiver-sc
  template:
    metadata:
      labels:
        app: thanos-receiver
        tenant: sc
        controller.receive.thanos.io: thanos-receive-controller
        controller.receive.thanos.io/hashring: hashring-sc
    spec:
      containers:
      - name: thanos-receiver
        image: thanos:0.23.1
        args:
        - receive
        - --label=replica="$(NAME)"
        - --receive.local-endpoint=$(NAME).thanos-receiver-sc.monitor.svc.cluster.local:10901
        - --receive.default-tenant-id=sc
        - --tsdb.path=/data/remote-write-receive-data
        - --tsdb.retention=12h     
        - --log.level=info
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/prometheus/obs-config/sc-bucket.yaml
        - --receive.hashrings-file=/etc/prometheus/hashring-config/hashrings.json
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: remote-write
        volumeMounts:
        - name: s3-store-credentials
          mountPath: /etc/prometheus/obs-config
          readOnly: true
        - name: remote-write-data
          mountPath: /data/remote-write-receive-data
        - mountPath: /etc/prometheus/hashring-config
          name: hashring-config
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
      volumes:
      - name: s3-store-credentials
        secret:
          secretName: store-s3-credentials
      - name: remote-write-data
        emptyDir: {}
      - configMap:
          name: thanos-receiver-hashring-generated-config
        name: hashring-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-receiver
    tenant: sc
    controller.receive.thanos.io/hashring: hashring-sc
  name: thanos-receiver-sc
spec:
  ports:
  - port: 10902
    protocol: TCP
    targetPort: http
    name: http
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  - port: 19291
    protocol: TCP
    targetPort: remote-write
    name: remote-write
  selector:
    app: thanos-receiver
    tenant: sc
    controller.receive.thanos.io: thanos-receive-controller
    controller.receive.thanos.io/hashring: hashring-sc
  type: ClusterIP
```

**Full logs to relevant components**:

Soft-tenant thanos receive:

```shell
level=warn ts=2021-12-24T02:16:50.179108714Z caller=writer.go:135 component=receive component=receive-writer msg="Error on ingesting samples with different value but same timestamp" numDropped=24
level=warn ts=2021-12-24T02:16:50.19322743Z caller=writer.go:135 component=receive component=receive-writer msg="Error on ingesting samples with different value but same timestamp" numDropped=18
level=warn ts=2021-12-24T02:16:50.217649244Z caller=writer.go:135 component=receive component=receive-writer msg="Error on ingesting samples with different value but same timestamp" numDropped=79
level=warn ts=2021-12-24T02:16:50.226910328Z caller=writer.go:135 component=receive component=receive-writer msg="Error on ingesting samples with different value but same timestamp" numDropped=3
level=warn ts=2021-12-24T02:16:50.231480852Z caller=writer.go:135 component=receive component=receive-writer msg="Error on ingesting samples with different value but same timestamp" numDropped=7
```

Hard-tenant thanos receive:

```shell
level=info ts=2021-12-23T08:32:13.582703406Z caller=multitsdb.go:327 component=receive component=multi-tsdb tenant=sc msg="TSDB is now ready"
level=info ts=2021-12-23T08:32:13.584023865Z caller=intrumentation.go:48 component=receive msg="changing probe status" status=ready
level=info ts=2021-12-23T08:32:13.584041434Z caller=receive.go:538 component=receive msg="storage started, and server is ready to receive web requests"
level=info ts=2021-12-23T08:32:13.584386803Z caller=receive.go:346 component=receive msg="listening for StoreAPI and WritableStoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2021-12-23T08:32:13.584435478Z caller=grpc.go:127 component=receive service=gRPC/server component=receive msg="listening for serving gRPC" address=0.0.0.0:10901
```

Nginx:

```shell
10.254.10.1 - - [24/Dec/2021:03:43:27 +0000]  200 "POST /api/v1/receive HTTP/1.1" 0 "-" "Prometheus/2.28.1" "11.125.64.78"
10.254.10.1 - - [24/Dec/2021:03:43:27 +0000]  200 "POST /api/v1/receive HTTP/1.1" 0 "-" "Prometheus/2.28.1" "11.125.64.78"
10.254.10.1 - - [24/Dec/2021:03:43:27 +0000]  200 "POST /api/v1/receive HTTP/1.1" 0 "-" "Prometheus/2.28.1" "11.125.64.78"
10.254.10.1 - - [24/Dec/2021:03:43:27 +0000]  200 "POST /api/v1/receive HTTP/1.1" 0 "-" "Prometheus/2.28.1" "11.125.64.78"
10.254.4.1 - - [24/Dec/2021:03:43:27 +0000]  409 "POST /api/v1/receive HTTP/1.1" 117 "-" "Prometheus/2.28.1" "11.125.64.146"
10.254.4.1 - - [24/Dec/2021:03:43:27 +0000]  200 "POST /api/v1/receive HTTP/1.1" 0 "-" "Prometheus/2.28.1" "11.125.64.146"
10.254.4.1 - - [24/Dec/2021:03:43:27 +0000]  409 "POST /api/v1/receive HTTP/1.1" 117 "-" "Prometheus/2.28.1" "11.125.64.146"
10.254.4.1 - - [24/Dec/2021:03:43:27 +0000]  200 "POST /api/v1/receive HTTP/1.1" 0 "-" "Prometheus/2.28.1" "11.125.64.146"
```

Prometheus：

```shell
ts=2021-12-24T04:21:47.172Z caller=dedupe.go:112 component=remote level=error remote_name=81a289 url=http://nginx-proxy-monitor.apps.ocp.com/api/v1/receive  msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 409 Conflict: store locally for endpoint thanos-receiver-public-0.thanos-receiver-public.monitor.svc.cluster.local:10901: conflict"
```

**Anything else we need to know**:

The metrics of the hard tenant can be actually queried, but are stored in the bucket of the soft tenant.

![微信截图_20211224123046](https://user-images.githubusercontent.com/73920302/147316491-8a75d244-a323-41d3-ade3-9764e0b49db2.png)

![微信截图_20211224122959](https://user-images.githubusercontent.com/73920302/147316495-5651ec02-7564-40e8-8f06-34648124d375.png)

And the connection between the receive of hard tenant and soft tenant is well:

```shell
[root@bastion ~]# oc rsh thanos-receiver-public-0 
~ $ nc -vz thanos-receiver-sc-0.thanos-receiver-sc.monitor.svc.cluster.local:10901
thanos-receiver-sc-0.thanos-receiver-sc.monitor.svc.cluster.local:10901 (10.254.7.43:10901) open
```
