### ISSUE TITLE
field tls_config not found in type s3.HTTPConfig

### ISSUE THREAD

**Issue by LukaszWasko** [thanos-io/thanos#5008]
**Thanos, Prometheus and Golang version used**:
thanos-compact:             0.24.0 with minio
go version:       go1.16.12

**Object Storage Provider**:
NetApp S3

**What happened**:
Got error `field tls_config not found in type s3.HTTPConfig` when using in `'--objstore.config-file /etc/thanos-compact/s3.yaml` with:
```
type: S3
config:
  bucket: ..
  endpoint: ..
  region: "us-east-1a"
  access_key: ..
  insecure: false
  signature_version2: false
  secret_key:
  http_config:
    (..)
    idle_conn_timeout: 0s
    tls_config:
      ca_file: "(..)"
  sse_config:
    type: "SSE-S3"
```
     

**What you expected to happen**:
Thanos+minio will read the content of CA file

**Full logs to relevant components**:

```
{"caller":"factory.go:49","level":"info","msg":"loading bucket configuration","date_time":"2021-12-28T12:37:28.678391246Z"}
{"caller":"main.go:132","err":"yaml: unmarshal errors:\n  line 6: field tls_config not found in type s3.HTTPConfig\ncreate S3 client\ngithub.com/thanos-io/thanos/pkg/objstore/client.NewBucket\n\t/app/pkg/objstore/client/factory.go:82\nmain.runCompact\n\t/app/cmd/thanos/compact.go:203\nmain.registerCompact.func1\n\t/app/cmd/thanos/compact.go:92\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\npreparing compact command failed\nmain.main\n\t/app/cmd/thanos/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371","level":"error","date_time":"2021-12-28T12:37:28.678811762Z"}
```

I was using documentation provided on https://thanos.io/tip/thanos/storage.md/#s3

**Environment**:
- OS : CentOS 8.5.2111
- Kernel: 4.18.0-348.2.1.el8_5.x86_64
