### ISSUE TITLE
Query: HTTP Logging - no error log when thanos is OOMkilled

### ISSUE THREAD

**Issue by dwilliams782** [thanos-io/thanos#5115]
**Thanos, Prometheus and Golang version used**
0.24.0

**Object Storage Provider**
GCS

**What happened**
I'm testing out the logging config with `--request.logging-config`:

```
- args:
  - query
  - --query.replica-label=prometheus_replica
  - --store=dns+thanos-sidecar.monitoring.svc:10901
  - --store=thanos-store-gateway.monitoring.svc:10901
  - --log.level=debug
  - |
    --request.logging-config=http:
      options:
        level: DEBUG
        decision:
          log_start: true
          log_end: true
```

I have a query that will intentionally cause Thanos Query to get OOMkilled. I'm trying to generate any ERROR level HTTP logs.

When Query gets OOM killed, I see three **start** logs emitted and only two **end** logs. `/api/v1/query_range` doesn't return an end log. I was expecting to see a 500 log.

![image](https://user-images.githubusercontent.com/42545485/152131275-ffa2050b-4e23-47e7-a142-4e1a6d14ee5b.png)

![image](https://user-images.githubusercontent.com/42545485/152130951-88d195d4-30bf-4d15-90d2-da213305385c.png)

**What you expected to happen**
I expected to see a 5xx error generated.

**Full logs to relevant components**:

<details>Logs
<p>

```
ts=2022-02-02T09:37:51.054653138Z caller=level.go:63 protocol=http http.component=server level=debug http.start_time="2022-02-02 09:37:51.054630861 +0000 UTC m=+45.005753150" http.method="GET /api/v1/query_exemplars?query=container_memory_usage_bytes&start=1636012800&end=1643788800" http.request_id=01FTWWR9EER734C0GT4XYQ5KZH thanos.method_name=exemplars msg="started call"
--
ts=2022-02-02T09:37:51.057473511Z caller=level.go:63 protocol=http http.component=server level=debug http.start_time="2022-02-02 09:37:51.057454578 +0000 UTC m=+45.008576832" http.method="GET /api/v1/query?query=container_memory_usage_bytes&time=1643794671" http.request_id=01FTWWR9EHD1WACJESBVP500KX thanos.method_name=query msg="started call"
--
ts=2022-02-02T09:37:51.058186615Z caller=level.go:63 protocol=http http.component=server level=debug http.start_time="2022-02-02 09:37:51.058168735 +0000 UTC m=+45.009290982" http.method="GET /api/v1/query_range?query=container_memory_usage_bytes&start=1636012800&end=1643788800&step=7200" http.request_id=01FTWWR9EJNPSBWYGV5T3CXFQY thanos.method_name=query_range msg="started call"
--
ts=2022-02-02T09:37:51.116586397Z caller=level.go:63 protocol=http http.component=server http.method="GET /api/v1/query_exemplars?query=container_memory_usage_bytes&start=1636012800&end=1643788800" http.request_id=01FTWWR9EER734C0GT4XYQ5KZH http.status_code=200 http.time_ms=61.943 http.remote_addr=10.225.14.49:54188 thanos.method_name=exemplars level=debug msg="finished call"
--
ts=2022-02-02T09:37:51.382017421Z caller=level.go:63 protocol=http http.component=server http.method="GET /api/v1/query?query=container_memory_usage_bytes&time=1643794671" http.request_id=01FTWWR9EHD1WACJESBVP500KX http.status_code=200 http.time_ms=324.552 http.remote_addr=10.225.14.49:54190 thanos.method_name=query level=debug msg="finished call"

```

</p>
</details>
