### ISSUE TITLE
Thanos does not interpret a label variable at startup and considers it as a string.

### ISSUE THREAD

**Issue by tzarky** [thanos-io/thanos#5149]
Hello,

I am trying to deploy Prometheus in HA with Thanos.

When I try to add the unique label "$(POD_NAME)" to thanos, I have the impression that it interprets it as a string instead of a variable (see my screenshot below)
![Screenshot 2022-02-12 at 15 59 05](https://user-images.githubusercontent.com/76174192/153716410-a856e96e-6caa-4b7c-bc34-7bf51057f499.png)

My configmap seems correct and I have added the reference to the variable in the environment variable of the sidecar.

```yaml
  prometheus.yml: |
    global:
      external_labels:
        cluster: my-cluster
        replica: $(POD_NAME)
```

sidecar configuration

```yaml
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

Is this a known bug or did I miss something?
