### ISSUE TITLE
store: Thanos consumes 40G at startup

### ISSUE THREAD

**Issue by fagossa** [thanos-io/thanos#5367]
Hello,

I'm having some uncontrolled memory consumption with *thanos store*.

## What happened:

At start up, there is a peak of memory of ~40GiB that later decreases over time to ~26GiB. However, depending on the load, it reached back the peak value and even beyond (which means OEMKill).
![Capture d’écran 2022-05-16 à 17 16 56](https://user-images.githubusercontent.com/6917738/168626465-63ff3f3f-83b8-4c8d-b333-d699c8d07110.png)

even when i'm using a *memcached* precisely to avoid this situation.

I currently have more that *145k blocks* in my s3 storage and more than 80 prometheus (+sidecars).

## What I expected:
As per the use of a cache I expected the memory to stay low.

At least it seems the cache is used

![Capture d’écran 2022-05-16 à 17 59 37](https://user-images.githubusercontent.com/6917738/168635075-779e3432-7af2-4e4d-b540-b4434982545a.png)

## current configuration

```
thanos store \
--data-dir="/var/thanos/store" \
--objstore.config-file="/etc/thanos/bucket.yml" \
--http-address="0.0.0.0:10902" \
--grpc-address="0.0.0.0:10901" \
--log.format="json" \
--log.level="info" \
--store.index-header-posting-offsets-in-mem-sampling=50 \
--index-cache.config-file="/etc/thanos/thanos-store-cache-config.yml"
```

this is my cache configuration

```
type: MEMCACHED
config:
  addresses: ["memcached:11211"]
  timeout: 3s
  max_idle_connections: 200
  max_async_concurrency: 20
  max_async_buffer_size: 10000000
  max_item_size: 300MiB
  max_get_multi_concurrency: 5
  max_get_multi_batch_size: 20
  dns_provider_update_interval: 10s
```

## Environment:
* thanos 0.25.1
* prometheus 2.28.1

### 1 - sharding by date using flags

I created several stores for 3 months periods using this pattern
```
thanos store \
...
--max-time=-12w \
--min-time=-24w \
```

but, all stores ended-up consuming the same memory.

### 2 - changing the compact/level 
I basically followed this issue https://github.com/thanos-io/thanos/issues/325

## Anything else

I don't know if this information can be useful but the amt of samples changes greatly depending on my prometheus 

![Capture d’écran 2022-05-16 à 17 53 20](https://user-images.githubusercontent.com/6917738/168633778-6b308f90-38ce-4c38-a896-7e45dc5b0c1d.png)
