### ISSUE TITLE
`--tracing.config` to replace environment variables

### ISSUE THREAD

**Issue by carlosjgp** [thanos-io/thanos#5389]
### Is your proposal related to a problem?

When using OpenTelemetry agents (Deamonset) to ingest traces and decorate them with the node and pod metadata
container envs
```yaml
- name: HOST_IP
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
```
flag
```yaml
    --tracing.config=type: JAEGER
    config:
      service_name: "thanos"
      agent_host: "${HOST_IP}"
      agent_port: 14250
```

### Describe the solution you'd like

Something similar for the `tracing.config` flag
https://github.com/thanos-io/thanos/pull/4327

(Describe your proposed solution here.)

### Describe alternatives you've considered

Use OTEL `Deployment` with a `Service` but I'll lose important metadata

### Additional context

Related with https://github.com/thanos-io/thanos/issues/1972

**Comment by saswatamcode** [comment]
I think we already have env substitution for `--tracing.config` flag as defined [here](https://github.com/thanos-io/thanos/blob/release-0.26/pkg/extkingpin/flags.go#L125). The env substitutions follows [K8s style](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/) though so it would be something like this. :)

```yaml
    --tracing.config=type: JAEGER
    config:
      service_name: "thanos"
      agent_host: "$(HOST_IP)"
      agent_port: 14250
```
