### ISSUE TITLE
Thanos Querier/store gateway is failing to return just 2 months of data

### ISSUE THREAD

**Issue by anoop2503** [thanos-io/thanos#5450]
**Thanos, version used**: v0.23.1

**Object Storage Provider**: S3

**What happened**:  
Deployed only thanos-querier and thanos-store-gateway to use an S3 bucket to display historical data. However, it is failing to return just 2 months of data. 

**What you expected to happen**: Thanos should return data without failure

**How to reproduce it (as minimally and precisely as possible)**:

Deploy thanos-store-gateway to point to S3 bucket. Deploy thanos querier to use only thanos-store-gateway. Try to pull historical data for 2 months.

**Full logs to relevant components**:

Getting following error from thanos querier log:
`level=warn ts=2022-06-27T15:25:49.79866573Z caller=endpointset.go:525 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from xx.xx.xx.xxx:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address= xx.xx.xx.xxx:10901`

Getting following error from Store-Gateway logs:
`level=debug ts=2022-06-27T15:26:32.614591931Z caller=bucket.go:1087 msg="stats query processed" stats="&{blocksQueried:0 postingsTouched:0 postingsTouchedSizeSum:0 postingsToFetch:0 postingsFetched:0 postingsFetchedSizeSum:0 postingsFetchCount:0 postingsFetchDurationSum:0 cachedPostingsCompressions:0 cachedPostingsCompressionErrors:0 cachedPostingsOriginalSizeSum:0 cachedPostingsCompressedSizeSum:0 cachedPostingsCompressionTimeSum:0 cachedPostingsDecompressions:0 cachedPostingsDecompressionErrors:0 cachedPostingsDecompressionTimeSum:0 seriesTouched:0 seriesTouchedSizeSum:0 seriesFetched:0 seriesFetchedSizeSum:0 seriesFetchCount:0 seriesFetchDurationSum:0 chunksTouched:0 chunksTouchedSizeSum:0 chunksFetched:0 chunksFetchedSizeSum:0 chunksFetchCount:0 chunksFetchDurationSum:0 getAllDuration:0 mergedSeriesCount:0 mergedChunksCount:0 mergeDuration:0}" err="rpc error: code = Aborted desc = fetch series for block 01FQEABSWZBJVT8Z0E0F4Q8KY6: expanded matching posting: get postings: read postings range: read range: context canceled"`

**Anything else we need to know**:

Querier deployment configurations:

```
containers:
      - args:
        - query
        - --http-address=0.0.0.0:10902
        - --query.replica-label=replica
        - --query.auto-downsampling
        - --store=dnssrv+thanos-store-gateway.$(NAMESPACE):10901
        - --log.level=debug
        - --query.timeout=5m
        - --store.response-timeout=5m
      resources:
          limits:
            cpu: "2"
            memory: 12Gi
          requests:
            cpu: "1"
            memory: 12Gi
```

Store-Gateway deployment configurations:
```
 containers:
      - args:
        - store
        - --log.level=debug
        - --data-dir=/data
        - --index-cache-size=2GB
        - --chunk-pool-size=20GB
        - --objstore.config-file=/thanos-config/thanos-s3-config.yml
        - --http-address=0.0.0.0:10902
        - --max-time=-24h
        - --min-time=-52w
       resources:
          limits:
            cpu: "12"
            memory: 120Gi
          requests:
            cpu: "12"
            memory: 120Gi
```
**Actual CPU/Memory usage for thanos querier during the failure**: CPU - 0.05%, Memory - 3 %
**Actual CPU/Memory usage for thanos store gateway during the failure**: CPU - 3.36%, Memory - 14.2 %

**Environment**:
- OS (e.g. from /etc/os-release): Deployed the applications as docker containers in kubernetes.
