### ISSUE TITLE
query: with grafana gives inconsistent dashboard with every refresh

### ISSUE THREAD

**Issue by maartengo** [thanos-io/thanos#5501]
**Thanos, Prometheus and Golang version used**:
* Thanos: 11.1.0, deployed through [Bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/thanos), quay.io/thanos/thanos:v0.25.2
* Prometheus: 0.57.0 deployed through [kube-prometheus-stack helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)
* Grafana: v9.0.1, also through kube-prometheus-stack

**Object Storage Provider**:

**What happened**:
When using the Thanos querier as data source in Grafana, the dashboard data becomes inconsistent on every refresh. See gif for example. This doesn't happen if Grafana points directly to the Thanos sidecar. This is without usage of the storage gateway.

It might very well be a configuration issue, but we have no idea what could cause this.

![Animation](https://user-images.githubusercontent.com/46345801/178982571-2a97cb90-45f8-404c-b336-9e27097057f2.gif)

**What you expected to happen**:
Consistent data between refreshes

**How to reproduce it (as minimally and precisely as possible)**:
We haven't tried to reproduce this in a minimal setup, but it does happen on all of our environments (10+) all running the same configuration.
I can supply the complete values.yaml privately if needed, but it boils down to:

```yaml
thanos:
  storegateway:
    enabled: false
  query:
    enabled: true
    replicaLabel:
      - prometheus_replica
    dnsDiscovery:
      sidecarsService: 'prometheus-stack-kube-prom-thanos-discovery'
      sidecarsNamespace: 'prometheus'

kube-prometheus-stack:
  grafana:
    sidecar:
      datasources:
        url: http://prometheus-stack-thanos-query:9090/
        initDatasources: true
      dashboards:
        searchNamespace: ALL
        labelValue: null # Needs to be null in order to load our dashboards
  prometheus:
    replicas: 3
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true
    service:
      sessionAffinity: 'ClientIP'
    prometheusSpec:
      thanos:
        objectStorageConfig:
          key: config-file.yaml
          name: thanos-secret

```

Chart:
```yaml
  - name: kube-prometheus-stack
    version: 36.6.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: thanos
    version: 10.5.5
    repository: https://charts.bitnami.com/bitnami
```

**Full logs to relevant components**:
* Grafana: no logging occurs
* Query: no logging occurs

**Anything else we need to know**:

**Environment**:
K8S on AKS. First time deploying Thanos.
