### ISSUE TITLE
Multiple sidecar have set "prefix", how set store to read all of them?

### ISSUE THREAD

**Issue by X-Mars** [thanos-io/thanos#5519]
### Discussed in https://github.com/thanos-io/thanos/discussions/5517

<div type='discussions-op-text'>

<sup>Originally posted by **X-Mars** July 19, 2022</sup>
### sidecar 1
```
type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
      bucket: "thanos-dev"
      access_key_id: "2222"
      access_key_secret: "2222"
    prefix: "sidecar1"
```
### sidecar 2
```
type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
      bucket: "thanos-dev"
      access_key_id: "2222"
      access_key_secret: "2222"
    prefix: "sidecar2"
```

### store
```
type: ALIYUNOSS
config:
  endpoint: "oss-cn-hangzhou-internal.aliyuncs.com"
  bucket: "thanos-dev"
  access_key_id: "2222"
  access_key_secret: "2222"
prefix: ""
```
Thank you !
</div>
