### ISSUE TITLE
Thanos Compactor Crashing - Download blocks timeout

### ISSUE THREAD

**Issue by crockk** [thanos-io/thanos#5523]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.27.0
Prometheus: 2.25.2
Golang: go1.15.10

<details>Here's my `docker-compose.yml` for good measure:
<p>

```
services:
  sidecar:
    image: thanosio/thanos:v0.27.0
    container_name: thanos-sidecar
    command:
      - "sidecar"
      - "--debug.name=sidecar"
      - "--grpc-address=0.0.0.0:10901"
      - "--http-address=0.0.0.0:10902"
      - "--prometheus.url=http://172.17.0.1:9090"
      - "--tsdb.path=/data/"
      - "--objstore.config-file=/bucket.yml"
      - "--shipper.upload-compacted"
    ports:
      - 10902:10902
    restart: always
    volumes:
      - /data:/data
      - ./azure_bucket_config.yml:/bucket.yml
    networks:
      - thanos

  store:
    image: thanosio/thanos:v0.27.0
    container_name: thanos-store
    restart: always
    command:
      - "store"
      - "--grpc-address=0.0.0.0:10905"
      - "--http-address=0.0.0.0:10906"
      - "--data-dir=/data/store"
      - "--objstore.config-file=/bucket.yml"
    ports:
      - 10906:10906
    volumes:
      - store:/data
      - ./azure_bucket_config.yml:/bucket.yml
    networks:
      - thanos

  query:
    image: thanosio/thanos:v0.27.0
    container_name: thanos-query
    command:
      - "query"
      - "--grpc-address=0.0.0.0:10903"
      - "--http-address=0.0.0.0:10904"
      - "--query.replica-label=prometheus"
      - "--store=thanos-store:10905"
      - "--query.auto-downsampling"
    ports:
      - 10904:10904
    depends_on:
      - sidecar
      - store
    networks:
      - thanos
    restart: always

  compactor:
    image: thanosio/thanos:v0.27.0
    container_name: thanos-compactor
    command:
      - "compact"
      - "--wait"
      - "--data-dir=/tmp/thanos-compact"
      - "--objstore.config-file=/bucket.yml"
      - "--http-address=0.0.0.0:10907"
      - "--retention.resolution-raw=182d"
      - "--retention.resolution-5m=1y"
      - "--retention.resolution-1h=2y"
    ports:
      - 10907:10907
    volumes:
      - compact:/tmp
      - ./azure_bucket_config.yml:/bucket.yml
      - ./fs_backup_config.yml:/backup.yml
    depends_on:
      - sidecar
      - store
    networks:
      - thanos
    restart: always

networks:
  thanos: {}
volumes:
  store: {}
  compact: {}

```
</p>
</details>

**Object Storage Provider**:
Azure Blob Storage
<details>Bucket config
<p>

```
type: AZURE
config:
  storage_account: "xxxx"
  storage_account_key: "xxxx"
  container: "prometheus4"
  endpoint: ""
  max_retries: 0
  msi_resource: ""
  user_assigned_id: ""
  pipeline_config:
    max_tries: 0
    try_timeout: 0s
    retry_delay: 0s
    max_retry_delay: 0s
  reader_config:
    max_retry_requests: 0
  http_config:
    idle_conn_timeout: 0s
    response_header_timeout: 0s
    insecure_skip_verify: false
    tls_handshake_timeout: 0s
    expect_continue_timeout: 0s
    max_idle_conns: 0
    max_idle_conns_per_host: 0
    max_conns_per_host: 0
    tls_config:
      ca_file: ""
      cert_file: ""
      key_file: ""
      server_name: ""
      insecure_skip_verify: false
    disable_compression: false
prefix: "prometheus4"
```

</p>
</details>

**What happened**:
Thanos Compactor is crashing seemingly regularly after running for some period of time, timing out and then later experiences overlaps in the object store, seemingly due to the crash from before.

**What you expected to happen**:
If a download times out, Thanos should probably retry the download rather than shutting down.

**How to reproduce it (as minimally and precisely as possible)**:
Not entirely sure... I just know that it looks like Thanos is trying to download blocks, it times out, then crashes rather than attempting to download the block again.

**Full logs to relevant components**:

<details>Initial Crash and Reboot - 2022-07-19 5:03 UTC
<p>

```
level=info ts=2022-07-19T05:00:57.370656812Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=339.294198ms duration_ms=339 cached=91 returned=91 partial=0
level=info ts=2022-07-19T05:01:57.342172313Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=311.118213ms duration_ms=311 cached=91 returned=91 partial=0
level=info ts=2022-07-19T05:02:57.354952621Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=323.230806ms duration_ms=323 cached=91 returned=91 partial=0
level=warn ts=2022-07-19T05:03:14.1241479Z caller=objstore.go:289 msg="failed to remove file on partial dir download error" file=/tmp/thanos-compact/downsample/01G29KQFEVC2QW98275P3EHWD9 err="remove /tmp/thanos-compact/downsample/01G29KQFEVC2QW98275P3EHWD9: directory not empty"
level=warn ts=2022-07-19T05:03:14.253037996Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="error executing compaction: first pass of downsampling failed: downsampling to 5 min: download block 01G29KQFEVC2QW98275P3EHWD9: get file 01G29KQFEVC2QW98275P3EHWD9/chunks/000132: cannot download blob, address: https://prometheuseast.blob.core.windows.net/prometheus4/prometheus4/01G29KQFEVC2QW98275P3EHWD9/chunks/000132: context deadline exceeded"
level=info ts=2022-07-19T05:03:14.267923621Z caller=http.go:84 service=http/server component=compact msg="internal server is shutting down" err="error executing compaction: first pass of downsampling failed: downsampling to 5 min: download block 01G29KQFEVC2QW98275P3EHWD9: get file 01G29KQFEVC2QW98275P3EHWD9/chunks/000132: cannot download blob, address: https://prometheuseast.blob.core.windows.net/prometheus4/prometheus4/01G29KQFEVC2QW98275P3EHWD9/chunks/000132: context deadline exceeded"
level=info ts=2022-07-19T05:03:14.278933395Z caller=http.go:103 service=http/server component=compact msg="internal server is shutdown gracefully" err="error executing compaction: first pass of downsampling failed: downsampling to 5 min: download block 01G29KQFEVC2QW98275P3EHWD9: get file 01G29KQFEVC2QW98275P3EHWD9/chunks/000132: cannot download blob, address: https://prometheuseast.blob.core.windows.net/prometheus4/prometheus4/01G29KQFEVC2QW98275P3EHWD9/chunks/000132: context deadline exceeded"
level=info ts=2022-07-19T05:03:14.279031558Z caller=intrumentation.go:81 msg="changing probe status" status=not-healthy reason="error executing compaction: first pass of downsampling failed: downsampling to 5 min: download block 01G29KQFEVC2QW98275P3EHWD9: get file 01G29KQFEVC2QW98275P3EHWD9/chunks/000132: cannot download blob, address: https://prometheuseast.blob.core.windows.net/prometheus4/prometheus4/01G29KQFEVC2QW98275P3EHWD9/chunks/000132: context deadline exceeded"
level=error ts=2022-07-19T05:03:14.321547079Z caller=main.go:158 err="downsampling to 5 min: download block 01G29KQFEVC2QW98275P3EHWD9: get file 01G29KQFEVC2QW98275P3EHWD9/chunks/000132: cannot download blob, address: https://prometheuseast.blob.core.windows.net/prometheus4/prometheus4/01G29KQFEVC2QW98275P3EHWD9/chunks/000132: context deadline exceeded\nfirst pass of downsampling failed\nmain.runCompact.func7\n\t/app/cmd/thanos/compact.go:440\nmain.runCompact.func8.1\n\t/app/cmd/thanos/compact.go:476\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:75\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:475\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror executing compaction\nmain.runCompact.func8.1\n\t/app/cmd/thanos/compact.go:503\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:75\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:475\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\ncompact command failed\nmain.main\n\t/app/cmd/thanos/main.go:158\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
level=info ts=2022-07-19T05:03:28.2214006Z caller=factory.go:50 msg="loading bucket configuration"
level=info ts=2022-07-19T05:03:28.61335506Z caller=compact.go:387 msg="retention policy of raw samples is enabled" duration=4368h0m0s
level=info ts=2022-07-19T05:03:28.613473154Z caller=compact.go:394 msg="retention policy of 5 min aggregated samples is enabled" duration=8760h0m0s
level=info ts=2022-07-19T05:03:28.61350257Z caller=compact.go:397 msg="retention policy of 1 hour aggregated samples is enabled" duration=17520h0m0s
level=info ts=2022-07-19T05:03:28.615536041Z caller=compact.go:615 msg="starting compact node"
level=info ts=2022-07-19T05:03:28.615580162Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-07-19T05:03:28.616391532Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-07-19T05:03:28.616423401Z caller=http.go:73 service=http/server component=compact msg="listening for requests and metrics" address=0.0.0.0:10907
level=info ts=2022-07-19T05:03:28.6176218Z caller=tls_config.go:195 service=http/server component=compact msg="TLS is disabled." http2=false
level=info ts=2022-07-19T05:03:28.625083387Z caller=compact.go:1268 msg="start sync of metas"
level=info ts=2022-07-19T05:03:30.30407491Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1.688172615s duration_ms=1688 cached=92 returned=92 partial=0
level=info ts=2022-07-19T05:03:31.83913099Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1.534884123s duration_ms=1534 cached=92 returned=92 partial=0
level=info ts=2022-07-19T05:03:32.116512785Z caller=fetcher.go:470 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=3.500685699s duration_ms=3500 cached=92 returned=47 partial=0

```
</p>
</details>

<details>Compaction Starts - Overlapped Blocks Halting Compaction - 2022-07-19 13:30 UTC
<p>

```
level=info ts=2022-07-19T13:30:39.589842814Z caller=compact.go:1273 msg="start of GC"
level=info ts=2022-07-19T13:30:39.590738529Z caller=compact.go:1296 msg="start of compactions"
level=error ts=2022-07-19T13:30:39.66560371Z caller=compact.go:486 msg="critical error detected; halting" err="compaction: group 0@8403025132557603590: pre compaction overlap check: overlaps found while gathering blocks. [mint: 1658116800000, maxt: 1658124000000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQQ7FFAVMBYHD7EEBDYH79, mint: 1658116800000, maxt: 1658124000000, range: 2h0m0s>\n[mint: 1658131200000, maxt: 1658138400000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQRJ4DP1QXEX6MMVSJ88X3, mint: 1658131200000, maxt: 1658138400000, range: 2h0m0s>\n[mint: 1658044800000, maxt: 1658052000000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQHG3JRPNQXFYK643Y1F0Q, mint: 1658044800000, maxt: 1658052000000, range: 2h0m0s>\n[mint: 1658073600000, maxt: 1658080800000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQM4XZJH5BYH118CEP2AWP, mint: 1658073600000, maxt: 1658080800000, range: 2h0m0s>\n[mint: 1658066400000, maxt: 1658073600000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQKMDTW9C7AFMB2FM67E46, mint: 1658066400000, maxt: 1658073600000, range: 2h0m0s>\n[mint: 1658080800000, maxt: 1658088000000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQMNE9H6QNZJA4XAESFEWQ, mint: 1658080800000, maxt: 1658088000000, range: 2h0m0s>\n[mint: 1658088000000, maxt: 1658095200000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQN5X1FYNB5DZ6NKPRYYF3, mint: 1658088000000, maxt: 1658095200000, range: 2h0m0s>\n[mint: 1658095200000, maxt: 1658102400000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQNNVR4GYETFJNXBHHN7RA, mint: 1658095200000, maxt: 1658102400000, range: 2h0m0s>\n[mint: 1658102400000, maxt: 1658109600000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQP5FNZE93V91HE19BE9NS, mint: 1658102400000, maxt: 1658109600000, range: 2h0m0s>\n[mint: 1658109600000, maxt: 1658116800000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQPPPZCWDGRW5WQHTQ7CRQ, mint: 1658109600000, maxt: 1658116800000, range: 2h0m0s>\n[mint: 1658052000000, maxt: 1658059200000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQJD3VM384NDV7G0KF0TGM, mint: 1658052000000, maxt: 1658059200000, range: 2h0m0s>\n[mint: 1658059200000, maxt: 1658066400000, range: 2h0m0s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQK1PVP7PZWZDD34SE29FK, mint: 1658059200000, maxt: 1658066400000, range: 2h0m0s>\n[mint: 1658124000002, maxt: 1658131200000, range: 1h59m59s, blocks: 2]: <ulid: 01G8ADQB9EACGF27TJX4426ZZD, mint: 1658016000000, maxt: 1658188800000, range: 48h0m0s>, <ulid: 01G8AQQPNV65T33D285NXJCWJE, mint: 1658124000002, maxt: 1658131200000, range: 1h59m59s>"
```
</p>
</details>

**Anything else we need to know**:
This isn't the first time I've experienced this, and I know I can solve it by going in and manually removing the overlapped blocks. I have done that twice before, but each time this crash occurs and then overlapped blocks seem to arise afterwards.
