### ISSUE TITLE
Thanos receiver keeps growing

### ISSUE THREAD

**Issue by Ramshield** [thanos-io/thanos#5601]
**Thanos, Prometheus and Golang version used**:
Thanos version 0.27.0
Prometheus version 2.35.0

**Object Storage Provider**:
minio s3

**What happened**:
Currently we run thanos receiver, query compactor and storagegateway.
We have 6 prometheus with a remote rule writing to thanos.
But our thanos receiver keeps growing. In a week the persistent volume has grown by 80Gb.
We see the same growth in our s3 minio backend.

**What you expected to happen**:
Thanos receiver not to be this big.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure, but we installed Thanos via helm, version 10.5.5:
```
thanos: 
  existingObjstoreSecret: thanos-objstore-secret
 
  global:
    imageRegistry: ourharbor

  image:
    tag: v0.27.0
    repository: monitoring/thanos 

  query:
    enabled: true
    ingress:
      enabled: false
      hostname: querier.example.com
      ingressClassName: nginx 

  queryFrontend:
    enabled: true
    ingress:
      enabled: true
      hostname: thanos-query-frontend.example.com
      ingressClassName: nginx 

  bucketweb:
    enabled: false
    ingress:
      enabled: false
      hostname: thanos-bucketweb.example.com
      ingressClassName: nginx 

  storegateway:
    enabled: true
    ingress:
      enabled: false
      hostname: thanos-store.example.com
      ingressClassName: nginx 

  receive:
    enabled: true
    ingress:
      enabled: true
      hostname: thanos-receive.example.com
      ingressClassName: nginx

    persistence:
      enabled: true
      size: 150Gi

  compactor:
    enabled: true
    ingress:
      enabled: true
      hostname: thanos-compactor.example.com
      ingressClassName: nginx
    persistence:
      enabled: true
      size: 100Gi
```

**Full logs to relevant components**:
no errors are logged in thanos receiver.

**Anything else we need to know**:
We run this on a Kubernetes Rancher environment.
