### ISSUE TITLE
Thanos Store | Thanos Query is not able to connect to Thanos Store Gateway

### ISSUE THREAD

**Issue by sathishsoundharajan** [thanos-io/thanos#5669]
**Thanos, Prometheus and Golang version used**:
0.27 ( latest versions )

**Object Storage Provider**: FileSystem

**What happened**: Query is not able to connect to Thanos Store Gateway

**What you expected to happen**: Thanos Query should be able to connect to store and retrive results

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-thanos"
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
  labels:
    app: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.22.0
        args:
        - query
        - --log.level=debug
        - --query.replica-label=replica
        - --store=thanos-store-gateway:10901
        - --query.timeout=5m
        - --store.unhealthy-timeout=5m
        - --store.response-timeout=5m
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        livenessProbe:
          httpGet:
            port: http
            path: /-/healthy
        readinessProbe:
          httpGet:
            port: http
            path: /-/ready

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier
  namespace: monitoring
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 10902
      name: http
  selector:
    app: thanos-querier
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  namespace: monitoring
  labels:
    app: thanos-store-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-gateway
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.22.0
          args:
            - "store"
            - "--log.level=debug"
            - "--data-dir=/data"
            - "--objstore.config={type: FILESYSTEM, config: {directory: /etc/thanos-data/}}"
            - "--index-cache-size=500MB"
            - "--chunk-pool-size=500MB"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              port: 10902
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
  volumeClaimTemplates:
    - metadata:
        name: thanos-storage
        namespace: monitoring
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store-gateway
  name: thanos-store-gateway
  namespace: monitoring
spec:
  ports:
    - port: 9099
      protocol: TCP
      targetPort: 10902
      name: http
    - port: 9088
      protocol: TCP
      targetPort: 10901
      name: grpc
  selector:
    app: thanos-store-gateway
  type: NodePort

```

**Full logs to relevant components**:

```
kubectl logs -f service/thanos-querier -n monitoring
level=debug ts=2022-09-03T11:25:07.96305069Z caller=main.go:64 msg="maxprocs: Leaving GOMAXPROCS=[4]: CPU quota undefined"
level=debug ts=2022-09-03T11:25:07.966506567Z caller=engine.go:292 msg="Lookback delta is zero, setting to default value" value=5m0s
level=info ts=2022-09-03T11:25:07.969282048Z caller=options.go:24 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-09-03T11:25:07.97007625Z caller=query.go:640 msg="starting query node"
level=debug ts=2022-09-03T11:25:07.971096586Z caller=storeset.go:409 component=storeset msg="starting updating storeAPIs" cachedStores=0
level=info ts=2022-09-03T11:25:07.973059742Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2022-09-03T11:25:07.973519366Z caller=http.go:63 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2022-09-03T11:25:07.973754985Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2022-09-03T11:25:07.974050823Z caller=grpc.go:123 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2022-09-03T11:25:07.974049119Z caller=tls_config.go:191 service=http/server component=query msg="TLS is disabled." http2=false
level=warn ts=2022-09-03T11:25:12.973591403Z caller=storeset.go:570 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-store-gateway:10902: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-gateway:10902
level=debug ts=2022-09-03T11:25:12.974022853Z caller=storeset.go:412 component=storeset msg="checked requested storeAPIs" activeStores=0 cachedStores=0
level=debug ts=2022-09-03T11:25:12.97416176Z caller=storeset.go:409 component=storeset msg="starting updating storeAPIs" cachedStores=0
level=warn ts=2022-09-03T11:25:17.975935904Z caller=storeset.go:570 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-store-gateway:10902: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-gateway:10902
level=debug ts=2022-09-03T11:25:17.976077833Z caller=storeset.go:412 component=storeset msg="checked requested storeAPIs" activeStores=0 cachedStores=0
level=debug ts=2022-09-03T11:25:17.976273957Z caller=storeset.go:409 component=storeset msg="starting updating storeAPIs" cachedStores=0
level=warn ts=2022-09-03T11:25:22.977204848Z caller=storeset.go:570 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-store-gateway:10902: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-gateway:10902
level=debug ts=2022-09-03T11:25:22.977436488Z caller=storeset.go:412 component=storeset msg="checked requested storeAPIs" activeStores=0 cachedStores=0
level=debug ts=2022-09-03T11:25:22.977487368Z caller=storeset.go:409 component=storeset msg="starting updating storeAPIs" cachedStores=0
level=warn ts=2022-09-03T11:25:27.978654135Z caller=storeset.go:570 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from thanos-store-gateway:10902: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-gateway:10902
level=debug ts=2022-09-03T11:25:27.978817348Z caller=storeset.go:412 component=storeset msg="checked requested storeAPIs" activeStores=0 cachedStores=0
level=debug ts=2022-09-03T11:25:27.97901269Z caller=storeset.go:409 component=storeset msg="starting updating storeAPIs" cachedStores=0
```

**Anything else we need to know**:
