### ISSUE TITLE
[General] Improve gRPCs Logging

### ISSUE THREAD

**Issue by Moep90** [thanos-io/thanos#5671]
### Problem

I was unable to establish a connection to my remote endpoints. Which seams to relate to a TLS problem.

3 of 4 endpoints are connected because I provided all the SANs etc below.

In my case its a querier to querier connection through ingress-nginx.

```yaml
[...]
      containers:
      - args:
        - query
        - --log.level=debug
        - --log.format=json
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --query.replica-label=replica
        - --endpoint=thanos-storegateway.monitoring:10901
        - --endpoint=kube-prometheus-stack-thanos-discovery.monitoring:10901
        - --endpoint=thanos.test.example.com:443
        - --endpoint=thanos-example.com:443
        - --grpc-server-tls-cert=/certs/server/tls.crt
        - --grpc-server-tls-key=/certs/server/tls.key
        - --grpc-server-tls-client-ca=/certs/server/ca.crt
        - --grpc-client-tls-secure
        - --grpc-client-tls-cert=/certs/client/tls.crt
        - --grpc-client-tls-key=/certs/client/tls.key
        - --grpc-client-tls-ca=/certs/client/ca.crt
[...]
```

SANs in certificate on both sides:
```
DNS Name: *.monitoring 
DNS Name: *.monitoring.svc.apps.example.com 
DNS Name: kube-prometheus-stack.monitoring.svc.cluster.local 
DNS Name: thanos.example.com 
DNS Name: thanos-query.monitoring.svc.apps.example.com 
DNS Name: thanos-sidecar-0.monitoring.svc.cluster.local 
DNS Name: thanos-storegateway-0.monitoring.svc.apps.example.com 
DNS Name: thanos-storegateway.monitoring.svc.apps.example.com 
DNS Name: thanos.test.example.com
```

### Describe the solution you'd like

The only solution I was able to find was to add the `--grpc-client-tls-skip-verify` to establish a successful connection.
As I want to provide only the certificates I have to, I'd like to get any clue from the log whats missing on my side.

### Describe alternatives you've considered

1. Providing every SAN and CN I could imagine and iterate slowly till I found the proper setup.
2. I can also imagine a deeper understanding of gRPCs on my side.
3. s well as a better description what to think of when adding more and more observee clusters.

### Additional context
Currently I only have found both of these proposals:
[Automated, per-endpoint mTLS](https://thanos.io/tip/proposals-accepted/202106-automated-per-endpoint-mtls.md/#automated-per-endpoint-mtls)
[Configuring Thanos Secure TLS Cross-Cluster Communication](https://thanos.io/tip/operating/cross-cluster-tls-communication.md/#proxy-based-communication-using-envoy)
