### ISSUE TITLE
Problem with Thanos query grpc endpoint behind AWS ALB 

### ISSUE THREAD

**Issue by sirjobzy** [thanos-io/thanos#5704]
**Thanos, Prometheus and Golang version used**:
Prometheus version: v2.34.0
Thanos docker image version: 0.27.0-scratch-r6

**What happened**:
I have currently deployed the bitnami thanos helm chart from [here](https://artifacthub.io/packages/helm/bitnami/thanos), 
I have exposed the query grpc endpoint via the AWS ALB ingress and I have an application load balancer and target group created and healthy. I have also created a Route53 record for the ALB endpoint and attached a certificate to the load Balancer. When I try to add this thanos query as a store to another thanos query via the load balancer created, I get the following errors bellow: 

```
thanos query --http-address "0.0.0.0:9090" --store "dns+query.test.cloud:443" --log.level=debug
level=info ts=2022-09-19T15:39:11.118205Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-09-19T15:39:11.118588Z caller=query.go:724 msg="starting query node"
level=info ts=2022-09-19T15:39:11.118698Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-09-19T15:39:11.118837Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-09-19T15:39:11.118884Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:9090
level=info ts=2022-09-19T15:39:11.118983Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2022-09-19T15:39:11.119048Z caller=tls_config.go:195 service=http/server component=query msg="TLS is disabled." http2=false
level=warn ts=2022-09-19T15:39:21.120901Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 54.211.92.124:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=54.211.92.124:443
level=warn ts=2022-09-19T15:39:21.120854Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 52.72.172.59:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=52.72.172.59:443
level=warn ts=2022-09-19T15:39:21.120854Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 35.168.249.84:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=35.168.249.84:443
level=warn ts=2022-09-19T15:39:26.122005Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 35.168.249.84:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=35.168.249.84:443
level=warn ts=2022-09-19T15:39:26.128084Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 52.72.172.59:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=52.72.172.59:443
level=warn ts=2022-09-19T15:39:26.128783Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 54.211.92.124:443: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=54.211.92.124:443
```

And when I test the endpoint via grpcurl I get the following below:

```
grpcurl --vv query.test.cloud:443 list
grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection
thanos.Exemplars
thanos.Metadata
thanos.Query
thanos.Rules
thanos.Store
thanos.Targets
thanos.info.Info
```

**What you expected to happen**:
Thanos query grpc endpoint behind an AWS ALB is able to server as a store to another thanos querier

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy this [chart](https://artifacthub.io/packages/helm/bitnami/thanos)
- Override with the values below:
```
query:
      ingress:
        grpc:
          enabled: true
          hostname: query.test.cloud
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/load-balancer-name: query
            alb.ingress.kubernetes.io/backend-protocol-version: GRPC
            alb.ingress.kubernetes.io/healthcheck-path: /grpc.health.v1.Health/Check
            alb.ingress.kubernetes.io/group.name: query
            external-dns.alpha.kubernetes.io/hostname: query.test.cloud
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:446******67:certificate/447a9ec8-845b-4faf-a4ab-f33efc66e838
            alb.ingress.kubernetes.io/security-groups: sg-05b42e0c22b938a38
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/success-codes: "0"
            alb.ingress.kubernetes.io/target-type: instance
            alb.ingress.kubernetes.io/target-group-attributes: load_balancing.algorithm.type=round_robin
            alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=false
      serviceGrpc:
        type: NodePort
```

**Full logs to relevant components**:
Logs are posted above

**Anything else we need to know**:
When I access the service directly via the NodePort, I am able to retrieve metrics, but I am unable to do it via the AWS ALB, am I missing a configuration?

**Comment by hanjm** [comment]
check this ALB loopback issue. https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#loopback-timeout

**Comment by sirjobzy** [comment]
> 

I am not using an NLB, so there is no option to `Disable client IP preservation`.

**Comment by sirjobzy** [comment]
> check this ALB loopback issue. https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#loopback-timeout

I am not using an NLB, so there is no option to Disable client IP preservation.

**Comment by hanjm** [comment]
> > check this ALB loopback issue. https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#loopback-timeout
> 
> 
> 
> I am not using an NLB, so there is no option to `Disable client IP preservation`.
> 
> 

aws alb is L7 proxy only for http. not support grpc, please use nlb.

**Comment by SoulKyu** [comment]
@hanjm, ALB is supporting GRPC and i have a support close to @sirjobzy which work well : 
https://aws.amazon.com/fr/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/

**Comment by envyj020** [comment]
@hanjm - any feedback around this issue, I'm experiencing also the same error message aggregating other queries exposed behind an ALB with GRPC support.

**Comment by dschaaff** [comment]
Here is my working ingress for query GRPC

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/group.name: internal-shared
    alb.ingress.kubernetes.io/healthcheck-path: /grpc.health.v1.Health/Check
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 10901}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "10901"
    alb.ingress.kubernetes.io/success-codes: "0"
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10,load_balancing.algorithm.type=least_outstanding_requests
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: v0.36.1
    kustomize.toolkit.fluxcd.io/name: thanos
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: thanos-query
  namespace: monitoring
spec:
  ingressClassName: aws
  rules:
  - host: thanos-query-internal.example.com
    http:
      paths:
      - backend:
          service:
            name: thanos-query
            port:
              number: 10901
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - thanos-query-internal.example.com
    secretName: thanos-q-tls
status:
```
