### ISSUE TITLE
HTTP status 409 Conflict Prometheus to Thanos Receiver Metrics

### ISSUE THREAD

**Issue by amit-patil** [thanos-io/thanos#5732]
Hello All,

I have built an integration between Prometheus and Thanos Receiver. This is through the Open Telemetry Collector. Below is the part of ConfigMap in Open Telemetry Collector.

otel-collector-config.yaml: |-
receivers:
prometheus:
config:
scrape_configs:
- job_name: "otel-collector-monitoring-1"
scrape_interval: 5s
honor_labels: true
metrics_path: '/federate'
params:
'match[]':
- '{job=~".+"}'
static_configs:
- targets:
- 'prometheus-k8s:9090'
exporters:
prometheus:
endpoint: "0.0.0.0:8889"
metric_expiration: 180m
prometheusremotewrite:
endpoint: http://host.minikube.internal:32200/api/v1/receive

I see the metrics correctly landing in Thanos-Receiver. But Open Telemetry Collector keeps throwing continuously this error:
What could be the reason for same? and also the fix?

2022-09-27T09:42:23.200Z error exporterhelper/queued_retry.go:183 Exporting failed. The error is not retryable. Dropping data. {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: remote write returned HTTP status 409 Conflict; err = %!w(): store locally for endpoint thanos-receive-default-0.thanos-receive-default.thanos.svc.cluster.local:10901: conflict\n", "dropped_items": 91}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry.go:183
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/metrics.go:132
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry_inmemory.go:119
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69

**Comment by lpegoraro** [comment]
Hi, I am experiencing the same situation here, but just when traffic is high. 
Did it ever get resolved or any clues of some configuration that can fix that?

**Comment by matej-g** [comment]
Hey folks,
Have you tried exporting to Prometheus as well? Could you post your full collector configurations?

I vaguely remember there are some related issues on the exporter in OTEL repo, this could be potentially bug where the data is not being exported correctly or could be also misconfiguration (especially in case you have multiple collector instances).

Related issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11438

**Comment by lpegoraro** [comment]
sure, 
```
---
receivers:
  kafka:
    brokers:
    - kafka:9092
    topic: otlp_metrics-sink-id-222
    protocol_version: 2.0.0
extensions:
  pprof:
    endpoint: 0.0.0.0:1888
  basicauth/exporter:
    client_auth:
      username: <<user>
      password: <<pass>
exporters:
  prometheusremotewrite:
    endpoint: <<endpoint>>
    auth:
      authenticator: basicauth/exporter
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 50
service:
  extensions:
  - pprof
  - basicauth/exporter
  pipelines:
    metrics:
      receivers:
      - kafka
      exporters:
      - prometheusremotewrite
```

This is a new scenario for us, we didn't have any issues running through a Mimir. but we faced this in thanos.
The load is a bit higher than from the mimir scenario as well.

Thanks @matej-g

**Comment by matej-g** [comment]
Hey @lpegoraro,
Thanks for providing that extra info.

What is your receiver setup? Are you using replication? Do you see all your data as expected or are some data points missing? (Feel free to post your receiver config as well).

It could be that in such case the 409 is benign. It can signal that your receiver instances already have this data, and so it refuses to write it. This could happen in a scenario with high load and replication.

**Comment by kimpetertanui** [comment]
am also facing the same issue

**Comment by fpetkovski** [comment]
This is generally not a problem, it often happens when agents retry sending samples. Unless data is missing, the error can be ignored.

**Comment by kimpetertanui** [comment]
how can add an option to ignore?

**Comment by Ygshvr** [comment]
I was also facing the same issue when ingesting metrics using OTel collector `prometheusremotewrite` exporter. The culprit seems to be the `target_info` metrics which are enabled by default. Sometime these target info metrics have some labels without any value (mostly `net_host_port`) which causes `409 conflict` error on the thanos side. 
The issue got fixed when I disabled the `target_info` metrics from OTel side.

```yaml
exporters:
  prometheusremotewrite:
    target_info:
      enabled: false
```
