### ISSUE TITLE
S3 storage Issue | config not initializing 

### ISSUE THREAD

**Issue by Ryu-code** [thanos-io/thanos#5786]
#### OS Details
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
#### comnand to initialize
```bash
kubectl apply -f manifests/
```
#### Used Configuration
```yaml
type: s3
config:
  bucket: thanos
  endpoint: bucket-name.s3.region-code.amazonaws.com
  aws_sdk_auth: true
```
#### eks serviceaccount
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arnxxxx"
  creationTimestamp: "2022-10-13T06:53:03Z"
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/managed-by: eksctl
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/version: v0.24.0
  name: thanos-store
  namespace: monitoring
```
#### I am getting below error
level=info ts=2022-10-13T07:07:03.445696869Z caller=factory.go:49 msg="loading bucket configuration"
level=error ts=2022-10-13T07:07:03.445945139Z caller=main.go:132 err="yaml: unmarshal errors:
  line 1: field aws_sdk_auth not found in type s3.Config
create s3 client
github.com/thanos-io/thanos/pkg/objstore/client.NewBucket
	/home/circleci/project/pkg/objstore/client/factory.go:82
main.runStore
	/home/circleci/project/cmd/thanos/store.go:250
main.registerStore.func1
	/home/circleci/project/cmd/thanos/store.go:195
main.main
	/home/circleci/project/cmd/thanos/main.go:130
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
create bucket client
main.runStore
	/home/circleci/project/cmd/thanos/store.go:252
main.registerStore.func1
	/home/circleci/project/cmd/thanos/store.go:195
main.main
	/home/circleci/project/cmd/thanos/main.go:130
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
preparing store command failed
main.main
	/home/circleci/project/cmd/thanos/main.go:132
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371"
