### ISSUE TITLE
Objstore: Automate `objstore` dependency update

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#5915]
We are seeing often issues originating with different object storage implementations that can be resolved by simple `objstore` update. One example for all: https://github.com/thanos-io/thanos/issues/5904.

Although the `objstore` is now a separate repository, once changes are made there, we should have an automated way of updating the dependency version, to avoid gaps in version and resolve issues related to object storage updated preemptively.

We could have a simple periodic job checking for changes in `objstore` that would automatically open a PR with the update. Using dependabot should actually fit squarely for this use case. Unless there are API changes, most of the updates should be a matter of bumping the version and ensuring tests succeed.

Similarly, we should consider other (internal) packages where want to keep close with the upstream, such as the https://github.com/thanos-community/promql-engine

**Comment by RagibAjmal** [comment]
Hi @matej-g 

Can I work on this

**Comment by matej-g** [comment]
Hi @RagibAjmal, sorry this fell through the cracks for me! It would be awesome if you still wanted to pick this up 🙇. Feel free to work on this.

**Comment by johurul000** [comment]
@matej-g will adding a new package ecosystem in the dependabot.yaml work?
https://github.com/thanos-io/thanos/blob/main/.github/dependabot.yml

**Comment by johurul000** [comment]
@matej-g i would like to work on this

**Comment by matej-g** [comment]
Please go ahead @johurul000!

**Comment by matej-g** [comment]
@johurul000  yes, but it's not working currently, I think we should:
1) Double check this configuration and why it's not being picked up by Dependabot
2) It would be nice if for `objstore` and `promql-engine` we could add daily interval to check, since we probably want to stay as close to latest version for those two as possible

**Comment by johurul000** [comment]
@matej-g  we can ignore the `objstore` and `promql-engine` using `ignore ` tag in the existing ecosystem and then create a separate package ecosystem for them with `allow` tag and `daily` interval.
below is the example code: 
```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    vendor: false
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    ignore:
      - dependency-name: "objstore"
      - dependency-name: "promql-engine"


  - package-ecosystem: "gomod"
    directory: "/"
    vendor: false
    schedule:
      interval: "daily"
    labels: ["dependencies"]
    allow:
      - dependency-name: "objstore"
      - dependency-name: "promql-engine"
```
