### ISSUE TITLE
Unable to drop all metrics with a prefix with some exceptions

### ISSUE THREAD

**Issue by SanthoshiMekala** [thanos-io/thanos#6029]
Hi Team,

We have some expensive metrics that are unnecessarily being scraped and stored in Prometheus. Those are some technology internal default metrics. Any help here is really appreciated!
**Scenario**:
We integrated Kafka. We have kafka_admin.* metrics being scraped by default. We are not using all the metrics except two. Those are kafka_admin_client_admin_client_metrics_incoming_byte_total and kafka_admin_client_admin_client_metrics_outgoing_byte_total. We want to drop all the metrics which start with kafka_admin.* but need to keep the above mentioned two metrics. I tried mutliple regex for the same but prometheus does not support negative lookahead feature. And I tried the below config in metric_relabel_configs. But it is dropping all other metrics also (That does not start with kafka_admin.*).
- source_labels: [ __name__ ]
          regex: 'kafka_admin_client_admin_client_metrics_incoming_byte_total'
          action: keep
        - source_labels: [ __name__ ]
          regex: 'kafka_admin_client_admin_client_metrics_outgoing_byte_total'
          action: keep
        - source_labels: [ __name__ ]
          regex: 'kafka_admin_.*'
          action: drop

**Requirement**:  I need to drop all the metrics only those are starting with "kafka_admin_.*" except two metrics kafka_admin_client_admin_client_metrics_incoming_byte_total and kafka_admin_client_admin_client_metrics_outgoing_byte_total

Thank you!

**Comment by hanjm** [comment]
use multi relabel step with __tmp label to solve it.
> Labels starting with __ will be removed from the label set after target relabeling is completed.

try it in relabel playground. https://relabeler.promlabs.com/
```yaml
# other keep
- source_labels: [ __name__ ]
  regex: '.*'
  target_label: __tmp
  action: replace
  replacement: 1
# drop kafka_admin_.*
- source_labels: [ __name__ ]
  regex: 'kafka_admin_.*'
  target_label: __tmp
  action: replace
  replacement: 0
# except kafka_admin_client_admin_client_metrics_incoming_byte_total
- source_labels: [ __name__ ]
  regex: 'kafka_admin_client_admin_client_metrics_incoming_byte_total'
  target_label: __tmp
  action: replace
  replacement: 1
# except kafka_admin_client_admin_client_metrics_incoming_byte_total
- source_labels: [ __name__ ]
  regex: 'kafka_admin_client_admin_client_metrics_outgoing_byte_total'
  target_label: __tmp
  action: replace
  replacement: 1
- source_labels: [ __tmp ]
  regex: '^1$'
  action: keep
```
