### ISSUE TITLE
Receive component got "AlreadyExists desc = store" error.

### ISSUE THREAD

**Issue by JayChanggithub** [thanos-io/thanos#6036]
Hi Thanos developers. 

I saw the issue https://github.com/thanos-io/thanos/issues/5407 regarding "AlreadyExists desc = store" error. I'd like to follow up whether this issue resolved. If so how to i updated to fix. Because i got the same issue today. The below is my configuration of receive component. Thanos image version is "v0.25.0". 

```yaml
    spec:
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config-file=/etc/thanos/objectstorage.yaml
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=12h
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --receive.hashrings-file=/etc/thanos/thanos-receive-hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.thanos.svc.cluster.local:10901
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: thanosio/thanos:v0.25.0
```
