### ISSUE TITLE
Thanos store gateway crashed when setup redis client-cache

### ISSUE THREAD

**Issue by tarrantro** [thanos-io/thanos#6173]
**Thanos, Prometheus and Golang version used**:
0.30.2

**Object Storage Provider**:
S3

**What happened**:
Store gateway crashed while setup `cache_size` in redis index cache.

**What you expected to happen**:
N/A

**How to reproduce it (as minimally and precisely as possible)**:

config:
```
type: REDIS
config:
  addr: "clustercfg.jina-monitor-redis.xtujrn.memorydb.us-east-1.amazonaws.com:6379"
  username: "default"
  password: "on ~* &* +@all"
  db: 0
  pool_size: 100
  min_idle_conns: 10
  cache_size: 40960
  idle_timeout: 5m0s
```

**Full logs to relevant components**:

```
level=error ts=2023-03-01T08:09:35.594329738Z caller=main.go:135 err="units: unknown unit  in 40960\ncreate REDIS index cache\ngithub.com/thanos-io/thanos/pkg/store/cache.NewIndexCache\n\t/app/pkg/store/cache/factory.go:66\nmain.runStore\n\t/app/cmd/thanos/store.go:304\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:210\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\ncreate index cache\nmain.runStore\n\t/app/cmd/thanos/store.go:312\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:210\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\npreparing store command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"
```

**Anything else we need to know**:
