### ISSUE TITLE
Storegateway seems unable to connect to Azure Cache for Redis after upgrading

### ISSUE THREAD

**Issue by konglingning** [thanos-io/thanos#6227]
**Thanos, Prometheus and Golang version used**:  
thanos application version: 0.30.2
bitnami chart version: 12.3.0 (https://artifacthub.io/packages/helm/bitnami/thanos/12.3.0)

**Object Storage Provider**: Azure Storage Account

**What happened**: 
After upgrading from 0.27.0 to 0.30.2, we found that storegateway is unable to connect Azure Cache for Redis anymore.
Here's our storegateway statefulset configurations:
```
   spec:
      containers:
      - args:
        - store
        - --log.level=info
        - --log.format=logfmt
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --data-dir=/data
        - --objstore.config-file=/conf/objstore.yml
        - --sync-block-duration=10m
        - --chunk-pool-size=10GB
        - |
          --selector.relabel-config=
            - action: hashmod
              source_labels: ["__block_id"]
              target_label: shard
              modulus: 3
            - action: keep
              source_labels: ["shard"]
              regex: 0
        - --index-cache.config-file=/index-cache.yml
        resources:
          limits:
            cpu: "10"
            memory: 60Gi
        sharded:
          enabled: true
          timePartitioning:
            - min: ""
              max: -8w
            - min: -8w
              max: -4w
            - min: -4w
              max: ""
        volumeMounts:
        - mountPath: /conf
          name: objstore-config
        - mountPath: /data
          name: data
        - mountPath: /index-cache.yml
          name: indexcacheconfig
          subPath: values.yaml
      volumes:
      - name: objstore-config
        secret:
          secretName: thanos-objstore-secret
      - name: indexcacheconfig
        secret:
          secretName: secret-thanos-storegateway-redis
```

And here's what in side secret 'secret-thanos-storegateway-redis':
```
type: REDIS
config:
  addr: "xxx-redis-standard.redis.cache.windows.net:6379"
  password: "xxx"
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_size: 100
  min_idle_conns: 10
  idle_timeout: 5m0s
  max_conn_age: 0s
  max_get_multi_concurrency: 100
  get_multi_batch_size: 100
  max_set_multi_concurrency: 100
  set_multi_batch_size: 100
  tls_enabled: false
  tls_config:
    insecure_skip_verify: true
  cache_size: 1.5GiB
```
Can some body please advise?

**What you expected to happen**:
the upgraded storegateway is able to connect to Azure Redis. 

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
in the other environment, we can see following logs 'caller=redis_client' regarding redis connection issue, however, there's no such logs in the upgraded environment.
` storegateway level=warn ts=2023-03-20T09:10:49.162240624Z caller=redis_client.go:184 msg="failed to set item into redis" err="context canceled" key=xxxx`

**Anything else we need to know**:
A test redis container has been established to verify the connection, the issue should has nothing to do with Azure Redis:
```
root@:~# kubectl exec -it -n blueprint redis -c redis -- redis-cli -h xxx-redis-standard.redis.cache.windows.net -p 6379 -a
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
xxx-redis-standard.redis.cache.windows.net:6379> keys *
(empty array)
```
