### ISSUE TITLE
v0.31.0 query parameter query.replica-label doesn't take effect on storegateway

### ISSUE THREAD

**Issue by zhangrj** [thanos-io/thanos#6248]
# Thanos version
After update from 0.30.1 to 0.31.0, query parameter `query.replica-label` doesn't run as expected.

# Config
```
      containers:
        - name: query
          image: registry.cn-hangzhou.aliyuncs.com/zhangrongjie/thanos:v0.31.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          args:
            - query
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.replica-label=replica
            - --query.replica-label=prometheus_replica
            - --store=dnssrv+_grpc._tcp.thanos-prod-storegateway-headless.thanos-prod.svc.cluster.local
            - --store=dnssrv+_grpc._tcp.thanos-prod-ruler-headless.thanos-prod.svc.cluster.local
            - --store=dnssrv+_grpc._tcp.thanos-prod-receive-headless.thanos-prod.svc.cluster.local
            - --query.lookback-delta=5m
            - --query.auto-downsampling
            - --query.partial-response
```

when query receive, the result is:

![receive](https://user-images.githubusercontent.com/15089393/229061164-f2cea056-101c-4b58-9433-c8f086ca1848.png)

when query storegateway, the result is:
![storegateway](https://user-images.githubusercontent.com/15089393/229061914-095f3738-eba6-4c66-97a8-b9bbb0a5122f.png)

We can see the `prometheus_replica` label doesn't be duplicated on storegateway. 

Then we delete `- --query.replica-label=prometheus_replica`, the query result become normal:
![normal](https://user-images.githubusercontent.com/15089393/229063768-31cf4577-d167-46ea-a768-56f86b32f27a.png)
