### ISSUE TITLE
Store: High memory usage on startup after upgrarding to 0.31.0

### ISSUE THREAD

**Issue by anas-aso** [thanos-io/thanos#6251]
**Thanos, Prometheus and Golang version used**:
Thanos: `goversion="go1.19.7", revision="50c464132c265eef64254a9fd063b1e2419e09b7", version="0.31.0"`
Prometheus: `goversion="go1.19.2", revision="dcd6af9e0d56165c6f5c64ebbc1fae798d24933a", version="2.39.1"`

**Object Storage Provider**:
GCP Storage and AWS S3

**What happened**:
Memory usage spike during startup after upgrading from 0.28.0 to 0.31.0.
After the memory spike I downgraded and started upgrading gradually from 0.28.0. I noticed that the memory spike on start up happens only from 0.30.2 to 0.31.0. So the changes in 0.31.0 are the culprit. 
![Screenshot 2023-03-31 at 12 26 11](https://user-images.githubusercontent.com/16538065/229095729-e270cf07-298b-4e5c-b144-0f137afaaac7.png)

**What you expected to happen**:
Memory usage stays roughly the same.

**How to reproduce it (as minimally and precisely as possible)**:
We run Thanos on both GCP and AWS and I noticed the issue on both cloud providers.

POD args
```yaml
    spec:
      containers:
      - args:
        - store
        - --log.format=json
        - --data-dir=/var/thanos/store
        - --objstore.config-file=/thanos_config.yaml
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:19191
        - --consistency-delay=10m
        - --ignore-deletion-marks-delay=0s
        - --max-time=-719h
        - --store.grpc.series-max-concurrency=5
        - --store.grpc.series-sample-limit=50000000
        - --store.enable-index-header-lazy-reader
        image: thanosio/thanos:v0.31.0
```
This store exposes metrics that are older than ~30 days. Our retention is 2 years (the 2 years - 30 days store is very rarely queried, that's why we delegate it to a single instance).

**Full logs to relevant components**:
There is nothing special in the logs, just a huge list of events like the one below :

<details>Logs
<p>

```json
{
    "@timestamp": "2023-03-31T10:15:18.234182290Z",
    "caller": "bucket.go:654",
    "elapsed": "5.849035528s",
    "id": "01FNAN7EDKBJ9762ZVSV0VDCSH",
    "level": "info",
    "msg": "loaded new block"
}
```

</p>
</details>

**Anything else we need to know**:
