### ISSUE TITLE
compact fails with securityContext runAsNonRoot

### ISSUE THREAD

**Issue by szymonpk** [thanos-io/thanos#629]
**Thanos, Prometheus and Golang version used**

improbable/thanos:v0.1.0

**What happened**

I am running compact as k8s StatefulSet with:

      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      volumes:
        - emptyDir: {}
          name: thanos-compact-tmp

Unfortunately it fails with permission denied during mkdir (see log below). I am not sure why this happens I can create directories on the volume when running sh from busybox container.

**What you expected to happen**

Successful compaction.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compact
  labels:
    app: thanos-compact
  namespace: monitoring
spec:
  replicas: 1
  serviceName: thanos-compact
  selector:
    matchLabels:
      app: thanos-compact
  template:
    metadata:
      labels:
        app: thanos-compact
    spec:
      containers:
      - name: thanos-compact
        image: improbable/thanos:v0.1.0
        args:
        - compact
        - --log.level=info
        - --data-dir="/thanos-compact"
        - --debug.disable-downsampling # https://github.com/improbable-eng/thanos/pull/529
        - --s3.bucket=<bucket name>
        - --s3.endpoint=s3.eu-west-1.amazonaws.com
        - --retention.resolution-raw=30d  
        - --retention.resolution-5m=30d  
        - --retention.resolution-1h=30d   
        - --wait  
        volumeMounts:
        - name: thanos-compact-tmp
          mountPath: /thanos-compact
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      volumes:
        - emptyDir: {}
          name: thanos-compact-tmp
```

**Full logs to relevant components**

```
level=info ts=2018-11-13T05:35:37.850609091Z caller=compact.go:817 msg="start of GC"
level=error ts=2018-11-13T05:35:37.851665669Z caller=main.go:161 msg="running command failed" err="error executing compaction: compaction failed: compaction: create compaction group dir: mkdir \": permission denied"
```
