### ISSUE TITLE
Thanos receiver adopted remote write headers for multi tenant

### ISSUE THREAD

**Issue by JayChanggithub** [thanos-io/thanos#6295]
Hi Team

We wonder to adopt HTTP headers of remote write via prometheus setup to send metrics for Thanos to achieve multi-tenant. But currently we cannot sure the behavior whether exactly. So wanna to confirm if any missing configuration.

#### thanos-receiver parameters 

```yaml
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --receive.hashrings-file-refresh-interval=1m
        - --receive.hashrings-algorithm=ketama
        - --objstore.config-file=/etc/thanos/objectstorage.yaml
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=6h
        - --tsdb.out-of-order.time-window=2h
        - --receive.tenant-header="THANOS-TENANT"
        - --receive-forward-timeout=5m
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --tsdb.no-lockfile
        - --tsdb.allow-overlapping-blocks
        - --receive.hashrings-file=/etc/thanos/thanos-receive-hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.thanos.svc.cluster.local:10901
```

#### thanos-receive-hashrings.json

```bash
    [
        {
          "hashring": "soft-tenants",
          "endpoints": [
              "thanos-receive-0.thanos-receive.thanos.svc.cluster.local:10901",
              "thanos-receive-1.thanos-receive.thanos.svc.cluster.local:10901",
              "thanos-receive-2.thanos-receive.thanos.svc.cluster.local:10901",
              "thanos-receive-3.thanos-receive.thanos.svc.cluster.local:10901"

          ]
        },
        {
          "hashring": "tenant-testing",
          "endpoints": [
              "thanos-receive-3.thanos-receive.thanos.svc.cluster.local:10901",
              "thanos-receive-4.thanos-receive.thanos.svc.cluster.local:10901"
          ],
          "tenants": ["testing"]
        }
    ]

```

#### Prometheus manifest via CLI 

```bash
$ k get prometheus/prometheus -n cic-system -o yaml
```

```yaml
  externalLabels:
    cluster: rm-uat
    project: rm
    purpose: staging
  externalUrl: https://prometheus.rm-uat.xxxxxxxxxxx.io.com
  image: quay.io/prometheus/prometheus:v2.42.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMetadata:
    annotations:
      sidecar.istio.io/inject: "false"
    labels:
      app: prometheus
      prometheus: prometheus
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prometheus
  remoteWrite:
  - headers:
      THANOS-TENANT: testing
    url: http://thanos-receive.thanos.xxxxxxxx/api/v1/receive
```

`Prometheus revision: v2.42.0`
`Thanos receive revision: v0.31.0`

#### issue as screenshot 

As far as i know the tenant_id need to be **tenant_id=testing**. But currently only showing default-tenant. Just wanna confirmed if any misunderstanding? 
<img width="885" alt="Xnip2023-04-19_21-55-52" src="https://user-images.githubusercontent.com/36335960/233097688-747d4bfe-b4ca-405f-92e1-aa336e5125ca.png">
