### ISSUE TITLE
SWIFT object storage

### ISSUE THREAD

**Issue by Orsek123** [thanos-io/thanos#636]
Hello,
I would like to migrate from minio to swift.

Now I test SWIFT client in thanos. 
I have configuration:
```
type: SWIFT
config:
    auth_url: "http://swiftpool:18080/auth/v1.0"
    username: thanos
    password: *****
    tenant_name: ab2
    container_name: "thanos-data"
```

But it's fail
Log:
`store command failed: create bucket client: create SWIFT client: invalid character '<' looking for beginning of value`

Where I have a misstake? 
Thanks.
