### ISSUE TITLE
SWIFT bad request

### ISSUE THREAD

**Issue by shmelkin** [thanos-io/thanos#6423]
**Thanos, Prometheus and Golang version used**: 

thanos 12.6.2 deployed via bitnami helm chart

**Object Storage Provider**:

SWIFT

**What happened**:

storegateway crashlooping

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
values:
    existingObjstoreSecret: thanos-objstore-secret
    storegateway:
      enabled: true
```

```
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
stringData:
  objstore.yml: |-
    type: SWIFT
    config:
      auth_version: 3
      auth_url: https://url/v3
      username: name
      password: pass
      project_name: pname
      project_domain_id: pdomainid
      region_name: regiom
      container_name: data
```

**Full logs to relevant components**:

```
level=error ts=2023-06-07T09:19:00.966418574Z caller=main.go:135 err="Bad Request\nauthentication\ngithub.com/thanos-io/objstore/providers/swift.NewContainerFromConfig\n\t/go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20230201072718-11ffbc490204/providers/swift/swift.go:178\ngithub.com/thanos-io/objstore/providers/swift.NewContainer\n\t/go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20230201072718-11ffbc490204/providers/swift/swift.go:156\ngithub.com/thanos-io/objstore/client.NewBucket\n\t/go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20230201072718-11ffbc490204/client/factory.go:72\nmain.runStore\n\t/app/cmd/thanos/store.go:275\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:214\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\ncreate SWIFT client\ngithub.com/thanos-io/objstore/client.NewBucket\n\t/go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20230201072718-11ffbc490204/client/factory.go:87\nmain.runStore\n\t/app/cmd/thanos/store.go:275\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:214\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\ncreate bucket client\nmain.runStore\n\t/app/cmd/thanos/store.go:277\nmain.registerStore.func1\n\t/app/cmd/thanos/store.go:214\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\npreparing store command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"
```
</p>
</details>
-->

**Anything else we need to know**:

**Comment by shmelkin** [comment]
Sometimes I hate this stuff.

After hours of debugging, the issue was resolved by also setting "domain_name:".
```
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
stringData:
  objstore.yml: |-
    type: SWIFT
    config:
      auth_version: 3
      auth_url: https://url/v3
      username: name
      password: pass
      project_name: pname
      project_domain_id: pdomainid
      region_name: regiom
      container_name: data
      domain_name: Default
```
