### ISSUE TITLE
Cannot scrape sidecar from another cluster

### ISSUE THREAD

**Issue by shmelkin** [thanos-io/thanos#6431]
**Thanos, Prometheus and Golang version used**:  

12.x

**Object Storage Provider**:  

SWIFT

**What happened**: 

I'm trying to query external sidecars through an ssh tunnel and I get errors

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Reverse proxy to the port of the sidecar in kube-prometheus-stack:

```
    User tunnel-endpoint 
    Port 2222
    IdentitiesOnly yes
    ServerAliveInterval 10
    ServerAliveCountMax 3
    BatchMode yes
    ExitOnForwardFailure yes
    CheckHostIP no
    GatewayPorts yes

    Host ssh-tunnel
      RemoteForward 0.0.0.0:9980 kube-prometheus-stack-prometheus:10901
      HostName xxx.xxx.xxx.xxx
```
```
query:
      enabled: true
      logLevel: debug
      stores:
      - thanos-site-f-storegateway:10901 <- local cluster gateway working!
      - sshd:9980 # sidecar site <- ssh tunnel not working
      - dnssrv+_grpc._tcp.kube-prometheus-stack-thanos-discovery.monitoring.svc.cluster.local  <- local cluster sidecar working!
```
**Full logs to relevant components**:
```
level=warn ts=2023-06-09T08:20:37.108938831Z caller=endpointset.go:451 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from sshd:9979: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=sshd:9980
```

**Anything else we need to know**:

**Comment by matej-g** [comment]
Hey @shmelkin, outside of Thanos, if you try manually, can you reach that sidecar? This seems like the store is simply "not there" or the query is not getting any response from the store.

**Comment by shmelkin** [comment]
Thank you  @matej-g  for coming back to me. Didnt have the chance yet to answer here again. 

I solved the issue. First off, the sidecar service is headless by standard within the kube-prometheus-stack. 
I changed this, see below.
```
prometheus:
   prometheusSpec:
      thanosService:
         enabled: true
         clusterIP: ""
         targetPort: 10901
         targetHttpPort: 10902
```


Then, after the first issue was out of the way, I noticed that my SSH service did not have the right ports exposed.

After exposing the port 9980 everything started working fine.
