### ISSUE TITLE
mTLS does not work when using DNS Store Discovery instead of FQDNs

### ISSUE THREAD

**Issue by avidpontoon** [thanos-io/thanos#6454]
**Thanos, Prometheus and Golang version used**:

Checked with Thanos 0.31.0 and 0.30.2. Using K8S, no Prometheus involved for this to occur

**Object Storage Provider**: Minio

**What happened**:

When using mTLS to secure gRPC communications between query and another component (tested with Store and Receive). If you specify the store as the FQDN using the pod name and service name etc, mTLS works and verifies the cert and the store appears in the 'Stores' tab of Query. However, when you use DNS Discovery, the components complain about 'context deadline exceeded' to the Store or Receive pods. Moving back to specifying each FQDN immediately fixes the issue. Also, when using DNS discovery, using the arg `--grpc-client-tls-skip-verify` does bring the stores in, so im guessing this is something in how the DNS is looked up post discovery.

This works:
```
    spec:
      serviceAccount: thanos
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: querier
          image: docker.io/bitnami/thanos:0.30.2
          args:
            - query
            - --log.level=debug
            - --endpoint.info-timeout=30s
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.replica-label=receive_replica
            - --query.replica-label=prometheus_replica
            #FQDNs Specified
            - --store=storegateway-0.storegateway-new.thanos.svc.cluster.local:10901
            - --store=storegateway-1.storegateway-new.thanos.svc.cluster.local:10901
            - --store=receiver-new-0.receiver-new.thanos.svc.cluster.local:10907
            - --store=receiver-new-1.receiver-new.thanos.svc.cluster.local:10907
            - --store=receiver-new-2.receiver-new.thanos.svc.cluster.local:10907
            - --store=receiver-new-3.receiver-new.thanos.svc.cluster.local:10907
            - --grpc-client-tls-secure
            - --grpc-client-tls-cert=/certs/tls.crt
            - --grpc-client-tls-key=/certs/tls.key
            - --grpc-client-tls-ca=/certs/ca.crt
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
...
          volumeMounts:
            - name: thanos-query-cert
              mountPath: /certs
      volumes:
        - name: thanos-query-cert
          secret:
            secretName: thanos-query-cert
```

This does not work:
```
    spec:
      serviceAccount: thanos
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: querier
          image: docker.io/bitnami/thanos:0.30.2
          args:
            - query
            - --log.level=debug
            - --endpoint.info-timeout=30s
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.replica-label=receive_replica
            - --query.replica-label=prometheus_replica
             #FQDNs NOT Specified
            - --store=dnssrv+_grpc._tcp.receiver-new.thanos.svc.cluster.local
            - --store=dnssrv+_grpc._tcp.storegateway-new.thanos.svc.cluster.local
            - --grpc-client-tls-secure
            - --grpc-client-tls-cert=/certs/tls.crt
            - --grpc-client-tls-key=/certs/tls.key
            - --grpc-client-tls-ca=/certs/ca.crt
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
...
          volumeMounts:
            - name: thanos-query-cert
              mountPath: /certs
      volumes:
        - name: thanos-query-cert
          secret:
            secretName: thanos-query-cert
```

**What you expected to happen**: I would expect mTLS to pass verification even if FQDNs are not specified and use DNS discovery instead.

**How to reproduce it (as minimally and precisely as possible)**: Configure mTLS and use DNS discovery between Query and a client component, rather than FQDN.

**Full logs to relevant components**:

Using FQDNs:
```
level=debug ts=2023-06-17T22:00:35.635077396Z caller=endpointset.go:419 component=endpointset msg="updated endpoints" activeEndpoints=0
level=info ts=2023-06-17T22:00:35.635173618Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-06-17T22:00:35.635195543Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2023-06-17T22:00:35.635418059Z caller=tls_config.go:232 service=http/server component=query msg="Listening on" address=[::]:10902
level=info ts=2023-06-17T22:00:35.635441555Z caller=tls_config.go:235 service=http/server component=query msg="TLS is disabled." http2=false address=[::]:10902
level=info ts=2023-06-17T22:00:35.635474925Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-06-17T22:00:35.635506159Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=debug ts=2023-06-17T22:00:40.636196723Z caller=endpointset.go:342 component=endpointset msg="starting to update API endpoints" cachedEndpoints=0
level=info ts=2023-06-17T22:00:40.716176325Z caller=endpointset.go:411 component=endpointset msg="adding new store with [storeAPI]" address=storegateway-0.storegateway-new.thanos.svc.cluster.local:10901 extLset="{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-0\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-1\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-2\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-3\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", tenant_id=\"default-tenant\"},{replica=\"thanos-ruler-0\", ruler_cluster=\"prometheus-ha\"},{replica=\"thanos-ruler-1\", ruler_cluster=\"prometheus-ha\"}"
level=info ts=2023-06-17T22:00:40.716211874Z caller=endpointset.go:411 component=endpointset msg="adding new store with [storeAPI]" address=storegateway-1.storegateway-new.thanos.svc.cluster.local:10901 extLset="{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-0\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-1\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-2\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", receive_replica=\"receiver-new-3\", tenant_id=\"default-tenant\"},{receive_cluster=\"rec-main\", tenant_id=\"default-tenant\"},{replica=\"thanos-ruler-0\", ruler_cluster=\"prometheus-ha\"},{replica=\"thanos-ruler-1\", ruler_cluster=\"prometheus-ha\"}"
level=debug ts=2023-06-17T22:00:40.716230517Z caller=endpointset.go:419 component=endpointset msg="updated endpoints" activeEndpoints=6
```

Using DNS Discovery:
```
level=debug ts=2023-06-17T22:11:41.540574567Z caller=endpointset.go:342 component=endpointset msg="starting to update API endpoints" cachedEndpoints=0
level=warn ts=2023-06-17T22:12:11.541864768Z caller=endpointset.go:446 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.244.3.40:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.244.3.40:10901
level=warn ts=2023-06-17T22:12:11.541943566Z caller=endpointset.go:446 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.244.1.149:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.244.1.149:10901
level=debug ts=2023-06-17T22:12:11.541965226Z caller=endpointset.go:419 component=endpointset msg="updated endpoints" activeEndpoints=0
level=debug ts=2023-06-17T22:12:11.541983712Z caller=endpointset.go:342 component=endpointset msg="starting to update API endpoints" cachedEndpoints=0
```

**Anything else we need to know**: I have tried multiple SANs on the certificate, I am using cert-manager and the cert yaml for my store gw is as follows:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanos-store-cert
  namespace: thanos
spec:
  secretName: thanos-store-cert
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 8760h
  renewBefore: 2208h
  subject:
    organizations:
      - testcerts
  commonName: storegateway-new.thanos.svc.cluster.local
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - storegateway.thanos.svc.cluster.local
    - storegateway-0.storegateway-new.thanos.svc.cluster.local
    - storegateway-1.storegateway-new.thanos.svc.cluster.local
    - "*.storegateway-new.thanos.svc.cluster.local"
    - storegateway-new.thanos.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
```

The above cert works when using FQDNs so its valid and does work, just not using DNS discovery. However, there are no other SAN DNS names that would make sense to add as all discovery should do is grab the FQDNs for us instead of being static in the args.
