### ISSUE TITLE
[query] [query frontend] Interaction between grafana and thanos

### ISSUE THREAD

**Issue by theodrim** [thanos-io/thanos#6480]
**Thanos, Prometheus and Golang version used**:
thanos/thanos:v0.31.0
prometheus/prometheus:v2.44.0

**Object Storage Provider**: AWS S3

**What happened**: Upon switching to thanos as a datasource for any dashboard, containing $__rate_interval variable, selecting "Absolute time range" lower than 8 hours will result in 'no data' 

**What you expected to happen**: Expect to be able to zoom into specific interval and drill down to maybe 20 minute graphs.

**How to reproduce it (as minimally and precisely as possible)**: With dashboard containing $__rate_interval - 100% reproducibility.

**Full logs to relevant components**: Nothing unusual in the logs during those actions.

<details>Query
<p>

```
query:
level=info ts=2023-06-28T02:48:49.309742119Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2023-06-28T02:48:49.310689943Z caller=query.go:840 msg="starting query node"
level=info ts=2023-06-28T02:48:49.311205533Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-06-28T02:48:49.311326862Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-06-28T02:48:49.311402127Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2023-06-28T02:48:49.31141898Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2023-06-28T02:48:49.311458627Z caller=tls_config.go:232 service=http/server component=query msg="Listening on" address=[::]:10902
level=info ts=2023-06-28T02:48:49.311650962Z caller=tls_config.go:235 service=http/server component=query msg="TLS is disabled." http2=false address=[::]:10902
level=info ts=2023-06-28T02:48:54.313912513Z caller=endpointset.go:416 component=endpointset msg="adding new store with [storeEndpoints]" address=172.20.175.168:10901 extLset="{prometheus=\"monitoring/prometheus-operator-kube-p-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-kube-p-prometheus-0\"},{prometheus=\"monitoring/prometheus-operator-kube-p-prometheus\"},{receive=\"true\", replica=\"thanos-receive-0\", tenant_id=\"default-tenant\"},{receive=\"true\", replica=\"thanos-receive-1\", tenant_id=\"default-tenant\"}"
level=info ts=2023-06-28T02:48:54.313959216Z caller=endpointset.go:416 component=endpointset msg="adding new sidecar with [storeEndpoints rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=10.5.109.99:10901 extLset="{prometheus=\"monitoring/prometheus-operator-kube-p-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-kube-p-prometheus-0\"}"
level=info ts=2023-06-28T02:48:54.313977981Z caller=endpointset.go:416 component=endpointset msg="adding new receive with [storeEndpoints exemplarsAPI]" address=172.20.82.111:10901 extLset="{receive=\"true\", replica=\"thanos-receive-0\", tenant_id=\"default-tenant\"}"

query-frontend:
level=info ts=2023-06-28T02:48:54.976621778Z caller=query_frontend.go:339 msg="starting query frontend"
level=info ts=2023-06-28T02:48:54.976653219Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-06-28T02:48:54.976706029Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-06-28T02:48:54.97672857Z caller=http.go:73 service=http/server component=query-frontend msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2023-06-28T02:48:54.976876103Z caller=tls_config.go:232 service=http/server component=query-frontend msg="Listening on" address=[::]:10902
level=info ts=2023-06-28T02:48:54.976906373Z caller=tls_config.go:235 service=http/server component=query-frontend msg="TLS is disabled." http2=false address=[::]:10902
```

</p>
</details>

**Anything else we need to know**: Thanos deployed via argo-cd using bitnami helm chart basically as template, without any unusual configuration.

<details>values
<p>

```
global:
  imagePullSecrets:
    - monitoring-v1-nexus-pull-secret

image:
  repository: thanos/thanos
  tag: v0.31.0
  pullSecrets:
    - monitoring-v1-nexus-pull-secret

objstoreConfig: |-
  type: s3
  config:
    bucket: secret
    endpoint: s3.secret.amazonaws.com

indexCacheConfig: |-
  type: memcached
  config:
    addresses:
    - dns+secret:11211
    dns_provider_update_interval: 10s
    max_async_buffer_size: 10000
    max_async_concurrency: 20
    max_get_multi_batch_size: 0
    max_get_multi_concurrency: 100
    max_idle_connections: 100
    timeout: 500ms

bucketCacheConfig: |-
  type: memcached
  config:
    addresses:
    - dns+secret:11211
    dns_provider_update_interval: 10s
    max_async_buffer_size: 10000
    max_async_concurrency: 20
    max_get_multi_batch_size: 0
    max_get_multi_concurrency: 100
    max_idle_connections: 100
    timeout: 500ms

query:
  dnsDiscovery:
    sidecarsService: prometheus-operator-kube-p-thanos-discovery
    sidecarsNamespace: monitoring
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
  tolerations:
    - key: "arm64"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

queryFrontend:
  extraFlags:
    - |-
      --query-range.response-cache-config="config":
        "addresses":
        - "dns+secret:11211"
        "dns_provider_update_interval": "10s"
        "max_async_buffer_size": 10000
        "max_async_concurrency": 20
        "max_get_multi_batch_size": 0
        "max_get_multi_concurrency": 100
        "max_idle_connections": 100
        "timeout": "500ms"
      "type": "memcached"
    - |-
      --labels.response-cache-config="config":
        "addresses":
        - "dns+secret:11211"
        "dns_provider_update_interval": "10s"
        "max_async_buffer_size": 10000
        "max_async_concurrency": 20
        "max_get_multi_batch_size": 0
        "max_get_multi_concurrency": 100
        "max_idle_connections": 100
        "timeout": "500ms"
      "type": "memcached"

bucketweb:
  enabled: true
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
  tolerations:
    - key: "arm64"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

compactor:
  enabled: true
  persistence:
    size: 20Gi
  retentionResolutionRaw: 90d
  retentionResolution5m: 90d
  retentionResolution1h: 90d
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
  tolerations:
    - key: "arm64"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

storegateway:
  enabled: true
  persistence:
    size: 20Gi
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::secret
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
  tolerations:
    - key: "arm64"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  podManagementPolicy: Parallel

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-operator

receive:
  enabled: true
  podManagementPolicy: Parallel
  podAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::secret
```

</p>
</details>

**Environment**:
- EKS v1.26.5-eks-c12679a
- OS (e.g. from /etc/os-release): /etc/os-release isn't present in docker image, but host running container is either Amazon Linux 2 or Bottlerocket OS 1.14.0 with more recent 5.15.108 kernel. 
- Kernel (e.g. `uname -a`): `Linux thanos-query 5.10.179-168.710.amzn2.aarch64 #1 SMP Mon May 22 23:10:30 UTC 2023 aarch64 GNU/Linux`
