### ISSUE TITLE
Storing secrets from Thanos' Objstore configuration in environment variables

### ISSUE THREAD

**Issue by tanguynicolas** [thanos-io/thanos#6508]
### Is your proposal related to a problem?

Is there a way to store Thanos' Objstore configuration without exposing the secrets, and without putting the entire configuration in a secret or in the command line?

### Describe the solution you'd like

Ideally, it should be something like this. Grafana [does it](https://github.com/helm/charts/issues/17289#issuecomment-533520132), for example.
```
type: GCS
config:
  bucket: "thanos"
  service_account: ${MY_SERVICE_ACCOUNT}  # this is env var
```

### Describe alternatives you've considered

I've searched extensively in the documentation and issues but there doesn't seem to be a way to do this. Doing it in the command line seems to be possible but it's not a pretty way to do it.

### Additional context

I'm using Thanos on Kubernetes with Helm (bitnami packaged).
