### ISSUE TITLE
Not able to configure Thanos with Istio

### ISSUE THREAD

**Issue by prashantcfc** [thanos-io/thanos#6510]
**What happened**:

I've a setup where I've Thanos Querier deployed alongside Istio which talks to Thanos sidecar that sits alongside prometheus deployed using kube-prometheus-stack.

However, communication between Thanos Querier and Thanos sidecar fails due to Istio in between.

Is deployment of Thanos supported with Istio (to communicate with thanos sidecar) ?

**Full logs to relevant components**:

`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

Thanos: v0.31.0
Prometheus: v2.40

**Comment by philgladman** [comment]
@prashantcfc we are experiencing the same issue. Any luck?

**Comment by prashantcfc** [comment]
> @prashantcfc we are experiencing the same issue. Any luck?

Yes, I was able to get stuff working.

**Comment by philgladman** [comment]
We were able to fix this by adding an istio `DestinationRule`. Found this from an istio issue [here](https://github.com/istio/istio/issues/35870).

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: thanos-query-to-thanos-sidecar
  namespace: monitoring
spec:
  host: monitoring-monitoring-kube-thanos-discovery.monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```
