### ISSUE TITLE
Store service caching memcache dns for ever

### ISSUE THREAD

**Issue by federicopires** [thanos-io/thanos#6551]
**Thanos, Prometheus and Golang version used**:

`docker.io/bitnami/thanos:0.31.0-scratch-r9`

**Object Storage Provider**:
```
type: S3
  config:
    endpoint: "s3.us-west-2.amazonaws.com"
    bucket: "xxxx"
    region: "us-west-2"
    put_user_metadata:
      X-Amz-Storage-Class: INTELLIGENT_TIERING
```

**What happened**:
I'm running Thanos with the following index, bucket and query cache configurations using memcached:

```
type: MEMCACHED
  config:
    addresses: ["thanos-memcached-0.thanos-memcached.monitoring.svc.cluster.local:11211", "thanos-memcached-1.thanos-memcached.monitoring.svc.cluster.local:11211", "thanos-memcached-2.thanos-memcached.monitoring.svc.cluster.local:11211"]
    auto_discovery: false
```

`thanos-memcached-x` is a kubernetes headless service pointing to 3 memcached PODs from a statefulset. Whenever one of the PODs die and change IP address, I see store service complaining about timeouts to memcached and showing the old IP in the logs. 

We are using `CoreDNS` for dns resolver in our cluster which is supposed to use 30s TTLs for records. Is store service caching DNS for ever and not respecting the TTL? Is the lookup only done on startup? 

**What you expected to happen**:
Store service lookups DNS addresses on cache servers after TTL is expired.

**How to reproduce it (as minimally and precisely as possible)**:
Run thanos with memcached as cache in kubernets, kill a memcached POD while store service is running. Check the logs to see timeouts.

**Full logs to relevant components**:

```
level=warn ts=2023-07-21T17:21:04.174067873Z caller=memcached_client.go:648 name=caching-bucket msg="failed update memcached servers list" err="lookup thanos-memcached-0.thanos-memcached.monitoring.svc.cluster.local on 169.254.20.10:53: no such host"
```

**Environment**:
Kubernetes 1.26
