### ISSUE TITLE
store/compact: bucket fetch is broken in v0.32 vs v0.31

### ISSUE THREAD

**Issue by sepich** [thanos-io/thanos#6707]
**Thanos, Prometheus and Golang version used**:
v0.32.2

**Object Storage Provider**: GCS

**What happened**:
Tried to upgrade from v0.31.0 to v0.32.2 and seeing for both `compactor` and `store`:
- increased `Ready` time to 20min (from 1min for v0.31.0):
```
ts=2023-09-06T14:38:10.996926271Z caller=store.go:435 level=info msg="bucket store ready" init_duration=19m17.494860523s
ts=2023-09-06T14:36:06.345890308Z caller=fetcher.go:487 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=17m12.843785017s duration_ms=1032843 cached=11790 returned=6634 partial=4168
```
- constant bandwidth of 60MBps of `store` container towards bucket, even after sync of blocks is completed, it is `Ready`, and there are no query requests coming
- constant cpu usage
<img width="723" alt="image" src="https://github.com/thanos-io/thanos/assets/1803804/29bd36c7-2d68-4e10-9b22-7aa6e445e222">

Using images available on docker hub the issue is narrowed down to:
`thanosio/thanos:main-2023-07-03-9710935` - ok
`thanosio/thanos:main-2023-07-03-b60452a` - bad
So it is https://github.com/thanos-io/thanos/pull/6474/files to blame
cc @fpetkovski 

Also attaching pprof cpu profile for 60s, when `store` becomes `ready` and there is no any queries to it:
[Archive.zip](https://github.com/thanos-io/thanos/files/12540716/Archive.zip)

**What you expected to happen**:
New version is better than previous ;)

**How to reproduce it (as minimally and precisely as possible)**:
```
          image: thanosio/thanos:main-2023-07-03-b60452a # main-2023-07-03-9710935 - works
          args:
            - store
            - |
              --objstore.config=type: GCS
              config:
                bucket: <bucketname>
```

**Full logs to relevant components**:
No any errors in logs, just very slow timings
