### ISSUE TITLE
Thanos Query shows the additional metric which is not found in the prometheus

### ISSUE THREAD

**Issue by wotkddl21** [thanos-io/thanos#6708]
**Thanos, Prometheus and Golang version used**: 
prometheus : v2.32.1
thanos: v0.24.0 , v0.30.0, v0.32.0

**Object Storage Provider**:

**What happened**: The result of query kube_pod_info{} is different between the prometheus and thanos query  
During the containercreating time, the pod doesn't have its ip (pod_ip).  
In this situation, the prometheus shows the kube_pod_info metric only with pod_ip.  
But the thanos query shows the kube_pod_info metric with and without pod_ip  

The result of query in the prometheus  
![prometheus-with-pod-ip](https://github.com/thanos-io/thanos/assets/57653556/70d9a72f-3db1-4e98-8324-3e732650a794)  
  
  
The result of query in the thanos query
![thanos-with-pod-ip](https://github.com/thanos-io/thanos/assets/57653556/76ad228e-f8ad-4e10-bd64-7a14cd1ab2bb)  

**What you expected to happen**: The result exactly same among prometheus and thanos query  

**How to reproduce it (as minimally and precisely as possible)**: Whenever the pod doesn't have its ip.  

**Full logs to relevant components**:

**Anything else we need to know**:

 
This is the commandline flags of the thanos query in my k8s. 
- query  
- --log.level=debug  
- --query.auto-downsampling  
- --query.timeout=1h  
- --query.instant.default.max_source_resolution=1h  
- --query.replica-label=prometheus_replica  
- --query.replica-label=thanos_ruler_replica  
- --http-grace-period=1h  
- --store=dnssrv+_grpc._tcp.thanos-sidecar.sre-mtr.svc.cluster.local  
- --store=dnssrv+_grpc._tcp.thanos-store.sre-mtr.svc.cluster.local  
- --store=dnssrv+_grpc._tcp.thanos-ruler.sre-mtr.svc.cluster.local  

This is the CRD of prometheus

``` yaml   
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
  shards: 3
...
  thanos:
    objectStorageConfigFile: /etc/objstore-config/bucketconfig.yaml
    volumeMounts:
    - mountPath: /etc/objstore-config
      name: objstore-config
  tolerations:
  - effect: NoSchedule
    operator: Exists
  version: v2.32.1
  volumes:
  - name: objstore-config
    secret:
      secretName: thanos-objstore-config
```
