### ISSUE TITLE
[Thanos Store] Container receive Error during 1 startup, then proceed to work

### ISSUE THREAD

**Issue by RainbowHerbicides** [thanos-io/thanos#6720]
**Thanos, Prometheus and Golang version used**: 
*0.32.2* or to be precise *docker.io/bitnami/thanos:0.32.2-debian-11-r0*

**Object Storage Provider**:
S3

**What happened**:
During first startup sequence container receive 1 restart due to error. After that - component working correctly but no data had been propagated to Redis 

**What you expected to happen**:
Component start without any issues and index cache will be created on Redis side

**How to reproduce it (as minimally and precisely as possible)**:
Can be reproduced possibly by deployment of single instance Redis and utilise Redis configuration below in flag *--index-cache.config-file=/conf/cache/config.yml*
```
apiVersion: v1
data:
  config.yml: |-
    type: REDIS
    config:
      addr: "thanos-redis-master.tools-test-thanos-evolution.svc.cluster.local:6379"
      db: 4
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
      max_get_multi_concurrency: 100
      get_multi_batch_size: 100
      max_set_multi_concurrency: 100
      set_multi_batch_size: 100
      tls_enabled: false
      cache_size: 0
      max_async_buffer_size: 10000
      max_async_concurrency: 20
      expiration: 24h0m0s
```

**Full logs to relevant components**:
```
ts=2023-09-12T15:03:27.390532841Z caller=factory.go:53 level=info msg="loading bucket configuration"
ts=2023-09-12T15:03:27.391049062Z caller=factory.go:35 level=info msg="loading index cache configuration"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14534ac]
goroutine 1 [running]:
github.com/redis/rueidis.(*clusterClient)._pick(0x4000247680?, 0x5f?)
	/bitnami/blacksmith-sandox/thanos-0.32.2/pkg/mod/github.com/redis/rueidis@v1.0.14-go1.18/cluster.go:289 +0x1c
github.com/redis/rueidis.(*clusterClient).single(...)
	/bitnami/blacksmith-sandox/thanos-0.32.2/pkg/mod/github.com/redis/rueidis@v1.0.14-go1.18/cluster.go:233
github.com/redis/rueidis.NewClient({{0x12a05f200, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	/bitnami/blacksmith-sandox/thanos-0.32.2/pkg/mod/github.com/redis/rueidis@v1.0.14-go1.18/rueidis.go:306 +0x270
github.com/thanos-io/thanos/pkg/cacheutil.NewRedisClientWithConfig({0x259e9e0?, _}, {_, _}, {{0x4000053130, 0x46}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/bitnami/blacksmith-sandox/thanos-0.32.2/src/github.com/thanos-io/thanos/pkg/cacheutil/redis_client.go:215 +0x288
github.com/thanos-io/thanos/pkg/cacheutil.NewRedisClient({0x259e9e0, 0x4000063800}, {0x200de04, 0xb}, {0x40009e6c00?, 0x1926301?, 0x40009e6800?}, {0x25b29d0, 0x400050e9b0})
	/bitnami/blacksmith-sandox/thanos-0.32.2/src/github.com/thanos-io/thanos/pkg/cacheutil/redis_client.go:162 +0x10c
github.com/thanos-io/thanos/pkg/store/cache.NewIndexCache({0x259e9e0, 0x4000063800}, {0x40001ac4e0, 0x196, 0x1a0}, {0x25b29d0, 0x400050e9b0})
	/bitnami/blacksmith-sandox/thanos-0.32.2/src/github.com/thanos-io/thanos/pkg/store/cache/factory.go:59 +0x1bc
main.runStore(_, {_, _}, _, {_, _}, {_, _, _}, {_, ...}, ...)
	/bitnami/blacksmith-sandox/thanos-0.32.2/src/github.com/thanos-io/thanos/cmd/thanos/store.go:326 +0x860
main.registerStore.func1(0x1cf3e40?, {0x259e9e0, 0x4000063800}, 0x6?, {0x25b28b0, 0x3abdf40}, 0x68?, 0x0)
	/bitnami/blacksmith-sandox/thanos-0.32.2/src/github.com/thanos-io/thanos/cmd/thanos/store.go:226 +0x1b0
main.main()
	/bitnami/blacksmith-sandox/thanos-0.32.2/src/github.com/thanos-io/thanos/cmd/thanos/main.go:133 +0x1074
```

**Anything else we need to know**:
Before address had been = thanos-redis-master.tools-test-thanos-evolution, which caused different error 
```dial tcp: lookup thanos-redis-master.tools-test-thanos-evolution: i/o timeout``` . Though debug container attached to Store container - this url were resolvable
