### ISSUE TITLE
sidecar: Memory consumption spike during block upload in v0.32.3

### ISSUE THREAD

**Issue by Tassatux** [thanos-io/thanos#6744]
**Thanos, Prometheus and Golang version used**:

quay.io/thanos/thanos:v0.32.3
quay.io/prometheus/prometheus:v2.46.0

Used via Prometheus resources from prometheus-operator.

**Object Storage Provider**:

S3 (MinIO)

**What happened**:

During block upload to the object storage, the memory consumption spike and lead to OOMKill. This started after upgrading to v0.32.3, on each of my Prometheus pods.

![image](https://github.com/thanos-io/thanos/assets/1558396/564c7328-e885-4bed-8aec-d74942645fa6)
![image](https://github.com/thanos-io/thanos/assets/1558396/e8e9111d-3e04-4c82-a7c5-ed37ed821f54)
![image](https://github.com/thanos-io/thanos/assets/1558396/7e1e93b1-1d5c-4ce0-8728-b22758e9f658)

**What you expected to happen**:

Memory consumption remain under control as in v0.32.2

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade Thanos sidecar to v0.32.3

**Full logs to relevant components**:

I only had such logs before my container being OOMKilled:

```
ts=2023-09-21T09:00:53.576667908Z caller=shipper.go:354 level=info msg="upload new block" id=01HAVFFCMME4J0QV4A3KY7QQRP
ts=2023-09-21T09:00:53.789459807Z caller=s3.go:487 level=warn msg="could not guess file size for multipart upload; upload might be not optimized" name=01HAVFFCMME4J0QV4A3KY7QQRP/chunks/000001 err="unsupported type of io.Reader: io.nopCloser"
ts=2023-09-21T09:00:55.815369104Z caller=s3.go:487 level=warn msg="could not guess file size for multipart upload; upload might be not optimized" name=01HAVFFCMME4J0QV4A3KY7QQRP/index err="unsupported type of io.Reader: io.nopCloser"
```

But the warning seem to be related to https://github.com/thanos-io/objstore/pull/77

**Anything else we need to know**:

Container args/resources:

```
  - args:
    - sidecar
    - --prometheus.url=http://127.0.0.1:9090/
    - '--prometheus.http-client={"tls_config": {"insecure_skip_verify":true}}'
    - --grpc-address=:10901
    - --http-address=:10902
    - --objstore.config=$(OBJSTORE_CONFIG)
    - --tsdb.path=/prometheus
    image: quay.io/thanos/thanos:v0.32.3
    name: thanos-sidecar
    resources:
      limits:
        cpu: "4"
        ephemeral-storage: 100Mi
        memory: 1Gi
      requests:
        cpu: 100m
        ephemeral-storage: 10Mi
        memory: 64Mi
```
