### ISSUE TITLE
Prometheus remote write to Thanos Receiver (AWS ALB) 502 bad gateway and err="context canceled"

### ISSUE THREAD

**Issue by codevally** [thanos-io/thanos#6755]
**Thanos, Prometheus and Golang version used**:
thanos:v0.28.0
Prometheus: 2.37.0

**Object Storage Provider**:
AWS S3

**What happened**:
I have setup the Thanos Receiver and expose it through an AWS ALB. Then configure Prometheus (in another EKS cluster) remore_write to send WAL logs to this endpoint.

remote_write configs:
```
      - url: https://thanos-receiver.foobar.com/api/v1/receive
        remote_timeout: 360s
        queue_config:
          capacity: 2500
          max_backoff: 10s
          max_samples_per_send: 500
        tls_config:
          ca_file: /etc/prometheus/certs/ca.crt
```
**What you expected to happen**:
Prometheus should be able to send the WAL logs without errors. But I can see these issues in prometheus logs.

```
../api/v1/receive msg="Failed to send batch, retrying" err="server returned HTTP status 502 Bad Gateway: <html>"
---
msg="Failed to send batch, retrying" err="Post \"https://thanos-receiver.foobar.com/api/v1/receive\": context canceled"
```

**Anything else we need to know**:
I have set the ALB idle time out to 600s to avoid the timeouts, but didn't helped.
