### ISSUE TITLE
Thanos Ruler Facing Issue cannot trigger alerts from alertmanager 

### ISSUE THREAD

**Issue by vishnuvardhan-Dev** [thanos-io/thanos#6871]
we created two clusters, clusters named dev and test, we installed Thanos components, Kube Prometheus setup where as Test env Prometheus setup with sidecar which is exposed as a service. In Thanos components, we can see metrics from Thanos query as well as Grafana.

**Issue Facing : Thanos Ruler **:
***thanos-rule.yml file***
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-ruler-rules
  namespace: monitoring
data:
  alert_down_services.rules.yaml: |
    groups:
    - name: metamonitoring
      rules:
      - alert: PrometheusReplicaDown
        annotations:
          message: Prometheus replica in cluster {{$labels.cluster}} has disappeared from Prometheus target discovery.
        expr: |
          sum(up{cluster="test", cluster="dev", instance=~".*:9090", job="kubernetes-service-endpoints"}) by (job, cluster) < 3
        for: 15s
        labels:
          severity: critical
          cluster: all
      - alert: KubeDeploymentReplicasMismatch
        annotations:
          description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes.
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentreplicasmismatch
          summary: Deployment has not matched the expected number of replicas.
        expr: |-
          (
            kube_deployment_spec_replicas{job="kube-state-metrics", namespace=~".*", cluster=~".*"} >
            kube_deployment_status_replicas_available{job="kube-state-metrics", namespace=~".*", cluster=~".*"}
          ) and (
            changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace=~".*", cluster=~".*"}[10m]) == 0
          )
        for: 15m  # Updated from 0m to 15 minutes
        labels:
          severity: warning
          cluster: "*"
          cluster: "dev"
          cluster: "test"

    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-ruler
  name: thanos-ruler
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-ruler
  serviceName: thanos-ruler
  template:
    metadata:
      labels:
        app: thanos-ruler
        thanos-store-api: "true"
    spec:
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.8.0
          args:
            - rule
            - --log.level=debug
            - --data-dir=/data
            - --eval-interval=15s
            - --rule-file=/etc/thanos-ruler/*.rules.yaml
            - --alertmanagers.url=http://alertmanager:9093
            - --alertmanagers.url=http://alertmanager-operated:9093
            - --query=http://thanos-query:9090
            - --query=http://10.15.1.217:10901
            - --query=http://thanos-store:10901
            - --objstore.config=$(OBJSTORE_CONFIG)
            - --label=cluster="dev"
            - --label=cluster="test"
            - --label=replica="$(POD_NAME)"
          env:
            - name : GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secret/thanos-gcs-credentials.json
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OBJSTORE_CONFIG
              valueFrom:
                secretKeyRef:
                  key: thanos.yaml
                  name: thanos-objstore-config
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              port: http
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: http
              path: /-/ready
          volumeMounts:
            - mountPath: /etc/thanos-ruler
              name: config
            - name: thanos-gcs-credentials
              mountPath: /etc/secret
              readOnly: false
      volumes:
        - configMap:
            name: thanos-ruler-rules
          name: config
        - name: thanos-gcs-credentials
          secret:
            secretName: thanos-objstore-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-ruler
  name: thanos-ruler
  namespace: monitoring
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: thanos-ruler



```
***alertmanager-configuaration.yml***
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: "9b97b3029b984500c07a992165d66"
      victorops_api_url: "<your_victorops_hook>"

    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m  
      receiver: default 
      routes:
      - match:
          team: test
        receiver: test
        continue: true 
      - match: 
          team: dev
        receiver: dev
        continue: true

    receivers:
    - name: 'default'
    - name: "thanos-pagerduty"
        entity_display_name: '{{ .CommonLabels.alertname }}'
        state_message: 'Alert: {{ .CommonLabels.alertname }}. Summary:{{ .CommonAnnotations.summary }}. RawData: {{ .CommonLabels }}'
        pagerduty_configs:
          - routing_key: 9b97b3029b984500c07a992165d66
            send_resolved: true

    


    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.15.3
        args:
          - '--config.file=/etc/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: alertmanager
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
```

**Full logs to relevant components**:
level=warn ts=2023-11-03T12:29:21.018268824Z caller=manager.go:525 component=rules group=metamonitoring msg="Evaluating rule failed" rule="alert: KubeDeploymentReplicasMismatch\nexpr: (kube_deployment_spec_replicas{cluster=~\".*\",job=~\".*\",namespace=~\".*\"} > kube_deployment_status_replicas_available{cluster=~\".*\",job=~\".*\",namespace=~\".*\"})\n  and (changes(kube_deployment_status_replicas_updated{cluster=~\".*\",job=~\".*\",namespace=~\".*\"}[10m])\n  == 0)\nfor: 15m\nlabels:\n  cluster: test\n  severity: warning\nannotations:\n  description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not\n    matched the expected number of replicas for longer than 15 minutes.\n  runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubedeploymentreplicasmismatch\n  summary: Deployment has not matched the expected number of replicas.\n" err="no query peer reachable"
level=debug ts=2023-11-03T12:29:35.971417743Z caller=promclient.go:304 msg="querying instant" url="http://http:/10.15.1.217:10901/api/v1/query?dedup=true&partial_response=false&query=sum+by%28job%2C+cluster%29+%28up%7Bcluster%3D%22dev%22%2Ccluster%3D%22test%22%2Cinstance%3D~%22.%2A%3A9090%22%2Cjob%3D%22kubernetes-service-endpoints%22%7D%29+%3C+3&time=2023-11-03T12%3A29%3A35.971064203Z"
level=error ts=2023-11-03T12:29:35.979459344Z caller=rule.go:775 err="perform GET request against http://http:/10.15.1.217:10901/api/v1/query?dedup=true&partial_response=false&query=sum+by%28job%2C+cluster%29+%28up%7Bcluster%3D%22dev%22%2Ccluster%3D%22test%22%2Cinstance%3D~%22.%2A%3A9090%22%2Cjob%3D%22kubernetes-service-endpoints%22%7D%29+%3C+3&time=2023-11-03T12%3A29%3A35.971064203Z: Get http://http/10.15.1.217:10901/api/v1/query?dedup=true&partial_response=false&query=sum+by%28job%2C+cluster%29+%28up%7Bcluster%3D%22dev%22%2Ccluster%3D%22test%22%2Cinstance%3D~%22.%2A%3A9090%22%2Cjob%3D%22kubernetes-service-endpoints%22%7D%29+%3C+3&time=2023-11-03T12%3A29%3A35.971064203Z: dial tcp: lookup http on 172.20.0.10:53: no such host" query="sum by(job, cluster) (up{cluster=\"dev\",cluster=\"test\",instance=~\".*:9090\",job=\"kubernetes-service-endpoints\"}) < 3"

we need help that how we can get alerts from test clusters but we are getting alerts from env dev which is self hosted thanos components, we are stucked in thanos-ruler, please help us to get out from this issue.
