### ISSUE TITLE
Ruler: Implement flag for max-source-resolution in the rule query

### ISSUE THREAD

**Issue by KingRebo38** [thanos-io/thanos#7077]
### Is your proposal related to a problem?
My feature request is related to the following bug ticket: https://github.com/thanos-io/thanos/issues/7070

After further investigation I came to the conclusion that the setting **max_source_resolution** in the http request is the solution.
The ruler, as it stands now, only calculates data using auto downsampling. This is an issue, as the querier then only uses raw data for calculating rules. As I want to calculate metrics aggregated across a long time period this becomes a problem, since my raw data only exists for 7 days. 
For example with the following query: increase(kong_http_requests_total[14d])
The ruler will only be able to calculate the last 7 days instead.

### Describe the solution you'd like

The solution I found was setting max_source_resolution=5m. This will force the querier to use the downsampled data which allows the ruler to get all data it needs for the aggregation.

I tested this by setting MaxSourceResolution manually in the code of the ruler and creating my own image:

```go
	v, warns, err := promClient.PromqlQueryInstant(ctx, endpoints[i], qs, t, promclient.QueryOptions{
		Deduplicate:             true,
		PartialResponseStrategy: partialResponseStrategy,
		Method:                  httpMethod,
		DoNotAddThanosParams:    doNotAddThanosParams,
		MaxSourceResolution:     "5m", // this would need to be retrieved by a flag

```
The flag could be something like: --query.max-source-resolution

After this is implemented, I am expecting to see my requests calculated like this:
![image](https://github.com/thanos-io/thanos/assets/60069080/a091afeb-ad51-4f6b-90a6-bf564ae692c5)

Ignore the gaps please. As you can see, the metric is calculated correctly again, before the switch we made.

For more context, please read the bug ticket.

**Comment by yeya24** [comment]
@KingRebo38 What's the query are you running in Ruler?
We are thinking about detecting the resolution rather than setting up the flag manually.
A ruler instance level flag might not work well if you have other rules which don't need 5m resolution

**Comment by KingRebo38** [comment]
@yeya24 The Queries are something like this:

```yaml
rules:
  - expr: increase(kong_http_requests_total[14d])
    record: kong_http_requests_total:rate:14d
  - expr: increase(kong_http_requests_total[30d])
    record: kong_http_requests_total:rate:30d
    ...
    and so on
```
I also think the instance level flag might cause some issues, but for now I would solve it by sharding the ruler instances.

**Comment by douglascamata** [comment]
@KingRebo38 you can optimize these rules by reusing data from others.

```yaml
rules:
  - expr: increase(kong_http_requests_total[1d])
    record: kong_http_requests_total:rate:1d
  - expr: sum_over_time(kong_http_requests_total:rate:1d[14d]) # sum the 1d-rate over 14d
    record: kong_http_requests_total:rate:14d
  - expr: sum_over_time(kong_http_requests_total:rate:1d[28d]) # sum the 1d-rate over 28d
    record: kong_http_requests_total:rate:28d
```

With this you basically have your own downsampling. As long as they are part of the same rule group, evaluation order is respected.
