### ISSUE TITLE
prometheus-thanos-sidecar helm chart has incorrect volume mounts, pods error on startup

### ISSUE THREAD

**Issue by danfinn** [thanos-io/thanos#7212]
I'm attempting to install the thanos sidecar with the following helm command taken from the thanos docs:

```
helm upgrade --version="25.11.0" --install --namespace="prometheus" --values /tmp/thanos_values.yml  prometheus-thanos-sidecar prometheus-community/prometheus
```

and here's my values file:

```
rbac:
  create: true

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

initChownData:
  resources:
    limits:
      memory: 16Mi
      cpu: 50m
    requests:
      memory: 16Mi
      cpu: 50m

server:
  extraArgs:
    log.level: debug
    storage.tsdb.min-block-duration: 2h # Don't change this, see docs/components/sidecar.md
    storage.tsdb.max-block-duration: 2h # Don't change this, see docs/components/sidecar.md
  retention: 4h
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  statefulSet:
    enabled: true
  nodeSelector:
    kubernetes.io/os: linux
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10902"
  sidecarContainers:
    thanos-sidecar:
      image: quay.io/thanos/thanos:v0.34.0
      resources:
        requests:
          memory: "512Mi"
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secret/sa
      args:
        - "sidecar"
        - "--log.level=debug"
        - "--tsdb.path=/data/"
        - "--prometheus.url=http://127.0.0.1:9090"
        - "--objstore.config={type:AZURE, config:{storage_account:'storage_account_name',storage_account_key:'storage_account_key,container:'thanos',endpoint: 'https://storage_account_name.blob.core.windows.net/',max_retries: 0}}"
        - "--reloader.config-file=/etc/prometheus-config/prometheus.yml"
        - "--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml"
        - "--reloader.rule-dir=/etc/prometheus-config/rules"
      ports:
        - name: sidecar-http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
      volumeMounts:
        - name: storage-volume
          mountPath: /data
#        - name: thanos-storage-secret
#          mountPath: /etc/secret
        - name: config-volume
          mountPath: /etc/prometheus-config
          readOnly: false
        - name: prometheus-config-shared
          mountPath: /etc/prometheus-shared/
          readOnly: false
  configPath: /etc/prometheus-shared/prometheus.yml
  replicaCount: 1
  persistentVolume:
    size: 20Gi
  extraVolumes: # spec.template.spec.volumes
    - name: prometheus-config-shared
      emptyDir: {}
  extraVolumeMounts: # spec.template.spec.containers.volumeMounts for prometheus container
    - name: prometheus-config-shared
      mountPath: /etc/prometheus-shared/
  resources:
    requests:
      memory: 1Gi
  global:
    scrape_interval: 5s
    scrape_timeout: 4s
    external_labels:
      prometheus_group: platdev2-cust-eastus
      prometheus_replica: '$(HOSTNAME)'
    evaluation_interval: 5s
#  extraSecretMounts:
#    - name: thanos-storage-secret
#      mountPath: /etc/secret/
#      subPath: sa
#      readOnly: false
#      secretName: thanos-storage-secret

# as thanos sidecar is taking care of the config reload
# we can disable the prometheus configmap reload
configmapReload:
  prometheus:
    enabled: false

serverFiles:
  alerts: {}
  rules: {}
```

This leads to the pod crashing because the prometheus.yml file doesn't exist:
ts=2024-03-14T18:42:44.592Z caller=main.go:492 level=error msg="Error loading config (--config.file=/etc/prometheus-shared/prometheus.yml)" file=/etc/prometheus-shared/prometheus.yml err="open /etc/prometheus-shared/prometheus.yml: no such file or directory"

Upon further investigation it's because the helm chart is using:

```
Volumes:
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  storage-volume-prometheus-thanos-sidecar-server-0
    ReadOnly:   false
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-thanos-sidecar-server
    Optional:  false
  prometheus-config-shared:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```
and

```
    Mounts:
      /data from storage-volume (rw)
      /etc/prometheus-config from config-volume (rw)
      /etc/prometheus-shared/ from prometheus-config-shared (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-msbr5 (ro)
```

it's looking for /etc/prometheus-shared/prometheus.yml however this is an EmptyDir.  The config files it actually is looking for are on the config-volume volume.

**Object Storage Provider**:
Azure

**What happened**:
helm chart doesn't work out of the box

**What you expected to happen**:
helm chart to work

**How to reproduce it (as minimally and precisely as possible)**:
helm install command given above
