### ISSUE TITLE
Thanos compactor "--min-time" parameter not working

### ISSUE THREAD

**Issue by paibok** [thanos-io/thanos#7226]
**Thanos, Prometheus and Golang version used**: 
Setup is through Docker:
prom/prometheus:v2.40.0
quay.io/thanos/thanos:v0.30.2

**Object Storage Provider**: minio/minio:RELEASE.2022-03-08T22-28-51Z

**What happened**: When the --min-time parameter is set in the Thanos compactor configuration, the compactor ceases to compact blocks. Without this parameter, the process works correctly.

**What you expected to happen**: I expect the Thanos compactor to compact blocks older than the --min-time parameter and ignore blocks that are newer.

**How to reproduce it (as minimally and precisely as possible)**: 
Compactor configuration : 
```yaml
    thanos-compactor:
        image: quay.io/thanos/thanos:v0.30.2
        depends_on:
            - minio
        volumes:
            - ./bucket/:/etc/thanos/
        command:
            - 'compact'
            - '--log.level=debug'
            - '--data-dir=/data'
            - '--objstore.config-file=/etc/thanos/bucket.yaml'
            - '--wait'
            - '--compact.progress-interval=5m'
            - '--retention.resolution-1h=365d'
            - '--retention.resolution-5m=90d'
            - '--retention.resolution-raw=30d'
            - '--min-time=72h' 
```

**Full logs to relevant components**: The logs do not indicate any errors, and everything appears to be functioning properly

<details>
  <summary>Logs compactor</summary>

```bash
level=info ts=2024-03-23T10:29:47.512668389Z caller=clean.go:34 msg="started cleaning of aborted partial uploads"
level=info ts=2024-03-23T10:29:47.512677819Z caller=clean.go:61 msg="cleaning of aborted partial uploads done"
level=info ts=2024-03-23T10:29:47.512684135Z caller=blocks_cleaner.go:44 msg="started cleaning of blocks marked for deletion"
level=info ts=2024-03-23T10:29:47.512690582Z caller=blocks_cleaner.go:58 msg="cleaning of blocks marked for deletion done"
level=debug ts=2024-03-23T10:29:47.512747739Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:29:47.721303971Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=208.600787ms duration_ms=208 cached=309 returned=0 partial=0
level=debug ts=2024-03-23T10:29:47.721409245Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:29:47.910771779Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=189.394166ms duration_ms=189 cached=309 returned=0 partial=0
level=info ts=2024-03-23T10:29:47.910831976Z caller=compact.go:1296 msg="start of GC"
level=info ts=2024-03-23T10:29:47.910856722Z caller=compact.go:1319 msg="start of compactions"
level=info ts=2024-03-23T10:29:47.910873232Z caller=compact.go:1355 msg="compaction iterations done"
level=info ts=2024-03-23T10:29:47.910924179Z caller=compact.go:430 msg="start first pass of downsampling"
level=debug ts=2024-03-23T10:29:47.911541344Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:29:48.133189349Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=222.250079ms duration_ms=222 cached=309 returned=0 partial=0
level=debug ts=2024-03-23T10:29:48.142741763Z caller=downsample.go:246 msg="downsampling bucket" concurrency=1
level=info ts=2024-03-23T10:29:48.143775863Z caller=compact.go:444 msg="start second pass of downsampling"
level=debug ts=2024-03-23T10:29:48.144135168Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:29:48.3947034Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=88.303806ms duration_ms=88 cached=309 returned=309 partial=0
level=info ts=2024-03-23T10:29:48.394872187Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=250.964692ms duration_ms=250 cached=309 returned=0 partial=0
level=debug ts=2024-03-23T10:29:48.395112946Z caller=downsample.go:246 msg="downsampling bucket" concurrency=1
level=info ts=2024-03-23T10:29:48.39520716Z caller=compact.go:451 msg="downsampling iterations done"
level=debug ts=2024-03-23T10:29:48.395265754Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:29:48.615708042Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=220.478927ms duration_ms=220 cached=309 returned=0 partial=0
level=info ts=2024-03-23T10:29:48.615763224Z caller=retention.go:32 msg="start optional retention"
level=info ts=2024-03-23T10:29:48.615773839Z caller=retention.go:47 msg="optional retention apply done"
level=debug ts=2024-03-23T10:29:48.615937174Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:29:48.833257585Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=217.470741ms duration_ms=217 cached=309 returned=0 partial=0
level=info ts=2024-03-23T10:29:48.833292367Z caller=clean.go:34 msg="started cleaning of aborted partial uploads"
level=info ts=2024-03-23T10:29:48.833303085Z caller=clean.go:61 msg="cleaning of aborted partial uploads done"
level=info ts=2024-03-23T10:29:48.833311463Z caller=blocks_cleaner.go:44 msg="started cleaning of blocks marked for deletion"
level=info ts=2024-03-23T10:29:48.833319626Z caller=blocks_cleaner.go:58 msg="cleaning of blocks marked for deletion done"
level=debug ts=2024-03-23T10:30:48.306423156Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:30:48.581950208Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=275.641898ms duration_ms=275 cached=309 returned=309 partial=0
level=debug ts=2024-03-23T10:31:48.306899012Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:31:48.534477665Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=227.624494ms duration_ms=227 cached=309 returned=309 partial=0
level=debug ts=2024-03-23T10:32:48.307060776Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
level=info ts=2024-03-23T10:32:48.536610341Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=229.599158ms duration_ms=229 cached=309 returned=309 partial=0
```

</details>

**Anything else we need to know**: The system works well except for this parameter, which appears to be buggy. According to the documentation, the --min-time parameter can be either positive or negative. When set to a positive value, the compactor does not compact at all, whereas a negative value causes it to compact all blocks, including those newer than the parameter value. Could you please clarify the purpose of having both positive and negative values for this parameter?

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`): Linux xxx-01 6.5.0-1015-aws #15~22.04.1-Ubuntu SMP Tue Feb 20 20:12:08 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yeya24** [comment]
Your usecase is for the Compactor to compact blocks created after 72h, correct? Based on your expectation, I think you should set `max-time` rather than `min-time`.

`min-time` is to compact blocks created within than a time window.

**Comment by paibok** [comment]
Hi @yeya24 , 

Thanks for your answer. 

Actually, I'm currently working on a setup where I intend to retain only raw data for the first 30 days and then use the compactor to downgrade the data. I envisioned the following configuration for this purpose:

```yaml
    thanos-compactor:
        image: quay.io/thanos/thanos:v0.30.2
        depends_on:
            - minio
        volumes:
            - ./bucket/:/etc/thanos/
        command:
            - 'compact'
            - '--log.level=debug'
            - '--data-dir=/data'
            - '--objstore.config-file=/etc/thanos/bucket.yaml'
            - '--wait'
            - '--compact.progress-interval=5m'
            - '--retention.resolution-1h=365d'
            - '--retention.resolution-5m=90d'
            - '--retention.resolution-raw=30d'
            - '--min-time=29d' 
```

For now, I'm just testing if the `--min-time` parameter works as expected. 

According to the thanos documentation : 

```
      --min-time=0000-01-01T00:00:00Z
                                Start of time range limit to compact.
                                Thanos Compactor will compact only blocks, which
                                happened later than this value. Option can be a
                                constant time in RFC3339 format or time duration
                                relative to current time, such as -1d or 2h45m.
                                Valid duration units are ms, s, m, h, d, w, y.
```

It appears I may have misunderstood the purpose of this parameter. To clarify, does "later" in this context imply a range from the current time up to 72 hours ago? If this interpretation is correct, why aren't my newer blocks (those younger than 72 hours) being compacted from 2-hour blocks to 4-hour/8-hour blocks, etc.?

Here a screenshot of my bucket blocks : 

![image](https://github.com/thanos-io/thanos/assets/100768303/8d4cad04-e8ff-4451-adf8-1745cf227b6c)
