### ISSUE TITLE
Instance Principal Provider - Region issue

### ISSUE THREAD

**Issue by saracm93** [thanos-io/thanos#7300]
Hi, it looks like with OCI Instance Principal we are not able to select the region.

example: 
```
type: OCI
config:
  provider: "instance-principal"
  bucket: ""
  region: "ap-melbourne-1"
  compartment_ocid: ""
```

this only works with the region where the server is.
Is there a workaround on this?
