### ISSUE TITLE
Unauthorized errors for some endpoints with query-frontend

### ISSUE THREAD

**Issue by lennartack** [thanos-io/thanos#7325]
**What happened**:
I have configured Thanos with HTTP basic authentication using the Bitnami Helm chart. The querier HTTP API works as expected. Some endpoints also work in query-frontend, but requests to `query-frontend/api/v1/query` give 401 Unauthorized. I have configured `--query-frontend.forward-header="Authorization"` as described [here](https://thanos.io/tip/components/query-frontend.md/#forward-headers-to-downstream-queriers).

Relevant portion of values.yaml:
```yaml
queryFrontend:
  logFormat: json

  extraFlags:
  - --query-frontend.forward-header="Authorization"

auth:
  basicAuthUsers:
    user: pass
```

query-frontend container args:
```yaml
  - args:
    - query-frontend
    - --log.level=info
    - --log.format=json
    - --http-address=0.0.0.0:9090
    - --query-frontend.downstream-url=http://thanos-query:9090
    - --http.config=/conf/http/http-config.yml
    - --query-frontend.forward-header="Authorization"
```

query container args:
```yaml
  - args:
    - query
    - --log.level=info
    - --log.format=json
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --http.config=/conf/http/http-config.yml
    - --query.replica-label=replica
```

**How to reproduce it (as minimally and precisely as possible)**:
Install the Bitnami Thanos chart version 15.4.1 with basic HTTP authentication.
