### ISSUE TITLE
Thanos Receive Pod is crashing with Readiness and livness Probe Failed

### ISSUE THREAD

**Issue by ashishstationcasinos** [thanos-io/thanos#7374]
Hello Team,

I have Deployed, Thanos onto the AKS Cluster Using Helm Chart with Below Values.yaml file.

I am Implementing Thanos Remote Write using Below Configuration using Azure Blob Storage As Object Storage

```
receive:
  enabled: true
  containerPorts:
    remote: 10908
  service:
    ports:
      remote: 10908
  logLevel: debug
  resources:
    limits:
      memory: 8Gi
      cpu: 4000m
    requests:
      memory: 4Gi
      cpu: 2000m
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
  autoscaling:
    enabled: false
query:
  enabled: true
  replicas: 2
storegateway:
  enabled: true
  logLevel: debug
  replicas: 2
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    timeoutSeconds: 30
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
```
Used the Below Command to Deploy `Thanos` on the cluster

helm upgrade --install thanos --create-namespace -n thanos  --set existingObjstoreSecret=objstore  oci://registry-1.docker.io/bitnamicharts/thanos -f ~/Values.yaml

 After the Helm Chart Deployment Sucess

 I see the `thanos-store` is Able to Up and Running which is Able to Connect to Blob Storage. 

But the `Thanos-receive` Pod is Crashing with Below Error

```
ts=2024-05-20T13:21:15.780557429Z caller=main.go:145 level=error err="Get \"https://telemetricssa.blob.core.windows.net/cortex?restype=container\": dial tcp: lookup telemetricssa.blob.core.windows.net: i/o timeout\ncreate AZURE client\ngithub.com/thanos-io/objstore/client.NewBucket\n\t/bitnami/blacksmith-sandox/thanos-0.35.0/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20240309075357-e8336a5fd5f3/client/factory.go:90\nmain.runReceive\n\t/bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/receive.go:182\nmain.registerReceive.func1\n\t/bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/receive.go:102\nmain.main\n\t/bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/main.go:143\nruntime.main\n\t/opt/bitnami/go/src/runtime/proc.go:267\nruntime.goexit\n\t/opt/bitnami/go/src/runtime/asm_amd64.s:1650\npreparing receive command failed\nmain.main\n\t/bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/main.go:145\nruntime.main\n\t/opt/bitnami/go/src/runtime/proc.go:267\nruntime.goexit\n\t/opt/bitnami/go/src/runtime/asm_amd64.s:1650"
```

Later, Thanos-store Pod Logs with Below error but not Crashing Frequently

```
ts=2024-05-20T14:09:34.564440275Z caller=fetcher.go:476 level=debug component=block.BaseFetcher msg="fetching meta data" concurrency=32
ts=2024-05-20T14:11:03.420411595Z caller=fetcher.go:626 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1m28.856214505s duration_ms=88856 cached=0 returned=0 partial=0
ts=2024-05-20T14:24:34.571593489Z caller=fetcher.go:476 level=debug component=block.BaseFetcher msg="fetching meta data" concurrency=32
ts=2024-05-20T14:26:43.930531964Z caller=store.go:477 level=warn msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://telemetricssa.blob.core.windows.net/cortex?comp=list&delimiter=%2F&prefix=&restype=container\": dial tcp: lookup telemetricssa.blob.core.windows.net: i/o timeout"
ts=2024-05-20T14:39:34.572459554Z caller=fetcher.go:476 level=debug component=block.BaseFetcher msg="fetching meta data" concurrency=32

```
I am not able to UnderStand What Could be the Issue. Seems like Network Connection issue But Not Sure Where to Troubleshoot the Issue.

FYI: 
1. AKS Cluster and Storage Account are in Same Region.
2. Storage Account is Configured such a way that Only the AKS Cluster Subnet can Acces it.

Please let me know How can I fix it ?
