### ISSUE TITLE
found duplicate storeEndpoints producer (sidecar or ruler)

### ISSUE THREAD

**Issue by danielstankw** [thanos-io/thanos#7482]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.35.1
Prometheus: v2.52.0

**Object Storage Provider**:
AWS S3 Bucket

**What happened**:
I have deployed promethus + sidecar using kube-prometheus-stack.
I have set for the main cluster:

```yaml
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: toolset
      env: dev
    replicas: 1
```

and for the slave cluster (one being monitored from the main one)

```yaml
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: vllmmodels
      env: dev
     replicas: 1
```
When checking the logs of the thanos query pod I obtain:
```
ts=2024-06-25T09:54:38.14722922Z caller=endpointset.go:453 level=warn component=endpointset msg="found duplicate storeEndpoints producer (sidecar or ruler). 
This is not advices as it will malform data in in the same bucket" address=10.137.127.43:10901 
extLset="{cluster=\"vllmmodels\", env=\"dev\", prometheus=\"monitoring/monitoring-kube-prometheus-prometheus\", prometheus_replica=\"prometheus-monitoring-kube-prometheus-prometheus-0\"}" duplicates=2
```

I can also see the duplication in the UI

![image](https://github.com/thanos-io/thanos/assets/72759092/c9d3d27a-cfbe-48be-96b0-07465f257f20)

I have set up the thanos-query-deployment.yaml

```yaml
      - args:
        - query
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --log.level=info
        - --log.format=logfmt
        - --query.replica-label=cluster
        - --endpoint=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local:10901
        - --endpoint=dnssrv+_grpc._tcp.thanos-receive-ingestor-default.monitoring.svc.cluster.local:10901
        - --endpoint=dnssrv+_grpc._tcp.monitoring-kube-prometheus-thanos-discovery.monitoring.svc.cluster.local:10901
```

**What you expected to happen**:
Not to get an error, see one endpoint per cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:
I have also tried to set in the querier labels such as env/ prometheus and prometheus_replica but that didnt solve my issue
