### ISSUE TITLE
thanos query  update of store node failed: initial store client info fetch

### ISSUE THREAD

**Issue by Mnbill** [thanos-io/thanos#749]

**Comment by Mnbill** [comment]
Hello,

I have the error on my thanos query: 

level=info ts=2019-01-17T11:45:24.145115867Z caller=storeset.go:226 component=storeset msg="adding new store to query storeset" address=10.14.2.36:10901

level=warn ts=2019-01-17T11:56:23.600979669Z caller=storeset.go:265 component=storeset msg="update of store node failed" err="fetching store info from 10.14.2.36:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.14.2.36:10901

level=info ts=2019-01-17T11:56:23.601144812Z caller=storeset.go:206 component=storeset msg="store unhealthy or does not exists, closed gRPC client and removed from storeset" address=10.14.2.36:10901

level=warn ts=2019-01-17T11:56:33.601897016Z caller=storeset.go:282 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.14.2.36:10901



**Environment**:
- prometheus v2.3.1
- thanos sidcare:v0.1.0-rc.1
- thanos query: v0.1.0

**Comment by Mnbill** [comment]
### My thanos query config

 containers:
      - name: thanos-query
        image: improbable/thanos:v0.1.0
        args:
        - "query"
        - "--log.level=debug"
        - "--query.replica-label=prometheus_replica"
        - "--cluster.peers=thanos-peers.monitoring.svc:10900"
        - "--selector-label=prometheus=\"monitoring/kube-prometheus\""
        - "--store=10.14.2.36:10901"
		

------------------------------------------
### My thanos sidecar config:

 sidecarsSpec:
  - name: thanos
    image: improbable/thanos:v0.1.0-rc.1
    args:
    - "sidecar"
    - "--log.level=debug"
    - "--tsdb.path=/prometheus"
    - "--cluster.peers=thanos-peers.monitoring.svc:10900"
    ports:
    - name: thanos-http
      containerPort: 10902
    - name: thanos-grpc
      containerPort: 10901
    - name: thanos-cluster
      containerPort: 10900


NB: I have a VPN connection between my thanos query and my sidecar

**Comment by FUSAKLA** [comment]
Hi, it looks like the address `10.14.2.36:10901` is timing out from the container of the query node.
try execing to the container of the query node and find out why you cannot reach the sidecar. 

This issue most probably won't be caused by the Thanos itself. Possibly give us more description of the environment? It's probably kubernetes? what is the IP? pod ip or service ip?

**Comment by bwplotka** [comment]
You set both `"--cluster.peers=thanos-peers.monitoring.svc:10900"` and `--store`. Are you sure you are not duplicating the store entry there? 

Also please upgrade your Thanos version as there were many fixes that might help debugging.

**Comment by Mnbill** [comment]
## kuebrnetes services: 
kubectl get svc -n monitor

thanos-sidecar-svc                    ClusterIP      10.0.131.172   <none>        10902/TCP         7d
thanos-sidecar-lb                     LoadBalancer   10.0.205.171   10.14.2.36    10901:31501/TCP   7d

NB: I can not upgrade thanos for now
       In thanos query i have  4 others  "--store" and it's work, i have just a problem with "--store=10.14.2.36:10901"

**Comment by Mnbill** [comment]
### Thanos query config

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
    thanos-peer: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peer: "true"
    spec:
      containers:
      - name: thanos-query
        image: improbable/thanos:v0.1.0
        args:
        - "query"
        - "--log.level=debug"
        - "--query.replica-label=prometheus_replica"
        - "--cluster.peers=thanos-peers.monitoring.svc:10900"
        - "--selector-label=prometheus=\"monitoring/kube-prometheus\""
        - "--store=10.3.0.40:10901"
        - "--store=10.14.2.36:10901"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  type: NodePort
  selector:
    app: thanos-query
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http-query
    nodePort: 31111

**Comment by Mnbill** [comment]
### Thanos query config
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
    thanos-peer: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peer: "true"
    spec:
      containers:
      - name: thanos-query
        image: improbable/thanos:v0.1.0
        args:
        - "query"
        - "--log.level=debug"
        - "--query.replica-label=prometheus_replica"
        - "--cluster.peers=thanos-peers.monitoring.svc:10900"
        - "--selector-label=prometheus=\"monitoring/kube-prometheus\""
        - "--store=10.3.0.40:10901"
        - "--store=10.14.2.36:10901"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  type: NodePort
  selector:
    app: thanos-query
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http-query
    nodePort: 31111
		
```
### Thanos sidecar config

sidecarsSpec:
  - name: thanos
    image: improbable/thanos:v0.1.0-rc.1
    args:
    - "sidecar"
    - "--log.level=debug"
    - "--tsdb.path=/prometheus"
    ports:
    - name: thanos-http
      containerPort: 10902
    - name: thanos-grpc
      containerPort: 10901
    - name: thanos-cluster
      containerPort: 10900
    
```
