### ISSUE TITLE
compactor: Fails cleaning blocks marked for deletion with Access Denied (solved)

### ISSUE THREAD

**Issue by pelzerim** [thanos-io/thanos#7497]
**Thanos, Prometheus and Golang version used**:

Tried both:
 ```
docker.io/bitnami/thanos:0.35.1-debian-12-r1
docker.io/thanosio/thanos:v0.36.0-rc.0
```

Thanos is deployed using the Bitnami helm chart. The compactor is deployed as a CronJob

**Object Storage Provider**: AWS S3

**What happened**:

Compactor is able to finish all previous steps but fails at deletion of blocks marked for deletion with an Access Denied error.

**What you expected to happen**: Deletion of blocks that are marked for deletion

**Full logs to relevant components**:

<details>Logs
<p>

```
thanos-compactor-manual-6v8v7 compactor ts=2024-07-01T09:57:56.515344877Z caller=blocks_cleaner.go:44 level=info msg="started cleaning of blocks marked for deletion"
thanos-compactor-manual-6v8v7 compactor ts=2024-07-01T09:57:56.526400652Z caller=intrumentation.go:67 level=warn msg="changing probe status" status=not-ready reason="cleaning marked blocks: delete block: delete 01J1AYPJ079SQG86D2HJ859JDV/meta.json: Access Denied"
thanos-compactor-manual-6v8v7 compactor ts=2024-07-01T09:57:56.52643412Z caller=http.go:91 level=info service=http/server component=compact msg="internal server is shutting down" err="cleaning marked blocks: delete block: delete 01J1AYPJ079SQG86D2HJ859JDV/meta.json: Access Denied"
thanos-compactor-manual-6v8v7 compactor ts=2024-07-01T09:57:56.526521439Z caller=http.go:110 level=info service=http/server component=compact msg="internal server is shutdown gracefully" err="cleaning marked blocks: delete block: delete 01J1AYPJ079SQG86D2HJ859JDV/meta.json: Access Denied"
thanos-compactor-manual-6v8v7 compactor ts=2024-07-01T09:57:56.526554563Z caller=intrumentation.go:81 level=info msg="changing probe status" status=not-healthy reason="cleaning marked blocks: delete block: delete 01J1AYPJ079SQG86D2HJ859JDV/meta.json: Access Denied"
thanos-compactor-manual-6v8v7 compactor ts=2024-07-01T09:57:56.526696027Z caller=main.go:171 level=error err="Access Denied\ndelete 01J1AYPJ079SQG86D2HJ859JDV/meta.json\ngithub.com/thanos-io/thanos/pkg/block.Delete\n\t/app/pkg/block/block.go:225\ngithub.com/thanos-io/thanos/pkg/compact.(*BlocksCleaner).DeleteMarkedBlocks\n\t/app/pkg/compact/blocks_cleaner.go:49\nmain.runCompact.func6\n\t/app/cmd/thanos/compact.go:437\nmain.runCompact.func7\n\t/app/cmd/thanos/compact.go:520\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:527\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197\ndelete block\ngithub.com/thanos-io/thanos/pkg/compact.(*BlocksCleaner).DeleteMarkedBlocks\n\t/app/pkg/compact/blocks_cleaner.go:51\nmain.runCompact.func6\n\t/app/cmd/thanos/compact.go:437\nmain.runCompact.func7\n\t/app/cmd/thanos/compact.go:520\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:527\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197\ncleaning marked blocks\nmain.runCompact.func6\n\t/app/cmd/thanos/compact.go:438\nmain.runCompact.func7\n\t/app/cmd/thanos/compact.go:520\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:527\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197\ncompact command failed\nmain.main\n\t/app/cmd/thanos/main.go:171\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197"
```

</p>
</details>

**Anything else we need to know**:

This is the configuration of the CronJob:

```
          - args:
            - compact
            - --log.level=info
            - --log.format=logfmt
            - --http-address=0.0.0.0:10902
            - --data-dir=/data
            - --retention.resolution-raw=0d
            - --retention.resolution-5m=0d
            - --retention.resolution-1h=0d
            - --consistency-delay=30m
            - |
              --objstore.config=type: s3
              config:
                bucket: ****
                endpoint: ****
                aws_sdk_auth: true
                region: eu-west-1
            - --compact.concurrency=3
            - --downsample.concurrency=3
            - --compact.enable-vertical-compaction
            - --deduplication.replica-label="replica"
```

The cronjob has a service account attached to it that has these IAM roles:

```
{

    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement",
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": [
                "arn:aws:s3:::${local.thanos_name}/*",
                "arn:aws:s3:::${local.thanos_name}"
            ]
        }
    ]
}
```

Everything works fine for the receive and store-gateway components.

[edit]

Found the issue myself. Still creating this ticket so maybe someone else can save themselves 2 days:

I was missing the Service Account annotation that attaches the AMI role to the Service account for the component in the bitnami helm chart. I had read permissions from another unrelated role to S3 so all other components worked.

```
...
compactor:
  ...
  serviceAccount:
    annotations:
      "eks.amazonaws.com/role-arn": ${s3_role_arn}
```
