### ISSUE TITLE
 The result of "Use Deduplication" is not as expected

### ISSUE THREAD

**Issue by debuggedme** [thanos-io/thanos#7586]
**Thanos, Prometheus and Golang version used**:

Thanos: thanos:0.32.5-debian-11-r2

Prometheus: prometheus:2.43.0-debian-11-r2

Golang: Not involved.

**Object Storage Provider**:

 Not involved.

**What happened**:

In the Thanos documentation for query deduplication, it is mentioned that duplicates with the replica label "replica: A" will be removed from the query results.

https://thanos.io/v0.32/components/query.md/#deduplication    

In fact, I have deployed two Prometheus replicas, and their default external labels are `prometheus_replica: prometheus-prometheus-0` and `prometheus_replica: prometheus-prometheus-1`. It can be seen that the values of their `prometheus_replica` labels are different, so according to the documentation, they should not be deduplicated.

However, when I select "Use Deduplication," they are deduplicated anyway. Why is this happening, and has any special processing been applied?

**What you expected to happen**:

 they should not be deduplicated.

**How to reproduce it (as minimally and precisely as possible)**:

easy to reproduce.

Prometheus Helm deployment file.

```yaml
## Deploy a Prometheus instance
##
prometheus:
  ## @param prometheus.replicaCount Number of Prometheus replicas desired
  ##
  replicaCount: 2
```

Thanos Helm deployment file.

```yaml
## @section Thanos Query parameters

query:
  ## @param query.enabled Set to true to enable Thanos Query component
  ##
  enabled: true
  ## @param query.replicaCount Number of Thanos Query replicas to deploy
  ##
  replicaCount: 1
  ## @param query.replicaLabel Replica indicator(s) along which data is de-duplicated
  ##
  replicaLabel:
    - prometheus_replica
```

example promql:

```
up{namespace="test"} - without Use Deduplication
---
up{ ...prometheus_replica="prometheus-prometheus-0"} 1
up{ ...prometheus_replica="prometheus-prometheus-1"} 1

up{namespace="test"} - with Use Deduplication
---
up{ ...} 1
```

**Full logs to relevant components**:

 Not involved.

**Anything else we need to know**:

I tried to add an additional external label `region: us` and then specify deduplication based on the `region` label, but it didn't take effect and only the `region` label was removed from the query results.

```
up{namespace="test"} - without Use Deduplication
---
up{ ...prometheus_replica="prometheus-prometheus-0", region="us"} 1
up{ ...prometheus_replica="prometheus-prometheus-1", region="us"} 1

up{namespace="test"} - with Use Deduplication
---
up{ ...prometheus_replica="prometheus-prometheus-0"} 1
up{ ...prometheus_replica="prometheus-prometheus-1"} 1
```

I'm not sure if this is expected; at least according to the documentation's expectation, the result is completely opposite.

> I couldn't find any information in the documentation about whether Thanos supports Prometheus sharding. If there is relevant information, please point it out.

**Comment by MichaHoffmann** [comment]
Can you bump Thanos? I think the 0.32 version has had deduplication issues. Can you also check versions of all involved Thanos components really quick?

**Comment by debuggedme** [comment]
> Can you bump Thanos? I think the 0.32 version has had deduplication issues. Can you also check versions of all involved Thanos components really quick?

Sure, but I see that the 0.32 release mentions some deduplication issues was fixed. That's why I used this version.

The sidecar component of Prometheus and the query component of Thanos both use the image bitnami/thanos:0.32.5-debian-11-r2.

**Comment by MichaHoffmann** [comment]
Can you check configuration and share the config flags of the querier please?

**Comment by debuggedme** [comment]
https://github.com/thanos-io/thanos/issues/7586#issuecomment-2264919826

query: 

```yaml
  - args:
    - query
    - --log.level=info
    - --log.format=logfmt
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --query.replica-label=cluster
    - --endpoint=dnssrv+kp-prometheus-thanos:10901
    image: bitnami/thanos:0.34.1-debian-12-r3
```

sidecar: 

```yaml
  - args:
    - sidecar
    - --prometheus.url=http://localhost:9090
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --tsdb.path=/prometheus/
    - --objstore.config=$(OBJSTORE_CONFIG)
    image: bitnami/thanos:0.34.1-debian-12-r3
```

query result:

```
up{namespace="test"} - without Use Deduplication
---
up{ ...prometheus_replica="prometheus-prometheus-0"} 1
up{ ...prometheus_replica="prometheus-prometheus-1"} 1

up{namespace="test"} - with Use Deduplication
---
up{ ...} 1
```

Expected results, as their prometheus_replica are different.

```
up{namespace="test"} - without Use Deduplication
---
up{ ...prometheus_replica="prometheus-prometheus-0"} 1
up{ ...prometheus_replica="prometheus-prometheus-1"} 1

up{namespace="test"} - with Use Deduplication
---
up{ ...prometheus_replica="prometheus-prometheus-0"} 1
up{ ...prometheus_replica="prometheus-prometheus-1"} 1
```
