### ISSUE TITLE
Thanos plus Memcached Losing Metrics

### ISSUE THREAD

**Issue by antikilahdjs** [thanos-io/thanos#7662]
Thanos Store and Frontend with Memcached enabled

**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**: S3 MiniO

**What happened**:

I am using Thanos a long time ago but few days ago I needed configured the Memcached to accelerate my Queries so, the Memcached worked good but I do not know what I need to do to works as expected in my environment. I am losing some days of metrics as the screenshot below . The error show the connection refused but it just getting it after configured the Memcached.

![image](https://github.com/user-attachments/assets/eba6f238-fbd9-42d4-a347-6efb3efb8ba0)

![image](https://github.com/user-attachments/assets/6d1323da-1f29-45ea-8408-700fc2d86a2d)

![image](https://github.com/user-attachments/assets/c21b4497-698e-4c86-b945-9e0ee8fbd9a0)

My Thanos Store:

```yaml
args:
            - store
            - '--log.level=info'
            - '--log.format=logfmt'
            - '--data-dir=/var/thanos/store'
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:10902'
            - '--objstore.config=$(OBJSTORE_CONFIG)'
            - '--ignore-deletion-marks-delay=24h'
            - '--block-sync-concurrency=120'
            - '--sync-block-duration=60m'
            - '--index-cache-size=4096MB'
            - '--chunk-pool-size=4GB'
            - '--store.grpc.series-max-concurrency=300'
            - '--consistency-delay=30m'
            - |-
              --index-cache.config="config":
                "addresses":
                - "thanos-memcached-service.thanos:11211"
                "dns_provider_update_interval": "60s"
                "max_async_buffer_size": 0
                "max_async_concurrency": 1000
                "max_get_multi_batch_size": 0
                "max_get_multi_concurrency": 0
                "max_idle_connections": 400
                "max_item_size": 0
                "timeout": "180s"
              "type": "MEMCACHED"
            - |-
              --store.caching-bucket.config="blocks_iter_ttl": "720h"
              "chunk_object_attrs_ttl": "720h"
              "chunk_subrange_size": 128000
              "chunk_subrange_ttl": "720h"
              "config":
                "addresses":
                - "thanos-memcached-service.thanos:11211"
                "dns_provider_update_interval": "60s"
                "max_async_buffer_size": 0
                "max_async_concurrency": 1000
                "max_get_multi_batch_size": 0
                "max_get_multi_concurrency": 0
                "max_idle_connections": 400
                "max_item_size": 0
                "timeout": "180s"
              "max_chunks_get_range_requests": 3
              "metafile_content_ttl": "720h"
              "metafile_doesnt_exist_ttl": "1h"
              "metafile_exists_ttl": "720h"
              "metafile_max_size": "4MiB"
              "type": "MEMCACHED"
            - |-
              --tracing.config="config":
                "sampler_param": 2
                "sampler_type": "ratelimiting"
                "service_name": "thanos-store"
              "type": "JAEGER"
```

My Thanos Frontend 

```yaml
args:
            - query-frontend
            - '--enable-auto-gomemlimit'
            - '--log.level=info'
            - '--log.format=logfmt'
            - '--query-frontend.compress-responses'
            - '--http-address=0.0.0.0:9090'
            - >-
              --query-frontend.downstream-url=http://thanos-query.thanos.svc.cluster.local.:9090
            - '--query-range.split-interval=24h'
            - '--labels.split-interval=12h'
            - '--query-range.max-retries-per-request=100'
            - '--labels.max-retries-per-request=25'
            - '--query-frontend.log-queries-longer-than=0'
            - '--query-range.max-query-parallelism=120'
            - '--query-frontend.vertical-shards=0'
            - '--cache-compression-type='
            - '--query-frontend.downstream-tripper-config={"response_header_timeout": "5m", "max_idle_conns_per_host": 100}'
            - |-
              --query-range.response-cache-config="config":
                "addresses":
                - "thanos-memcached-service.thanos:11211"
                "dns_provider_update_interval": "30s"
                "max_async_buffer_size": 0
                "max_async_concurrency": 1000
                "max_get_multi_batch_size": 0
                "max_get_multi_concurrency": 0
                "max_idle_connections": 400
                "timeout": "180s"
                "expiration": "720h"
              "type": "MEMCACHED"
            - |-
              --labels.response-cache-config="config":
                "addresses":
                - "thanos-memcached-service.thanos:11211"
                "dns_provider_update_interval": "30s"
                "max_async_buffer_size": 0
                "max_async_concurrency": 1000
                "max_get_multi_batch_size": 0
                "max_get_multi_concurrency": 0
                "max_idle_connections": 400
                "timeout": "180s"
                "expiration": "720h"
              "type": "MEMCACHED"
            - |-
              --tracing.config="config":
                "sampler_param": 2
                "sampler_type": "ratelimiting"
                "service_name": "thanos-query-frontend"
              "type": "JAEGER"
```

My Prometheus:
```yaml 
containers:
    - args:
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--storage.tsdb.retention.time=12h'
        - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.enable-lifecycle'
        - '--web.enable-admin-api'
        - '--web.route-prefix=/'
        - '--web.config.file=/etc/prometheus/web_config/web-config.yaml'
        - '--storage.tsdb.max-block-duration=2h'
        - '--storage.tsdb.min-block-duration=2h'
        - '--web.max-connections=8096'
        - '--query.max-concurrency=60'
      image: 'prom/prometheus:v2.49.1'
```

**What you expected to happen**:

Without Memcached I am never got the issues

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

MinTime: 1721260800000 MaxTime: 1724421600000: rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeoutreceive series from Addr: 10.233.67.48:10901 LabelSets: {prometheus="xxxxxx/k8s", prometheus_replica="prometheus-k8s-0"},{prometheus="xxxxxx/k8s", prometheus_replica="prometheus-k8s-1"},{prometheus="xxxxxx/k8s"} MinTime: 1721260800000 MaxTime: 1724421600000: rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout

ts=2024-08-23T14:22:35.111868542Z caller=fetcher.go:623 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=1.19977705s duration_ms=1199 cached=87 returned=33 partial=2083

 ts=2024-08-23T14:22:35.701658815Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=517.770078ms id=01J5F6QEAVPFQSJF99WMVF1P28

 ts=2024-08-23T14:22:35.880376354Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=718.93871ms id=01J5MBGXMCHQNZBAENA9VEH163

 ts=2024-08-23T14:22:35.929284654Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=667.488223ms id=01J5SGCGPWRE1DT6TF39QFFD6K

 ts=2024-08-23T14:22:38.508696903Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=3.347586275s id=01J5X9M3SQS2D3WD9M75CNC271

 ts=2024-08-23T14:22:38.513134865Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=3.353084516s id=01J5ZGAN50G77PPH6HJE0T7PYM

 ts=2024-08-23T14:22:38.955023356Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=3.79565693s id=01J5XGFZ55DN8T0S0G5PEX7Z0J

 ts=2024-08-23T14:22:38.95849031Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=3.846507786s id=01J46P6NMVV7NE7GF6ESBN5NDH

 ts=2024-08-23T14:22:39.004733611Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=3.845503448s id=01J5XGG35X9R9D2KYY8EC44E54

 ts=2024-08-23T14:22:39.009257165Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=3.748085925s id=01J5X9M7N0NHTY3WXYXSXRXHW3

 ts=2024-08-23T14:22:39.260003149Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.100917028s id=01J5Y5359DK8DRH83TEK4T3TSZ

 ts=2024-08-23T14:22:39.333829887Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.150977099s id=01J5ZQ1FX88BA4DF8Q8811K9NE

 ts=2024-08-23T14:22:39.39643751Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.236264459s id=01J5ZE9DHT89GH1VYVXCRC3BCQ

 ts=2024-08-23T14:22:39.436374245Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.220304406s id=01J5A3C9R2YQ83MDDVJXAAWVBK

 ts=2024-08-23T14:22:39.522475519Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.306773396s id=01J5Z7DR7PBMCWZ63S0K8SASTG

 ts=2024-08-23T14:22:39.833644576Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.572024229s id=01J5ZN5B5PS88SSY8VWDYRYQTH

 ts=2024-08-23T14:22:39.836240033Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.674924311s id=01J5XY7AGWTKADYEQJQBWPYMN5

 ts=2024-08-23T14:22:39.961414967Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.800418671s id=01J5Y52ZX49MRAZDZ84YMV7RW0

 ts=2024-08-23T14:22:39.979722724Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.79600352s id=01J5YBYW9EG9X291JWGJ0EBQPT

 ts=2024-08-23T14:22:40.057093938Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.897427936s id=01J5XY7GRTC861YB0GYJ19WDQD

 ts=2024-08-23T14:22:40.071035704Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.913035143s id=01J5ZG5VGDK664J8X36D511KCK

 ts=2024-08-23T14:22:40.159411691Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=4.998976245s id=01J5ZE9JEY26DAB1F3XQTBEJ5M

 ts=2024-08-23T14:22:40.19580908Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.012580745s id=01J5YJTPB8WHYFD7M1BJZMV85M

 ts=2024-08-23T14:22:40.322165086Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.163497453s id=01J5Z0J4A9WMQZ27W1F5YMDATT

 ts=2024-08-23T14:22:40.374610531Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.21388207s id=01J5YJTNZQ439G20B52BTP0DMN

 ts=2024-08-23T14:22:40.450863344Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.291353516s id=01J5Z0HXXN5S8N00PJDWT0FT5P

 ts=2024-08-23T14:22:40.639155009Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.479366356s id=01J5YSPB443VBJKHVGQKQM9EKW

 ts=2024-08-23T14:22:40.751516517Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.591593751s id=01J5XQC0D1JP8E31YYB4D4FFRX

 ts=2024-08-23T14:22:40.860038754Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.699729421s id=01J5YN3E85R11K5QSB52YBJEZ6

 ts=2024-08-23T14:22:40.869268304Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.708700016s id=01J5ZN54E5FGT6RDFXB723ETJH

 ts=2024-08-23T14:22:40.903112197Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.74420312s id=01J5YSP56JHAVBZ4M0R8HK4B4C

 ts=2024-08-23T14:22:41.020479857Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.859260997s id=01J5Z7DTNYK1RV821YBE0HQMQC

 ts=2024-08-23T14:22:41.029266458Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.84587168s id=01J5YBYTHR8XHWMPYAN45D7J60

 ts=2024-08-23T14:22:41.034084417Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=5.873211843s id=01J5XQBM7YD88SWDCHYECZJM4P

 ts=2024-08-23T14:22:41.03751064Z caller=store.go:480 level=info msg="bucket store ready" init_duration=7.125467728s

 ts=2024-08-23T14:22:41.037938328Z caller=intrumentation.go:56 level=info msg="changing probe status" status=ready

 ts=2024-08-23T14:22:41.038004629Z caller=grpc.go:167 level=info service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:10901

 ts=2024-08-23T14:22:41.58742154Z caller=fetcher.go:623 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=549.826909ms duration_ms=549 cached=24 returned=7 partial=2083

 ts=2024-08-23T14:22:41.935226691Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=347.298761ms id=01J5V6ZY4VEC7VC6E9NFNN07VX

 ts=2024-08-23T14:22:41.962098025Z caller=bucket.go:781 level=info msg="loaded new block" elapsed=374.554033ms id=01J5TBK92K85GMSMXWRH3K2MEB

 ts=2024-08-23T14:22:41.963613733Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5XY7AGWTKADYEQJQBWPYMN5

 ts=2024-08-23T14:22:41.966140569Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YSP56JHAVBZ4M0R8HK4B4C

 ts=2024-08-23T14:22:41.967219359Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZGAN50G77PPH6HJE0T7PYM

 ts=2024-08-23T14:22:41.968410031Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5Y5359DK8DRH83TEK4T3TSZ

 ts=2024-08-23T14:22:41.969625104Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZQ1FX88BA4DF8Q8811K9NE

 ts=2024-08-23T14:22:41.970870896Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZN5B5PS88SSY8VWDYRYQTH

 ts=2024-08-23T14:22:41.973417393Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZE9JEY26DAB1F3XQTBEJ5M

 ts=2024-08-23T14:22:41.97593133Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZN54E5FGT6RDFXB723ETJH

 ts=2024-08-23T14:22:41.977284694Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5XGG35X9R9D2KYY8EC44E54

 ts=2024-08-23T14:22:41.978898354Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5XY7GRTC861YB0GYJ19WDQD

 ts=2024-08-23T14:22:41.981680435Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5Z7DTNYK1RV821YBE0HQMQC

 ts=2024-08-23T14:22:41.984394885Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YBYTHR8XHWMPYAN45D7J60

 ts=2024-08-23T14:22:41.987280338Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YJTNZQ439G20B52BTP0DMN

 ts=2024-08-23T14:22:41.990184492Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5XQC0D1JP8E31YYB4D4FFRX

 ts=2024-08-23T14:22:41.991817812Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YBYW9EG9X291JWGJ0EBQPT

 ts=2024-08-23T14:22:41.994078593Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZG5VGDK664J8X36D511KCK

 ts=2024-08-23T14:22:41.996657391Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5Z0J4A9WMQZ27W1F5YMDATT

 ts=2024-08-23T14:22:42.001457179Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YN3E85R11K5QSB52YBJEZ6

 ts=2024-08-23T14:22:42.004114938Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5XQBM7YD88SWDCHYECZJM4P

 ts=2024-08-23T14:22:42.005437703Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5XGFZ55DN8T0S0G5PEX7Z0J

 ts=2024-08-23T14:22:42.006780007Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5ZE9DHT89GH1VYVXCRC3BCQ

 ts=2024-08-23T14:22:42.009231872Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YJTPB8WHYFD7M1BJZMV85M

 ts=2024-08-23T14:22:42.010561377Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5X9M3SQS2D3WD9M75CNC271

 ts=2024-08-23T14:22:42.014128292Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5YSPB443VBJKHVGQKQM9EKW

 ts=2024-08-23T14:22:42.015390426Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5X9M7N0NHTY3WXYXSXRXHW3

 ts=2024-08-23T14:22:42.016866513Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5Z7DR7PBMCWZ63S0K8SASTG

 ts=2024-08-23T14:22:42.018860699Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5Y52ZX49MRAZDZ84YMV7RW0

 ts=2024-08-23T14:22:42.021017199Z caller=bucket.go:703 level=info msg="dropped outdated block" block=01J5Z0HXXN5S8N00PJDWT0FT5P

**Anything else we need to know**:

ts=2024-08-22T04:15:02.506236929Z caller=memcached_client.go:438 level=warn name=index-cache msg="failed to fetch items from memcached" numKeys=1 firstKey=EP:01J5TQ7GTAK7JFP1SDHAZQABMB:NskVASoO0H1CJRIx74k3hIBPzIM6wCRkKvWOjc9V3Dg:dss err="write tcp 10.233.66.17:47668->10.233.31.160:11211: write: connection timed out"

**Environment**:
- OS (e.g. from /etc/os-release): RedHat 8.5
- Kernel (e.g. `uname -a`): 4.8
- Others: Kubernetes

-->
