### ISSUE TITLE
Thanos compactor  msg="retriable error"

### ISSUE THREAD

**Issue by BouchaaraAdil** [thanos-io/thanos#7723]
**Thanos, Prometheus and Golang version used**:

thanos 0.36.1 (latest)
kube-prometheus-stack: 61.2.0

**Object Storage Provider**:
s3 bucket

**What happened**:

thanos compactor fails to download blocks with size bigger than 30GB 
these blocks are in compaction level 3(2d) and thanos tries to compact them into level: 4 (14d)

```
ts=2024-09-11T16:25:11.491964797Z caller=compact.go:546 level=error msg="retriable error" err="compaction: 2 errors: group 0@9204256579063621580: download block 01J0TF3B4B8HNRCSNFNKWN997Y: get file 01J0TF3B4B8HNRCSNFNKWN997Y/chunks/000003: The difference between the request time and the current time is too large.; group 0@7993504198507588329: download block 01J1DVPQCBHE5NWGJR69X5BKJP: get file 01J1DVPQCBHE5NWGJR69X5BKJP/chunks/000021: The difference between the request time and the current time is too large."
```

**What you expected to happen**:

downsampling to work
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by BouchaaraAdil** [comment]
@bwplotka  @GiedriusS @yeya24 any idea?

i isolated running a signleton compactor only for that giant k8s cluster, allocated much more resources 20cpu and 40memory, as well as increased concurrency

this is my config:

```
      - args:
        - compact
        - --log.level=info
        - --log.format=logfmt
        - --http-address=0.0.0.0:10902
        - --data-dir=/data
        - --retention.resolution-raw=180d
        - --retention.resolution-5m=365d
        - --retention.resolution-1h=0d
        - --consistency-delay=30m
        - --objstore.config-file=/conf/objstore.yml
        - --compact.concurrency=16
        - --downsample.concurrency=200
        - --block-files-concurrency=1500
        - --block-meta-fetch-concurrency=80
        - --compact.blocks-fetch-concurrency=400
        - --block-viewer.global.sync-block-timeout=60m
        - --block-viewer.global.sync-block-interval=15m
        - --wait-interval=5m
        - --delete-delay=48h
        - --wait
        - |
          --selector.relabel-config=
            - action: keep
              source_labels: ["cluster"]
              regex: "(live-eu)"
```
