### ISSUE TITLE
Thanos rule does not add labels to recording rules

### ISSUE THREAD

**Issue by atos-cosmin-gavagiuc** [thanos-io/thanos#7902]
**What happened**:

Labels added to `recording rules` through PrometheusRule are not visible in Thanos rule, even though they are present in the container configuration and appear in the Thanos API.

**What you expected to happen**:

Add labels to recording rules added to Thanos Rule as specified in the [Recording Rules documentation](https://thanos.io/tip/components/rule.md/#recording-rules)

**How to reproduce it (as minimally and precisely as possible)**:
Recording rule:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring: thanos-monitored
  name: up-rules
spec:
  groups:
  - name: thanos-rule-test
    rules:
    - expr: |
        up
      record: alpha:up
      labels:
        release_stage: alpha
```

The recording rule is correctly loaded in Thanos, including the lables specified in the configuration.

![image](https://github.com/user-attachments/assets/af26ea23-ae63-45a8-9b21-45b782dc8c55)

The labels declared in the recording rule are missing the Thanos rules dashboard and from the metric labels.

![image](https://github.com/user-attachments/assets/d082ac98-9bad-4a8b-bd79-dc30c74cc8e0)

**Full logs to relevant components**:

**Anything else we need to know**:
Thanos version 0.35.1
