### ISSUE TITLE
thanos s3 tier 2 request usage is very high

### ISSUE THREAD

**Issue by doctorpangloss** [thanos-io/thanos#7916]
There is a mind-numbing amount of arcana related to using thanos with s3 without suffering from insane request costs

https://github.com/thanos-io/thanos/issues/2643

https://github.com/thanos-io/thanos/issues/2389

What is the correct configuration for thanos so that when used as a storage backend for prometheus, which is 99% of people, with s3, which is probably 95% of people, such that there isn't a huge request load?

**Comment by yeya24** [comment]
Can you please share more details about the number of requests to S3 you have?
What types of request those are, GET, EXISTS or something else?
Thanos objstore metrics should tell you what kind of requests to object store you have the most. Do you have any data about which component it comes from? Compactor or Store Gateway?

**Comment by doctorpangloss** [comment]
I investigated further and it looks like thanos is not the cause!

**Comment by doctorpangloss** [comment]
> Can you please share more details about the number of requests to S3 you have? What types of request those are, GET, EXISTS or something else? Thanos objstore metrics should tell you what kind of requests to object store you have the most. Do you have any data about which component it comes from? Compactor or Store Gateway?
> 
> Have you tried the metadata caches?

Honestly I am overwhelmed by how difficult it is to answer any of these questions. Do you have any advice for investigating this? For now I am simply setting the number of replicas of thanos to zero, because the usage has absolutely exploded.

**Comment by TheReal1604** [comment]
Hi @doctorpangloss, 

just to get a quick overview, you can just scrape the metrics of thanos-store of its http-endpoint and import the official thanos-store example dashboard to your grafana instance.

https://github.com/thanos-io/thanos/blob/main/examples/dashboards/store.json

There is a row called "Bucket-Operations". Or you just scrape the metrics endpoint yourself.

![image](https://github.com/user-attachments/assets/6a5231f7-3425-4c04-a3d3-0f5778cd5fd2)

**Comment by julienlau** [comment]
I see Thanos rolled out on a bare metal data lake based on a shared Minio instance... Thanos immediately was the number 1 requester in terms of queries per day.
Thanos is the only workload that is rate limited by our 1000 qps cap on S3.
That is definitely something to improve before 1.0.0.

In addition, some sizing guides regarding S3 resources consumption would be nice.

**Comment by julienlau** [comment]
please find attached metrics from a thanos instance on an on premise test setup.
Note that this is after applying rate limiting to in front of our S3 cluster.

Thanos makes way too many getHeadObject et getObject requests.
![thanos-1 - anon](https://github.com/user-attachments/assets/22fcd798-1b67-4f9f-af1f-bc9a5aa85654)
![thanos-2 - anon](https://github.com/user-attachments/assets/cedb1700-db7a-41da-8ba6-719b6b40fe40)

**Comment by gschunicht** [comment]
Was this ever resolved? getting a preferred configuration that can reduce S3 usage would be great

**Comment by julienlau** [comment]
> I recommend the following settings ...
> 
> ```
> --wait-interval=4h
> --debug.accept-malformed-index
> --delete-delay=48h
> --compact.cleanup-interval=0s
> --compact.progress-interval=0s
> --web.disable
> ```
> 
> These settings have reduced my costs drastically. This ensures that the progress and cleanup happen just at the end of every interval which is controlled by the wait interval.

Thanks for sharing! 
I would say to stick to what is strictly necessary is the following configuration of the compactor component : 
```
--wait
--wait-interval=4h
--compact.cleanup-interval=0s
--compact.progress-interval=0s
```

I decreased thanos queries went from 200k queries per 5m to 5k queries per 5m with these settings.  

![Image](https://github.com/user-attachments/assets/fddf682b-e2a2-49bf-94b4-a23568421264)

**Comment by doctorpangloss** [comment]
thank you so much for investigating this guys, I am going to deploy it tonight and compare, then close ticket if it works with results or report with more info

**Comment by doctorpangloss** [comment]
none of these configuration settings worked, and just incurred $3,000 bills for a tiny cluster. so if i were you, i wouldn't use thanos with s3, unless you want to waste huge amounts of money.

my configuration:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      version: "15.7.26"
      chart: thanos
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/thanos
      tag: 0.39.2-debian-12-r2
    global:
      imagePullSecrets:
        - name: docker-doctorpangloss
    existingObjstoreSecret: thanos-objstore-config
    query:
      enabled: true
      replicaCount: 1
      extraFlags:
        - --query.timeout=5m
        - --query.lookback-delta=15m
        - --store.sd-dns-interval=30s
      dnsDiscovery:
        enabled: true
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 2Gi
          cpu: 1000m
          ephemeral-storage: 5Gi
      nodeSelector:
        kubernetes.io/os: linux
    queryFrontend:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 2Gi
          cpu: 1000m
          ephemeral-storage: 5Gi
      extraFlags:
        - --query-frontend.compress-responses
        - --query-range.split-interval=12h
        - --labels.split-interval=12h
        - --query-range.max-retries-per-request=10
        - --labels.max-retries-per-request=10
        - --query-frontend.log-queries-longer-than=10s
      nodeSelector:
        kubernetes.io/os: linux
    storegateway:
      enabled: true
      replicaCount: 1
      extraFlags:
        - --sync-block-duration=30m
        - --index-cache-size=1GB
        - --chunk-pool-size=1GB
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 3Gi
          cpu: 1000m
          ephemeral-storage: 20Gi
      nodeSelector:
        kubernetes.io/os: linux
    compactor:
      enabled: true
      strategyType: Recreate
      replicaCount: 1
      retentionResolutionRaw: 30d
      retentionResolution5m: 30d
      retentionResolution1h: 365d
      extraFlags:
        - --wait-interval=4h
        - --debug.accept-malformed-index
        - --delete-delay=48h
        - --compact.cleanup-interval=0s
        - --compact.progress-interval=0s
      resources:
        limits:
          memory: 2Gi
          cpu: 1000m
          ephemeral-storage: 10Gi
      nodeSelector:
        kubernetes.io/os: linux
```
