### ISSUE TITLE
Thanos-Querier error "rpc error: code = DeadlineExceeded desc = context deadline exceeded" with istio cross-cluster commnunication

### ISSUE THREAD

**Issue by inboxamitraj** [thanos-io/thanos#7948]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.33.0 (branch: HEAD, revision: 0f025f1ff97826a632435ba8fdcb9e3bc248bb27)
  build user:       root@9fb4d3c2f7ec
  build date:       20231217-16:49:45
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo
  
AWS EKS version: 1.29
Istio version: 1.20.2

 note- same error exists with old Thanos v0.26.0 and latest Thanos v0.37.0 version as well.

**Object Storage Provider**:
- --store=test-cluster-metrics-grpc-consumer.test:10901
- --store=test-component-metrics-grpc-consumer.test:10901
- --store=thanos-store-test.monitoring.svc.cluster.local:10901

**What happened**:
We are using Prometheus Operator in EKS with cross cluster communication setup with Istio Service Mesh.
We have Grafana and Thanos-Querier on Cluster A, which works as centralised Grafana/Querier.
For each clusters, e.g. Cluster B, C, D we have a Thanos-Querier running on our Centralised Cluster A which queries thanos-store and thanos-sidecar running on each cluster.

we recently upgraded Istio to 1.20 from 1.19 since then Grafana does not show latest prometheus metrics on other clusters. however we can see  prometheus metrics before 2 hours. This means- Thanos-Querier can talk to Thanos-Store but not able to connect to live Thanos-SideCar which has latest prometheus metrics.

**What you expected to happen**:
Centralised Grafana should show latest prometheus metrics from other clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Two EKS 1.29 Clusters
Istio 1.20
Prometheus Operator running on both the Clusters and one of the cluster working as Centralised Cluster.

 
**Full logs to relevant components**:
```
ts=2024-12-01T03:34:36.827530034Z caller=endpointset.go:460 level=warn component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from test-component-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-component-metrics-grpc-consumer.test:10901
ts=2024-12-01T03:34:36.827530004Z caller=endpointset.go:460 level=warn component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from test-cluster-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-cluster-metrics-grpc-consumer.test:10901
ts=2024-12-01T03:34:36.827616429Z caller=endpointset.go:433 level=debug component=endpointset msg="updated endpoints" activeEndpoints=1
ts=2024-12-01T03:34:36.827667822Z caller=endpointset.go:354 level=debug component=endpointset msg="starting to update API endpoints" cachedEndpoints=1
```

**Anything else we need to know**:
What we have done so far-
added --query.grpc.client.serverName
increased timeouts 
attempted with latest Thanos v0.37.0 image.

Thanos Querier Deployment in Cluster A
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        tls: permissive
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:9090
        - --store=test-cluster-metrics-grpc-consumer.test:10901
        - --store=test-component-metrics-grpc-consumer.test:10901
        - --store=thanos-store-test.monitoring.svc.cluster.local:10901
        name: thanos-querier
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: cstack-thanos-s3
        secret:
          defaultMode: 420
          secretName: cstack-thanos-sealed-s3-test

```

Service Entry in Cluster A
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-cluster-metrics-grpc-consumer-import
  namespace: monitoring
spec:
  endpoints:
  - address: test-e01-shared-mesh.istio-eastwest-internal
    labels:
      security.istio.io/tlsMode: istio
  exportTo:
  - .
  hosts:
  - test-cluster-metrics-grpc-consumer.test
  location: MESH_INTERNAL
  ports:
  - name: grpc-10901
    number: 10901
    protocol: GRPC
  resolution: DNS
```
Destination Rule in Cluster A
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: 
  name: test-cluster-metrics-grpc-consumer-import
  namespace: monitoring
spec:
  exportTo:
  - .
  host: test-cluster-metrics-grpc-consumer.test
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: outbound_.10901_._.cluster-metrics-grpc-provider.monitoring.svc.cluster.local
```

Attached- Grafana screenshot - we cannot see the latest metrics, however metrics older than 2 hours can be seen
<img width="595" alt="Screenshot 2024-12-01 at 11 36 44 AM" src="https://github.com/user-attachments/assets/5d82b80f-236d-4be7-8389-207e9aaa9578">

**Comment by inboxamitraj** [comment]
I found a workaround solution to this issue, just add the service name (endpoint) in another cluster to the thanos store.
The new line fixed the issue is : `- --store=kube-prometheus-stack-prometheus-sidecar-grpc.monitoring.svc.cluster.local:10901`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        tls: permissive
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:9090
        - --store=kube-prometheus-stack-prometheus-sidecar-grpc.monitoring.svc.cluster.local:10901
        - --store=gen-prd-cluster-metrics-grpc-consumer.gen-prd:10901

```

**Comment by inboxamitraj** [comment]
Hi All,
I noticed that thanos-proxy, still has same problem.
that means dashboards with thanos-querier work but dashboard with thanos-proxy do not work :(

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-stg-t-gvt-pic-test-i-stg
  name: thanos-proxy-t-gvt-pic-test-i-stg
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: thanos-stg-t-gvt-pic-test-i-stg
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thanos-stg-t-gvt-pic-test-i-stg
    spec:
      containers:
      - command:
        - grafana-ocpthanos-proxy
        - --listen-address=0.0.0.0:9096
        - --thanos-address=http://thanos-querier-test.monitoring.svc.cluster.local:9090
        image: thanos-proxy:1.0.5
        volumeMounts:
        - mountPath: /etc/conf
          name: ns-config
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: internal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: thanos-proxy-t-gvt-pic-test-i
      serviceAccountName: thanos-proxy-t-gvt-pic-test-i
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: type
        operator: Equal
        value: internal
      volumes:
      - configMap:
          defaultMode: 493
          name: thanos-proxy-t-gvt-pic-test-i-stg
        name: ns-config
```

Thank you
