### ISSUE TITLE
Thanos-Querier " component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from test-component-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-component-metrics-grpc-consumer.test:10901" 

### ISSUE THREAD

**Issue by inboxamitraj** [thanos-io/thanos#7971]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.33.0 (branch: HEAD, revision: 0f025f1ff97826a632435ba8fdcb9e3bc248bb27)
  build user:       root@9fb4d3c2f7ec
  build date:       20231217-16:49:45
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo
  
AWS EKS version: 1.29
Istio version: 1.20.2

 note- same error exists with old Thanos v0.26.0 and latest Thanos v0.37.0 version as well.

**Object Storage Provider**:
- --store=test-cluster-metrics-grpc-consumer.test:10901
- --store=test-component-metrics-grpc-consumer.test:10901
- --store=thanos-store-test.monitoring.svc.cluster.local:10901

**What happened**:
we have a Thanos-Querier running on our Centralised Cluster A which queries thanos-store and thanos-sidecar running on other EKS clusters

we recently upgraded Istio to 1.20 from 1.19 since then Grafana does not show latest prometheus metrics on other clusters. however we can see  prometheus metrics before 2 hours. This means- Thanos-Querier can talk to Thanos-Store but not able to connect to live Thanos-SideCar which has latest prometheus metrics.

**What you expected to happen**:
Centralised Grafana should show latest prometheus metrics from other clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Two EKS 1.29 Clusters
Istio 1.20
Prometheus Operator running on both the Clusters and one of the cluster working as Centralised Cluster.

 
**Full logs to relevant components**:
```
level=warn ts=2024-12-09T08:31:15.205305755Z caller=endpointset.go:517 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from test-component-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-component-metrics-grpc-consumer.test:10901
level=warn ts=2024-12-09T08:31:20.206042557Z caller=endpointset.go:517 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from test-cluster-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-cluster-metrics-grpc-consumer.test:10901
level=warn ts=2024-12-09T08:31:20.206102661Z caller=endpointset.go:517 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from test-component-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-component-metrics-grpc-consumer.test:10901
level=warn ts=2024-12-09T08:31:25.206932058Z caller=endpointset.go:517 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from test-component-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-component-metrics-grpc-consumer.test:10901
level=warn ts=2024-12-09T08:31:25.206936638Z caller=endpointset.go:517 component=endpointset msg="update of node failed" err="getting metadata: fallback fetching info from test-cluster-metrics-grpc-consumer.test:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test-cluster-metrics-grpc-consumer.test:10901
```

**Anything else we need to know**:
What we have done so far-

1. added --query.grpc.client.serverName in the thanos-querier deploymement
2. increased timeouts in thanos-querier
3. attempted with latest Thanos v0.37.0 image.

Thanos Querier Deployment in Cluster A
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        tls: permissive
    spec:
      containers:
      - args:
        - query
        - --http-address=0.0.0.0:9090
        - --store=test-cluster-metrics-grpc-consumer.test:10901
        - --store=test-component-metrics-grpc-consumer.test:10901
        - --store=thanos-store-test.monitoring.svc.cluster.local:10901
        name: thanos-querier
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: cstack-thanos-s3
        secret:
          defaultMode: 420
          secretName: cstack-thanos-sealed-s3-test

```

Service Entry in Cluster A
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-cluster-metrics-grpc-consumer-import
  namespace: monitoring
spec:
  endpoints:
  - address: test-e01-shared-mesh.istio-eastwest-internal
    labels:
      security.istio.io/tlsMode: istio
  exportTo:
  - .
  hosts:
  - test-cluster-metrics-grpc-consumer.test
  location: MESH_INTERNAL
  ports:
  - name: grpc-10901
    number: 10901
    protocol: GRPC
  resolution: DNS
```
Destination Rule in Cluster A
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: 
  name: test-cluster-metrics-grpc-consumer-import
  namespace: monitoring
spec:
  exportTo:
  - .
  host: test-cluster-metrics-grpc-consumer.test
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: outbound_.10901_._.cluster-metrics-grpc-provider.monitoring.svc.cluster.local
```

Attached- Grafana screenshot - we cannot see the latest metrics, however metrics older than 2 hours can be seen
<img width="595" alt="Screenshot 2024-12-01 at 11 36 44 AM" src="https://github.com/user-attachments/assets/5d82b80f-236d-4be7-8389-207e9aaa9578">
