### ISSUE TITLE
query: upgrade to 0.38.0 --endpoint.sd-config-file

### ISSUE THREAD

**Issue by trouaux** [thanos-io/thanos#8209]
**Thanos, Prometheus and Golang version used**:
thanos v0.38.0 docker

**What happened**:
After updating flag used to pass the path to sd-config file my pod crashes unmarshal eroor

**What you expected to happen**:
no changes

**How to reproduce it (as minimally and precisely as possible)**:
update --store.sd-files to --endpoint.sd-config-file in deployment.yaml

**Full logs to relevant components**:
```
ts=2025-04-16T09:21:12.447141135Z caller=main.go:145 level=error err="unable to load config initially\n> main.setupEndpointSet\t/app/cmd/thanos/endpointset.go:209\n> main.registerQuery.func1\t/app/cmd/thanos/query.go:260\n> main.main\t/app/cmd/thanos/main.go:143\n> runtime.main\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/proc.go:283\n> runtime.goexit\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/asm_amd64.s:1700\nunable to load config file\n> main.newEndpointConfigProvider\t/app/cmd/thanos/endpointset.go:144\n> main.setupEndpointSet\t/app/cmd/thanos/endpointset.go:199\n> main.registerQuery.func1\t/app/cmd/thanos/query.go:260\n> main.main\t/app/cmd/thanos/main.go:143\n> runtime.main\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/proc.go:283\n> runtime.goexit\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/asm_amd64.s:1700\nunable to unmarshal config content: /etc/thanos/sd-config/endpoint-targets.yaml\n> main.(*endpointConfigProvider).parse\t/app/cmd/thanos/endpointset.go:81\n> main.newEndpointConfigProvider\t/app/cmd/thanos/endpointset.go:142\n> main.setupEndpointSet\t/app/cmd/thanos/endpointset.go:199\n> main.registerQuery.func1\t/app/cmd/thanos/query.go:260\n> main.main\t/app/cmd/thanos/main.go:143\n> runtime.main\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/proc.go:283\n> runtime.goexit\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/asm_amd64.s:1700\nyaml: unmarshal errors:\n  line 1: cannot unmarshal !!seq into main.EndpointConfig\n\npreparing query command failed\nmain.main\n\t/app/cmd/thanos/main.go:145\nruntime.main\n\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/proc.go:283\nruntime.goexit\n\t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/asm_amd64.s:1700"
```

**Anything else we need to know**:
```
apiVersion: v1
data:
  endpoint-targets.yaml: |-
    - targets:
      - prometheus-operated:10901
      - thanos-store:10901
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: thanos
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: thanos-sd-config
  namespace: default
```
