### ISSUE TITLE
Envoy for a cross cluster Thanos endpoint discovery

### ISSUE THREAD

**Issue by michal0A** [thanos-io/thanos#906]
One response from @bwplotka in question #454 says 'you can use some proxy (we are doing this via envoy) to set up the connection between query and sidecars'. So I was trying the whole last week anything to configure Envoy to provide Thanos with endpoints based in a different cluster, but I am still unsuccessful. May I ask for clarification of this? Maybe some example for Envoy proxy. Maybe I am missing something and this is just not possible.

Here is our desired state:

Thanos Query
--store: remote.cluster:envoyport

Remote Cluster
Envoy with STRICT_DNS cluster discovery pointing to the headless service (DNS record with a multiple A records each for one Thanos StoreAPI).

**Comment by bwplotka** [comment]
Can you share what exactly issues you have? 

cc @domgreen

**Comment by domgreen** [comment]
This is indeed how we have our set-up internally. Could you share some more detail on your current issue?

It is most likely a config issue somewhere in the routing.

**Comment by michal0A** [comment]
Sure,

Here is my Envoy configuration. thanos-store-gateway is a DNS record with multiple A records in cluster one.

Cluster One:
(Kubernetes LB with external IP -> Envoy -> thanos-store-zero)

Cluster Zero:
(Thanos -> Cluster One (Kubernetes LB))

I can connect to Envoy listener on port 10901 from Thanos running in Cluster zero, but the result is that Thanos can see only one endpoint at a time. When I refresh the Thanos Store GUI, I can see a response from different endpoint behind the proxy each time. But I want to have them all there. 

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10901 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_backend
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_backend
    connect_timeout: 0.25s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts: [{ socket_address: { address: thanos-store-gateway, port_value: 10901 }}]

```

> Can you share what exactly issues you have?
> 
> cc @domgreen
