### ISSUE TITLE
Support additional SSE methods for S3

### ISSUE THREAD

**Issue by taharah** [thanos-io/thanos#946]
**Thanos, Prometheus and Golang version used**

**Thanos:** 0.3.2
**Prometheus:** 2.7.2
**Golang**: 1.11.5

**What happened**

Currently, the S3 bucket client only supports using the default key for SSE [[1](https://github.com/improbable-eng/thanos/blob/master/pkg/objstore/s3/s3.go#L151-L153)]. 

**What you expected to happen**

The S3 bucket client should be able to also support SSE-KMS and SSE-C encryption [[2](https://godoc.org/github.com/minio/minio-go/pkg/encrypt#ServerSide)]. 

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Full logs to relevant components**

N/A 

**Anything else we need to know**

I took a look at the code and this does introduce the opportunity to modify the existing SSE configuration in order to be a little cleaner as well as support the additional encryption methods.

For instance, the current configuration is this:

```yaml
type: S3
config:
  encrypt_sse: false
```

I think it would be nice if we changed the configuration to something like the following:

```yaml
type: S3
config:
  server_side_encryption:
    enabled: false
    kms_key_id: ""  # Used for SSE-KMS encrytpion
    encryption_key: ""  # Used for SSE-C encryption
```

NOTE: I've included only the relevant portions in the above examples.

However, the change could be made passive by just adding the parameters to the existing configuration at the top level.
